In [1]:
from pathlib import Path
import sys
import os

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / "src").exists():
    repo_root = repo_root.parent

sys.path.insert(0, str(repo_root / "src"))

from import_libraries import *  # NOSONAR
from global_variables import *  # NOSONAR
import common_libraries.io_library as io_l

from ml_classification.ml_classification_pipeline import (
    GeospatialClassificationPipeline,
    ClassificationPipelineConfig,
)

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\xicor\__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

WARNING:tensorflow:From E:\Eleni\git_repo\satellites\src\global_variables.py:28: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

In [2]:
WORK_PATH = Path("C:/work_dir/kozani-2023-2024")
# PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_time_stats.geoparquet"
# OUTPUT_PATH = WORK_PATH / "3_ml_classification_oversample"

# PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_annual_stats.geoparquet"
# OUTPUT_PATH = WORK_PATH / "3_ml_classification_reduced"

# PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_time_stats.geoparquet"
# OUTPUT_PATH = WORK_PATH / "3_ml_classification_tune_probabilities"

PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_time_stats.geoparquet"
OUTPUT_PATH = WORK_PATH / "3_ml_classification_tune_probabilities1"

class_column = "label"
parcel_id_column = "parcel_code"

In [3]:
gdf_parcels = io_l.read_data(str(PARCELS_PATH))
gdf_parcels.head(3)

Reading file: C:/work_dir/kozani-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet

,parcel_code,label,geometry,batch_number,eligible_pixel_count,meets_minimum_pixel_count,parcel_area_m2,approx_pixel_count,B02_bowley_skewness__20231001,B02_bowley_skewness__20231101,B02_bowley_skewness__20231201,B02_bowley_skewness__20240101,B02_bowley_skewness__20240201,B02_bowley_skewness__20240301,B02_bowley_skewness__20240401,B02_bowley_skewness__20240501,B02_bowley_skewness__20240601,B02_bowley_skewness__20240701,B02_bowley_skewness__20240801,B02_bowley_skewness__20240901,B02_coefficient_of_variation__20231001,B02_coefficient_of_variation__20231101,B02_coefficient_of_variation__20231201,B02_coefficient_of_variation__20240101,B02_coefficient_of_variation__20240201,B02_coefficient_of_variation__20240301,B02_coefficient_of_variation__20240401,B02_coefficient_of_variation__20240501,B02_coefficient_of_variation__20240601,B02_coefficient_of_variation__20240701,B02_coefficient_of_variation__20240801,B02_coefficient_of_variation__20240901,B02_iqr__20231001,B02_iqr__20231101,B02_iqr__20231201,B02_iqr__20240101,B02_iqr__20240201,B02_iqr__20240301,B02_iqr__20240401,B02_iqr__20240501,B02_iqr__20240601,B02_iqr__20240701,B02_iqr__20240801,B02_iqr__20240901,B02_max__20231001,B02_max__20231101,B02_max__20231201,B02_max__20240101,B02_max__20240201,B02_max__20240301,B02_max__20240401,B02_max__20240501,B02_max__20240601,B02_max__20240701,B02_max__20240801,B02_max__20240901,B02_mean__20231001,B02_mean__20231101,B02_mean__20231201,B02_mean__20240101,B02_mean__20240201,B02_mean__20240301,B02_mean__20240401,B02_mean__20240501,B02_mean__20240601,B02_mean__20240701,B02_mean__20240801,B02_mean__20240901,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_min__20231001,B02_min__20231101,B02_min__20231201,B02_min__20240101,B02_min__20240201,B02_min__20240301,B02_min__20240401,B02_min__20240501,B02_min__20240601,B02_min__20240701,B02_min__20240801,B02_min__20240901,B02_p10__20231001,B02_p10__20231101,B02_p10__20231201,B02_p10__20240101,B02_p10__20240201,B02_p10__20240301,B02_p10__20240401,B02_p10__20240501,B02_p10__20240601,B02_p10__20240701,B02_p10__20240801,B02_p10__20240901,B02_p25__20231001,B02_p25__20231101,B02_p25__20231201,B02_p25__20240101,B02_p25__20240201,B02_p25__20240301,B02_p25__20240401,B02_p25__20240501,B02_p25__20240601,B02_p25__20240701,B02_p25__20240801,B02_p25__20240901,B02_p75__20231001,B02_p75__20231101,B02_p75__20231201,B02_p75__20240101,B02_p75__20240201,B02_p75__20240301,B02_p75__20240401,B02_p75__20240501,B02_p75__20240601,B02_p75__20240701,B02_p75__20240801,B02_p75__20240901,B02_p90__20231001,B02_p90__20231101,B02_p90__20231201,B02_p90__20240101,B02_p90__20240201,B02_p90__20240301,B02_p90__20240401,B02_p90__20240501,B02_p90__20240601,B02_p90__20240701,B02_p90__20240801,B02_p90__20240901,B02_p90_p10_spread__20231001,B02_p90_p10_spread__20231101,B02_p90_p10_spread__20231201,B02_p90_p10_spread__20240101,B02_p90_p10_spread__20240201,B02_p90_p10_spread__20240301,B02_p90_p10_spread__20240401,B02_p90_p10_spread__20240501,B02_p90_p10_spread__20240601,B02_p90_p10_spread__20240701,B02_p90_p10_spread__20240801,B02_p90_p10_spread__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B02_variance__20231001,B02_variance__20231101,B02_variance__20231201,B02_variance__20240101,B02_variance__20240201,B02_variance__20240301,B02_variance__20240401,B02_variance__20240501,B02_variance__20240601,B02_variance__20240701,B02_variance__20240801,B02_variance__20240901,B03_bowley_skewness__20231001,B03_bowley_skewness__20231101,B03_bowley_skewness__20231201,B03_bowley_skewness__20240101,B03_bowley_skewness__20240201,B03_bowley_skewness__20240301,B03_bowley_skewness__20240401,B03_bowley_skewness__20240501,B03_bowley_skewness__20240601,B03_bowley_skewness__20240701,B03_bowley_skewness__20240801,B03_bowley_skewness__20240901,B03_coefficient_of_variation__20231001,B03_coefficient_of_variation__20231101,B03_coefficient_of_variation__20231201,B03_coefficient_of_variation__20240101,B03_coefficient_of_variation__20240201,B03_coefficient_of_variation__20240301,B03_coefficient_of_variation__20240401,B03_coefficient_of_variation__20240501,B03_coefficient_of_variation__20240601,B03_coefficient_of_variation__20240701,B03_coefficient_of_variation__20240801,B03_coefficient_of_variation__20240901,B03_iqr__20231001,B03_iqr__20231101,B03_iqr__20231201,B03_iqr__20240101,B03_iqr__20240201,B03_iqr__20240301,B03_iqr__20240401,B03_iqr__20240501,B03_iqr__20240601,B03_iqr__20240701,B03_iqr__20240801,B03_iqr__20240901,B03_max__20231001,B03_max__20231101,B03_max__20231201,B03_max__20240101,B03_max__20240201,B03_max__20240301,B03_max__20240401,B03_max__20240501,B03_max__20240601,B03_max__20240701,B03_max__20240801,B03_max__20240901,B03_mean__20231001,B03_mean__20231101,B03_mean__20231201,B03_mean__20240101,B03_mean__20240201,B03_mean__20240301,B03_mean__20240401,B03_mean__20240501,B03_mean__20240601,B03_mean__20240701,B03_mean__20240801,B03_mean__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_min__20231001,B03_min__20231101,B03_min__20231201,B03_min__20240101,B03_min__20240201,B03_min__20240301,B03_min__20240401,B03_min__20240501,B03_min__20240601,B03_min__20240701,B03_min__20240801,B03_min__20240901,B03_p10__20231001,B03_p10__20231101,B03_p10__20231201,B03_p10__20240101,B03_p10__20240201,B03_p10__20240301,B03_p10__20240401,B03_p10__20240501,B03_p10__20240601,B03_p10__20240701,B03_p10__20240801,B03_p10__20240901,B03_p25__20231001,B03_p25__20231101,B03_p25__20231201,B03_p25__20240101,B03_p25__20240201,B03_p25__20240301,B03_p25__20240401,B03_p25__20240501,B03_p25__20240601,B03_p25__20240701,B03_p25__20240801,B03_p25__20240901,B03_p75__20231001,B03_p75__20231101,B03_p75__20231201,B03_p75__20240101,B03_p75__20240201,B03_p75__20240301,B03_p75__20240401,B03_p75__20240501,B03_p75__20240601,B03_p75__20240701,B03_p75__20240801,B03_p75__20240901,B03_p90__20231001,B03_p90__20231101,B03_p90__20231201,B03_p90__20240101,B03_p90__20240201,B03_p90__20240301,B03_p90__20240401,B03_p90__20240501,B03_p90__20240601,B03_p90__20240701,B03_p90__20240801,B03_p90__20240901,B03_p90_p10_spread__20231001,B03_p90_p10_spread__20231101,B03_p90_p10_spread__20231201,B03_p90_p10_spread__20240101,B03_p90_p10_spread__20240201,B03_p90_p10_spread__20240301,B03_p90_p10_spread__20240401,B03_p90_p10_spread__20240501,B03_p90_p10_spread__20240601,B03_p90_p10_spread__20240701,B03_p90_p10_spread__20240801,B03_p90_p10_spread__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B03_variance__20231001,B03_variance__20231101,B03_variance__20231201,B03_variance__20240101,B03_variance__20240201,B03_variance__20240301,B03_variance__20240401,B03_variance__20240501,B03_variance__20240601,B03_variance__20240701,B03_variance__20240801,B03_variance__20240901,B04_bowley_skewness__20231001,B04_bowley_skewness__20231101,B04_bowley_skewness__20231201,B04_bowley_skewness__20240101,B04_bowley_skewness__20240201,B04_bowley_skewness__20240301,B04_bowley_skewness__20240401,B04_bowley_skewness__20240501,B04_bowley_skewness__20240601,B04_bowley_skewness__20240701,B04_bowley_skewness__20240801,B04_bowley_skewness__20240901,B04_coefficient_of_variation__20231001,B04_coefficient_of_variation__20231101,B04_coefficient_of_variation__20231201,B04_coefficient_of_variation__20240101,B04_coefficient_of_variation__20240201,B04_coefficient_of_variation__20240301,B04_coefficient_of_variation__20240401,B04_coefficient_of_variation__20240501,B04_coefficient_of_variation__20240601,B04_coefficient_of_variation__20240701,B04_coefficient_of_variation__20240801,B04_coefficient_of_variation__20240901,B04_iqr__20231001,B04_iqr__20231101,B04_iqr__20231201,B04_iqr__20240101,B04_iqr__20240201,B04_iqr__20240301,B04_iqr__20240401,B04_iqr__20240501,B04_iqr__20240601,B04_iqr__20240701,B04_iqr__20240801,B04_iqr__20240901,B04_max__20231001,B04_max__20231101,B04_max__20231201,B04_max__20240101,B04_max__20240201,B04_max__20240301,B04_max__20240401,B04_max__20240501,B04_max__20240601,B04_max__20240701,B04_max__20240801,B04_max__20240901,B04_mean__20231001,B04_mean__20231101,B04_mean__20231201,B04_mean__20240101,B04_mean__20240201,B04_mean__20240301,B04_mean__20240401,B04_mean__20240501,B04_mean__20240601,B04_mean__20240701,B04_mean__20240801,B04_mean__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_min__20231001,B04_min__20231101,B04_min__20231201,B04_min__20240101,B04_min__20240201,B04_min__20240301,B04_min__20240401,B04_min__20240501,B04_min__20240601,B04_min__20240701,B04_min__20240801,B04_min__20240901,B04_p10__20231001,B04_p10__20231101,B04_p10__20231201,B04_p10__20240101,B04_p10__20240201,B04_p10__20240301,B04_p10__20240401,B04_p10__20240501,B04_p10__20240601,B04_p10__20240701,B04_p10__20240801,B04_p10__20240901,B04_p25__20231001,B04_p25__20231101,B04_p25__20231201,B04_p25__20240101,B04_p25__20240201,B04_p25__20240301,B04_p25__20240401,B04_p25__20240501,B04_p25__20240601,B04_p25__20240701,B04_p25__20240801,B04_p25__20240901,B04_p75__20231001,B04_p75__20231101,B04_p75__20231201,B04_p75__20240101,B04_p75__20240201,B04_p75__20240301,B04_p75__20240401,B04_p75__20240501,B04_p75__20240601,B04_p75__20240701,B04_p75__20240801,B04_p75__20240901,B04_p90__20231001,B04_p90__20231101,B04_p90__20231201,B04_p90__20240101,B04_p90__20240201,B04_p90__20240301,B04_p90__20240401,B04_p90__20240501,B04_p90__20240601,B04_p90__20240701,B04_p90__20240801,B04_p90__20240901,B04_p90_p10_spread__20231001,B04_p90_p10_spread__20231101,B04_p90_p10_spread__20231201,B04_p90_p10_spread__20240101,B04_p90_p10_spread__20240201,B04_p90_p10_spread__20240301,B04_p90_p10_spread__20240401,B04_p90_p10_spread__20240501,B04_p90_p10_spread__20240601,B04_p90_p10_spread__20240701,B04_p90_p10_spread__20240801,B04_p90_p10_spread__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B04_variance__20231001,B04_variance__20231101,B04_variance__20231201,B04_variance__20240101,B04_variance__20240201,B04_variance__20240301,B04_variance__20240401,B04_variance__20240501,B04_variance__20240601,B04_variance__20240701,B04_variance__20240801,B04_variance__20240901,B05_bowley_skewness__20231001,B05_bowley_skewness__20231101,B05_bowley_skewness__20231201,B05_bowley_skewness__20240101,B05_bowley_skewness__20240201,B05_bowley_skewness__20240301,B05_bowley_skewness__20240401,B05_bowley_skewness__20240501,B05_bowley_skewness__20240601,B05_bowley_skewness__20240701,B05_bowley_skewness__20240801,B05_bowley_skewness__20240901,B05_coefficient_of_variation__20231001,B05_coefficient_of_variation__20231101,B05_coefficient_of_variation__20231201,B05_coefficient_of_variation__20240101,B05_coefficient_of_variation__20240201,B05_coefficient_of_variation__20240301,B05_coefficient_of_variation__20240401,B05_coefficient_of_variation__20240501,B05_coefficient_of_variation__20240601,B05_coefficient_of_variation__20240701,B05_coefficient_of_variation__20240801,B05_coefficient_of_variation__20240901,B05_iqr__20231001,B05_iqr__20231101,B05_iqr__20231201,B05_iqr__20240101,B05_iqr__20240201,B05_iqr__20240301,B05_iqr__20240401,B05_iqr__20240501,B05_iqr__20240601,B05_iqr__20240701,B05_iqr__20240801,B05_iqr__20240901,B05_max__20231001,B05_max__20231101,B05_max__20231201,B05_max__20240101,B05_max__20240201,B05_max__20240301,B05_max__20240401,B05_max__20240501,B05_max__20240601,B05_max__20240701,B05_max__20240801,B05_max__20240901,B05_mean__20231001,B05_mean__20231101,B05_mean__20231201,B05_mean__20240101,B05_mean__20240201,B05_mean__20240301,B05_mean__20240401,B05_mean__20240501,B05_mean__20240601,B05_mean__20240701,B05_mean__20240801,B05_mean__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_min__20231001,B05_min__20231101,B05_min__20231201,B05_min__20240101,B05_min__20240201,B05_min__20240301,B05_min__20240401,B05_min__20240501,B05_min__20240601,B05_min__20240701,B05_min__20240801,B05_min__20240901,B05_p10__20231001,B05_p10__20231101,B05_p10__20231201,B05_p10__20240101,B05_p10__20240201,B05_p10__20240301,B05_p10__20240401,B05_p10__20240501,B05_p10__20240601,B05_p10__20240701,B05_p10__20240801,B05_p10__20240901,B05_p25__20231001,B05_p25__20231101,B05_p25__20231201,B05_p25__20240101,B05_p25__20240201,B05_p25__20240301,B05_p25__20240401,B05_p25__20240501,B05_p25__20240601,B05_p25__20240701,B05_p25__20240801,B05_p25__20240901,B05_p75__20231001,B05_p75__20231101,B05_p75__20231201,B05_p75__20240101,B05_p75__20240201,B05_p75__20240301,B05_p75__20240401,B05_p75__20240501,B05_p75__20240601,B05_p75__20240701,B05_p75__20240801,B05_p75__20240901,B05_p90__20231001,B05_p90__20231101,B05_p90__20231201,B05_p90__20240101,B05_p90__20240201,B05_p90__20240301,B05_p90__20240401,B05_p90__20240501,B05_p90__20240601,B05_p90__20240701,B05_p90__20240801,B05_p90__20240901,B05_p90_p10_spread__20231001,B05_p90_p10_spread__20231101,B05_p90_p10_spread__20231201,B05_p90_p10_spread__20240101,B05_p90_p10_spread__20240201,B05_p90_p10_spread__20240301,B05_p90_p10_spread__20240401,B05_p90_p10_spread__20240501,B05_p90_p10_spread__20240601,B05_p90_p10_spread__20240701,B05_p90_p10_spread__20240801,B05_p90_p10_spread__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B05_variance__20231001,B05_variance__20231101,B05_variance__20231201,B05_variance__20240101,B05_variance__20240201,B05_variance__20240301,B05_variance__20240401,B05_variance__20240501,B05_variance__20240601,B05_variance__20240701,B05_variance__20240801,B05_variance__20240901,B08_bowley_skewness__20231001,B08_bowley_skewness__20231101,B08_bowley_skewness__20231201,B08_bowley_skewness__20240101,B08_bowley_skewness__20240201,B08_bowley_skewness__20240301,B08_bowley_skewness__20240401,B08_bowley_skewness__20240501,B08_bowley_skewness__20240601,B08_bowley_skewness__20240701,B08_bowley_skewness__20240801,B08_bowley_skewness__20240901,B08_coefficient_of_variation__20231001,B08_coefficient_of_variation__20231101,B08_coefficient_of_variation__20231201,B08_coefficient_of_variation__20240101,B08_coefficient_of_variation__20240201,B08_coefficient_of_variation__20240301,B08_coefficient_of_variation__20240401,B08_coefficient_of_variation__20240501,B08_coefficient_of_variation__20240601,B08_coefficient_of_variation__20240701,B08_coefficient_of_variation__20240801,B08_coefficient_of_variation__20240901,B08_iqr__20231001,B08_iqr__20231101,B08_iqr__20231201,B08_iqr__20240101,B08_iqr__20240201,B08_iqr__20240301,B08_iqr__20240401,B08_iqr__20240501,B08_iqr__20240601,B08_iqr__20240701,B08_iqr__20240801,B08_iqr__20240901,B08_max__20231001,B08_max__20231101,B08_max__20231201,B08_max__20240101,B08_max__20240201,B08_max__20240301,B08_max__20240401,B08_max__20240501,B08_max__20240601,B08_max__20240701,B08_max__20240801,B08_max__20240901,B08_mean__20231001,B08_mean__20231101,B08_mean__20231201,B08_mean__20240101,B08_mean__20240201,B08_mean__20240301,B08_mean__20240401,B08_mean__20240501,B08_mean__20240601,B08_mean__20240701,B08_mean__20240801,B08_mean__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_min__20231001,B08_min__20231101,B08_min__20231201,B08_min__20240101,B08_min__20240201,B08_min__20240301,B08_min__20240401,B08_min__20240501,B08_min__20240601,B08_min__20240701,B08_min__20240801,B08_min__20240901,B08_p10__20231001,B08_p10__20231101,B08_p10__20231201,B08_p10__20240101,B08_p10__20240201,B08_p10__20240301,B08_p10__20240401,B08_p10__20240501,B08_p10__20240601,B08_p10__20240701,B08_p10__20240801,B08_p10__20240901,B08_p25__20231001,B08_p25__20231101,B08_p25__20231201,B08_p25__20240101,B08_p25__20240201,B08_p25__20240301,B08_p25__20240401,B08_p25__20240501,B08_p25__20240601,B08_p25__20240701,B08_p25__20240801,B08_p25__20240901,B08_p75__20231001,B08_p75__20231101,B08_p75__20231201,B08_p75__20240101,B08_p75__20240201,B08_p75__20240301,B08_p75__20240401,B08_p75__20240501,B08_p75__20240601,B08_p75__20240701,B08_p75__20240801,B08_p75__20240901,B08_p90__20231001,B08_p90__20231101,B08_p90__20231201,B08_p90__20240101,B08_p90__20240201,B08_p90__20240301,B08_p90__20240401,B08_p90__20240501,B08_p90__20240601,B08_p90__20240701,B08_p90__20240801,B08_p90__20240901,B08_p90_p10_spread__20231001,B08_p90_p10_spread__20231101,B08_p90_p10_spread__20231201,B08_p90_p10_spread__20240101,B08_p90_p10_spread__20240201,B08_p90_p10_spread__20240301,B08_p90_p10_spread__20240401,B08_p90_p10_spread__20240501,B08_p90_p10_spread__20240601,B08_p90_p10_spread__20240701,B08_p90_p10_spread__20240801,B08_p90_p10_spread__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B08_variance__20231001,B08_variance__20231101,B08_variance__20231201,B08_variance__20240101,B08_variance__20240201,B08_variance__20240301,B08_variance__20240401,B08_variance__20240501,B08_variance__20240601,B08_variance__20240701,B08_variance__20240801,B08_variance__20240901,B11_bowley_skewness__20231001,B11_bowley_skewness__20231101,B11_bowley_skewness__20231201,B11_bowley_skewness__20240101,B11_bowley_skewness__20240201,B11_bowley_skewness__20240301,B11_bowley_skewness__20240401,B11_bowley_skewness__20240501,B11_bowley_skewness__20240601,B11_bowley_skewness__20240701,B11_bowley_skewness__20240801,B11_bowley_skewness__20240901,B11_coefficient_of_variation__20231001,B11_coefficient_of_variation__20231101,

In [4]:
label_counts = gdf_parcels[class_column].value_counts()
rare_labels = label_counts[label_counts < 100].index

gdf_parcels.loc[gdf_parcels[class_column].isin(rare_labels), class_column] = 9999
print(gdf_parcels[class_column].value_counts())

label
110     23314
119      9525
111      5299
129      3660
112      3288
130      2990
108      1651
128      1372
114      1001
116       870
121       675
101       590
105       532
122       450
102       365
9999      304
106       250
104       153
Name: count, dtype: int64

In [5]:
display(gdf_parcels.head(3))

,parcel_code,label,geometry,batch_number,eligible_pixel_count,meets_minimum_pixel_count,parcel_area_m2,approx_pixel_count,B02_bowley_skewness__20231001,B02_bowley_skewness__20231101,B02_bowley_skewness__20231201,B02_bowley_skewness__20240101,B02_bowley_skewness__20240201,B02_bowley_skewness__20240301,B02_bowley_skewness__20240401,B02_bowley_skewness__20240501,B02_bowley_skewness__20240601,B02_bowley_skewness__20240701,B02_bowley_skewness__20240801,B02_bowley_skewness__20240901,B02_coefficient_of_variation__20231001,B02_coefficient_of_variation__20231101,B02_coefficient_of_variation__20231201,B02_coefficient_of_variation__20240101,B02_coefficient_of_variation__20240201,B02_coefficient_of_variation__20240301,B02_coefficient_of_variation__20240401,B02_coefficient_of_variation__20240501,B02_coefficient_of_variation__20240601,B02_coefficient_of_variation__20240701,B02_coefficient_of_variation__20240801,B02_coefficient_of_variation__20240901,B02_iqr__20231001,B02_iqr__20231101,B02_iqr__20231201,B02_iqr__20240101,B02_iqr__20240201,B02_iqr__20240301,B02_iqr__20240401,B02_iqr__20240501,B02_iqr__20240601,B02_iqr__20240701,B02_iqr__20240801,B02_iqr__20240901,B02_max__20231001,B02_max__20231101,B02_max__20231201,B02_max__20240101,B02_max__20240201,B02_max__20240301,B02_max__20240401,B02_max__20240501,B02_max__20240601,B02_max__20240701,B02_max__20240801,B02_max__20240901,B02_mean__20231001,B02_mean__20231101,B02_mean__20231201,B02_mean__20240101,B02_mean__20240201,B02_mean__20240301,B02_mean__20240401,B02_mean__20240501,B02_mean__20240601,B02_mean__20240701,B02_mean__20240801,B02_mean__20240901,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_min__20231001,B02_min__20231101,B02_min__20231201,B02_min__20240101,B02_min__20240201,B02_min__20240301,B02_min__20240401,B02_min__20240501,B02_min__20240601,B02_min__20240701,B02_min__20240801,B02_min__20240901,B02_p10__20231001,B02_p10__20231101,B02_p10__20231201,B02_p10__20240101,B02_p10__20240201,B02_p10__20240301,B02_p10__20240401,B02_p10__20240501,B02_p10__20240601,B02_p10__20240701,B02_p10__20240801,B02_p10__20240901,B02_p25__20231001,B02_p25__20231101,B02_p25__20231201,B02_p25__20240101,B02_p25__20240201,B02_p25__20240301,B02_p25__20240401,B02_p25__20240501,B02_p25__20240601,B02_p25__20240701,B02_p25__20240801,B02_p25__20240901,B02_p75__20231001,B02_p75__20231101,B02_p75__20231201,B02_p75__20240101,B02_p75__20240201,B02_p75__20240301,B02_p75__20240401,B02_p75__20240501,B02_p75__20240601,B02_p75__20240701,B02_p75__20240801,B02_p75__20240901,B02_p90__20231001,B02_p90__20231101,B02_p90__20231201,B02_p90__20240101,B02_p90__20240201,B02_p90__20240301,B02_p90__20240401,B02_p90__20240501,B02_p90__20240601,B02_p90__20240701,B02_p90__20240801,B02_p90__20240901,B02_p90_p10_spread__20231001,B02_p90_p10_spread__20231101,B02_p90_p10_spread__20231201,B02_p90_p10_spread__20240101,B02_p90_p10_spread__20240201,B02_p90_p10_spread__20240301,B02_p90_p10_spread__20240401,B02_p90_p10_spread__20240501,B02_p90_p10_spread__20240601,B02_p90_p10_spread__20240701,B02_p90_p10_spread__20240801,B02_p90_p10_spread__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B02_variance__20231001,B02_variance__20231101,B02_variance__20231201,B02_variance__20240101,B02_variance__20240201,B02_variance__20240301,B02_variance__20240401,B02_variance__20240501,B02_variance__20240601,B02_variance__20240701,B02_variance__20240801,B02_variance__20240901,B03_bowley_skewness__20231001,B03_bowley_skewness__20231101,B03_bowley_skewness__20231201,B03_bowley_skewness__20240101,B03_bowley_skewness__20240201,B03_bowley_skewness__20240301,B03_bowley_skewness__20240401,B03_bowley_skewness__20240501,B03_bowley_skewness__20240601,B03_bowley_skewness__20240701,B03_bowley_skewness__20240801,B03_bowley_skewness__20240901,B03_coefficient_of_variation__20231001,B03_coefficient_of_variation__20231101,B03_coefficient_of_variation__20231201,B03_coefficient_of_variation__20240101,B03_coefficient_of_variation__20240201,B03_coefficient_of_variation__20240301,B03_coefficient_of_variation__20240401,B03_coefficient_of_variation__20240501,B03_coefficient_of_variation__20240601,B03_coefficient_of_variation__20240701,B03_coefficient_of_variation__20240801,B03_coefficient_of_variation__20240901,B03_iqr__20231001,B03_iqr__20231101,B03_iqr__20231201,B03_iqr__20240101,B03_iqr__20240201,B03_iqr__20240301,B03_iqr__20240401,B03_iqr__20240501,B03_iqr__20240601,B03_iqr__20240701,B03_iqr__20240801,B03_iqr__20240901,B03_max__20231001,B03_max__20231101,B03_max__20231201,B03_max__20240101,B03_max__20240201,B03_max__20240301,B03_max__20240401,B03_max__20240501,B03_max__20240601,B03_max__20240701,B03_max__20240801,B03_max__20240901,B03_mean__20231001,B03_mean__20231101,B03_mean__20231201,B03_mean__20240101,B03_mean__20240201,B03_mean__20240301,B03_mean__20240401,B03_mean__20240501,B03_mean__20240601,B03_mean__20240701,B03_mean__20240801,B03_mean__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_min__20231001,B03_min__20231101,B03_min__20231201,B03_min__20240101,B03_min__20240201,B03_min__20240301,B03_min__20240401,B03_min__20240501,B03_min__20240601,B03_min__20240701,B03_min__20240801,B03_min__20240901,B03_p10__20231001,B03_p10__20231101,B03_p10__20231201,B03_p10__20240101,B03_p10__20240201,B03_p10__20240301,B03_p10__20240401,B03_p10__20240501,B03_p10__20240601,B03_p10__20240701,B03_p10__20240801,B03_p10__20240901,B03_p25__20231001,B03_p25__20231101,B03_p25__20231201,B03_p25__20240101,B03_p25__20240201,B03_p25__20240301,B03_p25__20240401,B03_p25__20240501,B03_p25__20240601,B03_p25__20240701,B03_p25__20240801,B03_p25__20240901,B03_p75__20231001,B03_p75__20231101,B03_p75__20231201,B03_p75__20240101,B03_p75__20240201,B03_p75__20240301,B03_p75__20240401,B03_p75__20240501,B03_p75__20240601,B03_p75__20240701,B03_p75__20240801,B03_p75__20240901,B03_p90__20231001,B03_p90__20231101,B03_p90__20231201,B03_p90__20240101,B03_p90__20240201,B03_p90__20240301,B03_p90__20240401,B03_p90__20240501,B03_p90__20240601,B03_p90__20240701,B03_p90__20240801,B03_p90__20240901,B03_p90_p10_spread__20231001,B03_p90_p10_spread__20231101,B03_p90_p10_spread__20231201,B03_p90_p10_spread__20240101,B03_p90_p10_spread__20240201,B03_p90_p10_spread__20240301,B03_p90_p10_spread__20240401,B03_p90_p10_spread__20240501,B03_p90_p10_spread__20240601,B03_p90_p10_spread__20240701,B03_p90_p10_spread__20240801,B03_p90_p10_spread__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B03_variance__20231001,B03_variance__20231101,B03_variance__20231201,B03_variance__20240101,B03_variance__20240201,B03_variance__20240301,B03_variance__20240401,B03_variance__20240501,B03_variance__20240601,B03_variance__20240701,B03_variance__20240801,B03_variance__20240901,B04_bowley_skewness__20231001,B04_bowley_skewness__20231101,B04_bowley_skewness__20231201,B04_bowley_skewness__20240101,B04_bowley_skewness__20240201,B04_bowley_skewness__20240301,B04_bowley_skewness__20240401,B04_bowley_skewness__20240501,B04_bowley_skewness__20240601,B04_bowley_skewness__20240701,B04_bowley_skewness__20240801,B04_bowley_skewness__20240901,B04_coefficient_of_variation__20231001,B04_coefficient_of_variation__20231101,B04_coefficient_of_variation__20231201,B04_coefficient_of_variation__20240101,B04_coefficient_of_variation__20240201,B04_coefficient_of_variation__20240301,B04_coefficient_of_variation__20240401,B04_coefficient_of_variation__20240501,B04_coefficient_of_variation__20240601,B04_coefficient_of_variation__20240701,B04_coefficient_of_variation__20240801,B04_coefficient_of_variation__20240901,B04_iqr__20231001,B04_iqr__20231101,B04_iqr__20231201,B04_iqr__20240101,B04_iqr__20240201,B04_iqr__20240301,B04_iqr__20240401,B04_iqr__20240501,B04_iqr__20240601,B04_iqr__20240701,B04_iqr__20240801,B04_iqr__20240901,B04_max__20231001,B04_max__20231101,B04_max__20231201,B04_max__20240101,B04_max__20240201,B04_max__20240301,B04_max__20240401,B04_max__20240501,B04_max__20240601,B04_max__20240701,B04_max__20240801,B04_max__20240901,B04_mean__20231001,B04_mean__20231101,B04_mean__20231201,B04_mean__20240101,B04_mean__20240201,B04_mean__20240301,B04_mean__20240401,B04_mean__20240501,B04_mean__20240601,B04_mean__20240701,B04_mean__20240801,B04_mean__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_min__20231001,B04_min__20231101,B04_min__20231201,B04_min__20240101,B04_min__20240201,B04_min__20240301,B04_min__20240401,B04_min__20240501,B04_min__20240601,B04_min__20240701,B04_min__20240801,B04_min__20240901,B04_p10__20231001,B04_p10__20231101,B04_p10__20231201,B04_p10__20240101,B04_p10__20240201,B04_p10__20240301,B04_p10__20240401,B04_p10__20240501,B04_p10__20240601,B04_p10__20240701,B04_p10__20240801,B04_p10__20240901,B04_p25__20231001,B04_p25__20231101,B04_p25__20231201,B04_p25__20240101,B04_p25__20240201,B04_p25__20240301,B04_p25__20240401,B04_p25__20240501,B04_p25__20240601,B04_p25__20240701,B04_p25__20240801,B04_p25__20240901,B04_p75__20231001,B04_p75__20231101,B04_p75__20231201,B04_p75__20240101,B04_p75__20240201,B04_p75__20240301,B04_p75__20240401,B04_p75__20240501,B04_p75__20240601,B04_p75__20240701,B04_p75__20240801,B04_p75__20240901,B04_p90__20231001,B04_p90__20231101,B04_p90__20231201,B04_p90__20240101,B04_p90__20240201,B04_p90__20240301,B04_p90__20240401,B04_p90__20240501,B04_p90__20240601,B04_p90__20240701,B04_p90__20240801,B04_p90__20240901,B04_p90_p10_spread__20231001,B04_p90_p10_spread__20231101,B04_p90_p10_spread__20231201,B04_p90_p10_spread__20240101,B04_p90_p10_spread__20240201,B04_p90_p10_spread__20240301,B04_p90_p10_spread__20240401,B04_p90_p10_spread__20240501,B04_p90_p10_spread__20240601,B04_p90_p10_spread__20240701,B04_p90_p10_spread__20240801,B04_p90_p10_spread__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B04_variance__20231001,B04_variance__20231101,B04_variance__20231201,B04_variance__20240101,B04_variance__20240201,B04_variance__20240301,B04_variance__20240401,B04_variance__20240501,B04_variance__20240601,B04_variance__20240701,B04_variance__20240801,B04_variance__20240901,B05_bowley_skewness__20231001,B05_bowley_skewness__20231101,B05_bowley_skewness__20231201,B05_bowley_skewness__20240101,B05_bowley_skewness__20240201,B05_bowley_skewness__20240301,B05_bowley_skewness__20240401,B05_bowley_skewness__20240501,B05_bowley_skewness__20240601,B05_bowley_skewness__20240701,B05_bowley_skewness__20240801,B05_bowley_skewness__20240901,B05_coefficient_of_variation__20231001,B05_coefficient_of_variation__20231101,B05_coefficient_of_variation__20231201,B05_coefficient_of_variation__20240101,B05_coefficient_of_variation__20240201,B05_coefficient_of_variation__20240301,B05_coefficient_of_variation__20240401,B05_coefficient_of_variation__20240501,B05_coefficient_of_variation__20240601,B05_coefficient_of_variation__20240701,B05_coefficient_of_variation__20240801,B05_coefficient_of_variation__20240901,B05_iqr__20231001,B05_iqr__20231101,B05_iqr__20231201,B05_iqr__20240101,B05_iqr__20240201,B05_iqr__20240301,B05_iqr__20240401,B05_iqr__20240501,B05_iqr__20240601,B05_iqr__20240701,B05_iqr__20240801,B05_iqr__20240901,B05_max__20231001,B05_max__20231101,B05_max__20231201,B05_max__20240101,B05_max__20240201,B05_max__20240301,B05_max__20240401,B05_max__20240501,B05_max__20240601,B05_max__20240701,B05_max__20240801,B05_max__20240901,B05_mean__20231001,B05_mean__20231101,B05_mean__20231201,B05_mean__20240101,B05_mean__20240201,B05_mean__20240301,B05_mean__20240401,B05_mean__20240501,B05_mean__20240601,B05_mean__20240701,B05_mean__20240801,B05_mean__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_min__20231001,B05_min__20231101,B05_min__20231201,B05_min__20240101,B05_min__20240201,B05_min__20240301,B05_min__20240401,B05_min__20240501,B05_min__20240601,B05_min__20240701,B05_min__20240801,B05_min__20240901,B05_p10__20231001,B05_p10__20231101,B05_p10__20231201,B05_p10__20240101,B05_p10__20240201,B05_p10__20240301,B05_p10__20240401,B05_p10__20240501,B05_p10__20240601,B05_p10__20240701,B05_p10__20240801,B05_p10__20240901,B05_p25__20231001,B05_p25__20231101,B05_p25__20231201,B05_p25__20240101,B05_p25__20240201,B05_p25__20240301,B05_p25__20240401,B05_p25__20240501,B05_p25__20240601,B05_p25__20240701,B05_p25__20240801,B05_p25__20240901,B05_p75__20231001,B05_p75__20231101,B05_p75__20231201,B05_p75__20240101,B05_p75__20240201,B05_p75__20240301,B05_p75__20240401,B05_p75__20240501,B05_p75__20240601,B05_p75__20240701,B05_p75__20240801,B05_p75__20240901,B05_p90__20231001,B05_p90__20231101,B05_p90__20231201,B05_p90__20240101,B05_p90__20240201,B05_p90__20240301,B05_p90__20240401,B05_p90__20240501,B05_p90__20240601,B05_p90__20240701,B05_p90__20240801,B05_p90__20240901,B05_p90_p10_spread__20231001,B05_p90_p10_spread__20231101,B05_p90_p10_spread__20231201,B05_p90_p10_spread__20240101,B05_p90_p10_spread__20240201,B05_p90_p10_spread__20240301,B05_p90_p10_spread__20240401,B05_p90_p10_spread__20240501,B05_p90_p10_spread__20240601,B05_p90_p10_spread__20240701,B05_p90_p10_spread__20240801,B05_p90_p10_spread__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B05_variance__20231001,B05_variance__20231101,B05_variance__20231201,B05_variance__20240101,B05_variance__20240201,B05_variance__20240301,B05_variance__20240401,B05_variance__20240501,B05_variance__20240601,B05_variance__20240701,B05_variance__20240801,B05_variance__20240901,B08_bowley_skewness__20231001,B08_bowley_skewness__20231101,B08_bowley_skewness__20231201,B08_bowley_skewness__20240101,B08_bowley_skewness__20240201,B08_bowley_skewness__20240301,B08_bowley_skewness__20240401,B08_bowley_skewness__20240501,B08_bowley_skewness__20240601,B08_bowley_skewness__20240701,B08_bowley_skewness__20240801,B08_bowley_skewness__20240901,B08_coefficient_of_variation__20231001,B08_coefficient_of_variation__20231101,B08_coefficient_of_variation__20231201,B08_coefficient_of_variation__20240101,B08_coefficient_of_variation__20240201,B08_coefficient_of_variation__20240301,B08_coefficient_of_variation__20240401,B08_coefficient_of_variation__20240501,B08_coefficient_of_variation__20240601,B08_coefficient_of_variation__20240701,B08_coefficient_of_variation__20240801,B08_coefficient_of_variation__20240901,B08_iqr__20231001,B08_iqr__20231101,B08_iqr__20231201,B08_iqr__20240101,B08_iqr__20240201,B08_iqr__20240301,B08_iqr__20240401,B08_iqr__20240501,B08_iqr__20240601,B08_iqr__20240701,B08_iqr__20240801,B08_iqr__20240901,B08_max__20231001,B08_max__20231101,B08_max__20231201,B08_max__20240101,B08_max__20240201,B08_max__20240301,B08_max__20240401,B08_max__20240501,B08_max__20240601,B08_max__20240701,B08_max__20240801,B08_max__20240901,B08_mean__20231001,B08_mean__20231101,B08_mean__20231201,B08_mean__20240101,B08_mean__20240201,B08_mean__20240301,B08_mean__20240401,B08_mean__20240501,B08_mean__20240601,B08_mean__20240701,B08_mean__20240801,B08_mean__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_min__20231001,B08_min__20231101,B08_min__20231201,B08_min__20240101,B08_min__20240201,B08_min__20240301,B08_min__20240401,B08_min__20240501,B08_min__20240601,B08_min__20240701,B08_min__20240801,B08_min__20240901,B08_p10__20231001,B08_p10__20231101,B08_p10__20231201,B08_p10__20240101,B08_p10__20240201,B08_p10__20240301,B08_p10__20240401,B08_p10__20240501,B08_p10__20240601,B08_p10__20240701,B08_p10__20240801,B08_p10__20240901,B08_p25__20231001,B08_p25__20231101,B08_p25__20231201,B08_p25__20240101,B08_p25__20240201,B08_p25__20240301,B08_p25__20240401,B08_p25__20240501,B08_p25__20240601,B08_p25__20240701,B08_p25__20240801,B08_p25__20240901,B08_p75__20231001,B08_p75__20231101,B08_p75__20231201,B08_p75__20240101,B08_p75__20240201,B08_p75__20240301,B08_p75__20240401,B08_p75__20240501,B08_p75__20240601,B08_p75__20240701,B08_p75__20240801,B08_p75__20240901,B08_p90__20231001,B08_p90__20231101,B08_p90__20231201,B08_p90__20240101,B08_p90__20240201,B08_p90__20240301,B08_p90__20240401,B08_p90__20240501,B08_p90__20240601,B08_p90__20240701,B08_p90__20240801,B08_p90__20240901,B08_p90_p10_spread__20231001,B08_p90_p10_spread__20231101,B08_p90_p10_spread__20231201,B08_p90_p10_spread__20240101,B08_p90_p10_spread__20240201,B08_p90_p10_spread__20240301,B08_p90_p10_spread__20240401,B08_p90_p10_spread__20240501,B08_p90_p10_spread__20240601,B08_p90_p10_spread__20240701,B08_p90_p10_spread__20240801,B08_p90_p10_spread__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B08_variance__20231001,B08_variance__20231101,B08_variance__20231201,B08_variance__20240101,B08_variance__20240201,B08_variance__20240301,B08_variance__20240401,B08_variance__20240501,B08_variance__20240601,B08_variance__20240701,B08_variance__20240801,B08_variance__20240901,B11_bowley_skewness__20231001,B11_bowley_skewness__20231101,B11_bowley_skewness__20231201,B11_bowley_skewness__20240101,B11_bowley_skewness__20240201,B11_bowley_skewness__20240301,B11_bowley_skewness__20240401,B11_bowley_skewness__20240501,B11_bowley_skewness__20240601,B11_bowley_skewness__20240701,B11_bowley_skewness__20240801,B11_bowley_skewness__20240901,B11_coefficient_of_variation__20231001,B11_coefficient_of_variation__20231101,

In [6]:
# NON_FEATURE_COLUMNS = {
#     parcel_id_column, class_column, "parcel_id", "parcel_code", "class", "label", "label_code", "initial_label", "initial_label_code", "period_start", "period_end",
#     "predicted_label", "predicted_label_code", "rfv_true", "svm_novelty_full", "parcel_area_m2", "eligible_pixel_count",
#     "parcel_id", "period_start", "period_end", "geometry", "batch_number", "prediction_probability",
#     "categ_code", "data_clean_mid", "has_rfv", "normal", "svm_outlier_full", "holdout_mid", "holdout_full", "meets_minimum_pixel_count"
# }

# BASE_COLUMNS = [parcel_id_column, class_column, "geometry"]
# remove_keywords = ["B02_", "B03_", "B04_", "count", "_mean", "_p25", "_p75", "_p10", "_p90", "_variance", "_coefficient_of_variation", "_bowley_skewness"] + list(NON_FEATURE_COLUMNS)

# keep_statistics_columns = [x for x in list(gdf.columns) if all(keyword not in x for keyword in remove_keywords) and x not in BASE_COLUMNS]
# keep_columns = BASE_COLUMNS + keep_statistics_columns
# df_final = gdf[keep_columns].copy()
# print(f"Columns dropped from the merged dataframe: {[x for x in list(gdf.columns) if x not in keep_columns]}")

# numeric_or_boolean = set(df_final.select_dtypes(include=["number", "bool"]).columns)
# features = [col for col in df_final.columns if col in numeric_or_boolean and col not in BASE_COLUMNS]

# print(f"Identified {len(features)} features for modeling: {features}")

In [7]:
gdf_parcels = gdf_parcels.to_crs("EPSG:2100")
gdf_parcels["x"] = gdf_parcels.centroid.x
gdf_parcels["y"] = gdf_parcels.centroid.y

extra_features = ["elevation_mean_m", "distance_to_nearest_lake_m", "GAIOIKANOT", "x", "y"]

# original_features = ["SAVI_median__20231201", "NDVI_median__20231101", "NDWI_median__20231201", "SAVI_median__20240101", "NDVI_median__20240701", "B04_median__20240701", "NDMI_median__20231101", "NDMI_median__20231201", "NDVI_median__20231001", "NDVI_median__20240901", "NDWI_median__20240801", "NDWI_median__20240101", "B08_median__20231201", "NDRE_median__20240801", "NDRE_median__20240201", "NDMI_median__20231001", "NDMI_median__20240101", "B04_median__20231001", "EVI_median__20240601", "B08_median__20240101", "B04_median__20240901", "B11_median__20240701", "NDMI_median__20240901", "NDMI_median__20240401", "B11_median__20240501", "B12_median__20240801", "B04_median__20231101", "EVI_sd__20240101", "EVI_sd__20231201", "NDMI_sd__20240701", "EVI_sd__20240701", "NDMI_sd__20240801", "NDMI_median__20240201", "EVI_sd__20240201", "NDMI_median__20240701", "EVI_median__20240301", "B11_median__20240401", "B08_median__20231001", "B08_median__20240401", "NDRE_sd__20240701", "B08_median__20240301", "B08_median__20240201", "B08_median__20240601", "B11_median__20240301", "NDWI_median__20240601", "B04_median__20240601", "EVI_sd__20240901", "B08_median__20240901", "B03_median__20231001", "NDWI_sd__20240801", "EVI_sd__20240601", "B08_sd__20231201", "NDMI_median__20240801", "B08_median__20240701", "B04_median__20240401", "B05_median__20240501", "NDMI_sd__20240201", "NDMI_median__20240501", "NDMI_sd__20240601", "B11_median__20240901", "B08_median__20240801", "NDVI_sd__20240101", "NDVI_sd__20240201", "B11_median__20231201", "NDMI_sd__20240901", "B08_sd__20240101", "B02_median__20231101", "B05_median__20240401", "NDWI_median__20240501", "B04_median__20240201", "B08_sd__20240301", "NDWI_sd__20240601", "NDMI_median__20240601", "B12_sd__20240701", "NDRE_sd__20240201", "B12_sd__20240801", "EVI_sd__20231101", "B12_median__20231101", "B08_sd__20240901", "B04_median__20231201", "B12_sd__20240601", "NDRE_sd__20240601", "B08_sd__20240701", "B08_sd__20240201", "B11_median__20231001", "NDRE_sd__20240901", "SAVI_sd__20240501", "NDMI_sd__20240101", "B08_sd__20240801", "B04_median__20240101", "EVI_sd__20240301", "B08_sd__20240501", "NDVI_sd__20231201", "B08_sd__20231101", "B08_median__20240501", "B05_median__20240301", "B05_median__20231201", "NDMI_sd__20240501", "B08_sd__20240601", "B03_median__20240201", "NDWI_sd__20240201"]
# original_features = [x for x in gdf_parcels.columns if any(keyword in x for keyword in ["_mean", "_sd", "_min", "_max"])]

original_features = [x for x in gdf_parcels.columns if any(keyword in x for keyword in ["_median", "_sd", "_range"]) and x not in extra_features and not x.startswith("B")]
base_cols = [parcel_id_column, class_column, "geometry"]
gdf_parcels = gdf_parcels[base_cols + original_features + extra_features].copy()
features = original_features + extra_features

gdf_parcels = gdf_parcels[gdf_parcels[class_column] != 9999].copy()
print(f"Final features for modeling ({len(features)} features): {features}")
display(gdf_parcels.head(3))

Final features for modeling (221 features): ['EVI_median__20231001', 'EVI_median__20231101', 'EVI_median__20231201', 'EVI_median__20240101', 'EVI_median__20240201', 'EVI_median__20240301', 'EVI_median__20240401', 'EVI_median__20240501', 'EVI_median__20240601', 'EVI_median__20240701', 'EVI_median__20240801', 'EVI_median__20240901', 'EVI_range__20231001', 'EVI_range__20231101', 'EVI_range__20231201', 'EVI_range__20240101', 'EVI_range__20240201', 'EVI_range__20240301', 'EVI_range__20240401', 'EVI_range__20240501', 'EVI_range__20240601', 'EVI_range__20240701', 'EVI_range__20240801', 'EVI_range__20240901', 'EVI_sd__20231001', 'EVI_sd__20231101', 'EVI_sd__20231201', 'EVI_sd__20240101', 'EVI_sd__20240201', 'EVI_sd__20240301', 'EVI_sd__20240401', 'EVI_sd__20240501', 'EVI_sd__20240601', 'EVI_sd__20240701', 'EVI_sd__20240801', 'EVI_sd__20240901', 'NDMI_median__20231001', 'NDMI_median__20231101', 'NDMI_median__20231201', 'NDMI_median__20240101', 'NDMI_median__20240201', 'NDMI_median__20240301', 'NDMI_median__20240401', 'NDMI_median__20240501', 'NDMI_median__20240601', 'NDMI_median__20240701', 'NDMI_median__20240801', 'NDMI_median__20240901', 'NDMI_range__20231001', 'NDMI_range__20231101', 'NDMI_range__20231201', 'NDMI_range__20240101', 'NDMI_range__20240201', 'NDMI_range__20240301', 'NDMI_range__20240401', 'NDMI_range__20240501', 'NDMI_range__20240601', 'NDMI_range__20240701', 'NDMI_range__20240801', 'NDMI_range__20240901', 'NDMI_sd__20231001', 'NDMI_sd__20231101', 'NDMI_sd__20231201', 'NDMI_sd__20240101', 'NDMI_sd__20240201', 'NDMI_sd__20240301', 'NDMI_sd__20240401', 'NDMI_sd__20240501', 'NDMI_sd__20240601', 'NDMI_sd__20240701', 'NDMI_sd__20240801', 'NDMI_sd__20240901', 'NDRE_median__20231001', 'NDRE_median__20231101', 'NDRE_median__20231201', 'NDRE_median__20240101', 'NDRE_median__20240201', 'NDRE_median__20240301', 'NDRE_median__20240401', 'NDRE_median__20240501', 'NDRE_median__20240601', 'NDRE_median__20240701', 'NDRE_median__20240801', 'NDRE_median__20240901', 'NDRE_range__20231001', 'NDRE_range__20231101', 'NDRE_range__20231201', 'NDRE_range__20240101', 'NDRE_range__20240201', 'NDRE_range__20240301', 'NDRE_range__20240401', 'NDRE_range__20240501', 'NDRE_range__20240601', 'NDRE_range__20240701', 'NDRE_range__20240801', 'NDRE_range__20240901', 'NDRE_sd__20231001', 'NDRE_sd__20231101', 'NDRE_sd__20231201', 'NDRE_sd__20240101', 'NDRE_sd__20240201', 'NDRE_sd__20240301', 'NDRE_sd__20240401', 'NDRE_sd__20240501', 'NDRE_sd__20240601', 'NDRE_sd__20240701', 'NDRE_sd__20240801', 'NDRE_sd__20240901', 'NDVI_median__20231001', 'NDVI_median__20231101', 'NDVI_median__20231201', 'NDVI_median__20240101', 'NDVI_median__20240201', 'NDVI_median__20240301', 'NDVI_median__20240401', 'NDVI_median__20240501', 'NDVI_median__20240601', 'NDVI_median__20240701', 'NDVI_median__20240801', 'NDVI_median__20240901', 'NDVI_range__20231001', 'NDVI_range__20231101', 'NDVI_range__20231201', 'NDVI_range__20240101', 'NDVI_range__20240201', 'NDVI_range__20240301', 'NDVI_range__20240401', 'NDVI_range__20240501', 'NDVI_range__20240601', 'NDVI_range__20240701', 'NDVI_range__20240801', 'NDVI_range__20240901', 'NDVI_sd__20231001', 'NDVI_sd__20231101', 'NDVI_sd__20231201', 'NDVI_sd__20240101', 'NDVI_sd__20240201', 'NDVI_sd__20240301', 'NDVI_sd__20240401', 'NDVI_sd__20240501', 'NDVI_sd__20240601', 'NDVI_sd__20240701', 'NDVI_sd__20240801', 'NDVI_sd__20240901', 'NDWI_median__20231001', 'NDWI_median__20231101', 'NDWI_median__20231201', 'NDWI_median__20240101', 'NDWI_median__20240201', 'NDWI_median__20240301', 'NDWI_median__20240401', 'NDWI_median__20240501', 'NDWI_median__20240601', 'NDWI_median__20240701', 'NDWI_median__20240801', 'NDWI_median__20240901', 'NDWI_range__20231001', 'NDWI_range__20231101', 'NDWI_range__20231201', 'NDWI_range__20240101', 'NDWI_range__20240201', 'NDWI_range__20240301', 'NDWI_range__20240401', 'NDWI_range__20240501', 'NDWI_range__20240601', 'NDWI_range__20240701', 'NDWI_range__20240801', 'NDWI_range__20240901', 'NDWI_sd__20231001', 'NDWI_sd__20231101', 'NDWI_sd__20231201', 'NDWI_sd__20240101', 'NDWI_sd__20240201', 'NDWI_sd__20240301', 'NDWI_sd__20240401', 'NDWI_sd__20240501', 'NDWI_sd__20240601', 'NDWI_sd__20240701', 'NDWI_sd__20240801', 'NDWI_sd__20240901', 'SAVI_median__20231001', 'SAVI_median__20231101', 'SAVI_median__20231201', 'SAVI_median__20240101', 'SAVI_median__20240201', 'SAVI_median__20240301', 'SAVI_median__20240401', 'SAVI_median__20240501', 'SAVI_median__20240601', 'SAVI_median__20240701', 'SAVI_median__20240801', 'SAVI_median__20240901', 'SAVI_range__20231001', 'SAVI_range__20231101', 'SAVI_range__20231201', 'SAVI_range__20240101', 'SAVI_range__20240201', 'SAVI_range__20240301', 'SAVI_range__20240401', 'SAVI_range__20240501', 'SAVI_range__20240601', 'SAVI_range__20240701', 'SAVI_range__20240801', 'SAVI_range__20240901', 'SAVI_sd__20231001', 'SAVI_sd__20231101', 'SAVI_sd__20231201', 'SAVI_sd__20240101', 'SAVI_sd__20240201', 'SAVI_sd__20240301', 'SAVI_sd__20240401', 'SAVI_sd__20240501', 'SAVI_sd__20240601', 'SAVI_sd__20240701', 'SAVI_sd__20240801', 'SAVI_sd__20240901', 'elevation_mean_m', 'distance_to_nearest_lake_m', 'GAIOIKANOT', 'x', 'y']

,parcel_code,label,geometry,EVI_median__20231001,EVI_median__20231101,EVI_median__20231201,EVI_median__20240101,EVI_median__20240201,EVI_median__20240301,EVI_median__20240401,EVI_median__20240501,EVI_median__20240601,EVI_median__20240701,EVI_median__20240801,EVI_median__20240901,EVI_range__20231001,EVI_range__20231101,EVI_range__20231201,EVI_range__20240101,EVI_range__20240201,EVI_range__20240301,EVI_range__20240401,EVI_range__20240501,EVI_range__20240601,EVI_range__20240701,EVI_range__20240801,EVI_range__20240901,EVI_sd__20231001,EVI_sd__20231101,EVI_sd__20231201,EVI_sd__20240101,EVI_sd__20240201,EVI_sd__20240301,EVI_sd__20240401,EVI_sd__20240501,EVI_sd__20240601,EVI_sd__20240701,EVI_sd__20240801,EVI_sd__20240901,NDMI_median__20231001,NDMI_median__20231101,NDMI_median__20231201,NDMI_median__20240101,NDMI_median__20240201,NDMI_median__20240301,NDMI_median__20240401,NDMI_median__20240501,NDMI_median__20240601,NDMI_median__20240701,NDMI_median__20240801,NDMI_median__20240901,NDMI_range__20231001,NDMI_range__20231101,NDMI_range__20231201,NDMI_range__20240101,NDMI_range__20240201,NDMI_range__20240301,NDMI_range__20240401,NDMI_range__20240501,NDMI_range__20240601,NDMI_range__20240701,NDMI_range__20240801,NDMI_range__20240901,NDMI_sd__20231001,NDMI_sd__20231101,NDMI_sd__20231201,NDMI_sd__20240101,NDMI_sd__20240201,NDMI_sd__20240301,NDMI_sd__20240401,NDMI_sd__20240501,NDMI_sd__20240601,NDMI_sd__20240701,NDMI_sd__20240801,NDMI_sd__20240901,NDRE_median__20231001,NDRE_median__20231101,NDRE_median__20231201,NDRE_median__20240101,NDRE_median__20240201,NDRE_median__20240301,NDRE_median__20240401,NDRE_median__20240501,NDRE_median__20240601,NDRE_median__20240701,NDRE_median__20240801,NDRE_median__20240901,NDRE_range__20231001,NDRE_range__20231101,NDRE_range__20231201,NDRE_range__20240101,NDRE_range__20240201,NDRE_range__20240301,NDRE_range__20240401,NDRE_range__20240501,NDRE_range__20240601,NDRE_range__20240701,NDRE_range__20240801,NDRE_range__20240901,NDRE_sd__20231001,NDRE_sd__20231101,NDRE_sd__20231201,NDRE_sd__20240101,NDRE_sd__20240201,NDRE_sd__20240301,NDRE_sd__20240401,NDRE_sd__20240501,NDRE_sd__20240601,NDRE_sd__20240701,NDRE_sd__20240801,NDRE_sd__20240901,NDVI_median__20231001,NDVI_median__20231101,NDVI_median__20231201,NDVI_median__20240101,NDVI_median__20240201,NDVI_median__20240301,NDVI_median__20240401,NDVI_median__20240501,NDVI_median__20240601,NDVI_median__20240701,NDVI_median__20240801,NDVI_median__20240901,NDVI_range__20231001,NDVI_range__20231101,NDVI_range__20231201,NDVI_range__20240101,NDVI_range__20240201,NDVI_range__20240301,NDVI_range__20240401,NDVI_range__20240501,NDVI_range__20240601,NDVI_range__20240701,NDVI_range__20240801,NDVI_range__20240901,NDVI_sd__20231001,NDVI_sd__20231101,NDVI_sd__20231201,NDVI_sd__20240101,NDVI_sd__20240201,NDVI_sd__20240301,NDVI_sd__20240401,NDVI_sd__20240501,NDVI_sd__20240601,NDVI_sd__20240701,NDVI_sd__20240801,NDVI_sd__20240901,NDWI_median__20231001,NDWI_median__20231101,NDWI_median__20231201,NDWI_median__20240101,NDWI_median__20240201,NDWI_median__20240301,NDWI_median__20240401,NDWI_median__20240501,NDWI_median__20240601,NDWI_median__20240701,NDWI_median__20240801,NDWI_median__20240901,NDWI_range__20231001,NDWI_range__20231101,NDWI_range__20231201,NDWI_range__20240101,NDWI_range__20240201,NDWI_range__20240301,NDWI_range__20240401,NDWI_range__20240501,NDWI_range__20240601,NDWI_range__20240701,NDWI_range__20240801,NDWI_range__20240901,NDWI_sd__20231001,NDWI_sd__20231101,NDWI_sd__20231201,NDWI_sd__20240101,NDWI_sd__20240201,NDWI_sd__20240301,NDWI_sd__20240401,NDWI_sd__20240501,NDWI_sd__20240601,NDWI_sd__20240701,NDWI_sd__20240801,NDWI_sd__20240901,SAVI_median__20231001,SAVI_median__20231101,SAVI_median__20231201,SAVI_median__20240101,SAVI_median__20240201,SAVI_median__20240301,SAVI_median__20240401,SAVI_median__20240501,SAVI_median__20240601,SAVI_median__20240701,SAVI_median__20240801,SAVI_median__20240901,SAVI_range__20231001,SAVI_range__20231101,SAVI_range__20231201,SAVI_range__20240101,SAVI_range__20240201,SAVI_range__20240301,SAVI_range__20240401,SAVI_range__20240501,SAVI_range__20240601,SAVI_range__20240701,SAVI_range__20240801,SAVI_range__20240901,SAVI_sd__20231001,SAVI_sd__20231101,SAVI_sd__20231201,SAVI_sd__20240101,SAVI_sd__20240201,SAVI_sd__20240301,SAVI_sd__20240401,SAVI_sd__20240501,SAVI_sd__20240601,SAVI_sd__20240701,SAVI_sd__20240801,SAVI_sd__20240901,elevation_mean_m,distance_to_nearest_lake_m,GAIOIKANOT,x,y
0,266124977,110,POLYGON ((346567...,0.5013272166,0.4966667891,0.4398130774,0.4661100507,0.4015560150,0.5395985842,0.6675298214,0.7141814232,0.4574473798,0.1879952848,0.1533288360,0.2189066112,0.2452494502,0.2780103087,0.3413347453,0.3872469515,0.2890205383,0.4000341296,0.3967901170,0.3517332375,0.2876405120,0.4189238846,0.3659896553,0.2515158951,0.0674657767,0.0749009513,0.0959265907,0.0977102635,0.0790079022,0.1126087099,0.1076306306,0.0857285582,0.0686453327,0.1078016084,0.0907195786,0.0612479712,0.1120132953,0.1183981150,0.0456872731,0.0894620568,0.0277879983,0.1449306011,0.2428329140,0.3579010367,0.1536271423,-0.1768553555,-0.2798199058,-0.2177819014,0.1719973832,0.2101558596,0.2463874817,0.1896898355,0.2017836496,0.2749164551,0.2410296425,0.2216183990,0.2025797814,0.4041156173,0.3639544025,0.2752623988,0.0371723127,0.0417705835,0.0570056827,0.0458961948,0.0470503599,0.0697757064,0.0669521559,0.0562271091,0.0509217054,0.1139543814,0.1070873602,0.0823261781,0.4809325337,0.4583089054,0.4012213945,0.3658924103,0.3752249479,0.4610086083,0.5314143896,0.5695176125,0.3933027983,0.2055193186,0.1494550258,0.2013412714,0.1731682718,0.2009385228,0.1725167930,0.1598020494,0.1561547518,0.2411462069,0.2120617926,0.1828298569,0.1896772683,0.3073446304,0.2690239549,0.1507900953,0.0406474234,0.0417976277,0.0417649154,0.0409761329,0.0361716909,0.0632918200,0.0582001548,0.0431817719,0.0500703475,0.0852893479,0.0781196986,0.0410100638,0.7663152218,0.7460404038,0.6869605780,0.6086053848,0.6074448824,0.7284209132,0.7803788185,0.8440637589,0.6125147343,0.3046587706,0.2512516379,0.3010734022,0.2281584144,0.2020541430,0.3013764322,0.3928505480,0.2746299803,0.3051317334,0.3426735699,0.2822874188,0.3040536642,0.4825323224,0.4466506690,0.3028556406,0.0609292592,0.0535207101,0.0779093265,0.0814745358,0.0708199179,0.0927705691,0.0810177915,0.0567371918,0.0720943136,0.1239318626,0.1120876018,0.0697670208,-0.6832424998,-0.6745974422,-0.6684315205,-0.6071170568,-0.6508895159,-0.6835615635,-0.7021911144,-0.7358894348,-0.6180349588,-0.4717560709,-0.4118033648,-0.3701940775,0.1589583158,0.1104247570,0.1328761578,0.2524721920,0.1998926699,0.2134704590,0.2271878719,0.2357103229,0.2097273469,0.2889140546,0.2648768425,0.2195775211,0.0302052250,0.0229308006,0.0323772132,0.0447083813,0.0410585584,0.0529883618,0.0496191007,0.0438109615,0.0381017801,0.0721644791,0.0653132635,0.0504854334,0.4747310281,0.4709782600,0.4362256229,0.4176775217,0.3992842436,0.5001245737,0.5763255358,0.6312261820,0.4413691461,0.2009874582,0.1584077626,0.1931137741,0.1859286726,0.2179936171,0.2834599912,0.3257224411,0.2489628643,0.3162204921,0.3087626398,0.2772105634,0.2386403084,0.3819130063,0.3282271624,0.2036059648,0.0508637926,0.0585448700,0.0820820428,0.0791208994,0.0686597443,0.0910982419,0.0786347848,0.0624612902,0.0555042033,0.0976318782,0.0834263264,0.0514574217,962.9800950958,20544.5263987583,W7W8-121-1-D9NB,346612.3019424750,4442005.7826928208
1,26857194,119,POLYGON ((336782...,0.5980167389,0.5013685226,0.4589431286,0.4714537561,0.4740579426,0.6784462929,0.5754303336,0.5917055607,0.2839187086,0.2259694040,0.2299657166,0.4476020038,0.3573357165,0.3747292608,0.2673075795,0.2391919196,0.2292088866,0.2928489745,0.1147629321,0.2996077240,0.3091229200,0.3857370764,0.3672036082,0.3009695411,0.0716242410,0.0802252060,0.0584453427,0.0597284575,0.0545353545,0.0696748616,0.0312486921,0.0721114139,0.0692011131,0.0859962520,0.0807574252,0.0614420376,0.2482582927,0.2354647964,0.1698043495,0.1790216863,0.1725512892,0.3594477177,0.2337177992,0.2714888155,-0.0388582759,-0.0469922274,-0.0397130288,0.1062965542,0.2838667994,0.3371310718,0.2422997882,0.1835271642,0.1940316297,0.2166395634,0.1191810817,0.2135900855,0.2663979456,0.2464742362,0.2277110964,0.1665631235,0.0622154081,0.0690297818,0.0514828307,0.0486134269,0.0450277528,0.0517554162,0.0282338718,0.0597790008,0.0580214367,0.0532136469,0.0492651143,0.0354293883,0.5414769053,0.4864338934,0.4308448434,0.4180441797,0.4222440720,0.5832678080,0.4782084823,0.5399959683,0.2591632903,0.2102443874,0.2113009393,0.3533682227,0.2178387940,0.2761801481,0.1808592081,0.1745369136,0.1443869770,0.1937131286,0.1702551246,0.2108606696,0.2798782140,0.2727999538,0.2656570673,0.2022463083,0.0462034607,0.0540911526,0.0459338407,0.0484661403,0.0394253765,0.0532357082,0.0409379700,0.0574654257,0.0656470304,0.0596559691,0.0594970165,0.0398327917,0.8262054324,0.7717168927,0.7152909636,0.6874842048,0.6618391871,0.8402702212,0.7825385928,0.7743046880,0.3752181530,0.2901047170,0.2966190279,0.4893450439,0.3583840132,0.3974571228,0.2960990965,0.2820232809,0.2343487144,0.2429909706,0.2029501796,0.3013332486,0.3196071386,0.4323092997,0.4559172839,0.3577525020,0.0675660744,0.0808313693,0.0725708697,0.0766780167,0.0652464258,0.0687496005,0.0543422920,0.0705536814,0.0774540260,0.1013750718,0.1042317483,0.0687534768,-0.7212035656,-0.6738502383,-0.6726874709,-0.6571717262,-0.6517614722,-0.7456002831,-0.6725685000,-0.6951274276,-0.4808043838,-0.4344163537,-0.4314274192,-0.4934797585,0.1956695914,0.2084664702,0.1580619812,0.1521027684,0.1645798683,0.1858863831,0.1380378008,0.1869733334,0.2662913799,0.2925388515,0.2993217707,0.2868539989,0.0403132997,0.0412012290,0.0394216633,0.0439743700,0.0413524165,0.0441731573,0.0314467947,0.0465441981,0.0598473056,0.0672237611,0.0672516572,0.0672848206,0.5484842062,0.4799362421,0.4551311731,0.4555079937,0.4559293091,0.6088715792,0.5374229550,0.5404234529,0.2772311866,0.2359457910,0.2386108786,0.3772789240,0.2900436521,0.3214910775,0.2345328927,0.2056999505,0.1900741160,0.2215789557,0.1180117130,0.2447978854,0.2664266527,0.3185004890,0.3199270219,0.2570242286,0.0581650890,0.0676139185,0.0520816490,0.0513942900,0.0464532347,0.0558847826,0.0284358626,0.0576758581,0.0620908211,0.0733989177,0.0706610012,0.0477914751,520.8588431222,19005.4329618684,T7T3-121-1-D9QQ,336810.1776891265,4435858.9435133608
2,26857195,119,POLYGON ((335690...,0.4583157599,0.4699067175,0.3989100158,0.3866666257,0.3687561750,0.5054290295,0.4448435903,0.3431333303,0.2421924770,0.1649617702,0.1589863300,0.4517584145,0.2102037370,0.2156883776,0.2588203549,0.2283836305,0.1709502339,0.2332803905,0.3166381419,0.1514345109,0.1230395734,0.1456402689,0.1451570243,0.3162572831,0.0414741378,0.0464019763,0.0543021004,0.0490637302,0.0377760081,0.0473218925,0.0636281127,0.0323725726,0.0247712397,0.0235548937,0.0214211334,0.0579851106,0.1405680925,0.2175546587,0.1053143665,0.1131270081,0.0711686611,0.2157126218,0.1705166847,0.0246732533,-0.0960139483,-0.1265787780,-0.1398881227,0.0874725431,0.1758835316,0.1732424721,0.1932881139,0.1780764554,0.1257819729,0.1624664962,0.1257784963,0.1079701986,0.1331428413,0.1531914417,0.1513697393,0.2783580348,0.0388014146,0.0304304338,0.0353545379,0.0370223370,0.0257977480,0.0281431090,0.0344697868,0.0244754325,0.0284932597,0.0345778348,0.0341007773,0.0468015434,0.4402024150,0.4508683085,0.3715498447,0.3618200123,0.3500941396,0.4613065422,0.3774537146,0.2906661630,0.2049877048,0.1428571492,0.1393961161,0.3926847279,0.1018699408,0.0944218338,0.1502012610,0.1245513856,0.1140321791,0.1349147856,0.1251721978,0.1050192118,0.1343960315,0.1643943489,0.1853229702,0.2230362296,0.0187099644,0.0214224055,0.0269532230,0.0230916994,0.0218537305,0.0304699636,0.0294509643,0.0238498864,0.0287026758,0.0338952528,0.0345569056,0.0448150227,0.6825035810,0.7151668072,0.6285448670,0.6012706161,0.5636461377,0.7217068672,0.5885167718,0.4692246020,0.3316062391,0.2327159047,0.2240094244,0.5859913826,0.2225559950,0.2451117635,0.3303871751,0.2555853426,0.2235288024,0.2781740427,0.3222301900,0.2022574246,0.1682726443,0.2416274101,0.2291425467,0.3296716213,0.0519899518,0.0534142762,0.0598448972,0.0482030618,0.0457124128,0.0618772369,0.0751746555,0.0428120150,0.0361871495,0.0377456882,0.0346027221,0.0738807348,-0.6268574595,-0.6524690986,-0.6260023117,-0.6162708402,-0.6017522812,-0.6837944388,-0.5877172947,-0.5163291097,-0.4316229820,-0.4025546014,-0.3948462307,-0.5974358320,0.1394040585,0.1715693474,0.2154020965,0.1906759143,0.1545325518,0.2002032995,0.1988477707,0.1542553306,0.1764305234,0.1733103991,0.1866970956,0.2017835081,0.0321853009,0.0371795328,0.0407079057,0.0346543489,0.0344649393,0.0440390322,0.0455115541,0.0317998851,0.0336821154,0.0310026664,0.0296540559,0.0525381409,0.4393728375,0.4498147070,0.3947741687,0.3843870163,0.3666895330,0.4840319753,0.4180378914,0.3327272832,0.2403924614,0.1767353117,0.1702454090,0.4276164472,0.1764706075,0.1694249213,0.2249415815,0.1906811893,0.1534688175,0.1965949535,0.1886561513,0.1322753131,0.1062803566,0.1490525082,0.1436979771,0.2617023140,0.0351856930,0.0371738153,0.0468382193,0.0419605854,0.0335463783,0.0408039918,0.0391740874,0.0253590244,0.0230876649,0.0238857485,0.0212603461,0.0504146686,620.2515800369,17940.1907408003,T3T7-462-1-D5BN,335715.4024644959,4436093.0072935894

In [ ]:
config = ClassificationPipelineConfig(
    project_dir=OUTPUT_PATH,
    target_column=class_column,
    feature_columns=features,
    id_column=parcel_id_column,

    apply_iqr=False,
    spatial_interpolation_method="nearest",
    spatial_interpolation_max_distance_in_meters=500,

    cv_folds=5,
    test_size=0.2,
    spatial_split=True,
    spatial_split_grid_size=10,
    spatial_split_method="by_row",  # or "by_group"

    random_state=SEED_NUMBER,
    n_jobs=4,

    scoring_primary="f1_macro",
    cv_ranking_method="score_minus_std",
    selection_type="soft_voting",
    top_voting_models=3,
    max_search_candidates=40,
    prediction_confidence_threshold=0.60,
    interpretability_top_models=3,
    interpretability_include_shap=True,

    optimize_class_probabilities=False,
    probability_multiplier_grid=(0.8, 1.0, 1.2, 1.5, 2.0),
    probability_optimization_iterations=2,
    probability_optimization_max_accuracy_drop=0.02,

    label_balancing_method="random_oversample",  # alternatively: "none", "random_oversample" or "smote"
    selected_models=(
        #"gradient_boosting",
        #"hist_gradient_boosting",
        "bagging",
        "random_forest",
        # "decision_tree",
        "extra_trees",
        # "bayesian",
        #"xgboost",
        #"lightgbm",
        # "knn",
        "neural_network"
   ),
    max_map_geometries=20000,
    open_html_report=True,
)
pipeline = GeospatialClassificationPipeline(config)

In [9]:
summary_check = pipeline.run_check(df=gdf_parcels)
summary_check

=========================================================
Function <run_check> started on 2026-08-16 18:46:30

Checking input data...

Resetting project output folder: C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1
Deleting folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\01_check'...
Successfully deleted folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\01_check' on attempt 1
Deleting folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\02_prepare'...
Successfully deleted folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\02_prepare' on attempt 1
Deleting folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\03_train'...
Successfully deleted folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\03_train' on attempt 1
Deleting folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\04_evaluate'...
Successfully deleted folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\04_evaluate' on attempt 1
Deleting folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\05_predict'...
Successfully deleted folder 'C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1\05_predict' on attempt 1

Recreated project output folders under: C:\work_dir\kozani-2023-2024\3_ml_classification_tune_probabilities1

IQR feature filtering: {'applied': False, 'lower_quantile': 0.25, 'upper_quantile': 0.75, 'multiplier': 1.5, 'outlier_counts': {}, 'total_outliers_replaced': 0, 'bounds': {}, 'skipped_non_numeric_features': ['GAIOIKANOT']}

Feature nulls before spatial interpolation: {}

Feature nulls after spatial interpolation: {}

Requested features: ['EVI_median__20231001', 'EVI_median__20231101', 'EVI_median__20231201', 'EVI_median__20240101', 'EVI_median__20240201', 'EVI_median__20240301', 'EVI_median__20240401', 'EVI_median__20240501', 'EVI_median__20240601', 'EVI_median__20240701', 'EVI_median__20240801', 'EVI_median__20240901', 'EVI_range__20231001', 'EVI_range__20231101', 'EVI_range__20231201', 'EVI_range__20240101', 'EVI_range__20240201', 'EVI_range__20240301', 'EVI_range__20240401', 'EVI_range__20240501', 'EVI_range__20240601', 'EVI_range__20240701', 'EVI_range__20240801', 'EVI_range__20240901', 'EVI_sd__20231001', 'EVI_sd__20231101', 'EVI_sd__20231201', 'EVI_sd__20240101', 'EVI_sd__20240201', 'EVI_sd__20240301', 'EVI_sd__20240401', 'EVI_sd__20240501', 'EVI_sd__20240601', 'EVI_sd__20240701', 'EVI_sd__20240801', 'EVI_sd__20240901', 'NDMI_median__20231001', 'NDMI_median__20231101', 'NDMI_median__20231201', 'NDMI_median__20240101', 'NDMI_median__20240201', 'NDMI_median__20240301', 'NDMI_median__20240401', 'NDMI_median__20240501', 'NDMI_median__20240601', 'NDMI_median__20240701', 'NDMI_median__20240801', 'NDMI_median__20240901', 'NDMI_range__20231001', 'NDMI_range__20231101', 'NDMI_range__20231201', 'NDMI_range__20240101', 'NDMI_range__20240201', 'NDMI_range__20240301', 'NDMI_range__20240401', 'NDMI_range__20240501', 'NDMI_range__20240601', 'NDMI_range__20240701', 'NDMI_range__20240801', 'NDMI_range__20240901', 'NDMI_sd__20231001', 'NDMI_sd__20231101', 'NDMI_sd__20231201', 'NDMI_sd__20240101', 'NDMI_sd__20240201', 'NDMI_sd__20240301', 'NDMI_sd__20240401', 'NDMI_sd__20240501', 'NDMI_sd__20240601', 'NDMI_sd__20240701', 'NDMI_sd__20240801', 'NDMI_sd__20240901', 'NDRE_median__20231001', 'NDRE_median__20231101', 'NDRE_median__20231201', 'NDRE_median__20240101', 'NDRE_median__20240201', 'NDRE_median__20240301', 'NDRE_median__20240401', 'NDRE_median__20240501', 'NDRE_median__20240601', 'NDRE_median__20240701', 'NDRE_median__20240801', 'NDRE_median__20240901', 'NDRE_range__20231001', 'NDRE_range__20231101', 'NDRE_range__20231201', 'NDRE_range__20240101', 'NDRE_range__20240201', 'NDRE_range__20240301', 'NDRE_range__20240401', 'NDRE_range__20240501', 'NDRE_range__20240601', 'NDRE_range__20240701', 'NDRE_range__20240801', 'NDRE_range__20240901', 'NDRE_sd__20231001', 'NDRE_sd__20231101', 'NDRE_sd__20231201', 'NDRE_sd__20240101', 'NDRE_sd__20240201', 'NDRE_sd__20240301', 'NDRE_sd__20240401', 'NDRE_sd__20240501', 'NDRE_sd__20240601', 'NDRE_sd__20240701', 'NDRE_sd__20240801', 'NDRE_sd__20240901', 'NDVI_median__20231001', 'NDVI_median__20231101', 'NDVI_median__20231201', 'NDVI_median__20240101', 'NDVI_median__20240201', 'NDVI_median__20240301', 'NDVI_median__20240401', 'NDVI_median__20240501', 'NDVI_median__20240601', 'NDVI_median__20240701', 'NDVI_median__20240801', 'NDVI_median__20240901', 'NDVI_range__20231001', 'NDVI_range__20231101', 'NDVI_range__20231201', 'NDVI_range__20240101', 'NDVI_range__20240201', 'NDVI_range__20240301', 'NDVI_range__20240401', 'NDVI_range__20240501', 'NDVI_range__20240601', 'NDVI_range__20240701', 'NDVI_range__20240801', 'NDVI_range__20240901', 'NDVI_sd__20231001', 'NDVI_sd__20231101', 'NDVI_sd__20231201', 'NDVI_sd__20240101', 'NDVI_sd__20240201', 'NDVI_sd__20240301', 'NDVI_sd__20240401', 'NDVI_sd__20240501', 'NDVI_sd__20240601', 'NDVI_sd__20240701', 'NDVI_sd__20240801', 'NDVI_sd__20240901', 'NDWI_median__20231001', 'NDWI_median__20231101', 'NDWI_median__20231201', 'NDWI_median__20240101', 'NDWI_median__20240201', 'NDWI_median__20240301', 'NDWI_median__20240401', 'NDWI_median__20240501', 'NDWI_median__20240601', 'NDWI_median__20240701', 'NDWI_median__20240801', 'NDWI_median__20240901', 'NDWI_range__20231001', 'NDWI_range__20231101', 'NDWI_range__20231201', 'NDWI_range__20240101', 'NDWI_range__20240201', 'NDWI_range__20240301', 'NDWI_range__20240401', 'NDWI_range__20240501', 'NDWI_range__20240601', 'NDWI_range__20240701', 'NDWI_range__20240801', 'NDWI_range__20240901', 'NDWI_sd__20231001', 'NDWI_sd__20231101', 'NDWI_sd__20231201', 'NDWI_sd__20240101', 'NDWI_sd__20240201', 'NDWI_sd__20240301', 'NDWI_sd__20240401', 'NDWI_sd__20240501', 'NDWI_sd__20240601', 'NDWI_sd__20240701', 'NDWI_sd__20240801', 'NDWI_sd__20240901', 'SAVI_median__20231001', 'SAVI_median__20231101', 'SAVI_median__20231201', 'SAVI_median__20240101', 'SAVI_median__20240201', 'SAVI_median__20240301', 'SAVI_median__20240401', 'SAVI_median__20240501', 'SAVI_median__20240601', 'SAVI_median__20240701', 'SAVI_median__20240801', 'SAVI_median__20240901', 'SAVI_range__20231001', 'SAVI_range__20231101', 'SAVI_range__20231201', 'SAVI_range__20240101', 'SAVI_range__20240201', 'SAVI_range__20240301', 'SAVI_range__20240401', 'SAVI_range__20240501', 'SAVI_range__20240601', 'SAVI_range__20240701', 'SAVI_range__20240801', 'SAVI_range__20240901', 'SAVI_sd__20231001', 'SAVI_sd__20231101', 'SAVI_sd__20231201', 'SAVI_sd__20240101', 'SAVI_sd__20240201', 'SAVI_sd__20240301', 'SAVI_sd__20240401', 'SAVI_sd__20240501', 'SAVI_sd__20240601', 'SAVI_sd__20240701', 'SAVI_sd__20240801', 'SAVI_sd__20240901', 'elevation_mean_m', 'distance_to_nearest_lake_m', 'GAIOIKANOT', 'x', 'y']
Writing file: C:/work_dir/kozani-2023-2024/3_ml_classification_tune_probabilities1/01_check/feature_profile.csv

Checked 55985 rows with 221 active features.

Execution time of function <run_check> ended on 2026-08-16 18:46:51 - duration: 00:00:20
==============================================================================================

{'rows_total': 55985,
 'rows_labeled': 55985,
 'rows_unknown_target': 0,
 'n_features_requested': 221,
 'n_features_active': 221,
 'numeric_features': ['EVI_median__20231001',
  'EVI_median__20231101',
  'EVI_median__20231201',
  'EVI_median__20240101',
  'EVI_median__20240201',
  'EVI_median__20240301',
  'EVI_median__20240401',
  'EVI_median__20240501',
  'EVI_median__20240601',
  'EVI_median__20240701',
  'EVI_median__20240801',
  'EVI_median__20240901',
  'EVI_range__20231001',
  'EVI_range__20231101',
  'EVI_range__20231201',
  'EVI_range__20240101',
  'EVI_range__20240201',
  'EVI_range__20240301',
  'EVI_range__20240401',
  'EVI_range__20240501',
  'EVI_range__20240601',
  'EVI_range__20240701',
  'EVI_range__20240801',
  'EVI_range__20240901',
  'EVI_sd__20231001',
  'EVI_sd__20231101',
  'EVI_sd__20231201',
  'EVI_sd__20240101',
  'EVI_sd__20240201',
  'EVI_sd__20240301',
  'EVI_sd__20240401',
  'EVI_sd__20240501',
  'EVI_sd__20240601',
  'EVI_sd__20240701',
  'EVI_sd__20240801',
  'EVI_sd__20240901',
  'NDMI_median__20231001',
  'NDMI_median__20231101',
  'NDMI_median__20231201',
  'NDMI_median__20240101',
  'NDMI_median__20240201',
  'NDMI_median__20240301',
  'NDMI_median__20240401',
  'NDMI_median__20240501',
  'NDMI_median__20240601',
  'NDMI_median__20240701',
  'NDMI_median__20240801',
  'NDMI_median__20240901',
  'NDMI_range__20231001',
  'NDMI_range__20231101',
  'NDMI_range__20231201',
  'NDMI_range__20240101',
  'NDMI_range__20240201',
  'NDMI_range__20240301',
  'NDMI_range__20240401',
  'NDMI_range__20240501',
  'NDMI_range__20240601',
  'NDMI_range__20240701',
  'NDMI_range__20240801',
  'NDMI_range__20240901',
  'NDMI_sd__20231001',
  'NDMI_sd__20231101',
  'NDMI_sd__20231201',
  'NDMI_sd__20240101',
  'NDMI_sd__20240201',
  'NDMI_sd__20240301',
  'NDMI_sd__20240401',
  'NDMI_sd__20240501',
  'NDMI_sd__20240601',
  'NDMI_sd__20240701',
  'NDMI_sd__20240801',
  'NDMI_sd__20240901',
  'NDRE_median__20231001',
  'NDRE_median__20231101',
  'NDRE_median__20231201',
  'NDRE_median__20240101',
  'NDRE_median__20240201',
  'NDRE_median__20240301',
  'NDRE_median__20240401',
  'NDRE_median__20240501',
  'NDRE_median__20240601',
  'NDRE_median__20240701',
  'NDRE_median__20240801',
  'NDRE_median__20240901',
  'NDRE_range__20231001',
  'NDRE_range__20231101',
  'NDRE_range__20231201',
  'NDRE_range__20240101',
  'NDRE_range__20240201',
  'NDRE_range__20240301',
  'NDRE_range__20240401',
  'NDRE_range__20240501',
  'NDRE_range__20240601',
  'NDRE_range__20240701',
  'NDRE_range__20240801',
  'NDRE_range__20240901',
  'NDRE_sd__20231001',
  'NDRE_sd__20231101',
  'NDRE_sd__20231201',
  'NDRE_sd__20240101',
  'NDRE_sd__20240201',
  'NDRE_sd__20240301',
  'NDRE_sd__20240401',
  'NDRE_sd__20240501',
  'NDRE_sd__20240601',
  'NDRE_sd__20240701',
  'NDRE_sd__20240801',
  'NDRE_sd__20240901',
  'NDVI_median__20231001',
  'NDVI_median__20231101',
  'NDVI_median__20231201',
  'NDVI_median__20240101',
  'NDVI_median__20240201',
  'NDVI_median__20240301',
  'NDVI_median__20240401',
  'NDVI_median__20240501',
  'NDVI_median__20240601',
  'NDVI_median__20240701',
  'NDVI_median__20240801',
  'NDVI_median__20240901',
  'NDVI_range__20231001',
  'NDVI_range__20231101',
  'NDVI_range__20231201',
  'NDVI_range__20240101',
  'NDVI_range__20240201',
  'NDVI_range__20240301',
  'NDVI_range__20240401',
  'NDVI_range__20240501',
  'NDVI_range__20240601',
  'NDVI_range__20240701',
  'NDVI_range__20240801',
  'NDVI_range__20240901',
  'NDVI_sd__20231001',
  'NDVI_sd__20231101',
  'NDVI_sd__20231201',
  'NDVI_sd__20240101',
  'NDVI_sd__20240201',
  'NDVI_sd__20240301',
  'NDVI_sd__20240401',
  'NDVI_sd__20240501',
  'NDVI_sd__20240601',
  'NDVI_sd__20240701',
  'NDVI_sd__20240801',
  'NDVI_sd__20240901',
  'NDWI_median__20231001',
  'NDWI_median__20231101',
  'NDWI_median__20231201',
  'NDWI_median__20240101',
  'NDWI_median__20240201',
  'NDWI_median__20240301',
  'NDWI_median__20240401',
  'NDWI_median__20240501',
  'NDWI_median__20240601',
  'NDWI_median__20240701',
  'NDWI_median__20240801',
  'NDWI_median__20240901',
  'NDWI_range__20231001',
  'NDWI_range__20231101',
  'NDWI_range__20231201',
  'NDWI_range__20240101',
  'NDWI_range__20240201',
  'NDWI_range__20240301',
  'NDWI_range__20240401',
  'NDWI_range__20240501',
  'NDWI_range__20240601',
  'NDWI_range__20240701',
  'NDWI_range__20240801',
  'NDWI_range__20240901',
  'NDWI_sd__20231001',
  'NDWI_sd__20231101',
  'NDWI_sd__20231201',
  'NDWI_sd__20240101',
  'NDWI_sd__20240201',
  'NDWI_sd__20240301',
  'NDWI_sd__20240401',
  'NDWI_sd__20240501',
  'NDWI_sd__20240601',
  'NDWI_sd__20240701',
  'NDWI_sd__20240801',
  'NDWI_sd__20240901',
  'SAVI_median__20231001',
  'SAVI_median__20231101',
  'SAVI_median__20231201',
  'SAVI_median__20240101',
  'SAVI_median__20240201',
  'SAVI_median__20240301',
  'SAVI_median__20240401',
  'SAVI_median__20240501',
  'SAVI_median__20240601',
  'SAVI_median__20240701',
  'SAVI_median__20240801',
  'SAVI_median__20240901',
  'SAVI_range__20231001',
  'SAVI_range__20231101',
  'SAVI_range__20231201',
  'SAVI_range__20240101',
  'SAVI_range__20240201',
  'SAVI_range__20240301',
  'SAVI_range__20240401',
  'SAVI_range__20240501',
  'SAVI_range__20240601',
  'SAVI_range__20240701',
  'SAVI_range__20240801',
  'SAVI_range__20240901',
  'SAVI_sd__20231001',
  'SAVI_sd__20231101',
  'SAVI_sd__20231201',
  'SAVI_sd__20240101',
  'SAVI_sd__20240201',
  'SAVI_sd__20240301',
  'SAVI_sd__20240401',
  'SAVI_sd__20240501',
  'SAVI_sd__20240601',
  'SAVI_sd__20240701',
  'SAVI_sd__20240801',
  'SAVI_sd__20240901',
  'elevation_mean_m',
  'distance_to_nearest_lake_m',
  'x',
  'y'],
 'categorical_features': ['GAIOIKANOT'],
 'all_null_features': [],
 'constant_features': [],
 'active_features': ['EVI_median__20231001',
  'EVI_median__20231101',
  'EVI_median__20231201',
  'EVI_median__20240101',
  'EVI_median__20240201',
  'EVI_median__20240301',
  'EVI_median__20240401',
  'EVI_median__20240501',
  'EVI_median__20240601',
  'EVI_median__20240701',
  'EVI_median__20240801',
  'EVI_median__20240901',
  'EVI_range__20231001',
  'EVI_range__20231101',
  'EVI_range__20231201',
  'EVI_range__20240101',
  'EVI_range__20240201',
  'EVI_range__20240301',
  'EVI_range__20240401',
  'EVI_range__20240501',
  'EVI_range__20240601',
  'EVI_range__20240701',
  'EVI_range__20240801',
  'EVI_range__20240901',
  'EVI_sd__20231001',
  'EVI_sd__20231101',
  'EVI_sd__20231201',
  'EVI_sd__20240101',
  'EVI_sd__20240201',
  'EVI_sd__20240301',
  'EVI_sd__20240401',
  'EVI_sd__20240501',
  'EVI_sd__20240601',
  'EVI_sd__20240701',
  'EVI_sd__20240801',
  'EVI_sd__20240901',
  'NDMI_median__20231001',
  'NDMI_median__20231101',
  'NDMI_median__20231201',
  'NDMI_median__20240101',
  'NDMI_median__20240201',
  'NDMI_median__20240301',
  'NDMI_median__20240401',
  'NDMI_median__20240501',
  'NDMI_median__20240601',
  'NDMI_median__20240701',
  'NDMI_median__20240801',
  'NDMI_median__20240901',
  'NDMI_range__20231001',
  'NDMI_range__20231101',
  'NDMI_range__20231201',
  'NDMI_range__20240101',
  'NDMI_range__20240201',
  'NDMI_range__20240301',
  'NDMI_range__20240401',
  'NDMI_range__20240501',
  'NDMI_range__20240601',
  'NDMI_range__20240701',
  'NDMI_range__20240801',
  'NDMI_range__20240901',
  'NDMI_sd__20231001',
  'NDMI_sd__20231101',
  'NDMI_sd__20231201',
  'NDMI_sd__20240101',
  'NDMI_sd__20240201',
  'NDMI_sd__20240301',
  'NDMI_sd__20240401',
  'NDMI_sd__20240501',
  'NDMI_sd__20240601',
  'NDMI_sd__20240701',
  'NDMI_sd__20240801',
  'NDMI_sd__20240901',
  'NDRE_median__20231001',
  'NDRE_median__20231101',
  'NDRE_median__20231201',
  'NDRE_median__20240101',
  'NDRE_median__20240201',
  'NDRE_median__20240301',
  'NDRE_median__20240401',
  'NDRE_median__20240501',
  'NDRE_median__20240601',
  'NDRE_median__20240701',
  'NDRE_median__20240801',
  'NDRE_median__20240901',
  'NDRE_range__20231001',
  'NDRE_range__20231101',
  'NDRE_range__20231201',
  'NDRE_range__20240101',
  'NDRE_range__20240201',
  'NDRE_range__20240301',
  'NDRE_range__20240401',
  'NDRE_range__20240501',
  'NDRE_range__20240601',
  'NDRE_range__20240701',
  'NDRE_range__20240801',
  'NDRE_range__20240901',
  'NDRE_sd__20231001',
  'NDRE_sd__20231101',
  'NDRE_sd__20231201',
  'NDRE_sd__20240101',
  'NDRE_sd__20240201',
  'NDRE_sd__20240301',
  'NDRE_sd__20240401',
  'NDRE_sd__20240501',
  'NDRE_sd__20240601',
  'NDRE_sd__20240701',
  'NDRE_sd__20240801',
  'NDRE_sd__20240901',
  'NDVI_median__20231001',
  'NDVI_median__20231101',
  'NDVI_median__20231201',
  'NDVI_median__20240101',
  'NDVI_median__20240201',
  'NDVI_median__20240301',
  'NDVI_median__20240401',
  'NDVI_median__20240501',
  'NDVI_median__20240601',
  'NDVI_median__20240701',
  'NDVI_median__20240801',
  'NDVI_median__20240901',
  'NDVI_range__20231001',
  'NDVI_range__20231101',
  'NDVI_range__20231201',
  'NDVI_range__20240101',
  'NDVI_range__20240201',
  'NDVI_range__20240301',
  'NDVI_range__20240401',
  'NDVI_range__20240501',
  'NDVI_range__20240601',
  'NDVI_range__20240701',
  'NDVI_range__20240801',
  'NDVI_range__20240901',
  'NDVI_sd__20231001',
  'NDVI_sd__20231101',
  'NDVI_sd__20231201',
  'NDVI_sd__20240101',
  'NDVI_sd__20240201',
  'NDVI_sd__20240301',
  'NDVI_sd__20240401',
  'NDVI_sd__20240501',
  'NDVI_sd__20240601',
  'NDVI_sd__20240701',
  'NDVI_sd__20240801',
  'NDVI_sd__20240901',
  'NDWI_median__20231001',
  'NDWI_median__20231101',
  'NDWI_median__20231201',
  'NDWI_median__20240101',
  'NDWI_median__20240201',
  'NDWI_median__20240301',
  'NDWI_median__20240401',
  'NDWI_median__20240501',
  'NDWI_median__20240601',
  'NDWI_median__20240701',
  'NDWI_median__20240801',
  'NDWI_median__20240901',
  'NDWI_range__20231001',
  'NDWI_range__20231101',
  'NDWI_range__20231201',
  'NDWI_range__20240101',
  'NDWI_range__20240201',
  'NDWI_range__20240301',
  'NDWI_range__20240401',
  'NDWI_range__20240501',
  'NDWI_range__20240601',
  'NDWI_range__20240701',
  'NDWI_range__20240801',
  'NDWI_range__20240901',
  'NDWI_sd__20231001',
  'NDWI_sd__20231101',
  'NDWI_sd__20231201',
  'NDWI_sd__20240101',
  'NDWI_sd__20240201',
  'NDWI_sd__20240301',
  'NDWI_sd__20240401',
  'NDWI_sd__20240501',
  'NDWI_sd__20240601',
  'NDWI_sd__20240701',
  'NDWI_sd__20240801',
  'NDWI_sd__20240901',
  'SAVI_median__20231001',
  'SAVI_median__20231101',
  'SAVI_median__20231201',
  'SAVI_median__20240101',
  'SAVI_median__20240201',
  'SAVI_median__20240301',
  'SAVI_median__20240401',
  'SAVI_median__20240501',
  'SAVI_median__20240601',
  'SAVI_median__20240701',
  'SAVI_median__20240801',
  'SAVI_median__20240901',
  'SAVI_range__20231001',
  'SAVI_range__20231101',
  'SAVI_range__20231201',
  'SAVI_range__20240101',
  'SAVI_range__20240201',
  'SAVI_range__20240301',
  'SAVI_range__20240401',
  'SAVI_range__20240501',
  'SAVI_range__20240601',
  'SAVI_range__20240701',
  'SAVI_range__20240801',
  'SAVI_range__20240901',
  'SAVI_sd__20231001',
  'SAVI_sd__20231101',
  'SAVI_sd__20231201',
  'SAVI_sd__20240101',
  'SAVI_sd__20240201',
  'SAVI_sd__20240301',
  'SAVI_sd__20240401',
  'SAVI_sd__20240501',
  'SAVI_sd__20240601',
  'SAVI_sd__20240701',
  'SAVI_sd__20240801',
  'SAVI_sd__20240901',
  'elevation_mean_m',
  'distance_to_nearest_lake_m',
  'GAIOIKANOT',
  'x',
  'y'],
 'iqr_filter': {'applied': False,
  'lower_quantile': 0.25,
  'upper_quantile': 0.75,
  'multiplier': 1.5,
  'outlier_counts': {},
  'total_outliers_replaced': 0,
  'bounds': {},
  'skipped_non_numeric_features': ['GAIOIKANOT']},
 'spatial_interpolation': {'interpolation_method': 'nearest',
  'null_counts_before_interpolation': {},
  'null_cells_before_interpolation': 0,
  'interpolation_skipped': {},
  'null_counts_after_interpolation': {},
  'null_cells_after_interpolation': 0},
 'class_distribution': {'110': 23314,
  '119': 9525,
  '111': 5299,
  '129': 3660,
  '112': 3288,
  '130': 2990,
  '108': 1651,
  '128': 1372,
  '114': 1001,
  '116': 870,
  '121': 675,
  '101': 590,
  '105': 532,
  '122': 450,
  '102': 365,
  '106': 250,
  '104': 153},
 'config': {'project_dir': WindowsPath('C:/work_dir/kozani-2023-2024/3_ml_classification_tune_probabilities1'),
  'target_column': 'label',
  'feature_columns': ['EVI_median__20231001',
   'EVI_median__20231101',
   'EVI_median__20231201',
   'EVI_median__20240101',
   'EVI_median__20240201',
   'EVI_median__20240301',
   'EVI_median__20240401',
   'EVI_median__20240501',
   'EVI_median__20240601',
   'EVI_median__20240701',
   'EVI_median__20240801',
   'EVI_median__20240901',
   'EVI_range__20231001',
   'EVI_range__20231101',
   'EVI_range__20231201',
   'EVI_range__20240101',
   'EVI_range__20240201',
   'EVI_range__20240301',
   'EVI_range__20240401',
   'EVI_range__20240501',
   'EVI_range__20240601',
   'EVI_range__20240701',
   'EVI_range__20240801',
   'EVI_range__20240901',
   'EVI_sd__20231001',
   'EVI_sd__20231101',
   'EVI_sd__20231201',
   'EVI_sd__20240101',
   'EVI_sd__20240201',
   'EVI_sd__20240301',
   'EVI_sd__20240401',
   'EVI_sd__20240501',
   'EVI_sd__20240601',
   'EVI_sd__20240701',
   'EVI_sd__20240801',
   'EVI_sd__20240901',
   'NDMI_median__20231001',
   'NDMI_median__20231101',
   'NDMI_median__20231201',
   'NDMI_median__20240101',
   'NDMI_median__20240201',
   'NDMI_median__20240301',
   'NDMI_median__20240401',
   'NDMI_median__20240501',
   'NDMI_median__20240601',
   'NDMI_median__20240701',
   'NDMI_median__20240801',
   'NDMI_median__20240901',
   'NDMI_range__20231001',
   'NDMI_range__20231101',
   'NDMI_range__20231201',
   'NDMI_range__20240101',
   'NDMI_range__20240201',
   'NDMI_range__20240301',
   'NDMI_range__20240401',
   'NDMI_range__20240501',
   'NDMI_range__20240601',
   'NDMI_range__20240701',
   'NDMI_range__20240801',
   'NDMI_range__20240901',
   'NDMI_sd__20231001',
   'NDMI_sd__20231101',
   'NDMI_sd__20231201',
   'NDMI_sd__20240101',
   'NDMI_sd__20240201',
   'NDMI_sd__20240301',
   'NDMI_sd__20240401',
   'NDMI_sd__20240501',
   'NDMI_sd__20240601',
   'NDMI_sd__20240701',
   'NDMI_sd__20240801',
   'NDMI_sd__20240901',
   'NDRE_median__20231001',
   'NDRE_median__20231101',
   'NDRE_median__20231201',
   'NDRE_median__20240101',
   'NDRE_median__20240201',
   'NDRE_median__20240301',
   'NDRE_median__20240401',
   'NDRE_median__20240501',
   'NDRE_median__20240601',
   'NDRE_median__20240701',
   'NDRE_median__20240801',
   'NDRE_median__20240901',
   'NDRE_range__20231001',
   'NDRE_range__20231101',
   'NDRE_range__20231201',
   'NDRE_range__20240101',
   'NDRE_range__20240201',
   'NDRE_range__20240301',
   'NDRE_range__20240401',
   'NDRE_range__20240501',
   'NDRE_range__20240601',
   'NDRE_range__20240701',
   'NDRE_range__20240801',
   'NDRE_range__20240901',
   'NDRE_sd__20231001',
   'NDRE_sd__20231101',
   'NDRE_sd__20231201',
   'NDRE_sd__20240101',
   'NDRE_sd__20240201',
   'NDRE_sd__20240301',
   'NDRE_sd__20240401',
   'NDRE_sd__20240501',
   'NDRE_sd__20240601',
   'NDRE_sd__20240701',
   'NDRE_sd__20240801',
   'NDRE_sd__20240901',
   'NDVI_median__20231001',
   'NDVI_median__20231101',
   'NDVI_median__20231201',
   'NDVI_median__20240101',
   'NDVI_median__20240201',
   'NDVI_median__20240301',
   'NDVI_median__20240401',
   'NDVI_median__20240501',
   'NDVI_median__20240601',
   'NDVI_median__20240701',
   'NDVI_median__20240801',
   'NDVI_median__20240901',
   'NDVI_range__20231001',
   'NDVI_range__20231101',
   'NDVI_range__20231201',
   'NDVI_range__20240101',
   'NDVI_range__20240201',
   'NDVI_range__20240301',
   'NDVI_range__20240401',
   'NDVI_range__20240501',
   'NDVI_range__20240601',
   'NDVI_range__20240701',
   'NDVI_range__20240801',
   'NDVI_range__20240901',
   'NDVI_sd__20231001',
   'NDVI_sd__20231101',
   'NDVI_sd__20231201',
   'NDVI_sd__20240101',
   'NDVI_sd__20240201',
   'NDVI_sd__20240301',
   'NDVI_sd__20240401',
   'NDVI_sd__20240501',
   'NDVI_sd__20240601',
   'NDVI_sd__20240701',
   'NDVI_sd__20240801',
   'NDVI_sd__20240901',
   'NDWI_median__20231001',
   'NDWI_median__20231101',
   'NDWI_median__20231201',
   'NDWI_median__20240101',
   'NDWI_median__20240201',
   'NDWI_median__20240301',
   'NDWI_median__20240401',
   'NDWI_median__20240501',
   'NDWI_median__20240601',
   'NDWI_median__20240701',
   'NDWI_median__20240801',
   'NDWI_median__20240901',
   'NDWI_range__20231001',
   'NDWI_range__20231101',
   'NDWI_range__20231201',
   'NDWI_range__20240101',
   'NDWI_range__20240201',
   'NDWI_range__20240301',
   'NDWI_range__20240401',
   'NDWI_range__20240501',
   'NDWI_range__20240601',
   'NDWI_range__20240701',
   'NDWI_range__20240801',
   'NDWI_range__20240901',
   'NDWI_sd__20231001',
   'NDWI_sd__20231101',
   'NDWI_sd__20231201',
   'NDWI_sd__20240101',
   'NDWI_sd__20240201',
   'NDWI_sd__20240301',
   'NDWI_sd__20240401',
   'NDWI_sd__20240501',
   'NDWI_sd__20240601',
   'NDWI_sd__20240701',
   'NDWI_sd__20240801',
   'NDWI_sd__20240901',
   'SAVI_median__20231001',
   'SAVI_median__20231101',
   'SAVI_median__20231201',
   'SAVI_median__20240101',
   'SAVI_median__20240201',
   'SAVI_median__20240301',
   'SAVI_median__20240401',
   'SAVI_median__20240501',
   'SAVI_median__20240601',
   'SAVI_median__20240701',
   'SAVI_median__20240801',
   'SAVI_median__20240901',
   'SAVI_range__20231001',
   'SAVI_range__20231101',
   'SAVI_range__20231201',
   'SAVI_range__20240101',
   'SAVI_range__20240201',
   'SAVI_range__20240301',
   'SAVI_range__20240401',
   'SAVI_range__20240501',
   'SAVI_range__20240601',
   'SAVI_range__20240701',
   'SAVI_range__20240801',
   'SAVI_range__20240901',
   'SAVI_sd__20231001',
   'SAVI_sd__20231101',
   'SAVI_sd__20231201',
   'SAVI_sd__20240101',
   'SAVI_sd__20240201',
   'SAVI_sd__20240301',
   'SAVI_sd__20240401',
   'SAVI_sd__20240501',
   'SAVI_sd__20240601',
   'SAVI_sd__20240701',
   'SAVI_sd__20240801',
   'SAVI_sd__20240901',
   'elevation_mean_m',
   'distance_to_nearest_lake_m',
   'GAIOIKANOT',
   'x',
   'y'],
  'selected_models': ('bagging',
   'random_forest',
   'extra_trees',
   'neural_network'),
  'reset_project_dir_on_run_check': True,
  'fail_on_cleanup_error': False,
  'id_column': 'parcel_code',
  'apply_iqr': False,
  'iqr_lower_quantile': 0.25,
  'iqr_upper_quantile': 0.75,
  'iqr_multiplier': 1.5,
  'spatial_interpolation_method': 'nearest',
  'spatial_interpolation_max_distance_in_meters': 500,
  'spatial_interpolation_variogram_lags': 15,
  'spatial_interpolation_variogram_max_distance_in_meters': None,
  'enforce_unique_ids': True,
  'test_size': 0.2,
  'cv_folds': 5,
  'random_state': 42,
  'n_jobs': 4,
  'scoring_primary': 'f1_macro',
  'scoring_secondary': ('balanced_accuracy', 'f1_weighted', 'accuracy'),
  'selection_type': 'soft_voting',
  'cv_ranking_method': 'score_minus_std',
  'rare_category_min_frequency': 10,
  'max_search_candidates': 40,
  'top_voting_models': 3,
  'interpretability_top_models': 3,
  'interpretability_include_shap': True,
  'shap_sample_size': 500,
  'feature_importance_top_n': 15,
  'max_distribution_features': 9,
  'max_map_geometries': 20000,
  'float_dtype': 'float32',
  'spatial_split': True,
  'spatial_split_method': 'by_row',
  'spatial_split_grid_size': 10,
  'label_balancing_method': 'random_oversample',
  'smote_k_neighbors': 5,
  'optimize_class_probabilities': False,
  'probability_multiplier_grid': (0.8, 1.0, 1.2, 1.5, 2.0),
  'probability_optimization_iterations': 2,
  'probability_optimization_max_accuracy_drop': 0.02,
  'prediction_column': 'label_prediction',
  'prediction_filled_column': 'label_filled',
  'probability_prefix': 'probability',
  'prediction_confidence_threshold': 0.6,
  'prediction_confidence_column': 'prediction_confidence',
  'prediction_review_column': 'prediction_needs_review',
  'output_schema_version': '1.0.0',
  'log_filename': 'pipeline.log',
  'step_names': ('01_check',
   '02_prepare',
   '03_train',
   '04_evaluate',
   '05_predict'),
  'open_html_report': True}}

In [10]:
summary_prepare = pipeline.run_prepare()

===========================================================
Function <run_prepare> started on 2026-08-16 18:46:51

Preparing data...
Writing file: C:/work_dir/kozani-2023-2024/3_ml_classification_tune_probabilities1/02_prepare/label_mapping.csv

E:\Eleni\git_repo\satellites\src\ml_classification\ml_classification_pipeline\visuals\maps.py:156: UserWarning: Legend does not support handles for PatchCollection instances.
See: https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#implementing-a-custom-legend-handler
  ax.legend()

Prepared train/test split: 44788 train rows, 11197 test rows.

Execution time of function <run_prepare> ended on 2026-08-16 18:47:23 - duration: 00:00:32
================================================================================================

In [ ]:
summary_train = pipeline.run_train()
summary_train

=========================================================
Function <run_train> started on 2026-08-16 18:47:23

Training models...
Reading file: C:/work_dir/kozani-2023-2024/3_ml_classification_tune_probabilities1/02_prepare/label_mapping.csv
____________________________________________________________________________________________________

Training model random_forest

In [ ]:
summary_evaluate = pipeline.run_evaluate()
summary_evaluate

In [ ]:
summary_predict = pipeline.run_predict()
summary_predict

In [ ]:
# Show only rows that were unknown during training
classified_gdf = pd.read_csv(os.path.join(str(OUTPUT_PATH), "05_predict", "final_predictions_preview.csv"))
classified_gdf[parcel_id_column] = classified_gdf[parcel_id_column].astype(str)
print(len(classified_gdf), "rows in classified_gdf")
display(classified_gdf.head())

In [ ]:
from ml_classification.ml_classification_pipeline.core.persistence import load_joblib
test_df = load_joblib(Path(f"{OUTPUT_PATH}/02_prepare/test_dataset.joblib"))
test_df[parcel_id_column] = test_df[parcel_id_column].astype(str)
print(len(test_df), "rows in test_df")
test_df.head()

In [ ]:
test_ids =list(test_df[parcel_id_column].unique())
classified_gdf = classified_gdf[classified_gdf[parcel_id_column].isin(test_ids)]
print(len(classified_gdf), "rows in classified_gdf after filtering with test_ids")
classified_gdf["accuracy"] = classified_gdf[class_column] == classified_gdf[f"{class_column}_prediction"]
accuracy = classified_gdf["accuracy"].mean()
print(f"Accuracy on data: {accuracy:.2%}")