# EDA Pipeline Example

This notebook shows how to run the reusable EDA pipeline on a pandas DataFrame and, when GeoPandas is installed, on a GeoDataFrame.

In [1]:
from pathlib import Path
import os
import random

from IPython.display import display
from pathlib import Path
import numpy as np
import os
import random
from satellites.shared.io import read_data
from satellites.eda import run_eda
import webbrowser

# Global reproducibility seed
random_seed = 42
os.environ["PYTHONHASHSEED"] = str(random_seed)
os.environ["TF_DETERMINISTIC_OPS"] = "1"
random.seed(random_seed)
np.random.seed(random_seed)

## GeoDataFrame Example

In [2]:
try:
    WORK_PATH = Path("C:/work_dir/volvi-2023-2024")
    PARCELS_PATH = WORK_PATH / "1_eo_parcel_stats_fill" / "satellite_parcel_time_stats.geoparquet"
    OUTPUT_PATH = WORK_PATH / "2_eo_results_eda_fill"
    COL_PARCEL_ID = "parcel_code"
    COL_TARGET = "label_gr"
    gdf = read_data(str(PARCELS_PATH))
    print(f"Initial columns in GeoDataFrame: {len(gdf.columns)}: {list(gdf.columns)}")

    extra_features = ["elevation_mean_m", "GAIOIKANOT", "geom_interior_area_ratio", "data_reliability_score", "geom_shape_complexity_score"]

    show_indices =  ("R", "RVI", "NDMI", "NDRE", "SAVI", "NDVI", "EVI", "NDWI",)
    show_statistics = ("_median",)
    base_columns = [x for x in gdf.columns if x in extra_features or (any(stat in x for stat in show_statistics) and any(idx in x for idx in show_indices))]

    columns_to_display = [COL_PARCEL_ID, COL_TARGET] + base_columns + ["geometry"]
    print(f"\nColumns to display {len(columns_to_display)}: {columns_to_display}")

    display(gdf[columns_to_display].head())
    geo_result = run_eda(
        gdf[columns_to_display],
        output_dir=str(OUTPUT_PATH),
        target_task="classification",
        target_column=COL_TARGET,
        id_column=COL_PARCEL_ID,
        report_title="Sample GeoDataFrame EDA",
        feature_selection_max_features=None,
        max_features_per_plot=36,
        max_target_levels_for_plots=20,
    )
    html_path = geo_result["report_path"]
    proposed_features = geo_result["proposed_features"]
    annotated_gdf = geo_result["annotated_data"]
    display(geo_result["artifacts"]["feature_selection_proposal"])
    print(f"Annotated GeoParquet: {geo_result['saved_paths']['annotated_data']}")
    webbrowser.open(html_path.as_uri())
except ImportError as exc:
    print(f"GeoDataFrame example skipped: {exc}")

Reading file: C:/work_dir/volvi-2023-2024/1_eo_parcel_stats_fill/satellite_parcel_time_stats.geoparquet

,parcel_code,label_gr,data_reliability_score,geom_interior_area_ratio,geom_shape_complexity_score,EVI_median__20231001,EVI_median__20231101,EVI_median__20231201,EVI_median__20240101,EVI_median__20240201,...,SAVI_median__20240301,SAVI_median__20240401,SAVI_median__20240501,SAVI_median__20240601,SAVI_median__20240701,SAVI_median__20240801,SAVI_median__20240901,elevation_mean_m,GAIOIKANOT,geometry
0,237535570,σιτάρι,0.740196,1.347729,0.513169,0.155278,0.125017,0.070109,0.084270,0.165140,...,0.394218,0.588036,0.334332,0.127809,0.111719,0.110047,0.137887,234.145380,T7-111-2-D9QQ,"POLYGON ((412455.851 4524641.592, 412393.377 4..."
1,237535579,σιτάρι,0.801749,1.531485,0.318393,0.174568,0.152696,0.080665,0.095380,0.162722,...,0.277424,0.370530,0.257984,0.149761,0.131422,0.125825,0.151509,249.113905,T7-111-2-D9QQ,"POLYGON ((412401.035 4523218.598, 412407.043 4..."
2,237535543,χορτοδοτικές καλλιέργειες,0.784550,1.493231,0.472371,0.205080,0.145056,0.102466,0.107011,0.132931,...,0.194451,0.302943,0.355109,0.239482,0.201779,0.178640,0.155270,256.417212,T7-111-2-D9QQ,"POLYGON ((412129.805 4523563.227, 412128.959 4..."
3,237535582,σιτάρι,0.803175,1.511779,0.381952,0.175993,0.148953,0.067652,0.082014,0.138933,...,0.270230,0.382538,0.286936,0.155827,0.139277,0.137456,0.156797,217.462046,T7-111-2-D9QQ,"POLYGON ((412513.852 4522829.275, 412578.79 45..."
4,237535577,σιτάρι,0.767308,1.417028,0.238742,0.184470,0.121717,0.102351,0.079322,0.117386,...,0.273656,0.464839,0.403394,0.167983,0.129912,0.154114,0.182860,214.203696,T7-111-2-D9QQ,"POLYGON ((412922.919 4524074.846, 412924.348 4..."

Proposed initial ML features (26): NDVI_median__20240701, NDVI_median__20240601, NDMI_median__20240401, NDMI_median__20240701, NDMI_median__20240601, NDRE_median__20240301, NDVI_median__20240201, EVI_median__20231201, NDRE_median__20231201, NDVI_median__20240801, NDRE_median__20240101, NDWI_median__20240501, NDMI_median__20240201, NDWI_median__20231201, NDRE_median__20231101, NDMI_median__20240801, NDWI_median__20231101, elevation_mean_m, NDMI_median__20231201, NDMI_median__20240101, NDVI_median__20240901, NDMI_median__20240501, NDRE_median__20231001, NDMI_median__20240901, NDMI_median__20231101, NDWI_median__20231001. Review separately (51): GAIOIKANOT, NDRE_median__20240701, NDWI_median__20240701, SAVI_median__20240701, EVI_median__20240701, NDRE_median__20240601, EVI_median__20240601, SAVI_median__20240601, NDRE_median__20240401, NDWI_median__20240401, ... 41 more (see feature_selection_proposal.csv). Automatically excluded: 0. Criteria order: hard exclusions and leakage review -> data quality and availability -> target association -> redundancy -> parsimonious initial shortlist -> train-only model validation. This is an EDA shortlist; confirm it with train-only cross-validation and permutation importance.
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/overview/column_profile.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/data_quality/data_quality_flags.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/numeric/numeric_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/numeric/robust_numeric_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/categorical/categorical_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/overview/datetime_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/numeric/normality_tests.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/numeric/outlier_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/correlation/strong_correlation_pairs.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/correlation/multicollinearity.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/data_quality/missingness_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/missingness_target_tests.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/categorical/categorical_associations.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/categorical_target_tests.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/categorical_numeric_target_tests.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/numeric_target_tests.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/numeric_target_correlations.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/feature_selection/feature_target_associations.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/feature_selection/feature_selection_criteria.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/feature_selection/feature_selection_proposal.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/multivariate/pca_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/multivariate/multivariate_outliers.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/target/target_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/geospatial/geospatial_summary.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/eda_annotated_data.parquet
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/correlation/pearson_correlation_matrix.csv
Writing file: C:/work_dir/volvi-2023-2024/2_eo_results_eda_fill/tables/correlation/spearman_correlation_matrix.csv

,selection_order,feature,feature_type,proposed_action,primary_reason,association_method,effect_size,association_strength,qvalue,missing_percent,redundant_with,redundancy_measure,passes_hard_exclusions,passes_data_quality,passes_target_evidence,passes_redundancy,passes_shortlist_limit
0,1,NDVI_median__20240701,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3802,large,0.0,0.0,,NaN,True,True,True,True,True
1,2,NDVI_median__20240601,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3383,large,0.0,0.0,,NaN,True,True,True,True,True
2,3,NDMI_median__20240401,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3034,large,0.0,0.0,,NaN,True,True,True,True,True
3,4,NDMI_median__20240701,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.2744,large,0.0,0.0,,NaN,True,True,True,True,True
4,5,NDMI_median__20240601,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.2471,large,0.0,0.0,,NaN,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,SAVI_median__20231001,numeric,review,redundant with retained feature NDRE_median__2...,kruskal_epsilon_squared,0.0759,moderate,0.0,0.0,NDRE_median__20231001,0.9307,True,True,True,False,True
73,74,data_reliability_score,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0495,small,0.0,0.0,,NaN,True,True,False,True,True
74,75,NDMI_median__20231001,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0412,small,0.0,0.0,,NaN,True,True,False,True,True
75,76,geom_interior_area_ratio,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0082,negligible,0.0,0.0,,NaN,True,True,False,True,True
76,77,geom_shape_complexity_score,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0029,negligible,0.0,0.0,,NaN,True,True,False,True,True

Annotated GeoParquet: C:\work_dir\volvi-2023-2024\2_eo_results_eda_fill\eda_annotated_data.parquet

In [3]:
# import satellites.shared.legacy.eda_report as eda_l

# report = eda_l.EdaReport(gdf[columns_to_display], report_folder=os.path.join(str(OUTPUT_PATH), "geodataframe_eda2"), report_name="eda_report_sample")
# report.create_eda_report()