# Add environmental features to Kozani parcels

This reusable feature-engineering notebook adds mean DEM elevation and nearest-lake context to the parcel GeoParquet. Each replacement is atomic, and more environmental feature steps can be added here later.

## Setup

In [1]:
from pathlib import Path
import os
import shutil
from common_libraries.io_library import read_data, write_data
from common_libraries.parcel_features import (
    append_nearest_lake_features,
    append_parcel_elevation,
    append_soil_feature,
    create_dem_mosaic,
    find_dem_tiles,
    validate_projected_metric_crs,
)

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\xicor\__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

## Paths and options

In [2]:
WORK_PATH = Path("C:/work_dir/volvi-2023-2024")
DEM_DIR = WORK_PATH / "dem"
DEM_DIR.mkdir(parents=True, exist_ok=True)
MOSAIC_PATH = DEM_DIR / "dem_mosaic.tif"

PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_time_stats.geoparquet"
LAKES_PATH = Path("C:/work_dir/Lakes.gpkg")
LAKES_LAYER = "lakes_qgis"
SOIL_PATH = Path("C:/work_dir/Agro_Soil.gpkg")
SOIL_LAYER = None

EPSG_CODE = 2100  # Greek Grid (metric)
# False uses pixels whose centers fall inside each parcel. Set True for very small parcels.
ALL_TOUCHED = False

assert PARCELS_PATH.is_file(), f"Missing parcel file: {PARCELS_PATH}"
assert LAKES_PATH.is_file(), f"Missing lake file: {LAKES_PATH}"
assert SOIL_PATH.is_file(), f"Missing soil file: {SOIL_PATH}"

# Load the parcel dataset
parcel_geometry = read_data(str(PARCELS_PATH))
print(f"Loaded parcel dataset with {len(parcel_geometry)} features")
print(f"Original CRS: {parcel_geometry.crs}")

# Ensure the CRS is set correctly
if parcel_geometry.crs is None:
    print(f"Parcel dataset has no CRS; setting to EPSG:{EPSG_CODE}")
    parcel_geometry = parcel_geometry.set_crs(epsg=EPSG_CODE)
    write_data(parcel_geometry, str(PARCELS_PATH))
elif parcel_geometry.crs.to_epsg() != EPSG_CODE:
    print(f"Parcel CRS is {parcel_geometry.crs.to_epsg()}; converting to EPSG:{EPSG_CODE}")
    parcel_geometry = parcel_geometry.to_crs(epsg=EPSG_CODE)
    write_data(parcel_geometry, str(PARCELS_PATH))
else:
    print(f"Parcel dataset already uses EPSG:{EPSG_CODE}")

# Validate the CRS
validate_projected_metric_crs(parcel_geometry.crs, dataset_name="Parcel dataset")
ORIGINAL_PARCEL_CRS = parcel_geometry.crs
print(f"Parcel CRS that will be preserved: {ORIGINAL_PARCEL_CRS}")
parcel_geometry.head()

Reading file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Loaded parcel dataset with 28699 features
Original CRS: {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "WGS 84 / UTM zone 35N", "base_crs": {"name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4326}}, "conversion": {"name": "UTM zone 35N", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 27, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Navigation and medium accuracy spatial referencing.", "area": "Between 24\u00b0E and 30\u00b0E, northern hemisphere between equator and 84\u00b0N, onshore and offshore. Belarus. Bulgaria. Central African Republic. Democratic Republic of the Congo (Zaire). Egypt. Estonia. Finland. Greece. Latvia. Lesotho. Libya. Lithuania. Moldova. Norway. Poland. Romania. Russian Federation. Sudan. Svalbard. T\u00fcrkiye (Turkey). Uganda. Ukraine.", "bbox": {"south_latitude": 0, "west_longitude": 24, "north_latitude": 84, "east_longitude": 30}, "id": {"authority": "EPSG", "code": 32635}}
Parcel CRS is 32635; converting to EPSG:2100
Removing existing file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Parcel CRS that will be preserved: EPSG:2100

,parcel_code,initial_label_code,initial_label,predicted_label_code,predicted_label,prediction_probability,set_type,label_gr,geometry,batch_number,intersected_pixel_count,meets_minimum_pixel_count,expected_pixel_count,temporal_filled_pixel_count,spatial_filled_pixel_count,temporal_filled_ratio,spatial_filled_ratio,data_reliability_score,pixel_area,geom_area,geom_interior_area_ratio,geom_compactness,geom_perimeter_area_ratio,geom_shape_index,geom_elongation,geom_shape_complexity_score,B02_coefficient_of_variation__20231001,B02_coefficient_of_variation__20231101,B02_coefficient_of_variation__20231201,B02_coefficient_of_variation__20240101,B02_coefficient_of_variation__20240201,B02_coefficient_of_variation__20240301,B02_coefficient_of_variation__20240401,B02_coefficient_of_variation__20240501,B02_coefficient_of_variation__20240601,B02_coefficient_of_variation__20240701,B02_coefficient_of_variation__20240801,B02_coefficient_of_variation__20240901,B02_max__20231001,B02_max__20231101,B02_max__20231201,B02_max__20240101,B02_max__20240201,B02_max__20240301,B02_max__20240401,B02_max__20240501,B02_max__20240601,B02_max__20240701,B02_max__20240801,B02_max__20240901,B02_mean__20231001,B02_mean__20231101,B02_mean__20231201,B02_mean__20240101,B02_mean__20240201,B02_mean__20240301,B02_mean__20240401,B02_mean__20240501,B02_mean__20240601,B02_mean__20240701,B02_mean__20240801,B02_mean__20240901,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_min__20231001,B02_min__20231101,B02_min__20231201,B02_min__20240101,B02_min__20240201,B02_min__20240301,B02_min__20240401,B02_min__20240501,B02_min__20240601,B02_min__20240701,B02_min__20240801,B02_min__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B02_variance__20231001,B02_variance__20231101,B02_variance__20231201,B02_variance__20240101,B02_variance__20240201,B02_variance__20240301,B02_variance__20240401,B02_variance__20240501,B02_variance__20240601,B02_variance__20240701,B02_variance__20240801,B02_variance__20240901,B03_coefficient_of_variation__20231001,B03_coefficient_of_variation__20231101,B03_coefficient_of_variation__20231201,B03_coefficient_of_variation__20240101,B03_coefficient_of_variation__20240201,B03_coefficient_of_variation__20240301,B03_coefficient_of_variation__20240401,B03_coefficient_of_variation__20240501,B03_coefficient_of_variation__20240601,B03_coefficient_of_variation__20240701,B03_coefficient_of_variation__20240801,B03_coefficient_of_variation__20240901,B03_max__20231001,B03_max__20231101,B03_max__20231201,B03_max__20240101,B03_max__20240201,B03_max__20240301,B03_max__20240401,B03_max__20240501,B03_max__20240601,B03_max__20240701,B03_max__20240801,B03_max__20240901,B03_mean__20231001,B03_mean__20231101,B03_mean__20231201,B03_mean__20240101,B03_mean__20240201,B03_mean__20240301,B03_mean__20240401,B03_mean__20240501,B03_mean__20240601,B03_mean__20240701,B03_mean__20240801,B03_mean__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_min__20231001,B03_min__20231101,B03_min__20231201,B03_min__20240101,B03_min__20240201,B03_min__20240301,B03_min__20240401,B03_min__20240501,B03_min__20240601,B03_min__20240701,B03_min__20240801,B03_min__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B03_variance__20231001,B03_variance__20231101,B03_variance__20231201,B03_variance__20240101,B03_variance__20240201,B03_variance__20240301,B03_variance__20240401,B03_variance__20240501,B03_variance__20240601,B03_variance__20240701,B03_variance__20240801,B03_variance__20240901,B04_coefficient_of_variation__20231001,B04_coefficient_of_variation__20231101,B04_coefficient_of_variation__20231201,B04_coefficient_of_variation__20240101,B04_coefficient_of_variation__20240201,B04_coefficient_of_variation__20240301,B04_coefficient_of_variation__20240401,B04_coefficient_of_variation__20240501,B04_coefficient_of_variation__20240601,B04_coefficient_of_variation__20240701,B04_coefficient_of_variation__20240801,B04_coefficient_of_variation__20240901,B04_max__20231001,B04_max__20231101,B04_max__20231201,B04_max__20240101,B04_max__20240201,B04_max__20240301,B04_max__20240401,B04_max__20240501,B04_max__20240601,B04_max__20240701,B04_max__20240801,B04_max__20240901,B04_mean__20231001,B04_mean__20231101,B04_mean__20231201,B04_mean__20240101,B04_mean__20240201,B04_mean__20240301,B04_mean__20240401,B04_mean__20240501,B04_mean__20240601,B04_mean__20240701,B04_mean__20240801,B04_mean__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_min__20231001,B04_min__20231101,B04_min__20231201,B04_min__20240101,B04_min__20240201,B04_min__20240301,B04_min__20240401,B04_min__20240501,B04_min__20240601,B04_min__20240701,B04_min__20240801,B04_min__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B04_variance__20231001,B04_variance__20231101,B04_variance__20231201,B04_variance__20240101,B04_variance__20240201,B04_variance__20240301,B04_variance__20240401,B04_variance__20240501,B04_variance__20240601,B04_variance__20240701,B04_variance__20240801,B04_variance__20240901,B05_coefficient_of_variation__20231001,B05_coefficient_of_variation__20231101,B05_coefficient_of_variation__20231201,B05_coefficient_of_variation__20240101,B05_coefficient_of_variation__20240201,B05_coefficient_of_variation__20240301,B05_coefficient_of_variation__20240401,B05_coefficient_of_variation__20240501,B05_coefficient_of_variation__20240601,B05_coefficient_of_variation__20240701,B05_coefficient_of_variation__20240801,B05_coefficient_of_variation__20240901,B05_max__20231001,B05_max__20231101,B05_max__20231201,B05_max__20240101,B05_max__20240201,B05_max__20240301,B05_max__20240401,B05_max__20240501,B05_max__20240601,B05_max__20240701,B05_max__20240801,B05_max__20240901,B05_mean__20231001,B05_mean__20231101,B05_mean__20231201,B05_mean__20240101,B05_mean__20240201,B05_mean__20240301,B05_mean__20240401,B05_mean__20240501,B05_mean__20240601,B05_mean__20240701,B05_mean__20240801,B05_mean__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_min__20231001,B05_min__20231101,B05_min__20231201,B05_min__20240101,B05_min__20240201,B05_min__20240301,B05_min__20240401,B05_min__20240501,B05_min__20240601,B05_min__20240701,B05_min__20240801,B05_min__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B05_variance__20231001,B05_variance__20231101,B05_variance__20231201,B05_variance__20240101,B05_variance__20240201,B05_variance__20240301,B05_variance__20240401,B05_variance__20240501,B05_variance__20240601,B05_variance__20240701,B05_variance__20240801,B05_variance__20240901,B08_coefficient_of_variation__20231001,B08_coefficient_of_variation__20231101,B08_coefficient_of_variation__20231201,B08_coefficient_of_variation__20240101,B08_coefficient_of_variation__20240201,B08_coefficient_of_variation__20240301,B08_coefficient_of_variation__20240401,B08_coefficient_of_variation__20240501,B08_coefficient_of_variation__20240601,B08_coefficient_of_variation__20240701,B08_coefficient_of_variation__20240801,B08_coefficient_of_variation__20240901,B08_max__20231001,B08_max__20231101,B08_max__20231201,B08_max__20240101,B08_max__20240201,B08_max__20240301,B08_max__20240401,B08_max__20240501,B08_max__20240601,B08_max__20240701,B08_max__20240801,B08_max__20240901,B08_mean__20231001,B08_mean__20231101,B08_mean__20231201,B08_mean__20240101,B08_mean__20240201,B08_mean__20240301,B08_mean__20240401,B08_mean__20240501,B08_mean__20240601,B08_mean__20240701,B08_mean__20240801,B08_mean__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_min__20231001,B08_min__20231101,B08_min__20231201,B08_min__20240101,B08_min__20240201,B08_min__20240301,B08_min__20240401,B08_min__20240501,B08_min__20240601,B08_min__20240701,B08_min__20240801,B08_min__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B08_variance__20231001,B08_variance__20231101,B08_variance__20231201,B08_variance__20240101,B08_variance__20240201,B08_variance__20240301,B08_variance__20240401,B08_variance__20240501,B08_variance__20240601,B08_variance__20240701,B08_variance__20240801,B08_variance__20240901,B11_coefficient_of_variation__20231001,B11_coefficient_of_variation__20231101,B11_coefficient_of_variation__20231201,B11_coefficient_of_variation__20240101,B11_coefficient_of_variation__20240201,B11_coefficient_of_variation__20240301,B11_coefficient_of_variation__20240401,B11_coefficient_of_variation__20240501,B11_coefficient_of_variation__20240601,B11_coefficient_of_variation__20240701,B11_coefficient_of_variation__20240801,B11_coefficient_of_variation__20240901,B11_max__20231001,B11_max__20231101,B11_max__20231201,B11_max__20240101,B11_max__20240201,B11_max__20240301,B11_max__20240401,B11_max__20240501,B11_max__20240601,B11_max__20240701,B11_max__20240801,B11_max__20240901,B11_mean__20231001,B11_mean__20231101,B11_mean__20231201,B11_mean__20240101,B11_mean__20240201,B11_mean__20240301,B11_mean__20240401,B11_mean__20240501,B11_mean__20240601,B11_mean__20240701,B11_mean__20240801,B11_mean__20240901,B11_median__20231001,B11_median__20231101,B11_median__20231201,B11_median__20240101,B11_median__20240201,B11_median__20240301,B11_median__20240401,B11_median__20240501,B11_median__20240601,B11_median__20240701,B11_median__20240801,B11_median__20240901,B11_min__20231001,B11_min__20231101,B11_min__20231201,B11_min__20240101,B11_min__20240201,B11_min__20240301,B11_min__20240401,B11_min__20240501,B11_min__20240601,B11_min__20240701,B11_min__20240801,B11_min__20240901,B11_range__20231001,B11_range__20231101,B11_range__20231201,B11_range__20240101,B11_range__20240201,B11_range__20240301,B11_range__20240401,B11_range__20240501,B11_range__20240601,B11_range__20240701,B11_range__20240801,B11_range__20240901,B11_sd__20231001,B11_sd__20231101,B11_sd__20231201,B11_sd__20240101,B11_sd__20240201,B11_sd__20240301,B11_sd__20240401,B11_sd__20240501,B11_sd__20240601,B11_sd__20240701,B11_sd__20240801,B11_sd__20240901,B11_variance__20231001,B11_variance__20231101,B11_variance__20231201,B11_variance__20240101,B11_variance__20240201,B11_variance__20240301,B11_variance__20240401,B11_variance__20240501,B11_variance__20240601,B11_variance__20240701,B11_variance__20240801,B11_variance__20240901,B12_coefficient_of_variation__20231001,B12_coefficient_of_variation__20231101,B12_coefficient_of_variation__20231201,B12_coefficient_of_variation__20240101,B12_coefficient_of_variation__20240201,B12_coefficient_of_variation__20240301,B12_coefficient_of_variation__20240401,B12_coefficient_of_variation__20240501,B12_coefficient_of_variation__20240601,B12_coefficient_of_variation__20240701,B12_coefficient_of_variation__20240801,B12_coefficient_of_variation__20240901,B12_max__20231001,B12_max__20231101,B12_max__20231201,B12_max__20240101,B12_max__20240201,B12_max__20240301,B12_max__20240401,B12_max__20240501,B12_max__20240601,B12_max__20240701,B12_max__20240801,B12_max__20240901,B12_mean__20231001,B12_mean__20231101,B12_mean__20231201,B12_mean__20240101,B12_mean__20240201,B12_mean__20240301,B12_mean__20240401,B12_mean__20240501,B12_mean__20240601,B12_mean__20240701,B12_mean__20240801,B12_mean__20240901,B12_median__20231001,B12_median__20231101,B12_median__20231201,B12_median__20240101,B12_median__20240201,B12_median__20240301,B12_median__20240401,B12_median__20240501,B12_median__20240601,B12_median__20240701,B12_median__20240801,B12_median__20240901,B12_min__20231001,B12_min__20231101,B12_min__20231201,B12_min__20240101,B12_min__20240201,B12_min__20240301,B12_min__20240401,B12_min__20240501,B12_min__20240601,B12_min__20240701,B12_min__20240801,B12_min__20240901,B12_range__20231001,B12_range__20231101,B12_range__20231201,B12_range__20240101,B12_range__20240201,B12_range__20240301,B12_range__20240401,B12_range__20240501,B12_range__20240601,B12_range__20240701,B12_range__20240801,B12_range__20240901,B12_sd__20231001,B12_sd__20231101,B12_sd__20231201,B12_sd__20240101,B12_sd__20240201,B12_sd__20240301,B12_sd__20240401,B12_sd__20240501,B12_sd__20240601,B12_sd__20240701,B12_sd__20240801,B12_sd__20240901,B12_variance__20231001,B12_variance__20231101,B12_variance__20231201,B12_variance__20240101,B12_variance__20240201,B12_variance__20240301,B12_variance__20240401,B12_variance__20240501,B12_variance__20240601,B12_variance__20240701,B12_variance__20240801,B12_variance__20240901,EVI_coefficient_of_variation__20231001,EVI_coefficient_of_variation__20231101,EVI_coefficient_of_variation__20231201,EVI_coefficient_of_variation__20240101,EVI_coefficient_of_variation__20240201,EVI_coefficient_of_variation__20240301,EVI_coefficient_of_variation__20240401,EVI_coefficient_of_variation__20240501,EVI_coefficient_of_variation__20240601,EVI_coefficient_of_variation__20240701,EVI_coefficient_of_variation__20240801,EVI_coefficient_of_variation__20240901,EVI_max__20231001,EVI_max__20231101,EVI_max__20231201,EVI_max__20240101,EVI_max__20240201,EVI_max__20240301,EVI_max__20240401,EVI_max__20240501,EVI_max__20240601,EVI_max__20240701,EVI_max__20240801,EVI_max__20240901,EVI_mean__20231001,EVI_mean__20231101,EVI_mean__20231201,EVI_mean__20240101,EVI_mean__20240201,EVI_mean__20240301,EVI_mean__20240401,EVI_mean__20240501,EVI_mean__20240601,EVI_mean__20240701,EVI_mean__20240801,EVI_mean__20240901,EVI_median__20231001,EVI_median__20231101,EVI_median__20231201,EVI_median__20240101,EVI_median__20240201,EVI_median__20240301,EVI_median__20240401,EVI_median__20240501,EVI_median__20240601,EVI_median__20240701,EVI_median__20240801,EVI_median__20240901,EVI_min__20231001,EVI_min__20231101,EVI_min__20231201,EVI_min__20240101,EVI_min__20240201,EVI_min__20240301,EVI_min__20240401,EVI_min__20240501,EVI_min__20240601,EVI_min__20240701,EVI_min__20240801,EVI_min__20240901,EVI_range__20231001,EVI_range__20231101,EVI_range__20231201,EVI_range__20240101,EVI_range__20240201,EVI_range__20240301,EVI_range__20240401,EVI_range__20240501,EVI_range__20240601,EVI_range__20240701,EVI_range__20240801,EVI_range__20240901,EVI_sd__20231001,EVI_sd__20231101,EVI_sd__20231201,EVI_sd__20240101,EVI_sd__20240201,EVI_sd__20240301,EVI_sd__20240401,EVI_sd__20240501,EVI_sd__20240601,EVI_sd__20240701,EVI_sd__20240801,EVI_sd__20240901,EVI_variance__20231001,EVI_variance__20231101,EVI_variance__20231201,EVI_variance__20240101,EVI_variance__20240201,EVI_variance__20240301,EVI_variance__20240401,EVI_variance__20240501,EVI_variance__20240601,EVI_variance__20240701,EVI_variance__20240801,EVI_variance__20240901,NDMI_coefficient_of_variation__20231001,NDMI_coefficient_of_variation__20231101,NDMI_coefficient_of_variation__20231201,NDMI_coefficient_of_variation__20240101,NDMI_coefficient_of_variation__20240201,NDMI_coefficient_of_variation__20240301,NDMI_coefficient_of_variation__20240401,NDMI_coefficient_of_variation__20240501,NDMI_coefficient_of_variation__20240601,NDMI_coefficient_of_variation__20240701,NDMI_coefficient_of_variation__20240801,NDMI_coefficient_of_variation__20240901,NDMI_max__20231001,NDMI_max__20231101,NDMI_max__20231201,NDMI_max__20240101,NDMI_max__20240201,NDMI_max__20240301,NDMI_max__20240401,NDMI_max__20240501,NDMI_max__20240601,NDMI_max__20240701,NDMI_max__20240801,NDMI_max__20240901,NDMI_mean__20231001,NDMI_mean__20231101,NDMI_mean__20231201,NDMI_mean__20240101,NDMI_mean__20240201,NDMI_mean__20240301,NDMI_mean__20240401,NDMI_mean__20240501,NDMI_mean__20240601,NDMI_mean__20240701,NDMI_mean__20240801,NDMI_mean__20240901,NDMI_median__20231001,NDMI_median__20231101,NDMI_median__20231201,NDMI_median__20240101,NDMI_median__20240201,NDMI_median__20240301,NDMI_median__20240401,NDMI_median__20240501,NDMI_median__20240601,NDMI_median__20240701,NDMI_median__20240801,NDMI_median__20240901,NDMI_min__20231001,NDMI_min__20231101,NDMI_min__20231201,NDMI_min__20240101,NDMI_min__20240201,NDMI_min__20240301,NDMI_min__20240401,NDMI_min__20240501,NDMI_min__20240601,NDMI_min__20240701,NDMI_min__20240801,NDMI_min__20240901,NDMI_range__20231001,NDMI_range__20231101,NDMI_range__20231201,NDMI_range__20240101,NDMI_range__20240201,NDMI_range__20240301,NDMI_range__20240401,NDMI_range__20240501,NDMI_range__20240601,NDMI_range__20240701,NDMI_range__20240801,NDMI_range__20240901,NDMI_sd__20231001,NDMI_sd__20231101,NDMI_sd__20231201,NDMI_sd__20240101,NDMI_sd__20240201,NDMI_sd__20240301,NDMI_sd__20240401,NDMI_sd__20240501,NDMI_sd__20240601,NDMI_sd__20240701,NDMI_sd__20240801,NDMI_sd__20240901,NDMI_variance__20231001,NDMI_variance__20231101,NDMI_variance__20231201,NDMI_variance__20240101,NDMI_variance__20240201,NDMI_variance__20240301,NDMI_variance__20240401,NDMI_variance__20240501,NDMI_variance__20240601,NDMI_variance__20240701,NDMI_variance__20240801,NDMI_variance__20240901,NDRE_coefficient_of_variation__20231001,NDRE_coefficient_of_variation__20231101,NDRE_coefficient_of_variation__20231201,NDRE_coefficient_of_variation__20240101,NDRE_coefficient_of_variation__20240201,NDRE_coefficient_of_variation__20240301,NDRE_coefficient_of_variation__20240401,NDRE_coefficient_of_variation__20240501,NDRE_coefficient_of_variation__20240601,NDRE_coefficient_of_variation__20240701,NDRE_coefficient_of_variation__20240801,NDRE_coefficient_of_variation__20240901,NDRE_max__20231001,NDRE_max__2023110

## Create or reuse the DEM mosaic

In [ ]:
# def_files_path = "F:/Dem/ESA_10"
# gdf_dem_tiles_path = os.path.join(def_files_path, "esa_tiles_dem_10m.gpkg")
# gdf_dem_tiles = read_data(gdf_dem_tiles_path)
# gdf_dem_tiles = gdf_dem_tiles.to_crs(epsg=EPSG_CODE)
# tiles_to_copy = gdf_dem_tiles[gdf_dem_tiles.geometry.intersects(parcel_geometry.union_all())]
# display(tiles_to_copy)
# for _, tile in tiles_to_copy.iterrows():
#     print(f"Processing tile: {tile}")
#     src_tile_path = os.path.join(def_files_path, tile.file_name)
#     dst_tile_path = os.path.join(DEM_DIR, tile.file_name)
#     if not os.path.isfile(dst_tile_path):
#         print(f"Copying {src_tile_path} to {dst_tile_path}")
#         shutil.copy(src_tile_path, dst_tile_path)

In [3]:
dem_tiles = find_dem_tiles(DEM_DIR, MOSAIC_PATH)
# Reuses a valid existing mosaic. Set overwrite=True to rebuild it.
MOSAIC_PATH = create_dem_mosaic(dem_tiles, MOSAIC_PATH, overwrite=False)

Using existing DEM mosaic: C:\work_dir\volvi-2023-2024\dem\dem_mosaic.tif

## Add elevation and overwrite the parcel file

In [4]:
parcels_with_elevation = append_parcel_elevation(
    parcels_path=PARCELS_PATH,
    mosaic_path=MOSAIC_PATH,
    output_path=PARCELS_PATH,
    all_touched=ALL_TOUCHED,
    overwrite=True,
)
assert parcels_with_elevation.crs == ORIGINAL_PARCEL_CRS

Reading file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Parcel dataset CRS: {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "GGRS87 / Greek Grid", "base_crs": {"name": "GGRS87", "datum": {"type": "GeodeticReferenceFrame", "name": "Greek Geodetic Reference System 1987", "ellipsoid": {"name": "GRS 1980", "semi_major_axis": 6378137, "inverse_flattening": 298.257222101}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4121}}, "conversion": {"name": "Greek Grid", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 24, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Engineering survey, topographic mapping.", "area": "Greece - onshore.", "bbox": {"south_latitude": 34.88, "west_longitude": 19.57, "north_latitude": 41.75, "east_longitude": 28.3}, "id": {"authority": "EPSG", "code": 2100}}
Parcel CRS type: <class 'pyproj.crs.crs.CRS'>
Parcel CRS to_epsg(): 2100
Parcel CRS is_projected: True
Reprojecting parcel geometries from {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "GGRS87 / Greek Grid", "base_crs": {"name": "GGRS87", "datum": {"type": "GeodeticReferenceFrame", "name": "Greek Geodetic Reference System 1987", "ellipsoid": {"name": "GRS 1980", "semi_major_axis": 6378137, "inverse_flattening": 298.257222101}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4121}}, "conversion": {"name": "Greek Grid", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 24, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Engineering survey, topographic mapping.", "area": "Greece - onshore.", "bbox": {"south_latitude": 34.88, "west_longitude": 19.57, "north_latitude": 41.75, "east_longitude": 28.3}, "id": {"authority": "EPSG", "code": 2100}} to EPSG:4326 for zonal statistics.
Processed 5,000/28,699 parcels
Processed 10,000/28,699 parcels
Processed 15,000/28,699 parcels
Processed 20,000/28,699 parcels
Processed 25,000/28,699 parcels
Processed 28,699/28,699 parcels
Writing file: C:/work_dir/volvi-2023-2024/1_parcel_stats/.satellite_parcel_time_stats.tmp.geoparquet
Saved parcels with mean elevation: C:\work_dir\volvi-2023-2024\1_parcel_stats\satellite_parcel_time_stats.geoparquet
Parcels without a valid DEM pixel: 0/28,699

## Add nearest-lake features

Distance is the minimum polygon-to-polygon distance in EPSG:2100 metres. `nearest_lake_row_id` stores the stable GeoPackage feature ID (`fid`) of the matched lake.

In [5]:
parcels_with_features = append_nearest_lake_features(
    parcels_path=PARCELS_PATH,
    lakes_path=LAKES_PATH,
    output_path=PARCELS_PATH,
    lakes_layer=LAKES_LAYER,
    overwrite=True,
)
assert parcels_with_features.crs == ORIGINAL_PARCEL_CRS

Reading file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Reading file: C:/work_dir/Lakes.gpkg Layer: lakes_qgis
Writing file: C:/work_dir/volvi-2023-2024/1_parcel_stats/.satellite_parcel_time_stats.tmp.geoparquet
Saved parcels with nearest-lake features: C:\work_dir\volvi-2023-2024\1_parcel_stats\satellite_parcel_time_stats.geoparquet

## Add the soil attribute

Each parcel receives `GAIOIKANOT` from the soil polygon intersecting its centroid. Centroids are calculated in the original projected parcel CRS.

In [6]:
parcels_with_features = append_soil_feature(
    parcels_path=PARCELS_PATH,
    soil_path=SOIL_PATH,
    output_path=PARCELS_PATH,
    soil_layer=SOIL_LAYER,
    attribute_column="GAIOIKANOT",
    overwrite=True,
)
assert parcels_with_features.crs == ORIGINAL_PARCEL_CRS

Reading file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Reading file: C:/work_dir/Agro_Soil.gpkg Layer: ____
Writing file: C:/work_dir/volvi-2023-2024/1_parcel_stats/.satellite_parcel_time_stats.tmp.geoparquet
Saved parcels with soil feature 'GAIOIKANOT': C:\work_dir\volvi-2023-2024\1_parcel_stats\satellite_parcel_time_stats.geoparquet
Parcels whose centroid did not intersect a soil polygon: 0/28,699

## Checks

In [7]:
feature_columns = [
    "elevation_mean_m",
    "elevation_valid_pixel_count",
    "distance_to_nearest_lake_m",
    "nearest_lake_row_id",
    "GAIOIKANOT",
]
saved_parcels = read_data(str(PARCELS_PATH))
assert saved_parcels.crs == ORIGINAL_PARCEL_CRS, (saved_parcels.crs, ORIGINAL_PARCEL_CRS)
validate_projected_metric_crs(saved_parcels.crs, dataset_name="Saved parcel dataset")
summary = saved_parcels[["elevation_mean_m", "elevation_valid_pixel_count", "distance_to_nearest_lake_m"]].describe()
missing_elevation = int(saved_parcels["elevation_mean_m"].isna().sum())
missing_lake = int(saved_parcels["distance_to_nearest_lake_m"].isna().sum())
missing_soil = int(saved_parcels["GAIOIKANOT"].isna().sum())
print(f"Rows: {len(saved_parcels):,}")
print(f"Preserved projected CRS: {saved_parcels.crs}")
print(f"Missing elevation: {missing_elevation:,}")
print(f"Missing nearest lake: {missing_lake:,}")
print(f"Missing soil attribute: {missing_soil:,}")
display(saved_parcels["GAIOIKANOT"].value_counts(dropna=False).head(10))
summary

Reading file: C:/work_dir/volvi-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet
Rows: 28,699
Preserved projected CRS: {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "GGRS87 / Greek Grid", "base_crs": {"name": "GGRS87", "datum": {"type": "GeodeticReferenceFrame", "name": "Greek Geodetic Reference System 1987", "ellipsoid": {"name": "GRS 1980", "semi_major_axis": 6378137, "inverse_flattening": 298.257222101}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4121}}, "conversion": {"name": "Greek Grid", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 24, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Engineering survey, topographic mapping.", "area": "Greece - onshore.", "bbox": {"south_latitude": 34.88, "west_longitude": 19.57, "north_latitude": 41.75, "east_longitude": 28.3}, "id": {"authority": "EPSG", "code": 2100}}
Missing elevation: 0
Missing nearest lake: 0
Missing soil attribute: 0

GAIOIKANOT
A8-111-4-D9EE      11099
T7-111-2-D9QQ       5872
T7-111-1-D9BB       1409
T7-121-1-D9EN       1391
A7-111-1-D9EE       1381
T7-221-1-D9EN       1188
T7-111-1-D9NN       1025
T7T3-121-1-D9NN     1000
X7X3-221-1-D9BB      927
B8A8-771-2-D4EE      312
Name: count, dtype: int64

,elevation_mean_m,elevation_valid_pixel_count,distance_to_nearest_lake_m
count,28699.0000000000,28699.0000000000,28699.0000000000
mean,142.9824670179,62.1190982264,6925.5555504542
std,80.8448544472,48.9172681083,4945.4571449699
min,36.0620073591,15.0000000000,0.0000000000
25%,86.9012568781,35.0000000000,2354.8396516067
50%,113.3735331874,50.0000000000,6049.1007563112
75%,190.5933425819,75.0000000000,11189.3877885827
max,610.1514601935,2283.0000000000,19823.3975368023

In [8]:
saved_parcels.head()

,parcel_code,initial_label_code,initial_label,predicted_label_code,predicted_label,prediction_probability,set_type,label_gr,geometry,batch_number,intersected_pixel_count,meets_minimum_pixel_count,expected_pixel_count,temporal_filled_pixel_count,spatial_filled_pixel_count,temporal_filled_ratio,spatial_filled_ratio,data_reliability_score,pixel_area,geom_area,geom_interior_area_ratio,geom_compactness,geom_perimeter_area_ratio,geom_shape_index,geom_elongation,geom_shape_complexity_score,B02_coefficient_of_variation__20231001,B02_coefficient_of_variation__20231101,B02_coefficient_of_variation__20231201,B02_coefficient_of_variation__20240101,B02_coefficient_of_variation__20240201,B02_coefficient_of_variation__20240301,B02_coefficient_of_variation__20240401,B02_coefficient_of_variation__20240501,B02_coefficient_of_variation__20240601,B02_coefficient_of_variation__20240701,B02_coefficient_of_variation__20240801,B02_coefficient_of_variation__20240901,B02_max__20231001,B02_max__20231101,B02_max__20231201,B02_max__20240101,B02_max__20240201,B02_max__20240301,B02_max__20240401,B02_max__20240501,B02_max__20240601,B02_max__20240701,B02_max__20240801,B02_max__20240901,B02_mean__20231001,B02_mean__20231101,B02_mean__20231201,B02_mean__20240101,B02_mean__20240201,B02_mean__20240301,B02_mean__20240401,B02_mean__20240501,B02_mean__20240601,B02_mean__20240701,B02_mean__20240801,B02_mean__20240901,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_min__20231001,B02_min__20231101,B02_min__20231201,B02_min__20240101,B02_min__20240201,B02_min__20240301,B02_min__20240401,B02_min__20240501,B02_min__20240601,B02_min__20240701,B02_min__20240801,B02_min__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B02_variance__20231001,B02_variance__20231101,B02_variance__20231201,B02_variance__20240101,B02_variance__20240201,B02_variance__20240301,B02_variance__20240401,B02_variance__20240501,B02_variance__20240601,B02_variance__20240701,B02_variance__20240801,B02_variance__20240901,B03_coefficient_of_variation__20231001,B03_coefficient_of_variation__20231101,B03_coefficient_of_variation__20231201,B03_coefficient_of_variation__20240101,B03_coefficient_of_variation__20240201,B03_coefficient_of_variation__20240301,B03_coefficient_of_variation__20240401,B03_coefficient_of_variation__20240501,B03_coefficient_of_variation__20240601,B03_coefficient_of_variation__20240701,B03_coefficient_of_variation__20240801,B03_coefficient_of_variation__20240901,B03_max__20231001,B03_max__20231101,B03_max__20231201,B03_max__20240101,B03_max__20240201,B03_max__20240301,B03_max__20240401,B03_max__20240501,B03_max__20240601,B03_max__20240701,B03_max__20240801,B03_max__20240901,B03_mean__20231001,B03_mean__20231101,B03_mean__20231201,B03_mean__20240101,B03_mean__20240201,B03_mean__20240301,B03_mean__20240401,B03_mean__20240501,B03_mean__20240601,B03_mean__20240701,B03_mean__20240801,B03_mean__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_min__20231001,B03_min__20231101,B03_min__20231201,B03_min__20240101,B03_min__20240201,B03_min__20240301,B03_min__20240401,B03_min__20240501,B03_min__20240601,B03_min__20240701,B03_min__20240801,B03_min__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B03_variance__20231001,B03_variance__20231101,B03_variance__20231201,B03_variance__20240101,B03_variance__20240201,B03_variance__20240301,B03_variance__20240401,B03_variance__20240501,B03_variance__20240601,B03_variance__20240701,B03_variance__20240801,B03_variance__20240901,B04_coefficient_of_variation__20231001,B04_coefficient_of_variation__20231101,B04_coefficient_of_variation__20231201,B04_coefficient_of_variation__20240101,B04_coefficient_of_variation__20240201,B04_coefficient_of_variation__20240301,B04_coefficient_of_variation__20240401,B04_coefficient_of_variation__20240501,B04_coefficient_of_variation__20240601,B04_coefficient_of_variation__20240701,B04_coefficient_of_variation__20240801,B04_coefficient_of_variation__20240901,B04_max__20231001,B04_max__20231101,B04_max__20231201,B04_max__20240101,B04_max__20240201,B04_max__20240301,B04_max__20240401,B04_max__20240501,B04_max__20240601,B04_max__20240701,B04_max__20240801,B04_max__20240901,B04_mean__20231001,B04_mean__20231101,B04_mean__20231201,B04_mean__20240101,B04_mean__20240201,B04_mean__20240301,B04_mean__20240401,B04_mean__20240501,B04_mean__20240601,B04_mean__20240701,B04_mean__20240801,B04_mean__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_min__20231001,B04_min__20231101,B04_min__20231201,B04_min__20240101,B04_min__20240201,B04_min__20240301,B04_min__20240401,B04_min__20240501,B04_min__20240601,B04_min__20240701,B04_min__20240801,B04_min__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B04_variance__20231001,B04_variance__20231101,B04_variance__20231201,B04_variance__20240101,B04_variance__20240201,B04_variance__20240301,B04_variance__20240401,B04_variance__20240501,B04_variance__20240601,B04_variance__20240701,B04_variance__20240801,B04_variance__20240901,B05_coefficient_of_variation__20231001,B05_coefficient_of_variation__20231101,B05_coefficient_of_variation__20231201,B05_coefficient_of_variation__20240101,B05_coefficient_of_variation__20240201,B05_coefficient_of_variation__20240301,B05_coefficient_of_variation__20240401,B05_coefficient_of_variation__20240501,B05_coefficient_of_variation__20240601,B05_coefficient_of_variation__20240701,B05_coefficient_of_variation__20240801,B05_coefficient_of_variation__20240901,B05_max__20231001,B05_max__20231101,B05_max__20231201,B05_max__20240101,B05_max__20240201,B05_max__20240301,B05_max__20240401,B05_max__20240501,B05_max__20240601,B05_max__20240701,B05_max__20240801,B05_max__20240901,B05_mean__20231001,B05_mean__20231101,B05_mean__20231201,B05_mean__20240101,B05_mean__20240201,B05_mean__20240301,B05_mean__20240401,B05_mean__20240501,B05_mean__20240601,B05_mean__20240701,B05_mean__20240801,B05_mean__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_min__20231001,B05_min__20231101,B05_min__20231201,B05_min__20240101,B05_min__20240201,B05_min__20240301,B05_min__20240401,B05_min__20240501,B05_min__20240601,B05_min__20240701,B05_min__20240801,B05_min__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B05_variance__20231001,B05_variance__20231101,B05_variance__20231201,B05_variance__20240101,B05_variance__20240201,B05_variance__20240301,B05_variance__20240401,B05_variance__20240501,B05_variance__20240601,B05_variance__20240701,B05_variance__20240801,B05_variance__20240901,B08_coefficient_of_variation__20231001,B08_coefficient_of_variation__20231101,B08_coefficient_of_variation__20231201,B08_coefficient_of_variation__20240101,B08_coefficient_of_variation__20240201,B08_coefficient_of_variation__20240301,B08_coefficient_of_variation__20240401,B08_coefficient_of_variation__20240501,B08_coefficient_of_variation__20240601,B08_coefficient_of_variation__20240701,B08_coefficient_of_variation__20240801,B08_coefficient_of_variation__20240901,B08_max__20231001,B08_max__20231101,B08_max__20231201,B08_max__20240101,B08_max__20240201,B08_max__20240301,B08_max__20240401,B08_max__20240501,B08_max__20240601,B08_max__20240701,B08_max__20240801,B08_max__20240901,B08_mean__20231001,B08_mean__20231101,B08_mean__20231201,B08_mean__20240101,B08_mean__20240201,B08_mean__20240301,B08_mean__20240401,B08_mean__20240501,B08_mean__20240601,B08_mean__20240701,B08_mean__20240801,B08_mean__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_min__20231001,B08_min__20231101,B08_min__20231201,B08_min__20240101,B08_min__20240201,B08_min__20240301,B08_min__20240401,B08_min__20240501,B08_min__20240601,B08_min__20240701,B08_min__20240801,B08_min__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B08_variance__20231001,B08_variance__20231101,B08_variance__20231201,B08_variance__20240101,B08_variance__20240201,B08_variance__20240301,B08_variance__20240401,B08_variance__20240501,B08_variance__20240601,B08_variance__20240701,B08_variance__20240801,B08_variance__20240901,B11_coefficient_of_variation__20231001,B11_coefficient_of_variation__20231101,B11_coefficient_of_variation__20231201,B11_coefficient_of_variation__20240101,B11_coefficient_of_variation__20240201,B11_coefficient_of_variation__20240301,B11_coefficient_of_variation__20240401,B11_coefficient_of_variation__20240501,B11_coefficient_of_variation__20240601,B11_coefficient_of_variation__20240701,B11_coefficient_of_variation__20240801,B11_coefficient_of_variation__20240901,B11_max__20231001,B11_max__20231101,B11_max__20231201,B11_max__20240101,B11_max__20240201,B11_max__20240301,B11_max__20240401,B11_max__20240501,B11_max__20240601,B11_max__20240701,B11_max__20240801,B11_max__20240901,B11_mean__20231001,B11_mean__20231101,B11_mean__20231201,B11_mean__20240101,B11_mean__20240201,B11_mean__20240301,B11_mean__20240401,B11_mean__20240501,B11_mean__20240601,B11_mean__20240701,B11_mean__20240801,B11_mean__20240901,B11_median__20231001,B11_median__20231101,B11_median__20231201,B11_median__20240101,B11_median__20240201,B11_median__20240301,B11_median__20240401,B11_median__20240501,B11_median__20240601,B11_median__20240701,B11_median__20240801,B11_median__20240901,B11_min__20231001,B11_min__20231101,B11_min__20231201,B11_min__20240101,B11_min__20240201,B11_min__20240301,B11_min__20240401,B11_min__20240501,B11_min__20240601,B11_min__20240701,B11_min__20240801,B11_min__20240901,B11_range__20231001,B11_range__20231101,B11_range__20231201,B11_range__20240101,B11_range__20240201,B11_range__20240301,B11_range__20240401,B11_range__20240501,B11_range__20240601,B11_range__20240701,B11_range__20240801,B11_range__20240901,B11_sd__20231001,B11_sd__20231101,B11_sd__20231201,B11_sd__20240101,B11_sd__20240201,B11_sd__20240301,B11_sd__20240401,B11_sd__20240501,B11_sd__20240601,B11_sd__20240701,B11_sd__20240801,B11_sd__20240901,B11_variance__20231001,B11_variance__20231101,B11_variance__20231201,B11_variance__20240101,B11_variance__20240201,B11_variance__20240301,B11_variance__20240401,B11_variance__20240501,B11_variance__20240601,B11_variance__20240701,B11_variance__20240801,B11_variance__20240901,B12_coefficient_of_variation__20231001,B12_coefficient_of_variation__20231101,B12_coefficient_of_variation__20231201,B12_coefficient_of_variation__20240101,B12_coefficient_of_variation__20240201,B12_coefficient_of_variation__20240301,B12_coefficient_of_variation__20240401,B12_coefficient_of_variation__20240501,B12_coefficient_of_variation__20240601,B12_coefficient_of_variation__20240701,B12_coefficient_of_variation__20240801,B12_coefficient_of_variation__20240901,B12_max__20231001,B12_max__20231101,B12_max__20231201,B12_max__20240101,B12_max__20240201,B12_max__20240301,B12_max__20240401,B12_max__20240501,B12_max__20240601,B12_max__20240701,B12_max__20240801,B12_max__20240901,B12_mean__20231001,B12_mean__20231101,B12_mean__20231201,B12_mean__20240101,B12_mean__20240201,B12_mean__20240301,B12_mean__20240401,B12_mean__20240501,B12_mean__20240601,B12_mean__20240701,B12_mean__20240801,B12_mean__20240901,B12_median__20231001,B12_median__20231101,B12_median__20231201,B12_median__20240101,B12_median__20240201,B12_median__20240301,B12_median__20240401,B12_median__20240501,B12_median__20240601,B12_median__20240701,B12_median__20240801,B12_median__20240901,B12_min__20231001,B12_min__20231101,B12_min__20231201,B12_min__20240101,B12_min__20240201,B12_min__20240301,B12_min__20240401,B12_min__20240501,B12_min__20240601,B12_min__20240701,B12_min__20240801,B12_min__20240901,B12_range__20231001,B12_range__20231101,B12_range__20231201,B12_range__20240101,B12_range__20240201,B12_range__20240301,B12_range__20240401,B12_range__20240501,B12_range__20240601,B12_range__20240701,B12_range__20240801,B12_range__20240901,B12_sd__20231001,B12_sd__20231101,B12_sd__20231201,B12_sd__20240101,B12_sd__20240201,B12_sd__20240301,B12_sd__20240401,B12_sd__20240501,B12_sd__20240601,B12_sd__20240701,B12_sd__20240801,B12_sd__20240901,B12_variance__20231001,B12_variance__20231101,B12_variance__20231201,B12_variance__20240101,B12_variance__20240201,B12_variance__20240301,B12_variance__20240401,B12_variance__20240501,B12_variance__20240601,B12_variance__20240701,B12_variance__20240801,B12_variance__20240901,EVI_coefficient_of_variation__20231001,EVI_coefficient_of_variation__20231101,EVI_coefficient_of_variation__20231201,EVI_coefficient_of_variation__20240101,EVI_coefficient_of_variation__20240201,EVI_coefficient_of_variation__20240301,EVI_coefficient_of_variation__20240401,EVI_coefficient_of_variation__20240501,EVI_coefficient_of_variation__20240601,EVI_coefficient_of_variation__20240701,EVI_coefficient_of_variation__20240801,EVI_coefficient_of_variation__20240901,EVI_max__20231001,EVI_max__20231101,EVI_max__20231201,EVI_max__20240101,EVI_max__20240201,EVI_max__20240301,EVI_max__20240401,EVI_max__20240501,EVI_max__20240601,EVI_max__20240701,EVI_max__20240801,EVI_max__20240901,EVI_mean__20231001,EVI_mean__20231101,EVI_mean__20231201,EVI_mean__20240101,EVI_mean__20240201,EVI_mean__20240301,EVI_mean__20240401,EVI_mean__20240501,EVI_mean__20240601,EVI_mean__20240701,EVI_mean__20240801,EVI_mean__20240901,EVI_median__20231001,EVI_median__20231101,EVI_median__20231201,EVI_median__20240101,EVI_median__20240201,EVI_median__20240301,EVI_median__20240401,EVI_median__20240501,EVI_median__20240601,EVI_median__20240701,EVI_median__20240801,EVI_median__20240901,EVI_min__20231001,EVI_min__20231101,EVI_min__20231201,EVI_min__20240101,EVI_min__20240201,EVI_min__20240301,EVI_min__20240401,EVI_min__20240501,EVI_min__20240601,EVI_min__20240701,EVI_min__20240801,EVI_min__20240901,EVI_range__20231001,EVI_range__20231101,EVI_range__20231201,EVI_range__20240101,EVI_range__20240201,EVI_range__20240301,EVI_range__20240401,EVI_range__20240501,EVI_range__20240601,EVI_range__20240701,EVI_range__20240801,EVI_range__20240901,EVI_sd__20231001,EVI_sd__20231101,EVI_sd__20231201,EVI_sd__20240101,EVI_sd__20240201,EVI_sd__20240301,EVI_sd__20240401,EVI_sd__20240501,EVI_sd__20240601,EVI_sd__20240701,EVI_sd__20240801,EVI_sd__20240901,EVI_variance__20231001,EVI_variance__20231101,EVI_variance__20231201,EVI_variance__20240101,EVI_variance__20240201,EVI_variance__20240301,EVI_variance__20240401,EVI_variance__20240501,EVI_variance__20240601,EVI_variance__20240701,EVI_variance__20240801,EVI_variance__20240901,NDMI_coefficient_of_variation__20231001,NDMI_coefficient_of_variation__20231101,NDMI_coefficient_of_variation__20231201,NDMI_coefficient_of_variation__20240101,NDMI_coefficient_of_variation__20240201,NDMI_coefficient_of_variation__20240301,NDMI_coefficient_of_variation__20240401,NDMI_coefficient_of_variation__20240501,NDMI_coefficient_of_variation__20240601,NDMI_coefficient_of_variation__20240701,NDMI_coefficient_of_variation__20240801,NDMI_coefficient_of_variation__20240901,NDMI_max__20231001,NDMI_max__20231101,NDMI_max__20231201,NDMI_max__20240101,NDMI_max__20240201,NDMI_max__20240301,NDMI_max__20240401,NDMI_max__20240501,NDMI_max__20240601,NDMI_max__20240701,NDMI_max__20240801,NDMI_max__20240901,NDMI_mean__20231001,NDMI_mean__20231101,NDMI_mean__20231201,NDMI_mean__20240101,NDMI_mean__20240201,NDMI_mean__20240301,NDMI_mean__20240401,NDMI_mean__20240501,NDMI_mean__20240601,NDMI_mean__20240701,NDMI_mean__20240801,NDMI_mean__20240901,NDMI_median__20231001,NDMI_median__20231101,NDMI_median__20231201,NDMI_median__20240101,NDMI_median__20240201,NDMI_median__20240301,NDMI_median__20240401,NDMI_median__20240501,NDMI_median__20240601,NDMI_median__20240701,NDMI_median__20240801,NDMI_median__20240901,NDMI_min__20231001,NDMI_min__20231101,NDMI_min__20231201,NDMI_min__20240101,NDMI_min__20240201,NDMI_min__20240301,NDMI_min__20240401,NDMI_min__20240501,NDMI_min__20240601,NDMI_min__20240701,NDMI_min__20240801,NDMI_min__20240901,NDMI_range__20231001,NDMI_range__20231101,NDMI_range__20231201,NDMI_range__20240101,NDMI_range__20240201,NDMI_range__20240301,NDMI_range__20240401,NDMI_range__20240501,NDMI_range__20240601,NDMI_range__20240701,NDMI_range__20240801,NDMI_range__20240901,NDMI_sd__20231001,NDMI_sd__20231101,NDMI_sd__20231201,NDMI_sd__20240101,NDMI_sd__20240201,NDMI_sd__20240301,NDMI_sd__20240401,NDMI_sd__20240501,NDMI_sd__20240601,NDMI_sd__20240701,NDMI_sd__20240801,NDMI_sd__20240901,NDMI_variance__20231001,NDMI_variance__20231101,NDMI_variance__20231201,NDMI_variance__20240101,NDMI_variance__20240201,NDMI_variance__20240301,NDMI_variance__20240401,NDMI_variance__20240501,NDMI_variance__20240601,NDMI_variance__20240701,NDMI_variance__20240801,NDMI_variance__20240901,NDRE_coefficient_of_variation__20231001,NDRE_coefficient_of_variation__20231101,NDRE_coefficient_of_variation__20231201,NDRE_coefficient_of_variation__20240101,NDRE_coefficient_of_variation__20240201,NDRE_coefficient_of_variation__20240301,NDRE_coefficient_of_variation__20240401,NDRE_coefficient_of_variation__20240501,NDRE_coefficient_of_variation__20240601,NDRE_coefficient_of_variation__20240701,NDRE_coefficient_of_variation__20240801,NDRE_coefficient_of_variation__20240901,NDRE_max__20231001,NDRE_max__2023110