In [1]:
from pathlib import Path
import os

from import_libraries import *  # NOSONAR
from global_variables import *  # NOSONAR
import common_libraries.io_library as io_l

from ml_classification.ml_classification_pipeline import (
    GeospatialClassificationPipeline,
    ClassificationPipelineConfig,
)

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\xicor\__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

In [2]:
WORK_PATH = Path("C:/work_dir/k_makedonia-2023-2024")

PARCELS_PATH = WORK_PATH / "1_parcel_stats" / "satellite_parcel_time_stats.geoparquet"
OUTPUT_PATH = WORK_PATH / "3_ml_classification"

class_column = "initial_label_code"
parcel_id_column = "parcel_code"

In [3]:
gdf_parcels = io_l.read_data(str(PARCELS_PATH))
gdf_parcels.head(3)

Reading file: C:/work_dir/k_makedonia-2023-2024/1_parcel_stats/satellite_parcel_time_stats.geoparquet

,parcel_code,initial_label_code,initial_label,predicted_label_code,predicted_label,prediction_probability,set_type,geometry,batch_number,eligible_pixel_count,meets_minimum_pixel_count,parcel_area_m2,approx_pixel_count,B02_bowley_skewness__20231001,B02_bowley_skewness__20231101,B02_bowley_skewness__20231201,B02_bowley_skewness__20240101,B02_bowley_skewness__20240201,B02_bowley_skewness__20240301,B02_bowley_skewness__20240401,B02_bowley_skewness__20240501,B02_bowley_skewness__20240601,B02_bowley_skewness__20240701,B02_bowley_skewness__20240801,B02_bowley_skewness__20240901,B02_coefficient_of_variation__20231001,B02_coefficient_of_variation__20231101,B02_coefficient_of_variation__20231201,B02_coefficient_of_variation__20240101,B02_coefficient_of_variation__20240201,B02_coefficient_of_variation__20240301,B02_coefficient_of_variation__20240401,B02_coefficient_of_variation__20240501,B02_coefficient_of_variation__20240601,B02_coefficient_of_variation__20240701,B02_coefficient_of_variation__20240801,B02_coefficient_of_variation__20240901,B02_iqr__20231001,B02_iqr__20231101,B02_iqr__20231201,B02_iqr__20240101,B02_iqr__20240201,B02_iqr__20240301,B02_iqr__20240401,B02_iqr__20240501,B02_iqr__20240601,B02_iqr__20240701,B02_iqr__20240801,B02_iqr__20240901,B02_max__20231001,B02_max__20231101,B02_max__20231201,B02_max__20240101,B02_max__20240201,B02_max__20240301,B02_max__20240401,B02_max__20240501,B02_max__20240601,B02_max__20240701,B02_max__20240801,B02_max__20240901,B02_mean__20231001,B02_mean__20231101,B02_mean__20231201,B02_mean__20240101,B02_mean__20240201,B02_mean__20240301,B02_mean__20240401,B02_mean__20240501,B02_mean__20240601,B02_mean__20240701,B02_mean__20240801,B02_mean__20240901,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_min__20231001,B02_min__20231101,B02_min__20231201,B02_min__20240101,B02_min__20240201,B02_min__20240301,B02_min__20240401,B02_min__20240501,B02_min__20240601,B02_min__20240701,B02_min__20240801,B02_min__20240901,B02_p10__20231001,B02_p10__20231101,B02_p10__20231201,B02_p10__20240101,B02_p10__20240201,B02_p10__20240301,B02_p10__20240401,B02_p10__20240501,B02_p10__20240601,B02_p10__20240701,B02_p10__20240801,B02_p10__20240901,B02_p25__20231001,B02_p25__20231101,B02_p25__20231201,B02_p25__20240101,B02_p25__20240201,B02_p25__20240301,B02_p25__20240401,B02_p25__20240501,B02_p25__20240601,B02_p25__20240701,B02_p25__20240801,B02_p25__20240901,B02_p75__20231001,B02_p75__20231101,B02_p75__20231201,B02_p75__20240101,B02_p75__20240201,B02_p75__20240301,B02_p75__20240401,B02_p75__20240501,B02_p75__20240601,B02_p75__20240701,B02_p75__20240801,B02_p75__20240901,B02_p90__20231001,B02_p90__20231101,B02_p90__20231201,B02_p90__20240101,B02_p90__20240201,B02_p90__20240301,B02_p90__20240401,B02_p90__20240501,B02_p90__20240601,B02_p90__20240701,B02_p90__20240801,B02_p90__20240901,B02_p90_p10_spread__20231001,B02_p90_p10_spread__20231101,B02_p90_p10_spread__20231201,B02_p90_p10_spread__20240101,B02_p90_p10_spread__20240201,B02_p90_p10_spread__20240301,B02_p90_p10_spread__20240401,B02_p90_p10_spread__20240501,B02_p90_p10_spread__20240601,B02_p90_p10_spread__20240701,B02_p90_p10_spread__20240801,B02_p90_p10_spread__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B02_variance__20231001,B02_variance__20231101,B02_variance__20231201,B02_variance__20240101,B02_variance__20240201,B02_variance__20240301,B02_variance__20240401,B02_variance__20240501,B02_variance__20240601,B02_variance__20240701,B02_variance__20240801,B02_variance__20240901,B03_bowley_skewness__20231001,B03_bowley_skewness__20231101,B03_bowley_skewness__20231201,B03_bowley_skewness__20240101,B03_bowley_skewness__20240201,B03_bowley_skewness__20240301,B03_bowley_skewness__20240401,B03_bowley_skewness__20240501,B03_bowley_skewness__20240601,B03_bowley_skewness__20240701,B03_bowley_skewness__20240801,B03_bowley_skewness__20240901,B03_coefficient_of_variation__20231001,B03_coefficient_of_variation__20231101,B03_coefficient_of_variation__20231201,B03_coefficient_of_variation__20240101,B03_coefficient_of_variation__20240201,B03_coefficient_of_variation__20240301,B03_coefficient_of_variation__20240401,B03_coefficient_of_variation__20240501,B03_coefficient_of_variation__20240601,B03_coefficient_of_variation__20240701,B03_coefficient_of_variation__20240801,B03_coefficient_of_variation__20240901,B03_iqr__20231001,B03_iqr__20231101,B03_iqr__20231201,B03_iqr__20240101,B03_iqr__20240201,B03_iqr__20240301,B03_iqr__20240401,B03_iqr__20240501,B03_iqr__20240601,B03_iqr__20240701,B03_iqr__20240801,B03_iqr__20240901,B03_max__20231001,B03_max__20231101,B03_max__20231201,B03_max__20240101,B03_max__20240201,B03_max__20240301,B03_max__20240401,B03_max__20240501,B03_max__20240601,B03_max__20240701,B03_max__20240801,B03_max__20240901,B03_mean__20231001,B03_mean__20231101,B03_mean__20231201,B03_mean__20240101,B03_mean__20240201,B03_mean__20240301,B03_mean__20240401,B03_mean__20240501,B03_mean__20240601,B03_mean__20240701,B03_mean__20240801,B03_mean__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_min__20231001,B03_min__20231101,B03_min__20231201,B03_min__20240101,B03_min__20240201,B03_min__20240301,B03_min__20240401,B03_min__20240501,B03_min__20240601,B03_min__20240701,B03_min__20240801,B03_min__20240901,B03_p10__20231001,B03_p10__20231101,B03_p10__20231201,B03_p10__20240101,B03_p10__20240201,B03_p10__20240301,B03_p10__20240401,B03_p10__20240501,B03_p10__20240601,B03_p10__20240701,B03_p10__20240801,B03_p10__20240901,B03_p25__20231001,B03_p25__20231101,B03_p25__20231201,B03_p25__20240101,B03_p25__20240201,B03_p25__20240301,B03_p25__20240401,B03_p25__20240501,B03_p25__20240601,B03_p25__20240701,B03_p25__20240801,B03_p25__20240901,B03_p75__20231001,B03_p75__20231101,B03_p75__20231201,B03_p75__20240101,B03_p75__20240201,B03_p75__20240301,B03_p75__20240401,B03_p75__20240501,B03_p75__20240601,B03_p75__20240701,B03_p75__20240801,B03_p75__20240901,B03_p90__20231001,B03_p90__20231101,B03_p90__20231201,B03_p90__20240101,B03_p90__20240201,B03_p90__20240301,B03_p90__20240401,B03_p90__20240501,B03_p90__20240601,B03_p90__20240701,B03_p90__20240801,B03_p90__20240901,B03_p90_p10_spread__20231001,B03_p90_p10_spread__20231101,B03_p90_p10_spread__20231201,B03_p90_p10_spread__20240101,B03_p90_p10_spread__20240201,B03_p90_p10_spread__20240301,B03_p90_p10_spread__20240401,B03_p90_p10_spread__20240501,B03_p90_p10_spread__20240601,B03_p90_p10_spread__20240701,B03_p90_p10_spread__20240801,B03_p90_p10_spread__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B03_variance__20231001,B03_variance__20231101,B03_variance__20231201,B03_variance__20240101,B03_variance__20240201,B03_variance__20240301,B03_variance__20240401,B03_variance__20240501,B03_variance__20240601,B03_variance__20240701,B03_variance__20240801,B03_variance__20240901,B04_bowley_skewness__20231001,B04_bowley_skewness__20231101,B04_bowley_skewness__20231201,B04_bowley_skewness__20240101,B04_bowley_skewness__20240201,B04_bowley_skewness__20240301,B04_bowley_skewness__20240401,B04_bowley_skewness__20240501,B04_bowley_skewness__20240601,B04_bowley_skewness__20240701,B04_bowley_skewness__20240801,B04_bowley_skewness__20240901,B04_coefficient_of_variation__20231001,B04_coefficient_of_variation__20231101,B04_coefficient_of_variation__20231201,B04_coefficient_of_variation__20240101,B04_coefficient_of_variation__20240201,B04_coefficient_of_variation__20240301,B04_coefficient_of_variation__20240401,B04_coefficient_of_variation__20240501,B04_coefficient_of_variation__20240601,B04_coefficient_of_variation__20240701,B04_coefficient_of_variation__20240801,B04_coefficient_of_variation__20240901,B04_iqr__20231001,B04_iqr__20231101,B04_iqr__20231201,B04_iqr__20240101,B04_iqr__20240201,B04_iqr__20240301,B04_iqr__20240401,B04_iqr__20240501,B04_iqr__20240601,B04_iqr__20240701,B04_iqr__20240801,B04_iqr__20240901,B04_max__20231001,B04_max__20231101,B04_max__20231201,B04_max__20240101,B04_max__20240201,B04_max__20240301,B04_max__20240401,B04_max__20240501,B04_max__20240601,B04_max__20240701,B04_max__20240801,B04_max__20240901,B04_mean__20231001,B04_mean__20231101,B04_mean__20231201,B04_mean__20240101,B04_mean__20240201,B04_mean__20240301,B04_mean__20240401,B04_mean__20240501,B04_mean__20240601,B04_mean__20240701,B04_mean__20240801,B04_mean__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_min__20231001,B04_min__20231101,B04_min__20231201,B04_min__20240101,B04_min__20240201,B04_min__20240301,B04_min__20240401,B04_min__20240501,B04_min__20240601,B04_min__20240701,B04_min__20240801,B04_min__20240901,B04_p10__20231001,B04_p10__20231101,B04_p10__20231201,B04_p10__20240101,B04_p10__20240201,B04_p10__20240301,B04_p10__20240401,B04_p10__20240501,B04_p10__20240601,B04_p10__20240701,B04_p10__20240801,B04_p10__20240901,B04_p25__20231001,B04_p25__20231101,B04_p25__20231201,B04_p25__20240101,B04_p25__20240201,B04_p25__20240301,B04_p25__20240401,B04_p25__20240501,B04_p25__20240601,B04_p25__20240701,B04_p25__20240801,B04_p25__20240901,B04_p75__20231001,B04_p75__20231101,B04_p75__20231201,B04_p75__20240101,B04_p75__20240201,B04_p75__20240301,B04_p75__20240401,B04_p75__20240501,B04_p75__20240601,B04_p75__20240701,B04_p75__20240801,B04_p75__20240901,B04_p90__20231001,B04_p90__20231101,B04_p90__20231201,B04_p90__20240101,B04_p90__20240201,B04_p90__20240301,B04_p90__20240401,B04_p90__20240501,B04_p90__20240601,B04_p90__20240701,B04_p90__20240801,B04_p90__20240901,B04_p90_p10_spread__20231001,B04_p90_p10_spread__20231101,B04_p90_p10_spread__20231201,B04_p90_p10_spread__20240101,B04_p90_p10_spread__20240201,B04_p90_p10_spread__20240301,B04_p90_p10_spread__20240401,B04_p90_p10_spread__20240501,B04_p90_p10_spread__20240601,B04_p90_p10_spread__20240701,B04_p90_p10_spread__20240801,B04_p90_p10_spread__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B04_variance__20231001,B04_variance__20231101,B04_variance__20231201,B04_variance__20240101,B04_variance__20240201,B04_variance__20240301,B04_variance__20240401,B04_variance__20240501,B04_variance__20240601,B04_variance__20240701,B04_variance__20240801,B04_variance__20240901,B05_bowley_skewness__20231001,B05_bowley_skewness__20231101,B05_bowley_skewness__20231201,B05_bowley_skewness__20240101,B05_bowley_skewness__20240201,B05_bowley_skewness__20240301,B05_bowley_skewness__20240401,B05_bowley_skewness__20240501,B05_bowley_skewness__20240601,B05_bowley_skewness__20240701,B05_bowley_skewness__20240801,B05_bowley_skewness__20240901,B05_coefficient_of_variation__20231001,B05_coefficient_of_variation__20231101,B05_coefficient_of_variation__20231201,B05_coefficient_of_variation__20240101,B05_coefficient_of_variation__20240201,B05_coefficient_of_variation__20240301,B05_coefficient_of_variation__20240401,B05_coefficient_of_variation__20240501,B05_coefficient_of_variation__20240601,B05_coefficient_of_variation__20240701,B05_coefficient_of_variation__20240801,B05_coefficient_of_variation__20240901,B05_iqr__20231001,B05_iqr__20231101,B05_iqr__20231201,B05_iqr__20240101,B05_iqr__20240201,B05_iqr__20240301,B05_iqr__20240401,B05_iqr__20240501,B05_iqr__20240601,B05_iqr__20240701,B05_iqr__20240801,B05_iqr__20240901,B05_max__20231001,B05_max__20231101,B05_max__20231201,B05_max__20240101,B05_max__20240201,B05_max__20240301,B05_max__20240401,B05_max__20240501,B05_max__20240601,B05_max__20240701,B05_max__20240801,B05_max__20240901,B05_mean__20231001,B05_mean__20231101,B05_mean__20231201,B05_mean__20240101,B05_mean__20240201,B05_mean__20240301,B05_mean__20240401,B05_mean__20240501,B05_mean__20240601,B05_mean__20240701,B05_mean__20240801,B05_mean__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_min__20231001,B05_min__20231101,B05_min__20231201,B05_min__20240101,B05_min__20240201,B05_min__20240301,B05_min__20240401,B05_min__20240501,B05_min__20240601,B05_min__20240701,B05_min__20240801,B05_min__20240901,B05_p10__20231001,B05_p10__20231101,B05_p10__20231201,B05_p10__20240101,B05_p10__20240201,B05_p10__20240301,B05_p10__20240401,B05_p10__20240501,B05_p10__20240601,B05_p10__20240701,B05_p10__20240801,B05_p10__20240901,B05_p25__20231001,B05_p25__20231101,B05_p25__20231201,B05_p25__20240101,B05_p25__20240201,B05_p25__20240301,B05_p25__20240401,B05_p25__20240501,B05_p25__20240601,B05_p25__20240701,B05_p25__20240801,B05_p25__20240901,B05_p75__20231001,B05_p75__20231101,B05_p75__20231201,B05_p75__20240101,B05_p75__20240201,B05_p75__20240301,B05_p75__20240401,B05_p75__20240501,B05_p75__20240601,B05_p75__20240701,B05_p75__20240801,B05_p75__20240901,B05_p90__20231001,B05_p90__20231101,B05_p90__20231201,B05_p90__20240101,B05_p90__20240201,B05_p90__20240301,B05_p90__20240401,B05_p90__20240501,B05_p90__20240601,B05_p90__20240701,B05_p90__20240801,B05_p90__20240901,B05_p90_p10_spread__20231001,B05_p90_p10_spread__20231101,B05_p90_p10_spread__20231201,B05_p90_p10_spread__20240101,B05_p90_p10_spread__20240201,B05_p90_p10_spread__20240301,B05_p90_p10_spread__20240401,B05_p90_p10_spread__20240501,B05_p90_p10_spread__20240601,B05_p90_p10_spread__20240701,B05_p90_p10_spread__20240801,B05_p90_p10_spread__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B05_variance__20231001,B05_variance__20231101,B05_variance__20231201,B05_variance__20240101,B05_variance__20240201,B05_variance__20240301,B05_variance__20240401,B05_variance__20240501,B05_variance__20240601,B05_variance__20240701,B05_variance__20240801,B05_variance__20240901,B08_bowley_skewness__20231001,B08_bowley_skewness__20231101,B08_bowley_skewness__20231201,B08_bowley_skewness__20240101,B08_bowley_skewness__20240201,B08_bowley_skewness__20240301,B08_bowley_skewness__20240401,B08_bowley_skewness__20240501,B08_bowley_skewness__20240601,B08_bowley_skewness__20240701,B08_bowley_skewness__20240801,B08_bowley_skewness__20240901,B08_coefficient_of_variation__20231001,B08_coefficient_of_variation__20231101,B08_coefficient_of_variation__20231201,B08_coefficient_of_variation__20240101,B08_coefficient_of_variation__20240201,B08_coefficient_of_variation__20240301,B08_coefficient_of_variation__20240401,B08_coefficient_of_variation__20240501,B08_coefficient_of_variation__20240601,B08_coefficient_of_variation__20240701,B08_coefficient_of_variation__20240801,B08_coefficient_of_variation__20240901,B08_iqr__20231001,B08_iqr__20231101,B08_iqr__20231201,B08_iqr__20240101,B08_iqr__20240201,B08_iqr__20240301,B08_iqr__20240401,B08_iqr__20240501,B08_iqr__20240601,B08_iqr__20240701,B08_iqr__20240801,B08_iqr__20240901,B08_max__20231001,B08_max__20231101,B08_max__20231201,B08_max__20240101,B08_max__20240201,B08_max__20240301,B08_max__20240401,B08_max__20240501,B08_max__20240601,B08_max__20240701,B08_max__20240801,B08_max__20240901,B08_mean__20231001,B08_mean__20231101,B08_mean__20231201,B08_mean__20240101,B08_mean__20240201,B08_mean__20240301,B08_mean__20240401,B08_mean__20240501,B08_mean__20240601,B08_mean__20240701,B08_mean__20240801,B08_mean__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_min__20231001,B08_min__20231101,B08_min__20231201,B08_min__20240101,B08_min__20240201,B08_min__20240301,B08_min__20240401,B08_min__20240501,B08_min__20240601,B08_min__20240701,B08_min__20240801,B08_min__20240901,B08_p10__20231001,B08_p10__20231101,B08_p10__20231201,B08_p10__20240101,B08_p10__20240201,B08_p10__20240301,B08_p10__20240401,B08_p10__20240501,B08_p10__20240601,B08_p10__20240701,B08_p10__20240801,B08_p10__20240901,B08_p25__20231001,B08_p25__20231101,B08_p25__20231201,B08_p25__20240101,B08_p25__20240201,B08_p25__20240301,B08_p25__20240401,B08_p25__20240501,B08_p25__20240601,B08_p25__20240701,B08_p25__20240801,B08_p25__20240901,B08_p75__20231001,B08_p75__20231101,B08_p75__20231201,B08_p75__20240101,B08_p75__20240201,B08_p75__20240301,B08_p75__20240401,B08_p75__20240501,B08_p75__20240601,B08_p75__20240701,B08_p75__20240801,B08_p75__20240901,B08_p90__20231001,B08_p90__20231101,B08_p90__20231201,B08_p90__20240101,B08_p90__20240201,B08_p90__20240301,B08_p90__20240401,B08_p90__20240501,B08_p90__20240601,B08_p90__20240701,B08_p90__20240801,B08_p90__20240901,B08_p90_p10_spread__20231001,B08_p90_p10_spread__20231101,B08_p90_p10_spread__20231201,B08_p90_p10_spread__20240101,B08_p90_p10_spread__20240201,B08_p90_p10_spread__20240301,B08_p90_p10_spread__20240401,B08_p90_p10_spread__20240501,B08_p90_p10_spread__20240601,B08_p90_p10_spread__20240701,B08_p90_p10_spread__20240801,B08_p90_p10_spread__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B08_variance__20231001,B08_variance__20231101,B08_variance__20231201,B08_variance__20240101,B08_variance__20240201,B08_variance__20240301,B08_variance__20240401,B08_variance__20240501,B08_variance__20240601,B08_variance__20240701,B08_variance__20240801,B08_variance__20240901,B11_bowley_skewness__20231001,B11_bowley_skewness__20231101,B11_bowley_skewness__20231201,B11_bowley_skewness__20240101,B11_bowley_skewness__20240201,B11_bowley_skewness__20240301,B11_bowley_skewness__20240401,B11_bowley_skewness__20240501,B11_bowley_skewness__20240601,B11_bowley_skewness__20240701,B11_bowley_skewness__20240801,B11_bowley_s

In [4]:
label_counts = gdf_parcels[class_column].value_counts()
rare_labels = label_counts[label_counts < 100].index

gdf_parcels.loc[gdf_parcels[class_column].isin(rare_labels), class_column] = 9999
print(gdf_parcels[class_column].value_counts())

initial_label_code
110     49902
119     41226
111     12418
129      5786
112      4763
109      3939
114      3932
116      3040
113      2781
101      1398
128      1185
102       765
108       644
117       598
130       552
9999      295
106       289
121       236
127       234
126       118
125       102
Name: count, dtype: int64

In [5]:
gdf_parcels = gdf_parcels.to_crs("EPSG:2100")
gdf_parcels["x"] = gdf_parcels.centroid.x
gdf_parcels["y"] = gdf_parcels.centroid.y

base_cols = [parcel_id_column, class_column, "geometry"]
extra_features = ["elevation_mean_m", "distance_to_nearest_lake_m", "GAIOIKANOT", "x", "y"]
temporal_features = ("_median", "_sd", "_range",)
original_features = [x for x in gdf_parcels.columns if any(keyword in x for keyword in temporal_features)]

gdf_parcels = gdf_parcels[base_cols + original_features + extra_features].copy()
features = original_features + extra_features

gdf_parcels = gdf_parcels[gdf_parcels[class_column] != 9999].copy()
print(f"Final features for modeling ({len(features)} features): {features}")
display(gdf_parcels.head(3))

Final features for modeling (545 features): ['B02_median__20231001', 'B02_median__20231101', 'B02_median__20231201', 'B02_median__20240101', 'B02_median__20240201', 'B02_median__20240301', 'B02_median__20240401', 'B02_median__20240501', 'B02_median__20240601', 'B02_median__20240701', 'B02_median__20240801', 'B02_median__20240901', 'B02_range__20231001', 'B02_range__20231101', 'B02_range__20231201', 'B02_range__20240101', 'B02_range__20240201', 'B02_range__20240301', 'B02_range__20240401', 'B02_range__20240501', 'B02_range__20240601', 'B02_range__20240701', 'B02_range__20240801', 'B02_range__20240901', 'B02_sd__20231001', 'B02_sd__20231101', 'B02_sd__20231201', 'B02_sd__20240101', 'B02_sd__20240201', 'B02_sd__20240301', 'B02_sd__20240401', 'B02_sd__20240501', 'B02_sd__20240601', 'B02_sd__20240701', 'B02_sd__20240801', 'B02_sd__20240901', 'B03_median__20231001', 'B03_median__20231101', 'B03_median__20231201', 'B03_median__20240101', 'B03_median__20240201', 'B03_median__20240301', 'B03_median__20240401', 'B03_median__20240501', 'B03_median__20240601', 'B03_median__20240701', 'B03_median__20240801', 'B03_median__20240901', 'B03_range__20231001', 'B03_range__20231101', 'B03_range__20231201', 'B03_range__20240101', 'B03_range__20240201', 'B03_range__20240301', 'B03_range__20240401', 'B03_range__20240501', 'B03_range__20240601', 'B03_range__20240701', 'B03_range__20240801', 'B03_range__20240901', 'B03_sd__20231001', 'B03_sd__20231101', 'B03_sd__20231201', 'B03_sd__20240101', 'B03_sd__20240201', 'B03_sd__20240301', 'B03_sd__20240401', 'B03_sd__20240501', 'B03_sd__20240601', 'B03_sd__20240701', 'B03_sd__20240801', 'B03_sd__20240901', 'B04_median__20231001', 'B04_median__20231101', 'B04_median__20231201', 'B04_median__20240101', 'B04_median__20240201', 'B04_median__20240301', 'B04_median__20240401', 'B04_median__20240501', 'B04_median__20240601', 'B04_median__20240701', 'B04_median__20240801', 'B04_median__20240901', 'B04_range__20231001', 'B04_range__20231101', 'B04_range__20231201', 'B04_range__20240101', 'B04_range__20240201', 'B04_range__20240301', 'B04_range__20240401', 'B04_range__20240501', 'B04_range__20240601', 'B04_range__20240701', 'B04_range__20240801', 'B04_range__20240901', 'B04_sd__20231001', 'B04_sd__20231101', 'B04_sd__20231201', 'B04_sd__20240101', 'B04_sd__20240201', 'B04_sd__20240301', 'B04_sd__20240401', 'B04_sd__20240501', 'B04_sd__20240601', 'B04_sd__20240701', 'B04_sd__20240801', 'B04_sd__20240901', 'B05_median__20231001', 'B05_median__20231101', 'B05_median__20231201', 'B05_median__20240101', 'B05_median__20240201', 'B05_median__20240301', 'B05_median__20240401', 'B05_median__20240501', 'B05_median__20240601', 'B05_median__20240701', 'B05_median__20240801', 'B05_median__20240901', 'B05_range__20231001', 'B05_range__20231101', 'B05_range__20231201', 'B05_range__20240101', 'B05_range__20240201', 'B05_range__20240301', 'B05_range__20240401', 'B05_range__20240501', 'B05_range__20240601', 'B05_range__20240701', 'B05_range__20240801', 'B05_range__20240901', 'B05_sd__20231001', 'B05_sd__20231101', 'B05_sd__20231201', 'B05_sd__20240101', 'B05_sd__20240201', 'B05_sd__20240301', 'B05_sd__20240401', 'B05_sd__20240501', 'B05_sd__20240601', 'B05_sd__20240701', 'B05_sd__20240801', 'B05_sd__20240901', 'B08_median__20231001', 'B08_median__20231101', 'B08_median__20231201', 'B08_median__20240101', 'B08_median__20240201', 'B08_median__20240301', 'B08_median__20240401', 'B08_median__20240501', 'B08_median__20240601', 'B08_median__20240701', 'B08_median__20240801', 'B08_median__20240901', 'B08_range__20231001', 'B08_range__20231101', 'B08_range__20231201', 'B08_range__20240101', 'B08_range__20240201', 'B08_range__20240301', 'B08_range__20240401', 'B08_range__20240501', 'B08_range__20240601', 'B08_range__20240701', 'B08_range__20240801', 'B08_range__20240901', 'B08_sd__20231001', 'B08_sd__20231101', 'B08_sd__20231201', 'B08_sd__20240101', 'B08_sd__20240201', 'B08_sd__20240301', 'B08_sd__20240401', 'B08_sd__20240501', 'B08_sd__20240601', 'B08_sd__20240701', 'B08_sd__20240801', 'B08_sd__20240901', 'B11_median__20231001', 'B11_median__20231101', 'B11_median__20231201', 'B11_median__20240101', 'B11_median__20240201', 'B11_median__20240301', 'B11_median__20240401', 'B11_median__20240501', 'B11_median__20240601', 'B11_median__20240701', 'B11_median__20240801', 'B11_median__20240901', 'B11_range__20231001', 'B11_range__20231101', 'B11_range__20231201', 'B11_range__20240101', 'B11_range__20240201', 'B11_range__20240301', 'B11_range__20240401', 'B11_range__20240501', 'B11_range__20240601', 'B11_range__20240701', 'B11_range__20240801', 'B11_range__20240901', 'B11_sd__20231001', 'B11_sd__20231101', 'B11_sd__20231201', 'B11_sd__20240101', 'B11_sd__20240201', 'B11_sd__20240301', 'B11_sd__20240401', 'B11_sd__20240501', 'B11_sd__20240601', 'B11_sd__20240701', 'B11_sd__20240801', 'B11_sd__20240901', 'B12_median__20231001', 'B12_median__20231101', 'B12_median__20231201', 'B12_median__20240101', 'B12_median__20240201', 'B12_median__20240301', 'B12_median__20240401', 'B12_median__20240501', 'B12_median__20240601', 'B12_median__20240701', 'B12_median__20240801', 'B12_median__20240901', 'B12_range__20231001', 'B12_range__20231101', 'B12_range__20231201', 'B12_range__20240101', 'B12_range__20240201', 'B12_range__20240301', 'B12_range__20240401', 'B12_range__20240501', 'B12_range__20240601', 'B12_range__20240701', 'B12_range__20240801', 'B12_range__20240901', 'B12_sd__20231001', 'B12_sd__20231101', 'B12_sd__20231201', 'B12_sd__20240101', 'B12_sd__20240201', 'B12_sd__20240301', 'B12_sd__20240401', 'B12_sd__20240501', 'B12_sd__20240601', 'B12_sd__20240701', 'B12_sd__20240801', 'B12_sd__20240901', 'EVI_median__20231001', 'EVI_median__20231101', 'EVI_median__20231201', 'EVI_median__20240101', 'EVI_median__20240201', 'EVI_median__20240301', 'EVI_median__20240401', 'EVI_median__20240501', 'EVI_median__20240601', 'EVI_median__20240701', 'EVI_median__20240801', 'EVI_median__20240901', 'EVI_range__20231001', 'EVI_range__20231101', 'EVI_range__20231201', 'EVI_range__20240101', 'EVI_range__20240201', 'EVI_range__20240301', 'EVI_range__20240401', 'EVI_range__20240501', 'EVI_range__20240601', 'EVI_range__20240701', 'EVI_range__20240801', 'EVI_range__20240901', 'EVI_sd__20231001', 'EVI_sd__20231101', 'EVI_sd__20231201', 'EVI_sd__20240101', 'EVI_sd__20240201', 'EVI_sd__20240301', 'EVI_sd__20240401', 'EVI_sd__20240501', 'EVI_sd__20240601', 'EVI_sd__20240701', 'EVI_sd__20240801', 'EVI_sd__20240901', 'NDMI_median__20231001', 'NDMI_median__20231101', 'NDMI_median__20231201', 'NDMI_median__20240101', 'NDMI_median__20240201', 'NDMI_median__20240301', 'NDMI_median__20240401', 'NDMI_median__20240501', 'NDMI_median__20240601', 'NDMI_median__20240701', 'NDMI_median__20240801', 'NDMI_median__20240901', 'NDMI_range__20231001', 'NDMI_range__20231101', 'NDMI_range__20231201', 'NDMI_range__20240101', 'NDMI_range__20240201', 'NDMI_range__20240301', 'NDMI_range__20240401', 'NDMI_range__20240501', 'NDMI_range__20240601', 'NDMI_range__20240701', 'NDMI_range__20240801', 'NDMI_range__20240901', 'NDMI_sd__20231001', 'NDMI_sd__20231101', 'NDMI_sd__20231201', 'NDMI_sd__20240101', 'NDMI_sd__20240201', 'NDMI_sd__20240301', 'NDMI_sd__20240401', 'NDMI_sd__20240501', 'NDMI_sd__20240601', 'NDMI_sd__20240701', 'NDMI_sd__20240801', 'NDMI_sd__20240901', 'NDRE_median__20231001', 'NDRE_median__20231101', 'NDRE_median__20231201', 'NDRE_median__20240101', 'NDRE_median__20240201', 'NDRE_median__20240301', 'NDRE_median__20240401', 'NDRE_median__20240501', 'NDRE_median__20240601', 'NDRE_median__20240701', 'NDRE_median__20240801', 'NDRE_median__20240901', 'NDRE_range__20231001', 'NDRE_range__20231101', 'NDRE_range__20231201', 'NDRE_range__20240101', 'NDRE_range__20240201', 'NDRE_range__20240301', 'NDRE_range__20240401', 'NDRE_range__20240501', 'NDRE_range__20240601', 'NDRE_range__20240701', 'NDRE_range__20240801', 'NDRE_range__20240901', 'NDRE_sd__20231001', 'NDRE_sd__20231101', 'NDRE_sd__20231201', 'NDRE_sd__20240101', 'NDRE_sd__20240201', 'NDRE_sd__20240301', 'NDRE_sd__20240401', 'NDRE_sd__20240501', 'NDRE_sd__20240601', 'NDRE_sd__20240701', 'NDRE_sd__20240801', 'NDRE_sd__20240901', 'NDVI_median__20231001', 'NDVI_median__20231101', 'NDVI_median__20231201', 'NDVI_median__20240101', 'NDVI_median__20240201', 'NDVI_median__20240301', 'NDVI_median__20240401', 'NDVI_median__20240501', 'NDVI_median__20240601', 'NDVI_median__20240701', 'NDVI_median__20240801', 'NDVI_median__20240901', 'NDVI_range__20231001', 'NDVI_range__20231101', 'NDVI_range__20231201', 'NDVI_range__20240101', 'NDVI_range__20240201', 'NDVI_range__20240301', 'NDVI_range__20240401', 'NDVI_range__20240501', 'NDVI_range__20240601', 'NDVI_range__20240701', 'NDVI_range__20240801', 'NDVI_range__20240901', 'NDVI_sd__20231001', 'NDVI_sd__20231101', 'NDVI_sd__20231201', 'NDVI_sd__20240101', 'NDVI_sd__20240201', 'NDVI_sd__20240301', 'NDVI_sd__20240401', 'NDVI_sd__20240501', 'NDVI_sd__20240601', 'NDVI_sd__20240701', 'NDVI_sd__20240801', 'NDVI_sd__20240901', 'NDWI_median__20231001', 'NDWI_median__20231101', 'NDWI_median__20231201', 'NDWI_median__20240101', 'NDWI_median__20240201', 'NDWI_median__20240301', 'NDWI_median__20240401', 'NDWI_median__20240501', 'NDWI_median__20240601', 'NDWI_median__20240701', 'NDWI_median__20240801', 'NDWI_median__20240901', 'NDWI_range__20231001', 'NDWI_range__20231101', 'NDWI_range__20231201', 'NDWI_range__20240101', 'NDWI_range__20240201', 'NDWI_range__20240301', 'NDWI_range__20240401', 'NDWI_range__20240501', 'NDWI_range__20240601', 'NDWI_range__20240701', 'NDWI_range__20240801', 'NDWI_range__20240901', 'NDWI_sd__20231001', 'NDWI_sd__20231101', 'NDWI_sd__20231201', 'NDWI_sd__20240101', 'NDWI_sd__20240201', 'NDWI_sd__20240301', 'NDWI_sd__20240401', 'NDWI_sd__20240501', 'NDWI_sd__20240601', 'NDWI_sd__20240701', 'NDWI_sd__20240801', 'NDWI_sd__20240901', 'SAVI_median__20231001', 'SAVI_median__20231101', 'SAVI_median__20231201', 'SAVI_median__20240101', 'SAVI_median__20240201', 'SAVI_median__20240301', 'SAVI_median__20240401', 'SAVI_median__20240501', 'SAVI_median__20240601', 'SAVI_median__20240701', 'SAVI_median__20240801', 'SAVI_median__20240901', 'SAVI_range__20231001', 'SAVI_range__20231101', 'SAVI_range__20231201', 'SAVI_range__20240101', 'SAVI_range__20240201', 'SAVI_range__20240301', 'SAVI_range__20240401', 'SAVI_range__20240501', 'SAVI_range__20240601', 'SAVI_range__20240701', 'SAVI_range__20240801', 'SAVI_range__20240901', 'SAVI_sd__20231001', 'SAVI_sd__20231101', 'SAVI_sd__20231201', 'SAVI_sd__20240101', 'SAVI_sd__20240201', 'SAVI_sd__20240301', 'SAVI_sd__20240401', 'SAVI_sd__20240501', 'SAVI_sd__20240601', 'SAVI_sd__20240701', 'SAVI_sd__20240801', 'SAVI_sd__20240901', 'VH_median__20231001', 'VH_median__20231101', 'VH_median__20231201', 'VH_median__20240101', 'VH_median__20240201', 'VH_median__20240301', 'VH_median__20240401', 'VH_median__20240501', 'VH_median__20240601', 'VH_median__20240701', 'VH_median__20240801', 'VH_median__20240901', 'VH_range__20231001', 'VH_range__20231101', 'VH_range__20231201', 'VH_range__20240101', 'VH_range__20240201', 'VH_range__20240301', 'VH_range__20240401', 'VH_range__20240501', 'VH_range__20240601', 'VH_range__20240701', 'VH_range__20240801', 'VH_range__20240901', 'VH_sd__20231001', 'VH_sd__20231101', 'VH_sd__20231201', 'VH_sd__20240101', 'VH_sd__20240201', 'VH_sd__20240301', 'VH_sd__20240401', 'VH_sd__20240501', 'VH_sd__20240601', 'VH_sd__20240701', 'VH_sd__20240801', 'VH_sd__20240901', 'VV_median__20231001', 'VV_median__20231101', 'VV_median__20231201', 'VV_median__20240101', 'VV_median__20240201', 'VV_median__20240301', 'VV_median__20240401', 'VV_median__20240501', 'VV_median__20240601', 'VV_median__20240701', 'VV_median__20240801', 'VV_median__20240901', 'VV_range__20231001', 'VV_range__20231101', 'VV_range__20231201', 'VV_range__20240101', 'VV_range__20240201', 'VV_range__20240301', 'VV_range__20240401', 'VV_range__20240501', 'VV_range__20240601', 'VV_range__20240701', 'VV_range__20240801', 'VV_range__20240901', 'VV_sd__20231001', 'VV_sd__20231101', 'VV_sd__20231201', 'VV_sd__20240101', 'VV_sd__20240201', 'VV_sd__20240301', 'VV_sd__20240401', 'VV_sd__20240501', 'VV_sd__20240601', 'VV_sd__20240701', 'VV_sd__20240801', 'VV_sd__20240901', 'elevation_mean_m', 'distance_to_nearest_lake_m', 'GAIOIKANOT', 'x', 'y']

,parcel_code,initial_label_code,geometry,B02_median__20231001,B02_median__20231101,B02_median__20231201,B02_median__20240101,B02_median__20240201,B02_median__20240301,B02_median__20240401,B02_median__20240501,B02_median__20240601,B02_median__20240701,B02_median__20240801,B02_median__20240901,B02_range__20231001,B02_range__20231101,B02_range__20231201,B02_range__20240101,B02_range__20240201,B02_range__20240301,B02_range__20240401,B02_range__20240501,B02_range__20240601,B02_range__20240701,B02_range__20240801,B02_range__20240901,B02_sd__20231001,B02_sd__20231101,B02_sd__20231201,B02_sd__20240101,B02_sd__20240201,B02_sd__20240301,B02_sd__20240401,B02_sd__20240501,B02_sd__20240601,B02_sd__20240701,B02_sd__20240801,B02_sd__20240901,B03_median__20231001,B03_median__20231101,B03_median__20231201,B03_median__20240101,B03_median__20240201,B03_median__20240301,B03_median__20240401,B03_median__20240501,B03_median__20240601,B03_median__20240701,B03_median__20240801,B03_median__20240901,B03_range__20231001,B03_range__20231101,B03_range__20231201,B03_range__20240101,B03_range__20240201,B03_range__20240301,B03_range__20240401,B03_range__20240501,B03_range__20240601,B03_range__20240701,B03_range__20240801,B03_range__20240901,B03_sd__20231001,B03_sd__20231101,B03_sd__20231201,B03_sd__20240101,B03_sd__20240201,B03_sd__20240301,B03_sd__20240401,B03_sd__20240501,B03_sd__20240601,B03_sd__20240701,B03_sd__20240801,B03_sd__20240901,B04_median__20231001,B04_median__20231101,B04_median__20231201,B04_median__20240101,B04_median__20240201,B04_median__20240301,B04_median__20240401,B04_median__20240501,B04_median__20240601,B04_median__20240701,B04_median__20240801,B04_median__20240901,B04_range__20231001,B04_range__20231101,B04_range__20231201,B04_range__20240101,B04_range__20240201,B04_range__20240301,B04_range__20240401,B04_range__20240501,B04_range__20240601,B04_range__20240701,B04_range__20240801,B04_range__20240901,B04_sd__20231001,B04_sd__20231101,B04_sd__20231201,B04_sd__20240101,B04_sd__20240201,B04_sd__20240301,B04_sd__20240401,B04_sd__20240501,B04_sd__20240601,B04_sd__20240701,B04_sd__20240801,B04_sd__20240901,B05_median__20231001,B05_median__20231101,B05_median__20231201,B05_median__20240101,B05_median__20240201,B05_median__20240301,B05_median__20240401,B05_median__20240501,B05_median__20240601,B05_median__20240701,B05_median__20240801,B05_median__20240901,B05_range__20231001,B05_range__20231101,B05_range__20231201,B05_range__20240101,B05_range__20240201,B05_range__20240301,B05_range__20240401,B05_range__20240501,B05_range__20240601,B05_range__20240701,B05_range__20240801,B05_range__20240901,B05_sd__20231001,B05_sd__20231101,B05_sd__20231201,B05_sd__20240101,B05_sd__20240201,B05_sd__20240301,B05_sd__20240401,B05_sd__20240501,B05_sd__20240601,B05_sd__20240701,B05_sd__20240801,B05_sd__20240901,B08_median__20231001,B08_median__20231101,B08_median__20231201,B08_median__20240101,B08_median__20240201,B08_median__20240301,B08_median__20240401,B08_median__20240501,B08_median__20240601,B08_median__20240701,B08_median__20240801,B08_median__20240901,B08_range__20231001,B08_range__20231101,B08_range__20231201,B08_range__20240101,B08_range__20240201,B08_range__20240301,B08_range__20240401,B08_range__20240501,B08_range__20240601,B08_range__20240701,B08_range__20240801,B08_range__20240901,B08_sd__20231001,B08_sd__20231101,B08_sd__20231201,B08_sd__20240101,B08_sd__20240201,B08_sd__20240301,B08_sd__20240401,B08_sd__20240501,B08_sd__20240601,B08_sd__20240701,B08_sd__20240801,B08_sd__20240901,B11_median__20231001,B11_median__20231101,B11_median__20231201,B11_median__20240101,B11_median__20240201,B11_median__20240301,B11_median__20240401,B11_median__20240501,B11_median__20240601,B11_median__20240701,B11_median__20240801,B11_median__20240901,B11_range__20231001,B11_range__20231101,B11_range__20231201,B11_range__20240101,B11_range__20240201,B11_range__20240301,B11_range__20240401,B11_range__20240501,B11_range__20240601,B11_range__20240701,B11_range__20240801,B11_range__20240901,B11_sd__20231001,B11_sd__20231101,B11_sd__20231201,B11_sd__20240101,B11_sd__20240201,B11_sd__20240301,B11_sd__20240401,B11_sd__20240501,B11_sd__20240601,B11_sd__20240701,B11_sd__20240801,B11_sd__20240901,B12_median__20231001,B12_median__20231101,B12_median__20231201,B12_median__20240101,B12_median__20240201,B12_median__20240301,B12_median__20240401,B12_median__20240501,B12_median__20240601,B12_median__20240701,B12_median__20240801,B12_median__20240901,B12_range__20231001,B12_range__20231101,B12_range__20231201,B12_range__20240101,B12_range__20240201,B12_range__20240301,B12_range__20240401,B12_range__20240501,B12_range__20240601,B12_range__20240701,B12_range__20240801,B12_range__20240901,B12_sd__20231001,B12_sd__20231101,B12_sd__20231201,B12_sd__20240101,B12_sd__20240201,B12_sd__20240301,B12_sd__20240401,B12_sd__20240501,B12_sd__20240601,B12_sd__20240701,B12_sd__20240801,B12_sd__20240901,EVI_median__20231001,EVI_median__20231101,EVI_median__20231201,EVI_median__20240101,EVI_median__20240201,EVI_median__20240301,EVI_median__20240401,EVI_median__20240501,EVI_median__20240601,EVI_median__20240701,EVI_median__20240801,EVI_median__20240901,EVI_range__20231001,EVI_range__20231101,EVI_range__20231201,EVI_range__20240101,EVI_range__20240201,EVI_range__20240301,EVI_range__20240401,EVI_range__20240501,EVI_range__20240601,EVI_range__20240701,EVI_range__20240801,EVI_range__20240901,EVI_sd__20231001,EVI_sd__20231101,EVI_sd__20231201,EVI_sd__20240101,EVI_sd__20240201,EVI_sd__20240301,EVI_sd__20240401,EVI_sd__20240501,EVI_sd__20240601,EVI_sd__20240701,EVI_sd__20240801,EVI_sd__20240901,NDMI_median__20231001,NDMI_median__20231101,NDMI_median__20231201,NDMI_median__20240101,NDMI_median__20240201,NDMI_median__20240301,NDMI_median__20240401,NDMI_median__20240501,NDMI_median__20240601,NDMI_median__20240701,NDMI_median__20240801,NDMI_median__20240901,NDMI_range__20231001,NDMI_range__20231101,NDMI_range__20231201,NDMI_range__20240101,NDMI_range__20240201,NDMI_range__20240301,NDMI_range__20240401,NDMI_range__20240501,NDMI_range__20240601,NDMI_range__20240701,NDMI_range__20240801,NDMI_range__20240901,NDMI_sd__20231001,NDMI_sd__20231101,NDMI_sd__20231201,NDMI_sd__20240101,NDMI_sd__20240201,NDMI_sd__20240301,NDMI_sd__20240401,NDMI_sd__20240501,NDMI_sd__20240601,NDMI_sd__20240701,NDMI_sd__20240801,NDMI_sd__20240901,NDRE_median__20231001,NDRE_median__20231101,NDRE_median__20231201,NDRE_median__20240101,NDRE_median__20240201,NDRE_median__20240301,NDRE_median__20240401,NDRE_median__20240501,NDRE_median__20240601,NDRE_median__20240701,NDRE_median__20240801,NDRE_median__20240901,NDRE_range__20231001,NDRE_range__20231101,NDRE_range__20231201,NDRE_range__20240101,NDRE_range__20240201,NDRE_range__20240301,NDRE_range__20240401,NDRE_range__20240501,NDRE_range__20240601,NDRE_range__20240701,NDRE_range__20240801,NDRE_range__20240901,NDRE_sd__20231001,NDRE_sd__20231101,NDRE_sd__20231201,NDRE_sd__20240101,NDRE_sd__20240201,NDRE_sd__20240301,NDRE_sd__20240401,NDRE_sd__20240501,NDRE_sd__20240601,NDRE_sd__20240701,NDRE_sd__20240801,NDRE_sd__20240901,NDVI_median__20231001,NDVI_median__20231101,NDVI_median__20231201,NDVI_median__20240101,NDVI_median__20240201,NDVI_median__20240301,NDVI_median__20240401,NDVI_median__20240501,NDVI_median__20240601,NDVI_median__20240701,NDVI_median__20240801,NDVI_median__20240901,NDVI_range__20231001,NDVI_range__20231101,NDVI_range__20231201,NDVI_range__20240101,NDVI_range__20240201,NDVI_range__20240301,NDVI_range__20240401,NDVI_range__20240501,NDVI_range__20240601,NDVI_range__20240701,NDVI_range__20240801,NDVI_range__20240901,NDVI_sd__20231001,NDVI_sd__20231101,NDVI_sd__20231201,NDVI_sd__20240101,NDVI_sd__20240201,NDVI_sd__20240301,NDVI_sd__20240401,NDVI_sd__20240501,NDVI_sd__20240601,NDVI_sd__20240701,NDVI_sd__20240801,NDVI_sd__20240901,NDWI_median__20231001,NDWI_median__20231101,NDWI_median__20231201,NDWI_median__20240101,NDWI_median__20240201,NDWI_median__20240301,NDWI_median__20240401,NDWI_median__20240501,NDWI_median__20240601,NDWI_median__20240701,NDWI_median__20240801,NDWI_median__20240901,NDWI_range__20231001,NDWI_range__20231101,NDWI_range__20231201,NDWI_range__20240101,NDWI_range__20240201,NDWI_range__20240301,NDWI_range__20240401,NDWI_range__20240501,NDWI_range__20240601,NDWI_range__20240701,NDWI_range__20240801,NDWI_range__20240901,NDWI_sd__20231001,NDWI_sd__20231101,NDWI_sd__20231201,NDWI_sd__20240101,NDWI_sd__20240201,NDWI_sd__20240301,NDWI_sd__20240401,NDWI_sd__20240501,NDWI_sd__20240601,NDWI_sd__20240701,NDWI_sd__20240801,NDWI_sd__20240901,SAVI_median__20231001,SAVI_median__20231101,SAVI_median__20231201,SAVI_median__20240101,SAVI_median__20240201,SAVI_median__20240301,SAVI_median__20240401,SAVI_median__20240501,SAVI_median__20240601,SAVI_median__20240701,SAVI_median__20240801,SAVI_median__20240901,SAVI_range__20231001,SAVI_range__20231101,SAVI_range__20231201,SAVI_range__20240101,SAVI_range__20240201,SAVI_range__20240301,SAVI_range__20240401,SAVI_range__20240501,SAVI_range__20240601,SAVI_range__20240701,SAVI_range__20240801,SAVI_range__20240901,SAVI_sd__20231001,SAVI_sd__20231101,SAVI_sd__20231201,SAVI_sd__20240101,SAVI_sd__20240201,SAVI_sd__20240301,SAVI_sd__20240401,SAVI_sd__20240501,SAVI_sd__20240601,SAVI_sd__20240701,SAVI_sd__20240801,SAVI_sd__20240901,VH_median__20231001,VH_median__20231101,VH_median__20231201,VH_median__20240101,VH_median__20240201,VH_median__20240301,VH_median__20240401,VH_median__20240501,VH_median__20240601,VH_median__20240701,VH_median__20240801,VH_median__20240901,VH_range__20231001,VH_range__20231101,VH_range__20231201,VH_range__20240101,VH_range__20240201,VH_range__20240301,VH_range__20240401,VH_range__20240501,VH_range__20240601,VH_range__20240701,VH_range__20240801,VH_range__20240901,VH_sd__20231001,VH_sd__20231101,VH_sd__20231201,VH_sd__20240101,VH_sd__20240201,VH_sd__20240301,VH_sd__20240401,VH_sd__20240501,VH_sd__20240601,VH_sd__20240701,VH_sd__20240801,VH_sd__20240901,VV_median__20231001,VV_median__20231101,VV_median__20231201,VV_median__20240101,VV_median__20240201,VV_median__20240301,VV_median__20240401,VV_median__20240501,VV_median__20240601,VV_median__20240701,VV_median__20240801,VV_median__20240901,VV_range__20231001,VV_range__20231101,VV_range__20231201,VV_range__20240101,VV_range__20240201,VV_range__20240301,VV_range__20240401,VV_range__20240501,VV_range__20240601,VV_range__20240701,VV_range__20240801,VV_range__20240901,VV_sd__20231001,VV_sd__20231101,VV_sd__20231201,VV_sd__20240101,VV_sd__20240201,VV_sd__20240301,VV_sd__20240401,VV_sd__20240501,VV_sd__20240601,VV_sd__20240701,VV_sd__20240801,VV_sd__20240901,elevation_mean_m,distance_to_nearest_lake_m,GAIOIKANOT,x,y
0,174459115,129,POLYGON ((393737...,0.0520999990,0.0708999932,0.1083000004,0.1111999974,0.0811999962,0.0384499989,0.0420499966,0.0643499941,0.1155999973,0.1169999987,0.1107999980,0.0675999969,0.0330999978,0.0313999951,0.0509999990,0.0416000038,0.0595999993,0.0516499989,0.0516499989,0.0514500067,0.0442999974,0.0209999979,0.0232999995,0.0302000009,0.0079760094,0.0083532665,0.0125530376,0.0092673104,0.0145499493,0.0141834235,0.0144215514,0.0134149298,0.0101063047,0.0054261015,0.0056653539,0.0088722395,0.0742999986,0.1087999940,0.1632999927,0.1621999890,0.1271999925,0.0745500028,0.0835499987,0.0990999937,0.1627999991,0.1621999890,0.1586000025,0.1027999967,0.0350999981,0.0474999994,0.0732999891,0.0524000004,0.0829000026,0.0668500066,0.0619000047,0.0569999963,0.0619999990,0.0335999876,0.0303999931,0.0403999984,0.0089556881,0.0131320836,0.0184889997,0.0112608333,0.0193609855,0.0188194931,0.0173276403,0.0160416928,0.0144573828,0.0074409834,0.0068060241,0.0102239539,0.1079999954,0.1597999930,0.2324999869,0.2295999974,0.1389999986,0.0537000000,0.0742000043,0.1136000007,0.2293999940,0.2225999981,0.2177999914,0.1023999974,0.0649999976,0.0577999949,0.1231000125,0.0869999975,0.1289999932,0.1056000032,0.1044999920,0.0843000039,0.0830000043,0.0421999991,0.0255999863,0.0687000006,0.0139490420,0.0155272332,0.0306863240,0.0212359570,0.0303332991,0.0308306729,0.0295492622,0.0231557938,0.0182137459,0.0091742228,0.0068887881,0.0217309979,0.1360999942,0.1947999895,0.2541999817,0.2533999979,0.1913999915,0.1239999980,0.1378999949,0.1623499990,0.2658999860,0.2581999898,0.2563000023,0.1624999940,0.0374000072,0.0432500094,0.0815500021,0.0612999946,0.0703999996,0.0530500114,0.0542999953,0.0414000005,0.0607999861,0.0223999918,0.0175000131,0.0393000096,0.0084611701,0.0108967637,0.0220701390,0.0161568546,0.0176824554,0.0168038464,0.0170609596,0.0118142907,0.0141919815,0.0067402132,0.0050770684,0.0102847195,0.1873999983,0.2375499904,0.3161000013,0.3331999779,0.3556999862,0.4116500020,0.4099999666,0.2861999869,0.3479999900,0.3355999887,0.3483999968,0.3519999981,0.0588500053,0.1063499898,0.0722500086,0.0830999911,0.1205999851,0.1403999925,0.0866500139,0.0616500378,0.0696999729,0.0471000075,0.0512000024,0.1188000143,0.0171697356,0.0298370240,0.0158928692,0.0165567939,0.0271107511,0.0316929679,0.0236011717,0.0161230764,0.0151568939,0.0108006718,0.0112008025,0.0303485102,0.3094999790,0.3626999855,0.3900499940,0.4004999995,0.3141999841,0.2002499998,0.2168999910,0.2556499839,0.4379999936,0.4445999861,0.4384999871,0.3147999942,0.0397999883,0.0322999954,0.0931000113,0.0767999887,0.0887999833,0.0734500289,0.0746999979,0.0552499890,0.0489000082,0.0288000107,0.0260000229,0.0531000197,0.0099421091,0.0082942932,0.0238189227,0.0190533837,0.0229427186,0.0244604721,0.0227369921,0.0147966459,0.0151057965,0.0078031107,0.0069103757,0.0149088968,0.2164999992,0.3221499920,0.3573499918,0.3682000041,0.2356999964,0.1141500026,0.1255500019,0.1825499982,0.3333999813,0.3416999876,0.3217000067,0.2264999896,0.0411499888,0.0229500234,0.1134499907,0.1007999778,0.1022999883,0.0776000097,0.0809499994,0.0543499887,0.0531999767,0.0326000154,0.0203999877,0.0665999949,0.0116984969,0.0066778805,0.0301583076,0.0268489997,0.0271616388,0.0263430393,0.0254912167,0.0149983138,0.0155106464,0.0092903063,0.0061046640,0.0181871822,0.1366948038,0.1127079874,0.0984528661,0.1361230761,0.3446164131,0.6172669530,0.5404984951,0.2829421461,0.1640837491,0.1550712585,0.1794271469,0.4334670603,0.0972673073,0.1205740273,0.2688706592,0.2358530685,0.4342067838,0.4334277511,0.3365799189,0.1053807139,0.0674119741,0.0277730674,0.0568452477,0.3276762366,0.0237571879,0.0322119971,0.0633623818,0.0519757523,0.1004631974,0.1144205967,0.0951871968,0.0241579413,0.0144029516,0.0080732682,0.0143112083,0.0911398279,-0.2364604771,-0.2042955905,-0.1087271124,-0.0937238112,0.0580800436,0.3415993154,0.3133558929,0.0525347851,-0.1155115440,-0.1408090293,-0.1159274355,0.0730270967,0.1343615502,0.1913268417,0.2097106427,0.2116035819,0.2972811386,0.3028385267,0.2501266301,0.0767908357,0.0803879462,0.0862952098,0.0816763192,0.2213820890,0.0367089931,0.0526564228,0.0472040123,0.0463119629,0.0693997496,0.0843452080,0.0724970754,0.0190780144,0.0246645503,0.0205500426,0.0194291141,0.0642708283,0.1609711051,0.1175771654,0.1215206906,0.1442080140,0.2963978946,0.5385190845,0.4900619388,0.2710619867,0.1344250739,0.1255876124,0.1477179676,0.3810877502,0.1032764018,0.1533257887,0.2514591217,0.2284523547,0.2951062471,0.2501491904,0.2229079306,0.0887935609,0.0693130419,0.0722061023,0.0669798329,0.2326902300,0.0231208982,0.0400962472,0.0574159380,0.0505747628,0.0710920279,0.0744251414,0.0683939250,0.0193395135,0.0231714562,0.0203019274,0.0180381043,0.0621624800,0.2623325884,0.1882988513,0.1373002380,0.1813109964,0.4375382066,0.7708555460,0.6920983195,0.4297078848,0.2071475685,0.1977579445,0.2282336056,0.5571134090,0.1737722754,0.1527208984,0.3519013077,0.2916072160,0.4728454351,0.4384965003,0.3943887949,0.1950005293,0.1110696048,0.0391387343,0.0600605011,0.3561285734,0.0410940479,0.0389836376,0.0851880851,0.0644985682,0.1120352103,0.1264363711,0.1130602729,0.0502188693,0.0229593083,0.0105563241,0.0151056768,0.1011196754,-0.4276642203,-0.3794935942,-0.3087248206,-0.3439731300,-0.4704413116,-0.6919596791,-0.6616649032,-0.4792038500,-0.3608247638,-0.3469547033,-0.3723228574,-0.5498122573,0.1013966203,0.1052725911,0.2614573240,0.2009378672,0.3535813391,0.3051968515,0.2622925043,0.1386100948,0.1102641523,0.0421144068,0.0423267484,0.2161551714,0.0203027945,0.0219754702,0.0634009516,0.0442818414,0.0824321841,0.0856479360,0.0755828651,0.0360545536,0.0240194361,0.0101458126,0.0114776446,0.0600101585,0.1482541710,0.1253432631,0.1068372503,0.1436825395,0.3250731826,0.5570184588,0.5072615147,0.2823429704,0.1698615402,0.1572717279,0.1841911674,0.4008647501,0.0845912248,0.1195023879,0.2561007589,0.2298116237,0.3565835506,0.3383771181,0.2865689397,0.0993097574,0.0696214288,0.0282228440,0.0500532091,0.2739849538,0.0208483087,0.0316951517,0.0614990439,0.0496833324,0.0833927541,0.0922474178,0.0818477202,0.0243109441,0.0146153569,0.0077100839,0.0126133884,0.0748996177,0.0070054783,0.0046234108,0.0020617824,0.0012117191,0.0029892421,0.0151954023,0.0100694438,0.0129035022,0.0064251837,0.0066583855,0.0091296043,0.0210383628,0.0099438825,0.0068146903,0.0037216750,0.0019265786,0.0050936895,0.0130283907,0.0141398963,0.0104920939,0.0106081411,0.0095851091,0.0136212958,0.0217579668,0.0019215722,0.0017042801,0.0007910046,0.0005217226,0.0011634340,0.0026945087,0.0029771840,0.0029736576,0.0025310860,0.0019129777,0.0041736075,0.0056166743,0.0378828719,0.0464693233,0.0228708256,0.0211926475,0.0243368894,0.0486299992,0.0493992120,0.0633126199,0.0298996009,0.0356320478,0.0447194427,0.0684167966,0.0281387400,0.0561182685,0.0489118872,0.0232767379,0.0403950252,0.0498522446,0.0545615144,0.0484646298,0.0322075337,0.0405515060,0.0725424513,0.0381475389,0.0064887155,0.0126487546,0.0110162968,0.0062134504,0.0094442126,0.0116227414,0.0143619075,0.0123041574,0.0067849521,0.0114648844,0.0149343176,0.0102389746,115.3190114158,4718.7392116058,T7-111-1-D9QQ,393776.0237874503,4520195.8713141242

In [6]:
config = ClassificationPipelineConfig(
    project_dir=OUTPUT_PATH,
    target_column=class_column,
    feature_columns=features,
    id_column=parcel_id_column,

    apply_iqr=False,
    spatial_interpolation_method=None,

    cv_folds=5,
    test_size=0.2,
    spatial_split=True,
    spatial_split_grid_size=10,
    spatial_split_method="by_row",

    random_state=SEED_NUMBER,
    # n_jobs=1,

    scoring_primary="f1_macro",
    cv_ranking_method="score_minus_std",
    selection_type="soft_voting",
    top_voting_models=5,
    max_search_candidates=40,
    prediction_confidence_threshold=0.60,

    interpretability_top_models=5,
    interpretability_include_shap=False,

    optimize_class_probabilities=True,
    probability_multiplier_grid=(0.8, 1.0, 1.2, 1.5, 2.0),
    probability_optimization_iterations=2,
    probability_optimization_max_accuracy_drop=0.02,

    rank_confidence_enabled=True,
    force_retrain_models=False,

    label_balancing_method="random_oversample",
    lstm_temporal_statistics=temporal_features,
    selected_models=(
        "bagging",
        # "bayesian",
        # "decision_tree",
        "extra_trees",
        "random_forest",
        "gradient_boosting",
        # "lightgbm",
        "xgboost",
        # "knn",
        "neural_network",
        # "tensorflow_neural_network",
        # "keras_lstm",
   ),
    max_map_geometries=20000,
    open_html_report=True,
)

pipeline = GeospatialClassificationPipeline(config)

In [ ]:
summary_check = pipeline.run_check(df=gdf_parcels)
summary_check

In [ ]:
summary_prepare = pipeline.run_prepare()
summary_prepare

In [ ]:
summary_train = pipeline.run_train()
summary_train

In [7]:
summary_evaluate = pipeline.run_evaluate()
summary_evaluate

============================================================
Function <run_evaluate> started on 2026-08-23 21:10:06

Evaluating models...
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/02_prepare/label_mapping.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/03_train/training_summary.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/random_forest_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/random_forest_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/extra_trees_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/extra_trees_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/gradient_boosting_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/gradient_boosting_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/neural_network_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/neural_network_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/bagging_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/bagging_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/xgboost_classification_report.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/reports/xgboost_classification_report.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_train.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_train.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_test.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_test.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/xgboost_feature_importance.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/xgboost_feature_importance.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/gradient_boosting_feature_importance.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/gradient_boosting_feature_importance.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/extra_trees_feature_importance.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/extra_trees_feature_importance.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/random_forest_feature_importance.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/random_forest_feature_importance.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/interpretability_summary.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/interpretability_summary.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_train_with_voting.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_train_with_voting.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_test_with_voting.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_test_with_voting.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/geo_classifier_style_train_metrics.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/geo_classifier_style_train_metrics.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/geo_classifier_style_test_metrics.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/geo_classifier_style_test_metrics.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/parcel_best_class_by_ranking.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/parcel_best_class_by_ranking.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/parcel_best_class_by_ranking_train.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/parcel_best_class_by_ranking_train.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/ranking_method_metrics.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/ranking_method_metrics.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/ranking_method_metrics_train.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/ranking/ranking_method_metrics_train.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_calibration.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_calibration.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_test.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_test.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_level_metrics.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_level_metrics.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_by_class.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_by_class.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_oof.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/rank_confidence_oof.csv
Removing existing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_level_metrics_oof.csv
Writing file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/confidence/confidence_level_metrics_oof.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/interpretability_summary.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_train_with_voting.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/model_metrics_test_with_voting.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/04_evaluate/interpretability/interpretability_summary.csv
Reading file: C:/work_dir/k_makedonia-2023-2024/3_ml_classification/03_train/training_summary.csv

Generated final dashboard: C:\work_dir\k_makedonia-2023-2024\3_ml_classification\final_dashboard\report.html

Selected strategy: soft_voting using ['xgboost', 'bagging', 'gradient_boosting', 'extra_trees', 'random_forest']

Execution time of function <run_evaluate> ended on 2026-08-23 21:20:12 - duration: 00:10:06
=================================================================================================

{'selection_type': 'soft_voting',
 'selected_models': ['xgboost',
  'bagging',
  'gradient_boosting',
  'extra_trees',
  'random_forest'],
 'selected_metric': 'cv_score_minus_std',
 'selected_score': 0.3729697057135727,
 'selection_source': 'cross_validation',
 'labels': ['101',
  '102',
  '106',
  '108',
  '109',
  '110',
  '111',
  '112',
  '113',
  '114',
  '116',
  '117',
  '119',
  '121',
  '125',
  '126',
  '127',
  '128',
  '129',
  '130'],
 'class_probability_multipliers': {'101': 0.8,
  '102': 0.8,
  '106': 0.8,
  '108': 0.8,
  '109': 1.2,
  '110': 1.2,
  '111': 1.0,
  '112': 1.2,
  '113': 0.8,
  '114': 0.8,
  '116': 0.8,
  '117': 0.8,
  '119': 2.0,
  '121': 1.0,
  '125': 1.5,
  '126': 1.5,
  '127': 0.8,
  '128': 1.0,
  '129': 1.5,
  '130': 1.2},
 'probability_optimization': {'baseline_oof_macro_f1': 0.4571828610760975,
  'optimized_oof_macro_f1': 0.49316379207208694,
  'baseline_oof_accuracy': 0.5832290947109012,
  'optimized_oof_accuracy': 0.6300057875772455},
 'rank_confidence': {'enabled': True,
  'method': 'within_model_average_ranks_and_normalized_borda_scores',
  'prediction_basis': 'soft_voting',
  'minimum_models': 3,
  'thresholds': {'high': {'min_top1_agreement': 0.75,
    'min_top2_agreement': 0.8,
    'min_rank_score': 0.8,
    'min_rank_margin': 0.2},
   'medium': {'min_top1_agreement': 0.5,
    'min_top2_agreement': 0.6,
    'min_rank_score': 0.6,
    'min_rank_margin': 0.1}},
  'rank_rule_threshold_source': 'provisional_configuration',
  'thresholds_role': 'fallback_only_when_oof_calibration_is_unavailable',
  'threshold_source': 'oof_class_aware_empirical_calibration',
  'calibration': {'schema_version': '1.1.0',
   'method': 'oof_predicted_class_top1_empirical_accuracy',
   'feature': 'top1_agreement',
   'class_aware': True,
   'n_models': 5,
   'high_min_empirical_accuracy': 0.85,
   'medium_min_empirical_accuracy': 0.65,
   'minimum_oof_support': 100,
   'max_top1_pool_distance': 1,
   'pooling': 'bounded_adjacent_top1_bins_within_predicted_class',
   'unsupported_fallback': 'LOW_invalid',
   'oof_rows_total': 107126,
   'oof_rows_eligible': 78943,
   'table': [{'predicted_class': '101',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '101',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '101',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.3939393939393939,
     'support': 66,
     'exact_support': 14,
     'pooled_support': 66,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [2, 3]},
    {'predicted_class': '101',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.36904761904761907,
     'support': 168,
     'exact_support': 52,
     'pooled_support': 168,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [2, 3, 4]},
    {'predicted_class': '101',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.35294117647058826,
     'support': 102,
     'exact_support': 102,
     'pooled_support': 102,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [4]},
    {'predicted_class': '101',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.7818599311136625,
     'support': 871,
     'exact_support': 871,
     'pooled_support': 871,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '102',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '102',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': 0.16666666666666666,
     'support': 6,
     'exact_support': 1,
     'pooled_support': 6,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [1, 2]},
    {'predicted_class': '102',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.35294117647058826,
     'support': 34,
     'exact_support': 5,
     'pooled_support': 34,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [1, 2, 3]},
    {'predicted_class': '102',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.3949579831932773,
     'support': 119,
     'exact_support': 28,
     'pooled_support': 119,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [2, 3, 4]},
    {'predicted_class': '102',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.7867924528301887,
     'support': 530,
     'exact_support': 86,
     'pooled_support': 530,
     'max_pool_distance': 1,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [3, 4, 5]},
    {'predicted_class': '102',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.8918269230769231,
     'support': 416,
     'exact_support': 416,
     'pooled_support': 416,
     'max_pool_distance': 0,
     'confidence_level': 'HIGH',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '106',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '106',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '106',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.3333333333333333,
     'support': 15,
     'exact_support': 2,
     'pooled_support': 15,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [2, 3]},
    {'predicted_class': '106',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.35,
     'support': 40,
     'exact_support': 13,
     'pooled_support': 40,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [2, 3, 4]},
    {'predicted_class': '106',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.6871508379888268,
     'support': 179,
     'exact_support': 25,
     'pooled_support': 179,
     'max_pool_distance': 1,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [3, 4, 5]},
    {'predicted_class': '106',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.7730496453900709,
     'support': 141,
     'exact_support': 141,
     'pooled_support': 141,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '108',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '108',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': 0.3333333333333333,
     'support': 12,
     'exact_support': 1,
     'pooled_support': 12,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [1, 2]},
    {'predicted_class': '108',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.25,
     'support': 60,
     'exact_support': 11,
     'pooled_support': 60,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [1, 2, 3]},
    {'predicted_class': '108',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.26063829787234044,
     'support': 188,
     'exact_support': 48,
     'pooled_support': 188,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [2, 3, 4]},
    {'predicted_class': '108',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.26356589147286824,
     'support': 129,
     'exact_support': 129,
     'pooled_support': 129,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [4]},
    {'predicted_class': '108',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.28255528255528256,
     'support': 407,
     'exact_support': 407,
     'pooled_support': 407,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '109',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '109',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '109',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '109',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.896551724137931,
     'support': 29,
     'exact_support': 8,
     'pooled_support': 29,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [3, 4]},
    {'predicted_class': '109',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.9876543209876543,
     'support': 3159,
     'exact_support': 21,
     'pooled_support': 3159,
     'max_pool_distance': 1,
     'confidence_level': 'HIGH',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [3, 4, 5]},
    {'predicted_class': '109',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.9884984025559106,
     'support': 3130,
     'exact_support': 3130,
     'pooled_support': 3130,
     'max_pool_distance': 0,
     'confidence_level': 'HIGH',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '110',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': 0.576271186440678,
     'support': 59,
     'exact_support': 8,
     'pooled_support': 59,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [0, 1]},
    {'predicted_class': '110',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': 0.6498516320474778,
     'support': 337,
     'exact_support': 51,
     'pooled_support': 337,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [0, 1, 2]},
    {'predicted_class': '110',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.6654676258992805,
     'support': 278,
     'exact_support': 278,
     'pooled_support': 278,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [2]},
    {'predicted_class': '110',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.7378290659935088,
     'support': 2773,
     'exact_support': 2773,
     'pooled_support': 2773,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [3]},
    {'predicted_class': '110',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.7410375369042598,
     'support': 4742,
     'exact_support': 4742,
     'pooled_support': 4742,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [4]},
    {'predicted_class': '110',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.8337068111939132,
     'support': 19189,
     'exact_support': 19189,
     'pooled_support': 19189,
     'max_pool_distance': 0,
     'confidence_level': 'MEDIUM',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '111',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': None,
     'support': 0,
     'exact_support': 0,
     'pooled_support': 0,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'unseen_class_top1_bin',
     'included_top1_counts': []},
    {'predicted_class': '111',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': 0.3888888888888889,
     'support': 72,
     'exact_support': 7,
     'pooled_support': 72,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [1, 2]},
    {'predicted_class': '111',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.4098639455782313,
     'support': 588,
     'exact_support': 65,
     'pooled_support': 588,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [1, 2, 3]},
    {'predicted_class': '111',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.4127906976744186,
     'support': 516,
     'exact_support': 516,
     'pooled_support': 516,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [3]},
    {'predicted_class': '111',
     'top1_count': 4,
     'top1_agreement': 0.8,
     'empirical_accuracy': 0.3942161339421613,
     'support': 1314,
     'exact_support': 1314,
     'pooled_support': 1314,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [4]},
    {'predicted_class': '111',
     'top1_count': 5,
     'top1_agreement': 1.0,
     'empirical_accuracy': 0.4669771380186283,
     'support': 7086,
     'exact_support': 7086,
     'pooled_support': 7086,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [5]},
    {'predicted_class': '112',
     'top1_count': 0,
     'top1_agreement': 0.0,
     'empirical_accuracy': 0.16666666666666666,
     'support': 48,
     'exact_support': 2,
     'pooled_support': 48,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': False,
     'calibration_source': 'insufficient_adjacent_class_top1_support',
     'included_top1_counts': [0, 1]},
    {'predicted_class': '112',
     'top1_count': 1,
     'top1_agreement': 0.2,
     'empirical_accuracy': 0.17843866171003717,
     'support': 269,
     'exact_support': 46,
     'pooled_support': 269,
     'max_pool_distance': 1,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'adjacent_class_top1_bins',
     'included_top1_counts': [0, 1, 2]},
    {'predicted_class': '112',
     'top1_count': 2,
     'top1_agreement': 0.4,
     'empirical_accuracy': 0.18099547511312217,
     'support': 221,
     'exact_support': 221,
     'pooled_support': 221,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [2]},
    {'predicted_class': '112',
     'top1_count': 3,
     'top1_agreement': 0.6,
     'empirical_accuracy': 0.17884130982367757,
     'support': 397,
     'exact_support': 397,
     'pooled_support': 397,
     'max_pool_distance': 0,
     'confidence_level': 'LOW',
     'calibration_valid': True,
     'calibration_source': 'exact_class_top1_bin',
     'included_top1_counts': [3]},
    {'predicted_class': '112',
     'top1_count': 4,
     'top1_agreement': 0.8,

In [ ]:
summary_predict = pipeline.run_predict()
summary_predict

In [ ]:
# Show only rows that were unknown during training
classified_gdf = pd.read_csv(os.path.join(str(OUTPUT_PATH), "04_evaluate", "final_predictions_preview.csv"))
classified_gdf[parcel_id_column] = classified_gdf[parcel_id_column].astype(str)
print(len(classified_gdf), "rows in classified_gdf")
display(classified_gdf.head())

In [ ]:
from ml_classification.ml_classification_pipeline.core.persistence import load_joblib
test_df = load_joblib(Path(f"{OUTPUT_PATH}/02_prepare/test_dataset.joblib"))
test_df[parcel_id_column] = test_df[parcel_id_column].astype(str)
print(len(test_df), "rows in test_df")
test_df.head()

In [ ]:
test_ids =list(test_df[parcel_id_column].unique())
classified_gdf = classified_gdf[classified_gdf[parcel_id_column].isin(test_ids)]
print(len(classified_gdf), "rows in classified_gdf after filtering with test_ids")
classified_gdf["accuracy"] = classified_gdf[class_column] == classified_gdf[f"{class_column}_prediction"]
accuracy = classified_gdf["accuracy"].mean()
print(f"Accuracy on data: {accuracy:.2%}")