# Sentinel-1 and Sentinel-2 parcel zonal statistics

Configure and run `OpenEOJobManagerZonalStats` through the multi-user scheduler. openEO creates sensor-preprocessed physical-band NetCDF cubes per spatial batch. IQR cleaning, null filling, pixel indices, and parcel statistics run locally, producing one GeoParquet row per parcel with dated features and a separate annual summary. See [the detailed workflow](../../../docs/data_preparation/openeo/WORKFLOW.md).

In [1]:
from pathlib import Path
import os
from IPython.display import display

from data_preparation.parcel_stats import estimate_utm_epsg_from_parcels
from data_preparation.parcel_stats.job_manager import compute_tile_buffer_metres
from data_preparation.parcel_stats.multiuser import (
    load_openeo_users_from_db,
    merge_and_save_results,
    run_parallel_extractions,
)
from shared.io import read_data, write_data
from shared.spatial_statistics import spatial_clustering_using_buffer

## Inputs

Processing order:

`Sentinel-2 L2A`
`acquisition cloud mask`
`optional temporal reduction, or retain acquisitions`
`per-band, per-time-slice raster IQR outlier removal when enabled`
`local null filling`
`local pixel indices from cleaned physical bands`
`parcel statistics`
`one-row-per-parcel time-series pivot`
`ML-ready GeoParquet`

Temporal filling is past-only so later observations cannot leak into earlier feature periods.

In [2]:
# ============================================================================
# STEP 1: Read data and re-project
# ============================================================================
# Read the data and re-project to the desired EPSG

WORK_PATH = Path("C:/work_sat")
RUN_IDENTIFIER = "neuro_2024-2025"

# PARCELS_PATH = WORK_PATH / RUN_IDENTIFIER / "sample_parcels.csv"
# gdf_parcels = read_data(str(PARCELS_PATH))
# print("Initial parcels data:")
# display(gdf_parcels.head())

# print(f"Parcels before dropping duplicate geometries: {len(gdf_parcels)}")
# gdf_parcels = gdf_parcels.drop_duplicates(subset=["geom_wkt"]).copy()
# print(f"Parcels after dropping duplicate geometries: {len(gdf_parcels)}")

# gdf_parcels = gpd.GeoDataFrame(gdf_parcels, geometry=gpd.GeoSeries.from_wkt(gdf_parcels["geom_wkt"]), crs="EPSG:2100")
# print(f"Number of parcels: {len(gdf_parcels)}")
# gdf_parcels = geom_l.return_valid_geometries(gdf_parcels)
# gdf_parcels = geom_l.convert_multipolygons_to_polygons(gdf_parcels)
# print(f"Number of parcels after ensuring valid geometries and converting multipolygons to polygons: {len(gdf_parcels)}")
# gdf_parcels = gdf_parcels.drop(columns=["geom_wkt"])

# write_data(gdf_parcels, str(PARCELS_PATH).replace(".csv", ".gpkg"))

PARCELS_PATH = WORK_PATH / RUN_IDENTIFIER / "sample_parcels.gpkg"
gdf_parcels = read_data(str(PARCELS_PATH))
display(gdf_parcels)

Reading file: C:/work_sat/neuro_2024-2025/sample_parcels.gpkg

,parcel_id,crop_category,geometry
0,552,ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ,"POLYGON ((276662.481 4436671.199, 276678.713 4..."
1,553,jjjj,"POLYGON ((278512.622 4438032.513, 278569.445 4..."
2,554,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((278217.407 4437980.985, 278216.142 4..."
3,555,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((274769.372 4440021.269, 274765.086 4..."
4,556,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((272117.609 4439208.353, 272117.343 4..."
...,...,...,...
1147,25568,ΑΡΑΒΟΣΙΤΟΣ,"POLYGON ((279312.404 4518258.109, 279282.821 4..."
1148,25601,ΕΛΑΙΩΝΕΣ,"POLYGON ((617782.701 4067252.962, 617772.565 4..."
1149,25602,ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ,"POLYGON ((625014.344 3873755.626, 625003.543 3..."
1150,25651,ΒΑΜΒΑΚΙ,"POLYGON ((700907.829 4610302.442, 700796.329 4..."
1151,25652,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((696573.67 4346147.612, 696566.604 43..."

In [3]:
print(gdf_parcels.crs)
WORKING_EPSG = estimate_utm_epsg_from_parcels(gdf_parcels)
WORKING_EPSG

EPSG:2100

32635

In [4]:
# ============================================================================
# Define the class column and parcel ID column names.
# These are used in the extraction process to identify the class of each parcel
# and its unique identifier.
# ============================================================================
class_column = "crop_category"
parcel_id_column = "parcel_id"

In [5]:
gdf_parcels = gdf_parcels[gdf_parcels[class_column] != "jjjj"]
label_counts = gdf_parcels[class_column].value_counts()
print(f"Number of unique labels: {len(label_counts)}")
print(gdf_parcels[class_column].value_counts())
print(50*"-")
rare_labels = label_counts[label_counts < 10].index
gdf_parcels.loc[gdf_parcels[class_column].isin(rare_labels), class_column] = "9999"
print(f"Number of unique labels after grouping rare labels: {len(gdf_parcels[class_column].value_counts())}")
print(gdf_parcels[class_column].value_counts())

cond = gdf_parcels[class_column] == "9999"
print(50*"-")
print(f"Excluded parcels with label '9999': {cond.sum()} out of {len(gdf_parcels)}")
gdf_parcels = gdf_parcels[~cond].copy()
print(f"Selected parcels after excluding label '9999': {len(gdf_parcels)}")

Number of unique labels: 25
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       302
ΒΑΜΒΑΚΙ                                                 221
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           147
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           48
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 24
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     11
ΑΜΠΕΛΩΝΕΣ                                                10
ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)                              9
ΑΡΑΒΟΣΙΤΟΣ                                                6
ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ                                            5
KHPEYTIKA                                                 5
ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ                                4
ΚΑΠΝΟΣ                                                    4
ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ                                          4
ΠΥΡΗΝΟΚΑΡΠΑ                                               4
ΣΠΟΡΟΠΑΡΑΓΩΓΗ                                             2
ΜΗΛΟΕΙΔΗ                                                  2
ΡΟΔΑΚΙΝΙΕΣ                                                1
ΖΑΧΑΡΟΤΕΥΤΛΑ                                              1
ΕΣΠΕΡΙΔΟΕΙΔΗ                                              1
Name: count, dtype: int64
--------------------------------------------------
Number of unique labels after grouping rare labels: 13
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       302
ΒΑΜΒΑΚΙ                                                 221
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           147
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           48
9999                                                     48
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 24
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     11
ΑΜΠΕΛΩΝΕΣ                                                10
Name: count, dtype: int64
--------------------------------------------------
Excluded parcels with label '9999': 48 out of 1140
Selected parcels after excluding label '9999': 1092

In [6]:
# Reuse saved cluster labels; generate them only when the input has none.
CLUSTER_FIELD = "cluster"
if CLUSTER_FIELD in gdf_parcels.columns:
    gdf_grouped = gdf_parcels.copy()
else:
    gdf_grouped = spatial_clustering_using_buffer(
        gdf_parcels.to_crs(epsg=WORKING_EPSG),
        parcel_id_column,
        min_cluster_distance_in_m=20_000,
        field_cluster=CLUSTER_FIELD,
        plot_results=False,
    )

# groupby would silently omit parcels with missing labels.
if gdf_grouped[CLUSTER_FIELD].isna().any():
    raise ValueError("Every parcel must have a cluster label before partitioning.")

write_data(gdf_grouped, str(PARCELS_PATH).replace(".csv", ".gpkg").replace("sample_parcels", "cleaned_grouped_parcels"))

Buffer distance in data units:  10000.0

         cluster                                          parcel_id  total
0      Cluster 1  [590, 591, 592, 637, 638, 639, 640, 689, 690, ...     40
1     Cluster 10                                [951, 20752, 20804]      3
2     Cluster 11                                       [901, 20502]      2
3     Cluster 12                                             [1013]      1
4     Cluster 13                                         [751, 801]      2
5     Cluster 14                                              [664]      1
6     Cluster 15                                              [864]      1
7     Cluster 16                                              [701]      1
8     Cluster 17                                            [25567]      1
9     Cluster 18                                              [963]      1
10    Cluster 19                                            [25601]      1
11     Cluster 2  [552, 554, 555, 556, 557, 558, 560, 561, 562, ...     98
12     Cluster 3            [598, 645, 846, 1000, 1205, 1206, 1255]      7
13     Cluster 4                                  [559, 608, 25652]      3
14     Cluster 5  [595, 596, 597, 642, 643, 644, 697, 698, 699, ...     27
15     Cluster 6  [1338, 1548, 1549, 1562, 1620, 1621, 1622, 166...     19
16     Cluster 7                                         [651, 902]      2
17     Cluster 8  [636, 686, 687, 688, 741, 742, 791, 793, 838, ...     16
18     Cluster 9                                    [563, 612, 712]      3
19  Cluster Main  [564, 565, 566, 567, 568, 569, 570, 571, 572, ...    863

Removing existing file: C:/work_sat/neuro_2024-2025/cleaned_grouped_parcels.gpkg
Writing file: C:/work_sat/neuro_2024-2025/cleaned_grouped_parcels.gpkg

## Multi-user extraction planning

Accounts are loaded from PostgreSQL using `load_openeo_users_from_db()`. Install the `database` extra and set
`DB_NAME`, `TBL_USERS`, and `POSTGRES_*` in the kernel environment; `.env` is not loaded automatically.
The account table requires non-empty text `username` and `password` columns with unique usernames.
Accounts are sorted by username. Explicitly restore the original account order when resuming legacy jobs
without saved owners or using partition scheduling. See [database account setup](../../../docs/data_preparation/openeo/CREDENTIALS.md).

Create one spatial partition per cluster, then plan all tile batches before
submission. A shared queue lets every account process batches from any partition. With `fit_tiles_to_parcels=True`, a cube covers the
group's complete bounding box plus `TILE_BUFFER_METRES` on every side:

- width = east - west + 2 * buffer
- height = north - south + 2 * buffer

Only if either dimension exceeds `TILE_SIZE_METRES` does the planner split the
group spatially, then fit and check each subgroup in the same way. Parcels stay
whole and belong to exactly one job. A single parcel that exceeds the limit with
its buffer raises an error before submission.

A large partition can use all available accounts at once. Each account stays
within OPENEO_JOBS_PER_USER. Existing cubes are reused; previously submitted
jobs resume on their owning account. Keep the original account order when
first resuming a legacy run, which did not record account names.

Partition outputs and the merge step stay the same. Local statistics run after
the shared download queue completes, using LOCAL_BATCH_WORKERS per active
partition (up to one active partition per account).

In [7]:
# ============================================================================
# STEP 2: Load accounts for the shared batch queue
# ============================================================================
# Accounts share unsubmitted batches from all cluster partitions.

OPENEO_JOBS_PER_USER = 2  # This is default by openEO
users_list = load_openeo_users_from_db()
print(f"Loaded {len(users_list)} openEO user(s):")
for i, (user, _) in enumerate(users_list, 1):
    print(f"  User {i}: {user}")

Loaded 8 openEO user(s) from the database.
Loaded 8 openEO user(s):
  User 1: esagovhub1@gmail.com
  User 2: esagovhub2@gmail.com
  User 3: esagovhub3@gmail.com
  User 4: esagovhub4@gmail.com
  User 5: farfarasmpoytos@gmail.com
  User 6: katrinporo@gmail.com
  User 7: louvarieleni@gmail.com
  User 8: sofiaargirou03@gmail.com

In [8]:
# Keep each cluster together; the existing tile planner handles its size limit.
spatial_parts = [
    part.copy()
    for _, part in gdf_grouped.groupby(CLUSTER_FIELD, sort=True, observed=True)
]
assert sum(len(part) for part in spatial_parts) == len(gdf_grouped)

print(f"Created {len(spatial_parts)} cluster partitions:")
for i, part in enumerate(spatial_parts, 1):
    print(f"  Partition {i}: {part[CLUSTER_FIELD].iloc[0]} - {len(part)} parcels")

Created 20 cluster partitions:
  Partition 1: Cluster 1 - 40 parcels
  Partition 2: Cluster 10 - 3 parcels
  Partition 3: Cluster 11 - 2 parcels
  Partition 4: Cluster 12 - 1 parcels
  Partition 5: Cluster 13 - 2 parcels
  Partition 6: Cluster 14 - 1 parcels
  Partition 7: Cluster 15 - 1 parcels
  Partition 8: Cluster 16 - 1 parcels
  Partition 9: Cluster 17 - 1 parcels
  Partition 10: Cluster 18 - 1 parcels
  Partition 11: Cluster 19 - 1 parcels
  Partition 12: Cluster 2 - 98 parcels
  Partition 13: Cluster 3 - 7 parcels
  Partition 14: Cluster 4 - 3 parcels
  Partition 15: Cluster 5 - 27 parcels
  Partition 16: Cluster 6 - 19 parcels
  Partition 17: Cluster 7 - 2 parcels
  Partition 18: Cluster 8 - 16 parcels
  Partition 19: Cluster 9 - 3 parcels
  Partition 20: Cluster Main - 863 parcels

In [9]:
# Maximum requested cube width AND height, including the buffer.
# Each group gets its own fitted extent; only oversized groups are split.
TILE_SIZE_METRES = 20_000
TILE_BUFFER_METRES = compute_tile_buffer_metres(gdf_grouped, WORKING_EPSG)

Recommended tile buffer: 1,400 m

In [10]:
print(f"Maximum buffered cube width/height: {TILE_SIZE_METRES:,} m")
print(f"Buffer on each side: {TILE_BUFFER_METRES:,} m")

Maximum buffered cube width/height: 20,000 m
Buffer on each side: 1,400 m

In [11]:
# ============================================================================
# Confirm the planned global remote concurrency.
# ============================================================================
TOTAL_REMOTE_JOB_CAPACITY = len(users_list) * OPENEO_JOBS_PER_USER
print(
    f"Remote capacity: {len(users_list)} users x {OPENEO_JOBS_PER_USER} jobs "
    f"= {TOTAL_REMOTE_JOB_CAPACITY} simultaneous jobs"
)

Remote capacity: 8 users x 2 jobs = 16 simultaneous jobs

In [12]:
# ============================================================================
# STEP 3: Create extraction configuration dictionary
# ============================================================================
# Single dictionary containing all parameters for the extraction process,
# to be passed to each parallel worker.

START_DATE = "2024-10-01"
END_DATE = "2025-09-30"
OUTPUT_DIR = WORK_PATH / RUN_IDENTIFIER / "1_eo_parcel_stats_fill"

extraction_config = {
    # Output paths
    "output_dir": OUTPUT_DIR,
    "run_identifier": RUN_IDENTIFIER,

    # Parcel configuration
    "parcel_id_field": parcel_id_column,

    # Temporal bounds
    "start_date": START_DATE,
    "end_date": END_DATE,

    # Spatial configuration
    "working_epsg": WORKING_EPSG,

    # Fit cluster bounds plus buffer; split only above the maximum size.
    "fit_tiles_to_parcels": True,
    "tile_size_metres": TILE_SIZE_METRES,
    "tile_buffer_metres": TILE_BUFFER_METRES,

    # Parallel processing
    "openeo_parallel_jobs": OPENEO_JOBS_PER_USER,
    "job_poll_seconds": 30,

    # Sentinel-2 configuration
    "sentinel2_bands": ["B02", "B03", "B04", "B05", "B08", "B11", "B12"],
    "sentinel2_indices": ["EVI", "NDMI", "NDRE", "NDVI", "NDWI",  "SAVI"],

    # Sentinel-1 configuration
    "sentinel1_bands": ["VV", "VH"],
    "sentinel1_indices": ["R", "RVI"],
    "sentinel1_orbit_direction": "ASCENDING",  # ASCENDING, DESCENDING, or BOTH

    # Data cleaning (IQR outlier removal)
    "remove_outliers": False,
    "iqr_quantiles": (0.1, 0.9),
    "iqr_multiplier": 1.5,
    "iqr_min_valid_pixels": 20,

    # Null filling
    "fill_nulls": True,
    "temporal_fill_mode": "bidirectional",  # or past_only
    "minimum_parcel_pixels": 3,
    "minimum_observed_fraction_for_fill": 0.20,
    "temporal_fill_window_sizes": (3,),

    # Interpolation
    # 1. Try 3x3, then 5x5, then 7x7; if all fail, leave null.
    "spatial_fill_window_sizes": (3, 5, 7),
    # Fill remaining nulls using the specified interpolation method and maximum distance.
    "interpolation_method": "nearest",  # "idw"
    "interpolation_max_distance_in_meters": 500,

    # Temporal period and reducer for the temporal aggregation of the data.
    # "1M" means monthly aggregation, and "none" means no temporal reduction (keep all observations).
    "temporal_period": "1M",
    "temporal_reducer": "none",  # All valid pixels will be used

    # Statistics to calculate for the selected bands and indices; these are calculated for each parcel and each temporal period.
    "spatial_statistics": ["mean", "median", "sd", "min", "max", "range"],

    # Each worker loads one complete monthly cube; use one unless RAM has been sized for parallel cubes.
    "batch_workers": 4,  # For local processes only

    "remove_nc_after_completion": True,
    "resume_completed_partitions": True,
}

In [13]:
# ============================================================================
# STEP 4: Plan all batches, then download across all users
# ============================================================================
# Plan all partition tiles first; any free account slot takes the next batch.
# Batches from the same partition may run on different accounts.
run_parallel_extractions(
    spatial_parts=spatial_parts,
    users_list=users_list,
    config=extraction_config,
    scheduling="batches",
)

# Each partition result is saved below OUTPUT_DIR/partition_<n>.
print("\nExtraction complete!")

2026-10-10 10:27:45,655 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.orchestrator | Prepared 40 valid parcels.
2026-10-10 10:27:45,656 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_parcel_statistics.log.
2026-10-10 10:27:45,656 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,656 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,684 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.orchestrator | Prepared 3 valid parcels.
2026-10-10 10:27:45,685 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_parcel_statistics.log.
2026-10-10 10:27:45,686 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,686 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,701 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.orchestrator | Prepared 2 valid parcels.
2026-10-10 10:27:45,702 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_parcel_statistics.log.
2026-10-10 10:27:45,703 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,704 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,717 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,718 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_parcel_statistics.log.
2026-10-10 10:27:45,718 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,719 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,732 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.orchestrator | Prepared 2 valid parcels.
2026-10-10 10:27:45,732 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_parcel_statistics.log.
2026-10-10 10:27:45,733 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,733 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,743 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,744 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_parcel_statistics.log.
2026-10-10 10:27:45,744 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,744 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,754 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,754 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_parcel_statistics.log.
2026-10-10 10:27:45,755 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,755 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,765 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,766 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_parcel_statistics.log.
2026-10-10 10:27:45,766 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,767 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,776 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,777 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_parcel_statistics.log.
2026-10-10 10:27:45,778 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,778 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,788 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,788 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_parcel_statistics.log.
2026-10-10 10:27:45,789 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,789 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

======================================================================
Running extraction on 20 spatial partition(s) across 8 user queue(s)
Remote concurrency capacity: 8 users x 2 jobs = 16
======================================================================

Partition 1: 40 parcels, 4 batches, 4 queued.
Partition 2: 3 parcels, 1 batches, 1 queued.
Partition 3: 2 parcels, 1 batches, 1 queued.
Partition 4: 1 parcels, 1 batches, 1 queued.
Partition 5: 2 parcels, 1 batches, 1 queued.
Partition 6: 1 parcels, 1 batches, 1 queued.
Partition 7: 1 parcels, 1 batches, 1 queued.
Partition 8: 1 parcels, 1 batches, 1 queued.
Partition 9: 1 parcels, 1 batches, 1 queued.
Partition 10: 1 parcels, 1 batches, 1 queued.

2026-10-10 10:27:45,799 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.orchestrator | Prepared 1 valid parcels.
2026-10-10 10:27:45,800 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_parcel_statistics.log.
2026-10-10 10:27:45,801 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,801 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 11: 1 parcels, 1 batches, 1 queued.

2026-10-10 10:27:45,813 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.orchestrator | Prepared 98 valid parcels.
2026-10-10 10:27:45,814 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_parcel_statistics.log.
2026-10-10 10:27:45,815 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,815 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 12: 98 parcels, 2 batches, 2 queued.

2026-10-10 10:27:45,831 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.orchestrator | Prepared 7 valid parcels.
2026-10-10 10:27:45,831 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_parcel_statistics.log.
2026-10-10 10:27:45,832 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,832 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,844 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.orchestrator | Prepared 3 valid parcels.
2026-10-10 10:27:45,844 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_parcel_statistics.log.
2026-10-10 10:27:45,845 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,845 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 13: 7 parcels, 2 batches, 2 queued.
Partition 14: 3 parcels, 1 batches, 1 queued.

2026-10-10 10:27:45,856 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.orchestrator | Prepared 27 valid parcels.
2026-10-10 10:27:45,857 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_parcel_statistics.log.
2026-10-10 10:27:45,857 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,858 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,869 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.orchestrator | Prepared 19 valid parcels.
2026-10-10 10:27:45,869 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_parcel_statistics.log.
2026-10-10 10:27:45,870 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,870 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,881 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.orchestrator | Prepared 2 valid parcels.
2026-10-10 10:27:45,881 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_parcel_statistics.log.
2026-10-10 10:27:45,882 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,883 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,892 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.orchestrator | Prepared 16 valid parcels.
2026-10-10 10:27:45,893 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_parcel_statistics.log.
2026-10-10 10:27:45,893 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,894 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,904 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.orchestrator | Prepared 3 valid parcels.
2026-10-10 10:27:45,904 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_parcel_statistics.log.
2026-10-10 10:27:45,905 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,905 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.
2026-10-10 10:27:45,925 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.orchestrator | Prepared 863 valid parcels.
2026-10-10 10:27:45,926 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_parcel_statistics.log.
2026-10-10 10:27:45,927 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=4.
2026-10-10 10:27:45,927 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 15: 27 parcels, 1 batches, 1 queued.
Partition 16: 19 parcels, 1 batches, 1 queued.
Partition 17: 2 parcels, 1 batches, 1 queued.
Partition 18: 16 parcels, 1 batches, 1 queued.
Partition 19: 3 parcels, 1 batches, 1 queued.
Partition 20: 863 parcels, 17 batches, 17 queued.
Shared queue: 41 unsubmitted batches; 0 owned jobs to resume.
Created job j-26101007275041b389caad0bf9b6e762: partition 7, batch 1, user farfarasmpoytos@gmail.com.
Created job j-2610100727504ac79c8979b3e37d0e62: partition 8, batch 1, user katrinporo@gmail.com.
Created job j-26101007275048f3ab1046c0c15490f3: partition 4, batch 1, user esagovhub4@gmail.com.
Created job j-26101007275046bd8f6b4e6821d70958: partition 12, batch 2, user sofiaargirou03@gmail.com.
Created job j-2610100727524481b6cd23e2efd3497e: partition 1, batch 2, user esagovhub1@gmail.com.
Created job j-2610100727524c2f94b1ae2b5a7ae35e: partition 9, batch 1, user katrinporo@gmail.com.
Created job j-2610100727524f0591604e590d616027: partition 2, batch 1, user esagovhub3@gmail.com.
Created job j-2610100727524ac3985bd344fce72d8e: partition 6, batch 1, user farfarasmpoytos@gmail.com.
Created job j-261010072754432789eb0bcfb0e948b5: partition 12, batch 1, user sofiaargirou03@gmail.com.
Created job j-26101007275448c390eded3241c26d34: partition 11, batch 1, user louvarieleni@gmail.com.
Created job j-2610100727544e9e9ce3d02faaacea68: partition 1, batch 1, user esagovhub1@gmail.com.
Created job j-2610100727544f05992f293a3cbeef14: partition 5, batch 1, user esagovhub4@gmail.com.
Created job j-2610100727564c04b364104b3e88a21f: partition 3, batch 1, user esagovhub3@gmail.com.
Created job j-2610100727574b1b981ffc1d7661c43d: partition 10, batch 1, user louvarieleni@gmail.com.
Created job j-2610100727574d01a4ea800a82276250: partition 1, batch 4, user esagovhub2@gmail.com.
Created job j-26101007275747309d68632a021fc557: partition 1, batch 3, user esagovhub2@gmail.com.

2026-10-10 10:35:00,998 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\monthly_cubes\9972008b8852a1f4-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:35:01,396 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 10/113 for batch 1.
2026-10-10 10:35:01,724 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 20/113 for batch 1.
2026-10-10 10:35:02,035 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 30/113 for batch 1.
2026-10-10 10:35:02,336 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 40/113 for batch 1.
2026-10-10 10:35:02,636 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 50/113 for batch 1.
2026-10-10 10:35:02,936 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 60/113 for batch 1.
2026-10-10 10:35:03,258 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 70/113 for batch 1.
2026-10-10 10:35:03,571 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 80/113 for batch 1.
2026-10-10 10:35:03,896 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 90/113 for batch 1.
2026-10-10 10:35:04,216 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 100/113 for batch 1.
2026-10-10 10:35:04,532 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 110/113 for batch 1.
2026-10-10 10:35:04,629 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Stored observations 113/113 for batch 1.
2026-10-10 10:35:04,630 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 1/9 in strips of 63 rows.
2026-10-10 10:35:04,972 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 2/9 in strips of 63 rows.
2026-10-10 10:35:05,326 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 3/9 in strips of 63 rows.
2026-10-10 10:35:05,663 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 4/9 in strips of 63 rows.
2026-10-10 10:35:06,002 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 5/9 in strips of 63 rows.
2026-10-10 10:35:06,351 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 6/9 in strips of 63 rows.
2026-10-10 10:35:06,692 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 7/9 in strips of 63 rows.
2026-10-10 10:35:07,029 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 8/9 in strips of 63 rows.
2026-10-10 10:35:07,368 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Temporal filling band 9/9 in strips of 63 rows.
2026-10-10 10:35:07,723 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 1/113 for batch 1.
2026-10-10 10:35:07,738 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 2/113 for batch 1.
2026-10-10 10:35:07,756 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 3/113 for batch 1.
2026-10-10 10:35:07,771 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 4/113 for batch 1.
2026-10-10 10:35:07,787 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 5/113 for batch 1.
2026-10-10 10:35:07,802 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 6/113 for batch 1.
2026-10-10 10:35:07,817 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 7/113 for batch 1.
2026-10-10 10:35:07,834 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 8/113 for batch 1.
2026-10-10 10:35:07,849 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 9/113 for batch 1.
2026-10-10 10:35:07,865 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 10/113 for batch 1.
2026-10-10 10:35:07,880 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 11/113 for batch 1.
2026-10-10 10:35:07,896 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 12/113 for batch 1.
2026-10-10 10:35:07,911 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 13/113 for batch 1.
2026-10-10 10:35:07,927 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 14/113 for batch 1.
2026-10-10 10:35:07,942 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 15/113 for batch 1.
2026-10-10 10:35:07,957 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 16/113 for batch 1.
2026-10-10 10:35:07,971 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 17/113 for batch 1.
2026-10-10 10:35:07,986 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 18/113 for batch 1.
2026-10-10 10:35:08,001 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 19/113 for batch 1.
2026-10-10 10:35:08,015 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 20/113 for batch 1.
2026-10-10 10:35:08,030 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 21/113 for batch 1.
2026-10-10 10:35:08,044 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 22/113 for batch 1.
2026-10-10 10:35:08,062 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 23/113 for batch 1.
2026-10-10 10:35:08,080 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 24/113 for batch 1.
2026-10-10 10:35:08,104 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 25/113 for batch 1.
2026-10-10 10:35:08,184 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 26/113 for batch 1.
2026-10-10 10:35:08,200 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 27/113 for batch 1.
2026-10-10 10:35:08,215 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 28/113 for batch 1.
2026-10-10 10:35:08,230 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 29/113 for batch 1.
2026-10-10 10:35:08,246 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 30/113 for batch 1.
2026-10-10 10:35:08,261 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 31/113 for batch 1.
2026-10-10 10:35:08,276 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 32/113 for batch 1.
2026-10-10 10:35:08,290 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 33/113 for batch 1.
2026-10-10 10:35:08,305 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 34/113 for batch 1.
2026-10-10 10:35:08,320 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 35/113 for batch 1.
2026-10-10 10:35:08,336 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 36/113 for batch 1.
2026-10-10 10:35:08,351 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 37/113 for batch 1.
2026-10-10 10:35:08,365 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 38/113 for batch 1.
2026-10-10 10:35:08,381 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 39/113 for batch 1.
2026-10-10 10:35:08,396 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 40/113 for batch 1.
2026-10-10 10:35:08,411 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 41/113 for batch 1.
2026-10-10 10:35:08,425 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 42/113 for batch 1.
2026-10-10 10:35:08,440 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 43/113 for batch 1.
2026-10-10 10:35:08,456 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 44/113 for batch 1.
2026-10-10 10:35:08,471 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 45/113 for batch 1.
2026-10-10 10:35:08,487 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 46/113 for batch 1.
2026-10-10 10:35:08,568 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 47/113 for batch 1.
2026-10-10 10:35:08,583 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 48/113 for batch 1.
2026-10-10 10:35:08,596 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 49/113 for batch 1.
2026-10-10 10:35:08,677 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 50/113 for batch 1.
2026-10-10 10:35:08,692 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 51/113 for batch 1.
2026-10-10 10:35:08,707 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 52/113 for batch 1.
2026-10-10 10:35:08,787 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 53/113 for batch 1.
2026-10-10 10:35:08,801 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 54/113 for batch 1.
2026-10-10 10:35:08,816 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 55/113 for batch 1.
2026-10-10 10:35:08,830 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 56/113 for batch 1.
2026-10-10 10:35:08,911 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 57/113 for batch 1.
2026-10-10 10:35:08,926 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 58/113 for batch 1.
2026-10-10 10:35:08,942 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 59/113 for batch 1.
2026-10-10 10:35:08,958 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 60/113 for batch 1.
2026-10-10 10:35:08,974 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 61/113 for batch 1.
2026-10-10 10:35:08,990 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 62/113 for batch 1.
2026-10-10 10:35:09,005 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 63/113 for batch 1.
2026-10-10 10:35:09,021 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 64/113 for batch 1.
2026-10-10 10:35:09,038 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 65/113 for batch 1.
2026-10-10 10:35:09,054 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 66/113 for batch 1.
2026-10-10 10:35:09,070 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 67/113 for batch 1.
2026-10-10 10:35:09,084 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 68/113 for batch 1.
2026-10-10 10:35:09,098 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 69/113 for batch 1.
2026-10-10 10:35:09,114 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 70/113 for batch 1.
2026-10-10 10:35:09,128 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 71/113 for batch 1.
2026-10-10 10:35:09,145 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 72/113 for batch 1.
2026-10-10 10:35:09,159 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 73/113 for batch 1.
2026-10-10 10:35:09,174 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 74/113 for batch 1.
2026-10-10 10:35:09,190 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 75/113 for batch 1.
2026-10-10 10:35:09,205 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 76/113 for batch 1.
2026-10-10 10:35:09,219 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 77/113 for batch 1.
2026-10-10 10:35:09,234 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 78/113 for batch 1.
2026-10-10 10:35:09,249 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 79/113 for batch 1.
2026-10-10 10:35:09,264 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 80/113 for batch 1.
2026-10-10 10:35:09,282 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 81/113 for batch 1.
2026-10-10 10:35:09,296 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 82/113 for batch 1.
2026-10-10 10:35:09,311 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 83/113 for batch 1.
2026-10-10 10:35:09,325 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 84/113 for batch 1.
2026-10-10 10:35:09,340 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 85/113 for batch 1.
2026-10-10 10:35:09,354 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 86/113 for batch 1.
2026-10-10 10:35:09,368 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 87/113 for batch 1.
2026-10-10 10:35:09,381 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 88/113 for batch 1.
2026-10-10 10:35:09,396 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 89/113 for batch 1.
2026-10-10 10:35:09,410 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 90/113 for batch 1.
2026-10-10 10:35:09,426 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 91/113 for batch 1.
2026-10-10 10:35:09,440 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 92/113 for batch 1.
2026-10-10 10:35:09,455 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 93/113 for batch 1.
2026-10-10 10:35:09,470 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 94/113 for batch 1.
2026-10-10 10:35:09,484 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 95/113 for batch 1.
2026-10-10 10:35:09,499 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 96/113 for batch 1.
2026-10-10 10:35:09,514 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 97/113 for batch 1.
2026-10-10 10:35:09,527 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 98/113 for batch 1.
2026-10-10 10:35:09,542 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 99/113 for batch 1.
2026-10-10 10:35:09,555 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 100/113 for batch 1.
2026-10-10 10:35:09,571 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 101/113 for batch 1.
2026-10-10 10:35:09,585 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 102/113 for batch 1.
2026-10-10 10:35:09,599 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 103/113 for batch 1.
2026-10-10 10:35:09,615 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 104/113 for batch 1.
2026-10-10 10:35:09,696 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 105/113 for batch 1.
2026-10-10 10:35:09,711 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 106/113 for batch 1.
2026-10-10 10:35:09,726 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 107/113 for batch 1.
2026-10-10 10:35:09,742 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 108/113 for batch 1.
2026-10-10 10:35:09,764 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 109/113 for batch 1.
2026-10-10 10:35:09,780 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 110/113 for batch 1.
2026-10-10 10:35:09,795 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 111/113 for batch 1.
2026-10-10 10:35:09,809 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 112/113 for batch 1.
2026-10-10 10:35:09,823 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Cleaned acquisition 113/113 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_6/monthly_cubes/9972008b8852a1f4-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:35:10,147 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 10/113.
2026-10-10 10:35:10,394 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 20/113.
2026-10-10 10:35:10,643 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 30/113.
2026-10-10 10:35:10,888 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 40/113.
2026-10-10 10:35:11,135 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 50/113.
2026-10-10 10:35:11,374 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 60/113.
2026-10-10 10:35:11,628 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 70/113.
2026-10-10 10:35:11,881 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 80/113.
2026-10-10 10:35:12,126 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 90/113.
2026-10-10 10:35:12,367 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 100/113.
2026-10-10 10:35:12,608 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 110/113.
2026-10-10 10:35:12,694 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Saved output indices for acquisition 113/113.
2026-10-10 10:35:12,806 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\monthly_cubes\9972008b8852a1f4-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_6/monthly_cubes/9972008b8852a1f4-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:35:13,628 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.

Created job j-26101007351746b09a7f9048c9b4db98: partition 13, batch 1, user farfarasmpoytos@gmail.com.

2026-10-10 10:35:28,562 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\monthly_cubes\631882c707159639-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:35:28,936 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 10/113 for batch 1.
2026-10-10 10:35:29,260 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 20/113 for batch 1.
2026-10-10 10:35:29,565 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 30/113 for batch 1.
2026-10-10 10:35:29,898 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 40/113 for batch 1.
2026-10-10 10:35:30,210 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 50/113 for batch 1.
2026-10-10 10:35:30,528 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 60/113 for batch 1.
2026-10-10 10:35:30,855 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 70/113 for batch 1.
2026-10-10 10:35:31,178 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 80/113 for batch 1.
2026-10-10 10:35:31,505 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 90/113 for batch 1.
2026-10-10 10:35:31,833 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 100/113 for batch 1.
2026-10-10 10:35:32,151 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 110/113 for batch 1.
2026-10-10 10:35:32,246 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Stored observations 113/113 for batch 1.
2026-10-10 10:35:32,247 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 1/9 in strips of 63 rows.
2026-10-10 10:35:32,592 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 2/9 in strips of 63 rows.
2026-10-10 10:35:32,978 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 3/9 in strips of 63 rows.
2026-10-10 10:35:33,361 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 4/9 in strips of 63 rows.
2026-10-10 10:35:33,758 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 5/9 in strips of 63 rows.
2026-10-10 10:35:34,132 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 6/9 in strips of 63 rows.
2026-10-10 10:35:34,484 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 7/9 in strips of 63 rows.
2026-10-10 10:35:34,828 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 8/9 in strips of 63 rows.
2026-10-10 10:35:35,169 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Temporal filling band 9/9 in strips of 63 rows.
2026-10-10 10:35:35,531 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 1/113 for batch 1.
2026-10-10 10:35:35,546 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 2/113 for batch 1.
2026-10-10 10:35:35,567 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 3/113 for batch 1.
2026-10-10 10:35:35,582 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 4/113 for batch 1.
2026-10-10 10:35:35,601 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 5/113 for batch 1.
2026-10-10 10:35:35,615 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 6/113 for batch 1.
2026-10-10 10:35:35,630 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 7/113 for batch 1.
2026-10-10 10:35:35,649 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 8/113 for batch 1.
2026-10-10 10:35:35,664 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 9/113 for batch 1.
2026-10-10 10:35:35,681 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 10/113 for batch 1.
2026-10-10 10:35:35,759 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 11/113 for batch 1.
2026-10-10 10:35:35,774 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 12/113 for batch 1.
2026-10-10 10:35:35,791 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 13/113 for batch 1.
2026-10-10 10:35:35,808 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 14/113 for batch 1.
2026-10-10 10:35:35,885 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 15/113 for batch 1.
2026-10-10 10:35:35,900 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 16/113 for batch 1.
2026-10-10 10:35:35,919 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 17/113 for batch 1.
2026-10-10 10:35:35,934 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 18/113 for batch 1.
2026-10-10 10:35:35,948 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 19/113 for batch 1.
2026-10-10 10:35:35,967 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 20/113 for batch 1.
2026-10-10 10:35:36,025 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 21/113 for batch 1.
2026-10-10 10:35:36,084 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 22/113 for batch 1.
2026-10-10 10:35:36,100 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 23/113 for batch 1.
2026-10-10 10:35:36,115 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 24/113 for batch 1.
2026-10-10 10:35:36,192 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 25/113 for batch 1.
2026-10-10 10:35:36,270 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 26/113 for batch 1.
2026-10-10 10:35:36,287 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 27/113 for batch 1.
2026-10-10 10:35:36,301 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 28/113 for batch 1.
2026-10-10 10:35:36,316 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 29/113 for batch 1.
2026-10-10 10:35:36,335 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 30/113 for batch 1.
2026-10-10 10:35:36,349 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 31/113 for batch 1.
2026-10-10 10:35:36,368 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 32/113 for batch 1.
2026-10-10 10:35:36,447 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 33/113 for batch 1.
2026-10-10 10:35:36,465 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 34/113 for batch 1.
2026-10-10 10:35:36,544 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 35/113 for batch 1.
2026-10-10 10:35:36,561 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 36/113 for batch 1.
2026-10-10 10:35:36,578 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 37/113 for batch 1.
2026-10-10 10:35:36,593 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 38/113 for batch 1.
2026-10-10 10:35:36,612 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 39/113 for batch 1.
2026-10-10 10:35:36,699 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 40/113 for batch 1.
2026-10-10 10:35:36,714 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 41/113 for batch 1.
2026-10-10 10:35:36,792 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 42/113 for batch 1.
2026-10-10 10:35:36,871 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 43/113 for batch 1.
2026-10-10 10:35:36,889 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 44/113 for batch 1.
2026-10-10 10:35:36,966 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 45/113 for batch 1.
2026-10-10 10:35:36,983 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 46/113 for batch 1.
2026-10-10 10:35:37,063 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 47/113 for batch 1.
2026-10-10 10:35:37,080 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 48/113 for batch 1.
2026-10-10 10:35:37,098 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 49/113 for batch 1.
2026-10-10 10:35:37,176 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 50/113 for batch 1.
2026-10-10 10:35:37,192 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 51/113 for batch 1.
2026-10-10 10:35:37,269 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 52/113 for batch 1.
2026-10-10 10:35:37,285 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 53/113 for batch 1.
2026-10-10 10:35:37,301 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 54/113 for batch 1.
2026-10-10 10:35:37,318 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 55/113 for batch 1.
2026-10-10 10:35:37,333 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 56/113 for batch 1.
2026-10-10 10:35:37,348 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 57/113 for batch 1.
2026-10-10 10:35:37,364 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 58/113 for batch 1.
2026-10-10 10:35:37,380 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 59/113 for batch 1.
2026-10-10 10:35:37,404 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 60/113 for batch 1.
2026-10-10 10:35:37,423 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 61/113 for batch 1.
2026-10-10 10:35:37,440 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 62/113 for batch 1.
2026-10-10 10:35:37,454 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 63/113 for batch 1.
2026-10-10 10:35:37,468 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 64/113 for batch 1.
2026-10-10 10:35:37,485 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 65/113 for batch 1.
2026-10-10 10:35:37,562 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 66/113 for batch 1.
2026-10-10 10:35:37,578 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 67/113 for batch 1.
2026-10-10 10:35:37,593 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 68/113 for batch 1.
2026-10-10 10:35:37,608 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 69/113 for batch 1.
2026-10-10 10:35:37,624 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 70/113 for batch 1.
2026-10-10 10:35:37,639 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 71/113 for batch 1.
2026-10-10 10:35:37,656 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 72/113 for batch 1.
2026-10-10 10:35:37,733 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 73/113 for batch 1.
2026-10-10 10:35:37,809 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 74/113 for batch 1.
2026-10-10 10:35:37,826 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 75/113 for batch 1.
2026-10-10 10:35:37,844 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 76/113 for batch 1.
2026-10-10 10:35:37,859 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 77/113 for batch 1.
2026-10-10 10:35:37,875 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 78/113 for batch 1.
2026-10-10 10:35:37,951 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 79/113 for batch 1.
2026-10-10 10:35:37,968 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 80/113 for batch 1.
2026-10-10 10:35:37,983 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 81/113 for batch 1.
2026-10-10 10:35:37,999 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 82/113 for batch 1.
2026-10-10 10:35:38,017 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 83/113 for batch 1.
2026-10-10 10:35:38,032 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 84/113 for batch 1.
2026-10-10 10:35:38,050 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 85/113 for batch 1.
2026-10-10 10:35:38,064 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 86/113 for batch 1.
2026-10-10 10:35:38,078 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 87/113 for batch 1.
2026-10-10 10:35:38,094 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 88/113 for batch 1.
2026-10-10 10:35:38,109 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 89/113 for batch 1.
2026-10-10 10:35:38,123 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 90/113 for batch 1.
2026-10-10 10:35:38,140 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 91/113 for batch 1.
2026-10-10 10:35:38,155 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 92/113 for batch 1.
2026-10-10 10:35:38,171 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 93/113 for batch 1.
2026-10-10 10:35:38,186 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 94/113 for batch 1.
2026-10-10 10:35:38,200 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 95/113 for batch 1.
2026-10-10 10:35:38,216 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 96/113 for batch 1.
2026-10-10 10:35:38,230 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 97/113 for batch 1.
2026-10-10 10:35:38,246 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 98/113 for batch 1.
2026-10-10 10:35:38,261 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 99/113 for batch 1.
2026-10-10 10:35:38,275 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 100/113 for batch 1.
2026-10-10 10:35:38,293 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 101/113 for batch 1.
2026-10-10 10:35:38,308 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 102/113 for batch 1.
2026-10-10 10:35:38,322 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 103/113 for batch 1.
2026-10-10 10:35:38,337 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 104/113 for batch 1.
2026-10-10 10:35:38,352 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 105/113 for batch 1.
2026-10-10 10:35:38,367 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 106/113 for batch 1.
2026-10-10 10:35:38,383 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 107/113 for batch 1.
2026-10-10 10:35:38,397 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 108/113 for batch 1.
2026-10-10 10:35:38,413 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 109/113 for batch 1.
2026-10-10 10:35:38,427 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 110/113 for batch 1.
2026-10-10 10:35:38,445 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 111/113 for batch 1.
2026-10-10 10:35:38,460 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 112/113 for batch 1.
2026-10-10 10:35:38,474 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Cleaned acquisition 113/113 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_8/monthly_cubes/631882c707159639-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:35:38,817 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 10/113.
2026-10-10 10:35:39,074 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 20/113.
2026-10-10 10:35:39,340 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 30/113.
2026-10-10 10:35:39,595 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 40/113.
2026-10-10 10:35:39,847 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 50/113.
2026-10-10 10:35:40,098 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 60/113.
2026-10-10 10:35:40,354 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 70/113.
2026-10-10 10:35:40,610 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 80/113.
2026-10-10 10:35:40,860 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 90/113.
2026-10-10 10:35:41,104 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 100/113.
2026-10-10 10:35:41,347 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 110/113.
2026-10-10 10:35:41,424 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Saved output indices for acquisition 113/113.
2026-10-10 10:35:41,848 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\monthly_cubes\631882c707159639-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_8/monthly_cubes/631882c707159639-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:35:42,898 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.

Created job j-2610100735464666babdfcd6109184a1: partition 13, batch 2, user katrinporo@gmail.com.

2026-10-10 10:36:30,949 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\monthly_cubes\3ebc677009cd25e7-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:36:31,318 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 10/147 for batch 1.
2026-10-10 10:36:31,638 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 20/147 for batch 1.
2026-10-10 10:36:31,963 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 30/147 for batch 1.
2026-10-10 10:36:32,300 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 40/147 for batch 1.
2026-10-10 10:36:32,608 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 50/147 for batch 1.
2026-10-10 10:36:32,981 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 60/147 for batch 1.
2026-10-10 10:36:33,332 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 70/147 for batch 1.
2026-10-10 10:36:33,694 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 80/147 for batch 1.
2026-10-10 10:36:34,035 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 90/147 for batch 1.
2026-10-10 10:36:34,376 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 100/147 for batch 1.
2026-10-10 10:36:34,695 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 110/147 for batch 1.
2026-10-10 10:36:35,001 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 120/147 for batch 1.
2026-10-10 10:36:35,311 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 130/147 for batch 1.
2026-10-10 10:36:35,622 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 140/147 for batch 1.
2026-10-10 10:36:35,842 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Stored observations 147/147 for batch 1.
2026-10-10 10:36:35,843 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 1/9 in strips of 48 rows.
2026-10-10 10:36:36,351 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 2/9 in strips of 48 rows.
2026-10-10 10:36:36,861 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 3/9 in strips of 48 rows.
2026-10-10 10:36:37,375 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 4/9 in strips of 48 rows.
2026-10-10 10:36:37,886 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 5/9 in strips of 48 rows.
2026-10-10 10:36:38,398 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 6/9 in strips of 48 rows.
2026-10-10 10:36:38,910 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 7/9 in strips of 48 rows.
2026-10-10 10:36:39,422 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 8/9 in strips of 48 rows.
2026-10-10 10:36:39,936 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Temporal filling band 9/9 in strips of 48 rows.
2026-10-10 10:36:40,468 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 1/147 for batch 1.
2026-10-10 10:36:40,483 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 2/147 for batch 1.
2026-10-10 10:36:40,498 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 3/147 for batch 1.
2026-10-10 10:36:40,514 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 4/147 for batch 1.
2026-10-10 10:36:40,530 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 5/147 for batch 1.
2026-10-10 10:36:40,545 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 6/147 for batch 1.
2026-10-10 10:36:40,560 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 7/147 for batch 1.
2026-10-10 10:36:40,576 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 8/147 for batch 1.
2026-10-10 10:36:40,591 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 9/147 for batch 1.
2026-10-10 10:36:40,607 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 10/147 for batch 1.
2026-10-10 10:36:40,623 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 11/147 for batch 1.
2026-10-10 10:36:40,638 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 12/147 for batch 1.
2026-10-10 10:36:40,653 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 13/147 for batch 1.
2026-10-10 10:36:40,668 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 14/147 for batch 1.
2026-10-10 10:36:40,748 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 15/147 for batch 1.
2026-10-10 10:36:40,763 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 16/147 for batch 1.
2026-10-10 10:36:40,844 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 17/147 for batch 1.
2026-10-10 10:36:40,858 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 18/147 for batch 1.
2026-10-10 10:36:40,873 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 19/147 for batch 1.
2026-10-10 10:36:40,888 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 20/147 for batch 1.
2026-10-10 10:36:40,904 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 21/147 for batch 1.
2026-10-10 10:36:40,920 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 22/147 for batch 1.
2026-10-10 10:36:40,935 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 23/147 for batch 1.
2026-10-10 10:36:40,950 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 24/147 for batch 1.
2026-10-10 10:36:41,032 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 25/147 for batch 1.
2026-10-10 10:36:41,048 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 26/147 for batch 1.
2026-10-10 10:36:41,063 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 27/147 for batch 1.
2026-10-10 10:36:41,080 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 28/147 for batch 1.
2026-10-10 10:36:41,097 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 29/147 for batch 1.
2026-10-10 10:36:41,114 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 30/147 for batch 1.
2026-10-10 10:36:41,130 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 31/147 for batch 1.
2026-10-10 10:36:41,208 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 32/147 for batch 1.
2026-10-10 10:36:41,287 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 33/147 for batch 1.
2026-10-10 10:36:41,303 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 34/147 for batch 1.
2026-10-10 10:36:41,318 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 35/147 for batch 1.
2026-10-10 10:36:41,333 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 36/147 for batch 1.
2026-10-10 10:36:41,348 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 37/147 for batch 1.
2026-10-10 10:36:41,365 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 38/147 for batch 1.
2026-10-10 10:36:41,445 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 39/147 for batch 1.
2026-10-10 10:36:41,460 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 40/147 for batch 1.
2026-10-10 10:36:41,538 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 41/147 for batch 1.
2026-10-10 10:36:41,552 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 42/147 for batch 1.
2026-10-10 10:36:41,567 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 43/147 for batch 1.
2026-10-10 10:36:41,582 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 44/147 for batch 1.
2026-10-10 10:36:41,597 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 45/147 for batch 1.
2026-10-10 10:36:41,613 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 46/147 for batch 1.
2026-10-10 10:36:41,628 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 47/147 for batch 1.
2026-10-10 10:36:41,707 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 48/147 for batch 1.
2026-10-10 10:36:41,721 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 49/147 for batch 1.
2026-10-10 10:36:41,737 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 50/147 for batch 1.
2026-10-10 10:36:41,753 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 51/147 for batch 1.
2026-10-10 10:36:41,767 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 52/147 for batch 1.
2026-10-10 10:36:41,782 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 53/147 for batch 1.
2026-10-10 10:36:41,797 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 54/147 for batch 1.
2026-10-10 10:36:41,812 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 55/147 for batch 1.
2026-10-10 10:36:41,834 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 56/147 for batch 1.
2026-10-10 10:36:41,853 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 57/147 for batch 1.
2026-10-10 10:36:41,871 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 58/147 for batch 1.
2026-10-10 10:36:41,885 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 59/147 for batch 1.
2026-10-10 10:36:41,964 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 60/147 for batch 1.
2026-10-10 10:36:41,978 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 61/147 for batch 1.
2026-10-10 10:36:41,993 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 62/147 for batch 1.
2026-10-10 10:36:42,008 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 63/147 for batch 1.
2026-10-10 10:36:42,023 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 64/147 for batch 1.
2026-10-10 10:36:42,037 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 65/147 for batch 1.
2026-10-10 10:36:42,051 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 66/147 for batch 1.
2026-10-10 10:36:42,066 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 67/147 for batch 1.
2026-10-10 10:36:42,080 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 68/147 for batch 1.
2026-10-10 10:36:42,096 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 69/147 for batch 1.
2026-10-10 10:36:42,110 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 70/147 for batch 1.
2026-10-10 10:36:42,124 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 71/147 for batch 1.
2026-10-10 10:36:42,140 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 72/147 for batch 1.
2026-10-10 10:36:42,154 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 73/147 for batch 1.
2026-10-10 10:36:42,172 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 74/147 for batch 1.
2026-10-10 10:36:42,187 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 75/147 for batch 1.
2026-10-10 10:36:42,202 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 76/147 for batch 1.
2026-10-10 10:36:42,216 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 77/147 for batch 1.
2026-10-10 10:36:42,293 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 78/147 for batch 1.
2026-10-10 10:36:42,307 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 79/147 for batch 1.
2026-10-10 10:36:42,322 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 80/147 for batch 1.
2026-10-10 10:36:42,400 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 81/147 for batch 1.
2026-10-10 10:36:42,414 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 82/147 for batch 1.
2026-10-10 10:36:42,429 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 83/147 for batch 1.
2026-10-10 10:36:42,444 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 84/147 for batch 1.
2026-10-10 10:36:42,458 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 85/147 for batch 1.
2026-10-10 10:36:42,473 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 86/147 for batch 1.
2026-10-10 10:36:42,488 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 87/147 for batch 1.
2026-10-10 10:36:42,504 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 88/147 for batch 1.
2026-10-10 10:36:42,519 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 89/147 for batch 1.
2026-10-10 10:36:42,533 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 90/147 for batch 1.
2026-10-10 10:36:42,548 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 91/147 for batch 1.
2026-10-10 10:36:42,563 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 92/147 for batch 1.
2026-10-10 10:36:42,577 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 93/147 for batch 1.
2026-10-10 10:36:42,592 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 94/147 for batch 1.
2026-10-10 10:36:42,606 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 95/147 for batch 1.
2026-10-10 10:36:42,621 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 96/147 for batch 1.
2026-10-10 10:36:42,636 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 97/147 for batch 1.
2026-10-10 10:36:42,649 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 98/147 for batch 1.
2026-10-10 10:36:42,664 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 99/147 for batch 1.
2026-10-10 10:36:42,679 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 100/147 for batch 1.
2026-10-10 10:36:42,693 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 101/147 for batch 1.
2026-10-10 10:36:42,708 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 102/147 for batch 1.
2026-10-10 10:36:42,722 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 103/147 for batch 1.
2026-10-10 10:36:42,802 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 104/147 for batch 1.
2026-10-10 10:36:42,816 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 105/147 for batch 1.
2026-10-10 10:36:42,832 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 106/147 for batch 1.
2026-10-10 10:36:42,847 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 107/147 for batch 1.
2026-10-10 10:36:42,861 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 108/147 for batch 1.
2026-10-10 10:36:42,875 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 109/147 for batch 1.
2026-10-10 10:36:42,889 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 110/147 for batch 1.
2026-10-10 10:36:42,904 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 111/147 for batch 1.
2026-10-10 10:36:42,918 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 112/147 for batch 1.
2026-10-10 10:36:42,932 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 113/147 for batch 1.
2026-10-10 10:36:42,946 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 114/147 for batch 1.
2026-10-10 10:36:42,960 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 115/147 for batch 1.
2026-10-10 10:36:42,975 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 116/147 for batch 1.
2026-10-10 10:36:42,989 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 117/147 for batch 1.
2026-10-10 10:36:43,003 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 118/147 for batch 1.
2026-10-10 10:36:43,018 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 119/147 for batch 1.
2026-10-10 10:36:43,032 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 120/147 for batch 1.
2026-10-10 10:36:43,047 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 121/147 for batch 1.
2026-10-10 10:36:43,061 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 122/147 for batch 1.
2026-10-10 10:36:43,075 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 123/147 for batch 1.
2026-10-10 10:36:43,088 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 124/147 for batch 1.
2026-10-10 10:36:43,102 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 125/147 for batch 1.
2026-10-10 10:36:43,115 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 126/147 for batch 1.
2026-10-10 10:36:43,129 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Cleaned acquisition 127/147 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_7/monthly_cubes/3ebc677009cd25e7-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:36:43,984 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 10/147.
2026-10-10 10:36:44,252 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 20/147.
2026-10-10 10:36:44,507 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 30/147.
2026-10-10 10:36:44,759 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 40/147.
2026-10-10 10:36:45,002 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 50/147.
2026-10-10 10:36:45,249 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 60/147.
2026-10-10 10:36:45,492 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 70/147.
2026-10-10 10:36:45,742 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 80/147.
2026-10-10 10:36:45,994 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 90/147.
2026-10-10 10:36:46,239 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 100/147.
2026-10-10 10:36:46,484 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 110/147.
2026-10-10 10:36:46,725 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 120/147.
2026-10-10 10:36:46,963 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 130/147.
2026-10-10 10:36:47,203 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 140/147.
2026-10-10 10:36:47,369 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Saved output indices for acquisition 147/147.
2026-10-10 10:36:47,519 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\monthly_cubes\3ebc677009cd25e7-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_7/monthly_cubes/3ebc677009cd25e7-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:36:48,620 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.

Created job j-26101007365248b4a454cabeaca9b61c: partition 14, batch 1, user farfarasmpoytos@gmail.com.

2026-10-10 10:37:04,529 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\monthly_cubes\2f0d9383f0b652be-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:37:04,900 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 10/112 for batch 1.
2026-10-10 10:37:05,219 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 20/112 for batch 1.
2026-10-10 10:37:05,528 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 30/112 for batch 1.
2026-10-10 10:37:05,850 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 40/112 for batch 1.
2026-10-10 10:37:06,164 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 50/112 for batch 1.
2026-10-10 10:37:06,475 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 60/112 for batch 1.
2026-10-10 10:37:06,809 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 70/112 for batch 1.
2026-10-10 10:37:07,140 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 80/112 for batch 1.
2026-10-10 10:37:07,464 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 90/112 for batch 1.
2026-10-10 10:37:07,785 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 100/112 for batch 1.
2026-10-10 10:37:08,103 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 110/112 for batch 1.
2026-10-10 10:37:08,174 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Stored observations 112/112 for batch 1.
2026-10-10 10:37:08,175 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 1/9 in strips of 62 rows.
2026-10-10 10:37:08,522 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 2/9 in strips of 62 rows.
2026-10-10 10:37:08,867 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 3/9 in strips of 62 rows.
2026-10-10 10:37:09,222 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 4/9 in strips of 62 rows.
2026-10-10 10:37:09,569 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 5/9 in strips of 62 rows.
2026-10-10 10:37:09,914 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 6/9 in strips of 62 rows.
2026-10-10 10:37:10,265 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 7/9 in strips of 62 rows.
2026-10-10 10:37:10,615 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 8/9 in strips of 62 rows.
2026-10-10 10:37:10,961 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Temporal filling band 9/9 in strips of 62 rows.
2026-10-10 10:37:11,397 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 1/112 for batch 1.
2026-10-10 10:37:11,413 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 2/112 for batch 1.
2026-10-10 10:37:11,430 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 3/112 for batch 1.
2026-10-10 10:37:11,446 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 4/112 for batch 1.
2026-10-10 10:37:11,463 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 5/112 for batch 1.
2026-10-10 10:37:11,478 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 6/112 for batch 1.
2026-10-10 10:37:11,495 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 7/112 for batch 1.
2026-10-10 10:37:11,511 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 8/112 for batch 1.
2026-10-10 10:37:11,528 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 9/112 for batch 1.
2026-10-10 10:37:11,545 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 10/112 for batch 1.
2026-10-10 10:37:11,561 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 11/112 for batch 1.
2026-10-10 10:37:11,576 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 12/112 for batch 1.
2026-10-10 10:37:11,591 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 13/112 for batch 1.
2026-10-10 10:37:11,607 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 14/112 for batch 1.
2026-10-10 10:37:11,624 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 15/112 for batch 1.
2026-10-10 10:37:11,639 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 16/112 for batch 1.
2026-10-10 10:37:11,655 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 17/112 for batch 1.
2026-10-10 10:37:11,671 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 18/112 for batch 1.
2026-10-10 10:37:11,755 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 19/112 for batch 1.
2026-10-10 10:37:11,771 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 20/112 for batch 1.
2026-10-10 10:37:11,786 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 21/112 for batch 1.
2026-10-10 10:37:11,801 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 22/112 for batch 1.
2026-10-10 10:37:11,887 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 23/112 for batch 1.
2026-10-10 10:37:11,902 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 24/112 for batch 1.
2026-10-10 10:37:11,985 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 25/112 for batch 1.
2026-10-10 10:37:12,065 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 26/112 for batch 1.
2026-10-10 10:37:12,079 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 27/112 for batch 1.
2026-10-10 10:37:12,161 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 28/112 for batch 1.
2026-10-10 10:37:12,177 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 29/112 for batch 1.
2026-10-10 10:37:12,194 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 30/112 for batch 1.
2026-10-10 10:37:12,209 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 31/112 for batch 1.
2026-10-10 10:37:12,223 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 32/112 for batch 1.
2026-10-10 10:37:12,237 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 33/112 for batch 1.
2026-10-10 10:37:12,252 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 34/112 for batch 1.
2026-10-10 10:37:12,268 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 35/112 for batch 1.
2026-10-10 10:37:12,284 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 36/112 for batch 1.
2026-10-10 10:37:12,372 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 37/112 for batch 1.
2026-10-10 10:37:12,454 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 38/112 for batch 1.
2026-10-10 10:37:12,468 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 39/112 for batch 1.
2026-10-10 10:37:12,483 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 40/112 for batch 1.
2026-10-10 10:37:12,569 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 41/112 for batch 1.
2026-10-10 10:37:12,583 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 42/112 for batch 1.
2026-10-10 10:37:12,598 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 43/112 for batch 1.
2026-10-10 10:37:12,681 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 44/112 for batch 1.
2026-10-10 10:37:12,695 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 45/112 for batch 1.
2026-10-10 10:37:12,710 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 46/112 for batch 1.
2026-10-10 10:37:12,725 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 47/112 for batch 1.
2026-10-10 10:37:12,742 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 48/112 for batch 1.
2026-10-10 10:37:12,827 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 49/112 for batch 1.
2026-10-10 10:37:12,842 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 50/112 for batch 1.
2026-10-10 10:37:12,858 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 51/112 for batch 1.
2026-10-10 10:37:12,873 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 52/112 for batch 1.
2026-10-10 10:37:12,889 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 53/112 for batch 1.
2026-10-10 10:37:12,904 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 54/112 for batch 1.
2026-10-10 10:37:12,922 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 55/112 for batch 1.
2026-10-10 10:37:12,937 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 56/112 for batch 1.
2026-10-10 10:37:12,952 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 57/112 for batch 1.
2026-10-10 10:37:12,968 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 58/112 for batch 1.
2026-10-10 10:37:12,983 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 59/112 for batch 1.
2026-10-10 10:37:12,997 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 60/112 for batch 1.
2026-10-10 10:37:13,014 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 61/112 for batch 1.
2026-10-10 10:37:13,028 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 62/112 for batch 1.
2026-10-10 10:37:13,044 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 63/112 for batch 1.
2026-10-10 10:37:13,064 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 64/112 for batch 1.
2026-10-10 10:37:13,093 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 65/112 for batch 1.
2026-10-10 10:37:13,122 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 66/112 for batch 1.
2026-10-10 10:37:13,142 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 67/112 for batch 1.
2026-10-10 10:37:13,160 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 68/112 for batch 1.
2026-10-10 10:37:13,177 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 69/112 for batch 1.
2026-10-10 10:37:13,193 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 70/112 for batch 1.
2026-10-10 10:37:13,210 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 71/112 for batch 1.
2026-10-10 10:37:13,225 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 72/112 for batch 1.
2026-10-10 10:37:13,241 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 73/112 for batch 1.
2026-10-10 10:37:13,257 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 74/112 for batch 1.
2026-10-10 10:37:13,272 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 75/112 for batch 1.
2026-10-10 10:37:13,288 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 76/112 for batch 1.
2026-10-10 10:37:13,305 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 77/112 for batch 1.
2026-10-10 10:37:13,321 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 78/112 for batch 1.
2026-10-10 10:37:13,336 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 79/112 for batch 1.
2026-10-10 10:37:13,351 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 80/112 for batch 1.
2026-10-10 10:37:13,364 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 81/112 for batch 1.
2026-10-10 10:37:13,384 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 82/112 for batch 1.
2026-10-10 10:37:13,399 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 83/112 for batch 1.
2026-10-10 10:37:13,414 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 84/112 for batch 1.
2026-10-10 10:37:13,429 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 85/112 for batch 1.
2026-10-10 10:37:13,443 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 86/112 for batch 1.
2026-10-10 10:37:13,459 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 87/112 for batch 1.
2026-10-10 10:37:13,475 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 88/112 for batch 1.
2026-10-10 10:37:13,490 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 89/112 for batch 1.
2026-10-10 10:37:13,505 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 90/112 for batch 1.
2026-10-10 10:37:13,520 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 91/112 for batch 1.
2026-10-10 10:37:13,536 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 92/112 for batch 1.
2026-10-10 10:37:13,551 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 93/112 for batch 1.
2026-10-10 10:37:13,568 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 94/112 for batch 1.
2026-10-10 10:37:13,585 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 95/112 for batch 1.
2026-10-10 10:37:13,599 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 96/112 for batch 1.
2026-10-10 10:37:13,614 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 97/112 for batch 1.
2026-10-10 10:37:13,629 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 98/112 for batch 1.
2026-10-10 10:37:13,645 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 99/112 for batch 1.
2026-10-10 10:37:13,659 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 100/112 for batch 1.
2026-10-10 10:37:13,675 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 101/112 for batch 1.
2026-10-10 10:37:13,691 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 102/112 for batch 1.
2026-10-10 10:37:13,705 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 103/112 for batch 1.
2026-10-10 10:37:13,722 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 104/112 for batch 1.
2026-10-10 10:37:13,736 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 105/112 for batch 1.
2026-10-10 10:37:13,751 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 106/112 for batch 1.
2026-10-10 10:37:13,766 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 107/112 for batch 1.
2026-10-10 10:37:13,782 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 108/112 for batch 1.
2026-10-10 10:37:13,798 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 109/112 for batch 1.
2026-10-10 10:37:13,813 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 110/112 for batch 1.
2026-10-10 10:37:13,827 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 111/112 for batch 1.
2026-10-10 10:37:13,842 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Cleaned acquisition 112/112 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_5/monthly_cubes/2f0d9383f0b652be-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:37:14,193 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 10/112.
2026-10-10 10:37:14,454 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 20/112.
2026-10-10 10:37:14,725 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 30/112.
2026-10-10 10:37:14,979 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 40/112.
2026-10-10 10:37:15,228 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 50/112.
2026-10-10 10:37:15,483 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 60/112.
2026-10-10 10:37:15,738 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 70/112.
2026-10-10 10:37:15,993 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 80/112.
2026-10-10 10:37:16,248 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 90/112.
2026-10-10 10:37:16,501 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 100/112.
2026-10-10 10:37:16,740 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 110/112.
2026-10-10 10:37:16,791 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Saved output indices for acquisition 112/112.
2026-10-10 10:37:16,904 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\monthly_cubes\2f0d9383f0b652be-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_5/monthly_cubes/2f0d9383f0b652be-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:37:18,554 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 2 parcels from batch_00001_monthly.nc.

Created job j-26101007372247208da06f19f949913a: partition 15, batch 1, user esagovhub4@gmail.com.

2026-10-10 10:37:32,007 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\monthly_cubes\103ad5725e2606f8-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:37:32,368 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 10/118 for batch 1.
2026-10-10 10:37:32,684 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 20/118 for batch 1.
2026-10-10 10:37:33,017 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 30/118 for batch 1.
2026-10-10 10:37:33,361 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 40/118 for batch 1.
2026-10-10 10:37:33,712 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 50/118 for batch 1.
2026-10-10 10:37:34,039 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 60/118 for batch 1.
2026-10-10 10:37:34,371 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 70/118 for batch 1.
2026-10-10 10:37:34,699 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 80/118 for batch 1.
2026-10-10 10:37:35,024 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 90/118 for batch 1.
2026-10-10 10:37:35,352 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 100/118 for batch 1.
2026-10-10 10:37:35,688 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 110/118 for batch 1.
2026-10-10 10:37:35,954 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Stored observations 118/118 for batch 1.
2026-10-10 10:37:35,955 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 1/9 in strips of 61 rows.
2026-10-10 10:37:36,312 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 2/9 in strips of 61 rows.
2026-10-10 10:37:36,673 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 3/9 in strips of 61 rows.
2026-10-10 10:37:37,026 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 4/9 in strips of 61 rows.
2026-10-10 10:37:37,380 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 5/9 in strips of 61 rows.
2026-10-10 10:37:37,735 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 6/9 in strips of 61 rows.
2026-10-10 10:37:38,095 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 7/9 in strips of 61 rows.
2026-10-10 10:37:38,450 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 8/9 in strips of 61 rows.
2026-10-10 10:37:38,803 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Temporal filling band 9/9 in strips of 61 rows.
2026-10-10 10:37:39,236 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 1/118 for batch 1.
2026-10-10 10:37:39,316 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 2/118 for batch 1.
2026-10-10 10:37:39,330 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 3/118 for batch 1.
2026-10-10 10:37:39,347 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 4/118 for batch 1.
2026-10-10 10:37:39,362 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 5/118 for batch 1.
2026-10-10 10:37:39,379 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 6/118 for batch 1.
2026-10-10 10:37:39,393 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 7/118 for batch 1.
2026-10-10 10:37:39,413 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 8/118 for batch 1.
2026-10-10 10:37:39,427 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 9/118 for batch 1.
2026-10-10 10:37:39,485 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 10/118 for batch 1.
2026-10-10 10:37:39,498 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 11/118 for batch 1.
2026-10-10 10:37:39,514 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 12/118 for batch 1.
2026-10-10 10:37:39,591 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 13/118 for batch 1.
2026-10-10 10:37:39,671 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 14/118 for batch 1.
2026-10-10 10:37:39,687 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 15/118 for batch 1.
2026-10-10 10:37:39,703 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 16/118 for batch 1.
2026-10-10 10:37:39,718 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 17/118 for batch 1.
2026-10-10 10:37:39,733 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 18/118 for batch 1.
2026-10-10 10:37:39,749 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 19/118 for batch 1.
2026-10-10 10:37:39,763 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 20/118 for batch 1.
2026-10-10 10:37:39,779 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 21/118 for batch 1.
2026-10-10 10:37:39,857 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 22/118 for batch 1.
2026-10-10 10:37:39,873 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 23/118 for batch 1.
2026-10-10 10:37:39,889 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 24/118 for batch 1.
2026-10-10 10:37:39,905 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 25/118 for batch 1.
2026-10-10 10:37:39,920 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 26/118 for batch 1.
2026-10-10 10:37:40,000 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 27/118 for batch 1.
2026-10-10 10:37:40,059 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 28/118 for batch 1.
2026-10-10 10:37:40,136 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 29/118 for batch 1.
2026-10-10 10:37:40,153 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 30/118 for batch 1.
2026-10-10 10:37:40,168 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 31/118 for batch 1.
2026-10-10 10:37:40,184 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 32/118 for batch 1.
2026-10-10 10:37:40,199 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 33/118 for batch 1.
2026-10-10 10:37:40,278 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 34/118 for batch 1.
2026-10-10 10:37:40,295 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 35/118 for batch 1.
2026-10-10 10:37:40,310 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 36/118 for batch 1.
2026-10-10 10:37:40,325 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 37/118 for batch 1.
2026-10-10 10:37:40,340 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 38/118 for batch 1.
2026-10-10 10:37:40,356 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 39/118 for batch 1.
2026-10-10 10:37:40,370 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 40/118 for batch 1.
2026-10-10 10:37:40,386 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 41/118 for batch 1.
2026-10-10 10:37:40,400 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 42/118 for batch 1.
2026-10-10 10:37:40,415 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 43/118 for batch 1.
2026-10-10 10:37:40,493 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 44/118 for batch 1.
2026-10-10 10:37:40,508 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 45/118 for batch 1.
2026-10-10 10:37:40,586 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 46/118 for batch 1.
2026-10-10 10:37:40,600 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 47/118 for batch 1.
2026-10-10 10:37:40,614 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 48/118 for batch 1.
2026-10-10 10:37:40,629 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 49/118 for batch 1.
2026-10-10 10:37:40,645 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 50/118 for batch 1.
2026-10-10 10:37:40,660 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 51/118 for batch 1.
2026-10-10 10:37:40,678 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 52/118 for batch 1.
2026-10-10 10:37:40,754 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 53/118 for batch 1.
2026-10-10 10:37:40,770 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 54/118 for batch 1.
2026-10-10 10:37:40,784 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 55/118 for batch 1.
2026-10-10 10:37:40,799 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 56/118 for batch 1.
2026-10-10 10:37:40,815 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 57/118 for batch 1.
2026-10-10 10:37:40,830 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 58/118 for batch 1.
2026-10-10 10:37:40,845 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 59/118 for batch 1.
2026-10-10 10:37:40,859 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 60/118 for batch 1.
2026-10-10 10:37:40,874 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 61/118 for batch 1.
2026-10-10 10:37:40,891 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 62/118 for batch 1.
2026-10-10 10:37:40,915 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 63/118 for batch 1.
2026-10-10 10:37:40,937 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 64/118 for batch 1.
2026-10-10 10:37:40,952 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 65/118 for batch 1.
2026-10-10 10:37:40,966 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 66/118 for batch 1.
2026-10-10 10:37:40,981 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 67/118 for batch 1.
2026-10-10 10:37:40,997 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 68/118 for batch 1.
2026-10-10 10:37:41,012 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 69/118 for batch 1.
2026-10-10 10:37:41,027 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 70/118 for batch 1.
2026-10-10 10:37:41,042 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 71/118 for batch 1.
2026-10-10 10:37:41,057 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 72/118 for batch 1.
2026-10-10 10:37:41,071 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 73/118 for batch 1.
2026-10-10 10:37:41,086 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 74/118 for batch 1.
2026-10-10 10:37:41,100 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 75/118 for batch 1.
2026-10-10 10:37:41,114 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 76/118 for batch 1.
2026-10-10 10:37:41,129 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 77/118 for batch 1.
2026-10-10 10:37:41,144 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 78/118 for batch 1.
2026-10-10 10:37:41,159 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 79/118 for batch 1.
2026-10-10 10:37:41,174 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 80/118 for batch 1.
2026-10-10 10:37:41,189 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 81/118 for batch 1.
2026-10-10 10:37:41,203 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 82/118 for batch 1.
2026-10-10 10:37:41,217 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 83/118 for batch 1.
2026-10-10 10:37:41,234 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 84/118 for batch 1.
2026-10-10 10:37:41,249 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 85/118 for batch 1.
2026-10-10 10:37:41,265 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 86/118 for batch 1.
2026-10-10 10:37:41,280 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 87/118 for batch 1.
2026-10-10 10:37:41,294 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 88/118 for batch 1.
2026-10-10 10:37:41,309 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 89/118 for batch 1.
2026-10-10 10:37:41,323 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 90/118 for batch 1.
2026-10-10 10:37:41,338 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 91/118 for batch 1.
2026-10-10 10:37:41,352 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 92/118 for batch 1.
2026-10-10 10:37:41,366 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 93/118 for batch 1.
2026-10-10 10:37:41,382 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 94/118 for batch 1.
2026-10-10 10:37:41,397 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 95/118 for batch 1.
2026-10-10 10:37:41,412 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 96/118 for batch 1.
2026-10-10 10:37:41,427 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 97/118 for batch 1.
2026-10-10 10:37:41,441 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 98/118 for batch 1.
2026-10-10 10:37:41,456 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 99/118 for batch 1.
2026-10-10 10:37:41,470 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 100/118 for batch 1.
2026-10-10 10:37:41,529 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 101/118 for batch 1.
2026-10-10 10:37:41,543 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 102/118 for batch 1.
2026-10-10 10:37:41,558 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 103/118 for batch 1.
2026-10-10 10:37:41,573 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 104/118 for batch 1.
2026-10-10 10:37:41,589 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 105/118 for batch 1.
2026-10-10 10:37:41,605 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 106/118 for batch 1.
2026-10-10 10:37:41,619 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 107/118 for batch 1.
2026-10-10 10:37:41,633 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 108/118 for batch 1.
2026-10-10 10:37:41,648 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 109/118 for batch 1.
2026-10-10 10:37:41,665 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 110/118 for batch 1.
2026-10-10 10:37:41,680 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 111/118 for batch 1.
2026-10-10 10:37:41,694 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 112/118 for batch 1.
2026-10-10 10:37:41,708 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 113/118 for batch 1.
2026-10-10 10:37:41,723 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 114/118 for batch 1.
2026-10-10 10:37:41,740 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 115/118 for batch 1.
2026-10-10 10:37:41,756 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 116/118 for batch 1.
2026-10-10 10:37:41,772 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 117/118 for batch 1.
2026-10-10 10:37:41,787 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Cleaned acquisition 118/118 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_9/monthly_cubes/103ad5725e2606f8-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:37:42,122 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 10/118.
2026-10-10 10:37:42,382 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 20/118.
2026-10-10 10:37:42,635 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 30/118.
2026-10-10 10:37:42,890 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 40/118.
2026-10-10 10:37:43,141 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 50/118.
2026-10-10 10:37:43,402 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 60/118.
2026-10-10 10:37:43,664 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 70/118.
2026-10-10 10:37:43,928 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 80/118.
2026-10-10 10:37:44,169 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 90/118.
2026-10-10 10:37:44,413 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 100/118.
2026-10-10 10:37:44,735 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 110/118.
2026-10-10 10:37:44,947 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Saved output indices for acquisition 118/118.
2026-10-10 10:37:45,079 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\monthly_cubes\103ad5725e2606f8-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_9/monthly_cubes/103ad5725e2606f8-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:37:45,926 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.
2026-10-10 10:37:46,367 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\monthly_cubes\7d26fb0f3cb47c8f-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:37:46,746 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 10/145 for batch 1.
2026-10-10 10:37:47,085 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 20/145 for batch 1.
2026-10-10 10:37:47,409 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 30/145 for batch 1.
2026-10-10 10:37:47,727 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 40/145 for batch 1.
2026-10-10 10:37:48,042 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 50/145 for batch 1.
2026-10-10 10:37:48,359 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 60/145 for batch 1.
2026-10-10 10:37:48,680 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 70/145 for batch 1.

Created job j-2610100737494fb4809f24b2a2349ada: partition 16, batch 1, user katrinporo@gmail.com.

2026-10-10 10:37:49,013 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 80/145 for batch 1.
2026-10-10 10:37:49,329 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 90/145 for batch 1.
2026-10-10 10:37:49,670 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 100/145 for batch 1.
2026-10-10 10:37:49,997 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 110/145 for batch 1.
2026-10-10 10:37:50,320 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 120/145 for batch 1.
2026-10-10 10:37:50,662 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 130/145 for batch 1.
2026-10-10 10:37:50,992 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 140/145 for batch 1.
2026-10-10 10:37:51,161 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Stored observations 145/145 for batch 1.
2026-10-10 10:37:51,161 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 1/9 in strips of 46 rows.
2026-10-10 10:37:51,712 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 2/9 in strips of 46 rows.
2026-10-10 10:37:52,267 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 3/9 in strips of 46 rows.
2026-10-10 10:37:52,820 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 4/9 in strips of 46 rows.
2026-10-10 10:37:53,385 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 5/9 in strips of 46 rows.
2026-10-10 10:37:53,959 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 6/9 in strips of 46 rows.
2026-10-10 10:37:54,511 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 7/9 in strips of 46 rows.
2026-10-10 10:37:55,085 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 8/9 in strips of 46 rows.
2026-10-10 10:37:55,657 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Temporal filling band 9/9 in strips of 46 rows.
2026-10-10 10:37:56,242 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 1/145 for batch 1.
2026-10-10 10:37:56,259 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 2/145 for batch 1.
2026-10-10 10:37:56,276 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 3/145 for batch 1.
2026-10-10 10:37:56,292 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 4/145 for batch 1.
2026-10-10 10:37:56,309 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 5/145 for batch 1.
2026-10-10 10:37:56,325 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 6/145 for batch 1.
2026-10-10 10:37:56,341 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 7/145 for batch 1.
2026-10-10 10:37:56,357 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 8/145 for batch 1.
2026-10-10 10:37:56,375 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 9/145 for batch 1.
2026-10-10 10:37:56,464 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 10/145 for batch 1.
2026-10-10 10:37:56,480 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 11/145 for batch 1.
2026-10-10 10:37:56,496 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 12/145 for batch 1.
2026-10-10 10:37:56,512 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 13/145 for batch 1.
2026-10-10 10:37:56,529 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 14/145 for batch 1.
2026-10-10 10:37:56,617 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 15/145 for batch 1.
2026-10-10 10:37:56,705 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 16/145 for batch 1.
2026-10-10 10:37:56,721 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 17/145 for batch 1.
2026-10-10 10:37:56,736 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 18/145 for batch 1.
2026-10-10 10:37:56,751 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 19/145 for batch 1.
2026-10-10 10:37:56,766 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 20/145 for batch 1.
2026-10-10 10:37:56,781 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 21/145 for batch 1.
2026-10-10 10:37:56,796 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 22/145 for batch 1.
2026-10-10 10:37:56,811 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 23/145 for batch 1.
2026-10-10 10:37:56,826 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 24/145 for batch 1.
2026-10-10 10:37:56,843 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 25/145 for batch 1.
2026-10-10 10:37:56,858 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 26/145 for batch 1.
2026-10-10 10:37:56,875 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 27/145 for batch 1.
2026-10-10 10:37:56,892 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 28/145 for batch 1.
2026-10-10 10:37:56,908 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 29/145 for batch 1.
2026-10-10 10:37:56,932 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 30/145 for batch 1.
2026-10-10 10:37:56,948 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 31/145 for batch 1.
2026-10-10 10:37:56,964 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 32/145 for batch 1.
2026-10-10 10:37:57,053 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 33/145 for batch 1.
2026-10-10 10:37:57,069 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 34/145 for batch 1.
2026-10-10 10:37:57,084 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 35/145 for batch 1.
2026-10-10 10:37:57,106 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 36/145 for batch 1.
2026-10-10 10:37:57,124 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 37/145 for batch 1.
2026-10-10 10:37:57,141 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 38/145 for batch 1.
2026-10-10 10:37:57,159 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 39/145 for batch 1.
2026-10-10 10:37:57,175 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 40/145 for batch 1.
2026-10-10 10:37:57,190 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 41/145 for batch 1.
2026-10-10 10:37:57,208 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 42/145 for batch 1.
2026-10-10 10:37:57,225 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 43/145 for batch 1.
2026-10-10 10:37:57,313 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 44/145 for batch 1.
2026-10-10 10:37:57,327 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 45/145 for batch 1.
2026-10-10 10:37:57,342 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 46/145 for batch 1.
2026-10-10 10:37:57,357 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 47/145 for batch 1.
2026-10-10 10:37:57,374 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 48/145 for batch 1.
2026-10-10 10:37:57,389 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 49/145 for batch 1.
2026-10-10 10:37:57,407 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 50/145 for batch 1.
2026-10-10 10:37:57,422 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 51/145 for batch 1.
2026-10-10 10:37:57,439 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 52/145 for batch 1.
2026-10-10 10:37:57,455 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 53/145 for batch 1.
2026-10-10 10:37:57,471 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 54/145 for batch 1.
2026-10-10 10:37:57,490 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 55/145 for batch 1.
2026-10-10 10:37:57,506 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 56/145 for batch 1.
2026-10-10 10:37:57,529 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 57/145 for batch 1.
2026-10-10 10:37:57,546 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 58/145 for batch 1.
2026-10-10 10:37:57,561 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 59/145 for batch 1.
2026-10-10 10:37:57,578 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 60/145 for batch 1.
2026-10-10 10:37:57,593 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 61/145 for batch 1.
2026-10-10 10:37:57,609 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 62/145 for batch 1.
2026-10-10 10:37:57,624 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 63/145 for batch 1.
2026-10-10 10:37:57,640 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 64/145 for batch 1.
2026-10-10 10:37:57,657 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 65/145 for batch 1.
2026-10-10 10:37:57,672 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 66/145 for batch 1.
2026-10-10 10:37:57,687 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 67/145 for batch 1.
2026-10-10 10:37:57,702 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 68/145 for batch 1.
2026-10-10 10:37:57,717 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 69/145 for batch 1.
2026-10-10 10:37:57,734 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 70/145 for batch 1.
2026-10-10 10:37:57,749 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 71/145 for batch 1.
2026-10-10 10:37:57,764 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 72/145 for batch 1.
2026-10-10 10:37:57,779 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 73/145 for batch 1.
2026-10-10 10:37:57,794 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 74/145 for batch 1.
2026-10-10 10:37:57,809 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 75/145 for batch 1.
2026-10-10 10:37:57,824 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 76/145 for batch 1.
2026-10-10 10:37:57,842 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 77/145 for batch 1.
2026-10-10 10:37:57,871 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 78/145 for batch 1.
2026-10-10 10:37:57,892 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 79/145 for batch 1.
2026-10-10 10:37:57,911 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 80/145 for batch 1.
2026-10-10 10:37:57,929 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 81/145 for batch 1.
2026-10-10 10:37:57,945 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 82/145 for batch 1.
2026-10-10 10:37:57,963 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 83/145 for batch 1.
2026-10-10 10:37:57,978 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 84/145 for batch 1.
2026-10-10 10:37:57,994 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 85/145 for batch 1.
2026-10-10 10:37:58,009 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 86/145 for batch 1.
2026-10-10 10:37:58,027 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 87/145 for batch 1.
2026-10-10 10:37:58,043 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 88/145 for batch 1.
2026-10-10 10:37:58,059 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 89/145 for batch 1.
2026-10-10 10:37:58,075 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 90/145 for batch 1.
2026-10-10 10:37:58,092 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 91/145 for batch 1.
2026-10-10 10:37:58,108 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 92/145 for batch 1.
2026-10-10 10:37:58,123 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 93/145 for batch 1.
2026-10-10 10:37:58,139 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 94/145 for batch 1.
2026-10-10 10:37:58,154 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 95/145 for batch 1.
2026-10-10 10:37:58,170 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 96/145 for batch 1.
2026-10-10 10:37:58,186 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 97/145 for batch 1.
2026-10-10 10:37:58,202 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 98/145 for batch 1.
2026-10-10 10:37:58,220 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 99/145 for batch 1.
2026-10-10 10:37:58,236 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 100/145 for batch 1.
2026-10-10 10:37:58,255 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 101/145 for batch 1.
2026-10-10 10:37:58,270 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 102/145 for batch 1.
2026-10-10 10:37:58,286 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 103/145 for batch 1.
2026-10-10 10:37:58,301 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 104/145 for batch 1.
2026-10-10 10:37:58,316 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 105/145 for batch 1.
2026-10-10 10:37:58,332 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 106/145 for batch 1.
2026-10-10 10:37:58,347 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 107/145 for batch 1.
2026-10-10 10:37:58,363 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 108/145 for batch 1.
2026-10-10 10:37:58,379 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 109/145 for batch 1.
2026-10-10 10:37:58,394 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 110/145 for batch 1.
2026-10-10 10:37:58,409 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 111/145 for batch 1.
2026-10-10 10:37:58,424 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 112/145 for batch 1.
2026-10-10 10:37:58,439 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 113/145 for batch 1.
2026-10-10 10:37:58,454 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 114/145 for batch 1.
2026-10-10 10:37:58,469 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 115/145 for batch 1.
2026-10-10 10:37:58,485 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 116/145 for batch 1.
2026-10-10 10:37:58,501 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 117/145 for batch 1.
2026-10-10 10:37:58,516 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 118/145 for batch 1.
2026-10-10 10:37:58,532 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 119/145 for batch 1.
2026-10-10 10:37:58,547 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 120/145 for batch 1.
2026-10-10 10:37:58,562 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 121/145 for batch 1.
2026-10-10 10:37:58,578 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 122/145 for batch 1.
2026-10-10 10:37:58,593 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 123/145 for batch 1.
2026-10-10 10:37:58,609 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 124/145 for batch 1.
2026-10-10 10:37:58,625 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 125/145 for batch 1.
2026-10-10 10:37:58,642 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 126/145 for batch 1.
2026-10-10 10:37:58,658 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 127/145 for batch 1.
2026-10-10 10:37:58,673 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 128/145 for batch 1.
2026-10-10 10:37:58,692 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 129/145 for batch 1.
2026-10-10 10:37:58,710 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 130/145 for batch 1.
2026-10-10 10:37:58,728 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 131/145 for batch 1.
2026-10-10 10:37:58,742 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 132/145 for batch 1.
2026-10-10 10:37:58,758 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 133/145 for batch 1.
2026-10-10 10:37:58,774 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 134/145 for batch 1.
2026-10-10 10:37:58,789 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 135/145 for batch 1.
2026-10-10 10:37:58,804 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Cleaned acquisition 136/145 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_4/monthly_cubes/7d26fb0f3cb47c8f-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:37:59,330 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 10/145.
2026-10-10 10:37:59,611 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 20/145.
2026-10-10 10:37:59,890 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 30/145.
2026-10-10 10:38:00,185 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 40/145.
2026-10-10 10:38:00,452 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 50/145.
2026-10-10 10:38:00,739 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 60/145.
2026-10-10 10:38:01,022 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 70/145.
2026-10-10 10:38:01,305 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 80/145.
2026-10-10 10:38:01,562 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 90/145.
2026-10-10 10:38:01,839 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 100/145.
2026-10-10 10:38:02,104 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 110/145.
2026-10-10 10:38:02,374 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 120/145.
2026-10-10 10:38:02,645 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 130/145.
2026-10-10 10:38:02,898 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 140/145.
2026-10-10 10:38:03,024 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Saved output indices for acquisition 145/145.
2026-10-10 10:38:03,167 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\monthly_cubes\7d26fb0f3cb47c8f-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_4/monthly_cubes/7d26fb0f3cb47c8f-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:38:04,162 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.

Created job j-2610100738084f2cb00d7176ab9427e9: partition 17, batch 1, user esagovhub4@gmail.com.

2026-10-10 10:38:09,414 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\monthly_cubes\4f28ad2deccc84bb-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:38:09,803 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 10/112 for batch 1.
2026-10-10 10:38:10,144 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 20/112 for batch 1.
2026-10-10 10:38:10,469 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 30/112 for batch 1.
2026-10-10 10:38:10,809 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 40/112 for batch 1.
2026-10-10 10:38:11,135 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 50/112 for batch 1.
2026-10-10 10:38:11,459 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 60/112 for batch 1.
2026-10-10 10:38:11,794 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 70/112 for batch 1.
2026-10-10 10:38:12,147 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 80/112 for batch 1.
2026-10-10 10:38:12,494 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 90/112 for batch 1.
2026-10-10 10:38:12,834 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 100/112 for batch 1.
2026-10-10 10:38:13,169 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 110/112 for batch 1.
2026-10-10 10:38:13,244 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Stored observations 112/112 for batch 1.
2026-10-10 10:38:13,245 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 1/9 in strips of 56 rows.
2026-10-10 10:38:13,660 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 2/9 in strips of 56 rows.
2026-10-10 10:38:14,079 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 3/9 in strips of 56 rows.
2026-10-10 10:38:14,499 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 4/9 in strips of 56 rows.
2026-10-10 10:38:14,921 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 5/9 in strips of 56 rows.
2026-10-10 10:38:15,341 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 6/9 in strips of 56 rows.
2026-10-10 10:38:15,763 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 7/9 in strips of 56 rows.
2026-10-10 10:38:16,186 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 8/9 in strips of 56 rows.
2026-10-10 10:38:16,609 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Temporal filling band 9/9 in strips of 56 rows.
2026-10-10 10:38:17,066 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 1/112 for batch 1.
2026-10-10 10:38:17,082 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 2/112 for batch 1.
2026-10-10 10:38:17,099 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 3/112 for batch 1.
2026-10-10 10:38:17,121 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 4/112 for batch 1.
2026-10-10 10:38:17,138 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 5/112 for batch 1.
2026-10-10 10:38:17,154 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 6/112 for batch 1.
2026-10-10 10:38:17,170 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 7/112 for batch 1.
2026-10-10 10:38:17,188 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 8/112 for batch 1.
2026-10-10 10:38:17,203 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 9/112 for batch 1.
2026-10-10 10:38:17,219 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 10/112 for batch 1.
2026-10-10 10:38:17,237 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 11/112 for batch 1.
2026-10-10 10:38:17,254 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 12/112 for batch 1.
2026-10-10 10:38:17,269 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 13/112 for batch 1.
2026-10-10 10:38:17,285 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 14/112 for batch 1.
2026-10-10 10:38:17,300 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 15/112 for batch 1.
2026-10-10 10:38:17,316 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 16/112 for batch 1.
2026-10-10 10:38:17,412 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 17/112 for batch 1.
2026-10-10 10:38:17,429 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 18/112 for batch 1.
2026-10-10 10:38:17,452 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 19/112 for batch 1.
2026-10-10 10:38:17,472 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 20/112 for batch 1.
2026-10-10 10:38:17,491 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 21/112 for batch 1.
2026-10-10 10:38:17,511 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 22/112 for batch 1.
2026-10-10 10:38:17,537 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 23/112 for batch 1.
2026-10-10 10:38:17,557 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 24/112 for batch 1.
2026-10-10 10:38:17,581 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 25/112 for batch 1.
2026-10-10 10:38:17,600 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 26/112 for batch 1.
2026-10-10 10:38:17,624 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 27/112 for batch 1.
2026-10-10 10:38:17,766 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 28/112 for batch 1.
2026-10-10 10:38:17,793 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 29/112 for batch 1.
2026-10-10 10:38:17,821 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 30/112 for batch 1.
2026-10-10 10:38:17,856 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 31/112 for batch 1.
2026-10-10 10:38:17,876 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 32/112 for batch 1.
2026-10-10 10:38:17,897 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 33/112 for batch 1.
2026-10-10 10:38:17,920 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 34/112 for batch 1.
2026-10-10 10:38:17,940 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 35/112 for batch 1.
2026-10-10 10:38:17,961 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 36/112 for batch 1.
2026-10-10 10:38:17,984 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 37/112 for batch 1.
2026-10-10 10:38:18,006 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 38/112 for batch 1.
2026-10-10 10:38:18,029 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 39/112 for batch 1.
2026-10-10 10:38:18,067 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 40/112 for batch 1.
2026-10-10 10:38:18,202 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 41/112 for batch 1.
2026-10-10 10:38:18,219 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 42/112 for batch 1.
2026-10-10 10:38:18,235 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 43/112 for batch 1.
2026-10-10 10:38:18,336 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 44/112 for batch 1.
2026-10-10 10:38:18,351 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 45/112 for batch 1.
2026-10-10 10:38:18,454 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 46/112 for batch 1.
2026-10-10 10:38:18,547 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 47/112 for batch 1.
2026-10-10 10:38:18,562 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 48/112 for batch 1.
2026-10-10 10:38:18,580 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 49/112 for batch 1.
2026-10-10 10:38:18,596 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 50/112 for batch 1.
2026-10-10 10:38:18,612 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 51/112 for batch 1.
2026-10-10 10:38:18,627 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 52/112 for batch 1.
2026-10-10 10:38:18,643 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 53/112 for batch 1.
2026-10-10 10:38:18,660 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 54/112 for batch 1.
2026-10-10 10:38:18,676 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 55/112 for batch 1.
2026-10-10 10:38:18,692 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 56/112 for batch 1.
2026-10-10 10:38:18,708 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 57/112 for batch 1.
2026-10-10 10:38:18,723 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 58/112 for batch 1.
2026-10-10 10:38:18,738 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 59/112 for batch 1.
2026-10-10 10:38:18,754 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 60/112 for batch 1.
2026-10-10 10:38:18,770 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 61/112 for batch 1.
2026-10-10 10:38:18,785 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 62/112 for batch 1.
2026-10-10 10:38:18,801 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 63/112 for batch 1.
2026-10-10 10:38:18,817 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 64/112 for batch 1.
2026-10-10 10:38:18,835 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 65/112 for batch 1.
2026-10-10 10:38:18,853 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 66/112 for batch 1.
2026-10-10 10:38:18,871 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 67/112 for batch 1.
2026-10-10 10:38:18,888 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 68/112 for batch 1.
2026-10-10 10:38:18,903 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 69/112 for batch 1.
2026-10-10 10:38:18,919 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 70/112 for batch 1.
2026-10-10 10:38:18,934 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 71/112 for batch 1.
2026-10-10 10:38:18,950 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 72/112 for batch 1.
2026-10-10 10:38:18,965 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 73/112 for batch 1.
2026-10-10 10:38:18,980 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 74/112 for batch 1.
2026-10-10 10:38:19,006 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 75/112 for batch 1.
2026-10-10 10:38:19,026 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 76/112 for batch 1.
2026-10-10 10:38:19,042 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 77/112 for batch 1.
2026-10-10 10:38:19,058 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 78/112 for batch 1.
2026-10-10 10:38:19,077 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 79/112 for batch 1.
2026-10-10 10:38:19,093 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 80/112 for batch 1.
2026-10-10 10:38:19,108 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 81/112 for batch 1.
2026-10-10 10:38:19,126 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 82/112 for batch 1.
2026-10-10 10:38:19,142 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 83/112 for batch 1.
2026-10-10 10:38:19,157 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 84/112 for batch 1.
2026-10-10 10:38:19,173 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 85/112 for batch 1.
2026-10-10 10:38:19,199 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 86/112 for batch 1.
2026-10-10 10:38:19,215 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 87/112 for batch 1.
2026-10-10 10:38:19,233 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 88/112 for batch 1.
2026-10-10 10:38:19,249 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 89/112 for batch 1.
2026-10-10 10:38:19,266 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 90/112 for batch 1.
2026-10-10 10:38:19,281 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 91/112 for batch 1.
2026-10-10 10:38:19,299 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 92/112 for batch 1.
2026-10-10 10:38:19,316 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 93/112 for batch 1.
2026-10-10 10:38:19,331 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 94/112 for batch 1.
2026-10-10 10:38:19,349 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 95/112 for batch 1.
2026-10-10 10:38:19,366 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 96/112 for batch 1.
2026-10-10 10:38:19,382 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 97/112 for batch 1.
2026-10-10 10:38:19,397 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 98/112 for batch 1.
2026-10-10 10:38:19,412 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 99/112 for batch 1.
2026-10-10 10:38:19,427 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 100/112 for batch 1.
2026-10-10 10:38:19,442 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 101/112 for batch 1.
2026-10-10 10:38:19,458 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 102/112 for batch 1.
2026-10-10 10:38:19,473 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 103/112 for batch 1.
2026-10-10 10:38:19,489 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 104/112 for batch 1.
2026-10-10 10:38:19,504 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 105/112 for batch 1.
2026-10-10 10:38:19,521 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 106/112 for batch 1.
2026-10-10 10:38:19,538 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 107/112 for batch 1.
2026-10-10 10:38:19,555 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 108/112 for batch 1.
2026-10-10 10:38:19,570 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 109/112 for batch 1.
2026-10-10 10:38:19,586 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 110/112 for batch 1.
2026-10-10 10:38:19,602 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 111/112 for batch 1.
2026-10-10 10:38:19,617 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Cleaned acquisition 112/112 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_3/monthly_cubes/4f28ad2deccc84bb-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:38:20,009 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 10/112.
2026-10-10 10:38:20,292 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 20/112.
2026-10-10 10:38:20,581 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 30/112.
2026-10-10 10:38:20,865 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 40/112.
2026-10-10 10:38:21,149 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 50/112.
2026-10-10 10:38:21,442 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 60/112.
2026-10-10 10:38:21,711 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 70/112.
2026-10-10 10:38:21,982 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 80/112.
2026-10-10 10:38:22,264 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 90/112.
2026-10-10 10:38:22,552 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 100/112.
2026-10-10 10:38:22,814 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 110/112.
2026-10-10 10:38:22,868 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Saved output indices for acquisition 112/112.
2026-10-10 10:38:22,978 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\monthly_cubes\4f28ad2deccc84bb-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_3/monthly_cubes/4f28ad2deccc84bb-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:38:24,820 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 2 parcels from batch_00001_monthly.nc.

Created job j-26101007382840289b4f899c94ad0706: partition 18, batch 1, user esagovhub3@gmail.com.

2026-10-10 10:39:09,041 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\monthly_cubes\49caa5e9f75b6445-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:39:09,413 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 10/191 for batch 1.
2026-10-10 10:39:09,754 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 20/191 for batch 1.
2026-10-10 10:39:10,086 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 30/191 for batch 1.
2026-10-10 10:39:10,408 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 40/191 for batch 1.
2026-10-10 10:39:10,723 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 50/191 for batch 1.
2026-10-10 10:39:11,090 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 60/191 for batch 1.
2026-10-10 10:39:11,518 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 70/191 for batch 1.
2026-10-10 10:39:11,950 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 80/191 for batch 1.
2026-10-10 10:39:12,315 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 90/191 for batch 1.
2026-10-10 10:39:12,660 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 100/191 for batch 1.
2026-10-10 10:39:13,014 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 110/191 for batch 1.
2026-10-10 10:39:13,376 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 120/191 for batch 1.
2026-10-10 10:39:13,716 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 130/191 for batch 1.
2026-10-10 10:39:14,048 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 140/191 for batch 1.
2026-10-10 10:39:14,387 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 150/191 for batch 1.
2026-10-10 10:39:14,701 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 160/191 for batch 1.
2026-10-10 10:39:15,029 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 170/191 for batch 1.
2026-10-10 10:39:15,352 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 180/191 for batch 1.
2026-10-10 10:39:15,669 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 190/191 for batch 1.
2026-10-10 10:39:15,704 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Stored observations 191/191 for batch 1.
2026-10-10 10:39:15,704 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 1/9 in strips of 38 rows.
2026-10-10 10:39:16,398 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 2/9 in strips of 38 rows.
2026-10-10 10:39:17,116 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 3/9 in strips of 38 rows.
2026-10-10 10:39:17,945 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 4/9 in strips of 38 rows.
2026-10-10 10:39:18,666 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 5/9 in strips of 38 rows.
2026-10-10 10:39:19,424 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 6/9 in strips of 38 rows.
2026-10-10 10:39:20,181 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 7/9 in strips of 38 rows.
2026-10-10 10:39:20,956 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 8/9 in strips of 38 rows.
2026-10-10 10:39:21,758 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Temporal filling band 9/9 in strips of 38 rows.
2026-10-10 10:39:22,503 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 1/191 for batch 1.
2026-10-10 10:39:22,524 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 2/191 for batch 1.
2026-10-10 10:39:22,563 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 3/191 for batch 1.
2026-10-10 10:39:22,602 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 4/191 for batch 1.
2026-10-10 10:39:22,617 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 5/191 for batch 1.
2026-10-10 10:39:22,633 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 6/191 for batch 1.
2026-10-10 10:39:22,649 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 7/191 for batch 1.
2026-10-10 10:39:22,729 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 8/191 for batch 1.
2026-10-10 10:39:22,747 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 9/191 for batch 1.
2026-10-10 10:39:22,790 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 10/191 for batch 1.
2026-10-10 10:39:22,842 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 11/191 for batch 1.
2026-10-10 10:39:22,860 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 12/191 for batch 1.
2026-10-10 10:39:22,940 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 13/191 for batch 1.
2026-10-10 10:39:23,023 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 14/191 for batch 1.
2026-10-10 10:39:23,107 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 15/191 for batch 1.
2026-10-10 10:39:23,189 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 16/191 for batch 1.
2026-10-10 10:39:23,204 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 17/191 for batch 1.
2026-10-10 10:39:23,250 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 18/191 for batch 1.
2026-10-10 10:39:23,304 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 19/191 for batch 1.
2026-10-10 10:39:23,354 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 20/191 for batch 1.
2026-10-10 10:39:23,371 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 21/191 for batch 1.
2026-10-10 10:39:23,404 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 22/191 for batch 1.
2026-10-10 10:39:23,420 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 23/191 for batch 1.
2026-10-10 10:39:23,440 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 24/191 for batch 1.
2026-10-10 10:39:23,460 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 25/191 for batch 1.
2026-10-10 10:39:23,477 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 26/191 for batch 1.
2026-10-10 10:39:23,493 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 27/191 for batch 1.
2026-10-10 10:39:23,510 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 28/191 for batch 1.
2026-10-10 10:39:23,527 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 29/191 for batch 1.
2026-10-10 10:39:23,547 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 30/191 for batch 1.
2026-10-10 10:39:23,568 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 31/191 for batch 1.
2026-10-10 10:39:23,590 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 32/191 for batch 1.
2026-10-10 10:39:23,606 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 33/191 for batch 1.
2026-10-10 10:39:23,691 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 34/191 for batch 1.
2026-10-10 10:39:23,707 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 35/191 for batch 1.
2026-10-10 10:39:23,745 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 36/191 for batch 1.
2026-10-10 10:39:23,778 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 37/191 for batch 1.
2026-10-10 10:39:23,797 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 38/191 for batch 1.
2026-10-10 10:39:23,818 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 39/191 for batch 1.
2026-10-10 10:39:23,842 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 40/191 for batch 1.
2026-10-10 10:39:23,878 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 41/191 for batch 1.
2026-10-10 10:39:23,895 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 42/191 for batch 1.
2026-10-10 10:39:24,005 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 43/191 for batch 1.
2026-10-10 10:39:24,098 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 44/191 for batch 1.
2026-10-10 10:39:24,130 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 45/191 for batch 1.
2026-10-10 10:39:24,147 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 46/191 for batch 1.
2026-10-10 10:39:24,171 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 47/191 for batch 1.
2026-10-10 10:39:24,187 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 48/191 for batch 1.
2026-10-10 10:39:24,220 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 49/191 for batch 1.
2026-10-10 10:39:24,240 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 50/191 for batch 1.
2026-10-10 10:39:24,256 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 51/191 for batch 1.
2026-10-10 10:39:24,274 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 52/191 for batch 1.
2026-10-10 10:39:24,293 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 53/191 for batch 1.
2026-10-10 10:39:24,309 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 54/191 for batch 1.
2026-10-10 10:39:24,325 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 55/191 for batch 1.
2026-10-10 10:39:24,340 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 56/191 for batch 1.
2026-10-10 10:39:24,359 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 57/191 for batch 1.
2026-10-10 10:39:24,437 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 58/191 for batch 1.
2026-10-10 10:39:24,452 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 59/191 for batch 1.
2026-10-10 10:39:24,467 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 60/191 for batch 1.
2026-10-10 10:39:24,546 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 61/191 for batch 1.
2026-10-10 10:39:24,562 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 62/191 for batch 1.
2026-10-10 10:39:24,578 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 63/191 for batch 1.
2026-10-10 10:39:24,594 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 64/191 for batch 1.
2026-10-10 10:39:24,610 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 65/191 for batch 1.
2026-10-10 10:39:24,626 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 66/191 for batch 1.
2026-10-10 10:39:24,642 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 67/191 for batch 1.
2026-10-10 10:39:24,657 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 68/191 for batch 1.
2026-10-10 10:39:24,673 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 69/191 for batch 1.
2026-10-10 10:39:24,688 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 70/191 for batch 1.
2026-10-10 10:39:24,721 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 71/191 for batch 1.
2026-10-10 10:39:24,798 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 72/191 for batch 1.
2026-10-10 10:39:24,816 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 73/191 for batch 1.
2026-10-10 10:39:24,838 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 74/191 for batch 1.
2026-10-10 10:39:24,854 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 75/191 for batch 1.
2026-10-10 10:39:24,869 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 76/191 for batch 1.
2026-10-10 10:39:24,884 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 77/191 for batch 1.
2026-10-10 10:39:24,926 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 78/191 for batch 1.
2026-10-10 10:39:24,964 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 79/191 for batch 1.
2026-10-10 10:39:24,982 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 80/191 for batch 1.
2026-10-10 10:39:24,998 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 81/191 for batch 1.
2026-10-10 10:39:25,012 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 82/191 for batch 1.
2026-10-10 10:39:25,027 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 83/191 for batch 1.
2026-10-10 10:39:25,045 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 84/191 for batch 1.
2026-10-10 10:39:25,063 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 85/191 for batch 1.
2026-10-10 10:39:25,078 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 86/191 for batch 1.
2026-10-10 10:39:25,093 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 87/191 for batch 1.
2026-10-10 10:39:25,111 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 88/191 for batch 1.
2026-10-10 10:39:25,188 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 89/191 for batch 1.
2026-10-10 10:39:25,269 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 90/191 for batch 1.
2026-10-10 10:39:25,287 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 91/191 for batch 1.
2026-10-10 10:39:25,304 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 92/191 for batch 1.
2026-10-10 10:39:25,319 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 93/191 for batch 1.
2026-10-10 10:39:25,343 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 94/191 for batch 1.
2026-10-10 10:39:25,363 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 95/191 for batch 1.
2026-10-10 10:39:25,379 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 96/191 for batch 1.
2026-10-10 10:39:25,409 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 97/191 for batch 1.
2026-10-10 10:39:25,427 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 98/191 for batch 1.
2026-10-10 10:39:25,464 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 99/191 for batch 1.
2026-10-10 10:39:25,501 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 100/191 for batch 1.
2026-10-10 10:39:25,555 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 101/191 for batch 1.
2026-10-10 10:39:25,575 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 102/191 for batch 1.
2026-10-10 10:39:25,594 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 103/191 for batch 1.
2026-10-10 10:39:25,654 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 104/191 for batch 1.
2026-10-10 10:39:25,714 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 105/191 for batch 1.
2026-10-10 10:39:25,732 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 106/191 for batch 1.
2026-10-10 10:39:25,774 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 107/191 for batch 1.
2026-10-10 10:39:25,789 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 108/191 for batch 1.
2026-10-10 10:39:25,804 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 109/191 for batch 1.
2026-10-10 10:39:25,822 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 110/191 for batch 1.
2026-10-10 10:39:25,837 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 111/191 for batch 1.
2026-10-10 10:39:25,853 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 112/191 for batch 1.
2026-10-10 10:39:25,869 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 113/191 for batch 1.
2026-10-10 10:39:25,889 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 114/191 for batch 1.
2026-10-10 10:39:25,961 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 115/191 for batch 1.
2026-10-10 10:39:25,998 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 116/191 for batch 1.
2026-10-10 10:39:26,041 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 117/191 for batch 1.
2026-10-10 10:39:26,060 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 118/191 for batch 1.
2026-10-10 10:39:26,099 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 119/191 for batch 1.
2026-10-10 10:39:26,141 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 120/191 for batch 1.
2026-10-10 10:39:26,210 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 121/191 for batch 1.
2026-10-10 10:39:26,231 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Cleaned acquisition 122/191 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_11/monthly_cubes/49caa5e9f75b6445-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:39:28,562 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 10/191.
2026-10-10 10:39:28,829 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 20/191.
2026-10-10 10:39:29,099 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 30/191.
2026-10-10 10:39:29,364 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 40/191.
2026-10-10 10:39:29,626 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 50/191.
2026-10-10 10:39:29,893 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 60/191.
2026-10-10 10:39:30,148 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 70/191.
2026-10-10 10:39:30,401 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 80/191.
2026-10-10 10:39:30,646 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 90/191.
2026-10-10 10:39:30,908 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 100/191.
2026-10-10 10:39:31,149 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 110/191.
2026-10-10 10:39:31,400 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 120/191.
2026-10-10 10:39:31,646 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 130/191.
2026-10-10 10:39:31,889 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 140/191.
2026-10-10 10:39:32,154 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 150/191.
2026-10-10 10:39:32,408 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 160/191.
2026-10-10 10:39:32,655 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 170/191.
2026-10-10 10:39:32,942 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 180/191.
2026-10-10 10:39:33,276 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 190/191.
2026-10-10 10:39:33,307 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Saved output indices for acquisition 191/191.
2026-10-10 10:39:33,660 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\monthly_cubes\49caa5e9f75b6445-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_11/monthly_cubes/49caa5e9f75b6445-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:39:34,672 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.
2026-10-10 10:39:35,231 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\monthly_cubes\8f5302aa8dca676f-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:39:35,596 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 10/145 for batch 1.
2026-10-10 10:39:35,917 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 20/145 for batch 1.
2026-10-10 10:39:36,253 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 30/145 for batch 1.
2026-10-10 10:39:36,575 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 40/145 for batch 1.
2026-10-10 10:39:36,909 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 50/145 for batch 1.
2026-10-10 10:39:37,238 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 60/145 for batch 1.
2026-10-10 10:39:37,563 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 70/145 for batch 1.

Created job j-2610100739384510883b12ccd3535f2b: partition 19, batch 1, user louvarieleni@gmail.com.

2026-10-10 10:39:37,898 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 80/145 for batch 1.
2026-10-10 10:39:38,220 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 90/145 for batch 1.
2026-10-10 10:39:38,560 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 100/145 for batch 1.
2026-10-10 10:39:38,884 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 110/145 for batch 1.
2026-10-10 10:39:39,207 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 120/145 for batch 1.
2026-10-10 10:39:39,527 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 130/145 for batch 1.
2026-10-10 10:39:39,839 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 140/145 for batch 1.
2026-10-10 10:39:40,000 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Stored observations 145/145 for batch 1.
2026-10-10 10:39:40,001 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 1/9 in strips of 50 rows.
2026-10-10 10:39:40,490 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 2/9 in strips of 50 rows.
2026-10-10 10:39:40,982 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 3/9 in strips of 50 rows.
2026-10-10 10:39:41,466 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 4/9 in strips of 50 rows.
2026-10-10 10:39:41,945 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 5/9 in strips of 50 rows.
2026-10-10 10:39:42,431 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 6/9 in strips of 50 rows.
2026-10-10 10:39:42,908 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 7/9 in strips of 50 rows.
2026-10-10 10:39:43,397 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 8/9 in strips of 50 rows.
2026-10-10 10:39:43,878 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Temporal filling band 9/9 in strips of 50 rows.
2026-10-10 10:39:44,387 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 1/145 for batch 1.
2026-10-10 10:39:44,403 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 2/145 for batch 1.
2026-10-10 10:39:44,483 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 3/145 for batch 1.
2026-10-10 10:39:44,498 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 4/145 for batch 1.
2026-10-10 10:39:44,514 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 5/145 for batch 1.
2026-10-10 10:39:44,530 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 6/145 for batch 1.
2026-10-10 10:39:44,545 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 7/145 for batch 1.
2026-10-10 10:39:44,560 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 8/145 for batch 1.
2026-10-10 10:39:44,576 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 9/145 for batch 1.
2026-10-10 10:39:44,592 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 10/145 for batch 1.
2026-10-10 10:39:44,607 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 11/145 for batch 1.
2026-10-10 10:39:44,622 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 12/145 for batch 1.
2026-10-10 10:39:44,638 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 13/145 for batch 1.
2026-10-10 10:39:44,653 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 14/145 for batch 1.
2026-10-10 10:39:44,669 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 15/145 for batch 1.
2026-10-10 10:39:44,684 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 16/145 for batch 1.
2026-10-10 10:39:44,706 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 17/145 for batch 1.
2026-10-10 10:39:44,722 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 18/145 for batch 1.
2026-10-10 10:39:44,737 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 19/145 for batch 1.
2026-10-10 10:39:44,756 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 20/145 for batch 1.
2026-10-10 10:39:44,837 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 21/145 for batch 1.
2026-10-10 10:39:44,853 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 22/145 for batch 1.
2026-10-10 10:39:44,868 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 23/145 for batch 1.
2026-10-10 10:39:44,884 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 24/145 for batch 1.
2026-10-10 10:39:44,900 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 25/145 for batch 1.
2026-10-10 10:39:44,915 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 26/145 for batch 1.
2026-10-10 10:39:44,932 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 27/145 for batch 1.
2026-10-10 10:39:44,947 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 28/145 for batch 1.
2026-10-10 10:39:44,963 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 29/145 for batch 1.
2026-10-10 10:39:44,979 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 30/145 for batch 1.
2026-10-10 10:39:44,994 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 31/145 for batch 1.
2026-10-10 10:39:45,056 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 32/145 for batch 1.
2026-10-10 10:39:45,117 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 33/145 for batch 1.
2026-10-10 10:39:45,136 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 34/145 for batch 1.
2026-10-10 10:39:45,152 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 35/145 for batch 1.
2026-10-10 10:39:45,186 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 36/145 for batch 1.
2026-10-10 10:39:45,210 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 37/145 for batch 1.
2026-10-10 10:39:45,238 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 38/145 for batch 1.
2026-10-10 10:39:45,256 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 39/145 for batch 1.
2026-10-10 10:39:45,278 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 40/145 for batch 1.
2026-10-10 10:39:45,296 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 41/145 for batch 1.
2026-10-10 10:39:45,317 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 42/145 for batch 1.
2026-10-10 10:39:45,396 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 43/145 for batch 1.
2026-10-10 10:39:45,474 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 44/145 for batch 1.
2026-10-10 10:39:45,490 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 45/145 for batch 1.
2026-10-10 10:39:45,507 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 46/145 for batch 1.
2026-10-10 10:39:45,523 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 47/145 for batch 1.
2026-10-10 10:39:45,540 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 48/145 for batch 1.
2026-10-10 10:39:45,556 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 49/145 for batch 1.
2026-10-10 10:39:45,572 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 50/145 for batch 1.
2026-10-10 10:39:45,588 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 51/145 for batch 1.
2026-10-10 10:39:45,605 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 52/145 for batch 1.
2026-10-10 10:39:45,685 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 53/145 for batch 1.
2026-10-10 10:39:45,701 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 54/145 for batch 1.
2026-10-10 10:39:45,717 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 55/145 for batch 1.
2026-10-10 10:39:45,733 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 56/145 for batch 1.
2026-10-10 10:39:45,748 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 57/145 for batch 1.
2026-10-10 10:39:45,764 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 58/145 for batch 1.
2026-10-10 10:39:45,779 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 59/145 for batch 1.
2026-10-10 10:39:45,795 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 60/145 for batch 1.
2026-10-10 10:39:45,810 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 61/145 for batch 1.
2026-10-10 10:39:45,826 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 62/145 for batch 1.
2026-10-10 10:39:45,841 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 63/145 for batch 1.
2026-10-10 10:39:45,856 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 64/145 for batch 1.
2026-10-10 10:39:45,872 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 65/145 for batch 1.
2026-10-10 10:39:45,889 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 66/145 for batch 1.
2026-10-10 10:39:45,908 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 67/145 for batch 1.
2026-10-10 10:39:45,929 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 68/145 for batch 1.
2026-10-10 10:39:45,947 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 69/145 for batch 1.
2026-10-10 10:39:45,965 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 70/145 for batch 1.
2026-10-10 10:39:45,984 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 71/145 for batch 1.
2026-10-10 10:39:46,050 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 72/145 for batch 1.
2026-10-10 10:39:46,065 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 73/145 for batch 1.
2026-10-10 10:39:46,080 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 74/145 for batch 1.
2026-10-10 10:39:46,159 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 75/145 for batch 1.
2026-10-10 10:39:46,174 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 76/145 for batch 1.
2026-10-10 10:39:46,189 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 77/145 for batch 1.
2026-10-10 10:39:46,205 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 78/145 for batch 1.
2026-10-10 10:39:46,220 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 79/145 for batch 1.
2026-10-10 10:39:46,235 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 80/145 for batch 1.
2026-10-10 10:39:46,251 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 81/145 for batch 1.
2026-10-10 10:39:46,266 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 82/145 for batch 1.
2026-10-10 10:39:46,282 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 83/145 for batch 1.
2026-10-10 10:39:46,297 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 84/145 for batch 1.
2026-10-10 10:39:46,313 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 85/145 for batch 1.
2026-10-10 10:39:46,328 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 86/145 for batch 1.
2026-10-10 10:39:46,345 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 87/145 for batch 1.
2026-10-10 10:39:46,360 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 88/145 for batch 1.
2026-10-10 10:39:46,377 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 89/145 for batch 1.
2026-10-10 10:39:46,392 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 90/145 for batch 1.
2026-10-10 10:39:46,409 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 91/145 for batch 1.
2026-10-10 10:39:46,426 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 92/145 for batch 1.
2026-10-10 10:39:46,443 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 93/145 for batch 1.
2026-10-10 10:39:46,459 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 94/145 for batch 1.
2026-10-10 10:39:46,538 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 95/145 for batch 1.
2026-10-10 10:39:46,553 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 96/145 for batch 1.
2026-10-10 10:39:46,568 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 97/145 for batch 1.
2026-10-10 10:39:46,583 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 98/145 for batch 1.
2026-10-10 10:39:46,599 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 99/145 for batch 1.
2026-10-10 10:39:46,614 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 100/145 for batch 1.
2026-10-10 10:39:46,631 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 101/145 for batch 1.
2026-10-10 10:39:46,646 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 102/145 for batch 1.
2026-10-10 10:39:46,662 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 103/145 for batch 1.
2026-10-10 10:39:46,677 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 104/145 for batch 1.
2026-10-10 10:39:46,693 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 105/145 for batch 1.
2026-10-10 10:39:46,710 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 106/145 for batch 1.
2026-10-10 10:39:46,792 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 107/145 for batch 1.
2026-10-10 10:39:46,809 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 108/145 for batch 1.
2026-10-10 10:39:46,889 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 109/145 for batch 1.
2026-10-10 10:39:46,904 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 110/145 for batch 1.
2026-10-10 10:39:46,919 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 111/145 for batch 1.
2026-10-10 10:39:46,934 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 112/145 for batch 1.
2026-10-10 10:39:46,950 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 113/145 for batch 1.
2026-10-10 10:39:46,966 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 114/145 for batch 1.
2026-10-10 10:39:46,981 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 115/145 for batch 1.
2026-10-10 10:39:46,996 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 116/145 for batch 1.
2026-10-10 10:39:47,011 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 117/145 for batch 1.
2026-10-10 10:39:47,030 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 118/145 for batch 1.
2026-10-10 10:39:47,056 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 119/145 for batch 1.
2026-10-10 10:39:47,079 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 120/145 for batch 1.
2026-10-10 10:39:47,096 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 121/145 for batch 1.
2026-10-10 10:39:47,110 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 122/145 for batch 1.
2026-10-10 10:39:47,193 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 123/145 for batch 1.
2026-10-10 10:39:47,208 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 124/145 for batch 1.
2026-10-10 10:39:47,222 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 125/145 for batch 1.
2026-10-10 10:39:47,237 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 126/145 for batch 1.
2026-10-10 10:39:47,251 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 127/145 for batch 1.
2026-10-10 10:39:47,267 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 128/145 for batch 1.
2026-10-10 10:39:47,282 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 129/145 for batch 1.
2026-10-10 10:39:47,297 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 130/145 for batch 1.
2026-10-10 10:39:47,312 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 131/145 for batch 1.
2026-10-10 10:39:47,328 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 132/145 for batch 1.
2026-10-10 10:39:47,342 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 133/145 for batch 1.
2026-10-10 10:39:47,356 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 134/145 for batch 1.
2026-10-10 10:39:47,371 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 135/145 for batch 1.
2026-10-10 10:39:47,385 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Cleaned acquisition 136/145 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_10/monthly_cubes/8f5302aa8dca676f-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:39:47,881 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 10/145.
2026-10-10 10:39:48,155 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 20/145.
2026-10-10 10:39:48,430 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 30/145.
2026-10-10 10:39:48,695 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 40/145.
2026-10-10 10:39:48,977 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 50/145.
2026-10-10 10:39:49,238 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 60/145.
2026-10-10 10:39:49,490 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 70/145.
2026-10-10 10:39:49,750 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 80/145.
2026-10-10 10:39:50,459 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 90/145.
2026-10-10 10:39:50,836 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 100/145.
2026-10-10 10:39:51,087 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 110/145.
2026-10-10 10:39:51,345 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 120/145.
2026-10-10 10:39:51,611 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 130/145.
2026-10-10 10:39:51,982 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 140/145.
2026-10-10 10:39:52,104 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Saved output indices for acquisition 145/145.
2026-10-10 10:39:52,243 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\monthly_cubes\8f5302aa8dca676f-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_10/monthly_cubes/8f5302aa8dca676f-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:39:53,169 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00001_monthly.nc.

Created job j-2610100739564e009b78cb45e5810365: partition 20, batch 1, user louvarieleni@gmail.com.

2026-10-10 10:43:39,541 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\monthly_cubes\cfb44e2e2f8823a5-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:43:39,949 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 10/167 for batch 1.
2026-10-10 10:43:40,278 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 20/167 for batch 1.
2026-10-10 10:43:40,601 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 30/167 for batch 1.
2026-10-10 10:43:40,967 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 40/167 for batch 1.
2026-10-10 10:43:41,289 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 50/167 for batch 1.
2026-10-10 10:43:41,613 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 60/167 for batch 1.
2026-10-10 10:43:41,953 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 70/167 for batch 1.
2026-10-10 10:43:42,294 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 80/167 for batch 1.
2026-10-10 10:43:42,625 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 90/167 for batch 1.
2026-10-10 10:43:42,983 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 100/167 for batch 1.
2026-10-10 10:43:43,342 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 110/167 for batch 1.
2026-10-10 10:43:43,701 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 120/167 for batch 1.
2026-10-10 10:43:44,066 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 130/167 for batch 1.
2026-10-10 10:43:44,417 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 140/167 for batch 1.
2026-10-10 10:43:44,787 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 150/167 for batch 1.
2026-10-10 10:43:45,145 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 160/167 for batch 1.
2026-10-10 10:43:45,397 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Stored observations 167/167 for batch 1.
2026-10-10 10:43:45,398 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 1/9 in strips of 35 rows.
2026-10-10 10:43:46,163 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 2/9 in strips of 35 rows.
2026-10-10 10:43:46,949 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 3/9 in strips of 35 rows.
2026-10-10 10:43:47,740 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 4/9 in strips of 35 rows.
2026-10-10 10:43:48,535 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 5/9 in strips of 35 rows.
2026-10-10 10:43:49,337 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 6/9 in strips of 35 rows.
2026-10-10 10:43:50,131 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 7/9 in strips of 35 rows.
2026-10-10 10:43:50,924 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 8/9 in strips of 35 rows.
2026-10-10 10:43:51,701 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Temporal filling band 9/9 in strips of 35 rows.
2026-10-10 10:43:52,512 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 1/167 for batch 1.
2026-10-10 10:43:52,528 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 2/167 for batch 1.
2026-10-10 10:43:52,545 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 3/167 for batch 1.
2026-10-10 10:43:52,563 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 4/167 for batch 1.
2026-10-10 10:43:52,580 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 5/167 for batch 1.
2026-10-10 10:43:52,597 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 6/167 for batch 1.
2026-10-10 10:43:52,708 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 7/167 for batch 1.
2026-10-10 10:43:52,822 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 8/167 for batch 1.
2026-10-10 10:43:52,841 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 9/167 for batch 1.
2026-10-10 10:43:52,958 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 10/167 for batch 1.
2026-10-10 10:43:52,974 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 11/167 for batch 1.
2026-10-10 10:43:52,990 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 12/167 for batch 1.
2026-10-10 10:43:53,007 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 13/167 for batch 1.
2026-10-10 10:43:53,028 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 14/167 for batch 1.
2026-10-10 10:43:53,047 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 15/167 for batch 1.
2026-10-10 10:43:53,063 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 16/167 for batch 1.
2026-10-10 10:43:53,080 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 17/167 for batch 1.
2026-10-10 10:43:53,098 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 18/167 for batch 1.
2026-10-10 10:43:53,115 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 19/167 for batch 1.
2026-10-10 10:43:53,132 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 20/167 for batch 1.
2026-10-10 10:43:53,150 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 21/167 for batch 1.
2026-10-10 10:43:53,174 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 22/167 for batch 1.
2026-10-10 10:43:53,190 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 23/167 for batch 1.
2026-10-10 10:43:53,209 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 24/167 for batch 1.
2026-10-10 10:43:53,225 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 25/167 for batch 1.
2026-10-10 10:43:53,242 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 26/167 for batch 1.
2026-10-10 10:43:53,259 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 27/167 for batch 1.
2026-10-10 10:43:53,275 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 28/167 for batch 1.
2026-10-10 10:43:53,294 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 29/167 for batch 1.
2026-10-10 10:43:53,310 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 30/167 for batch 1.
2026-10-10 10:43:53,326 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 31/167 for batch 1.
2026-10-10 10:43:53,342 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 32/167 for batch 1.
2026-10-10 10:43:53,358 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 33/167 for batch 1.
2026-10-10 10:43:53,373 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 34/167 for batch 1.
2026-10-10 10:43:53,485 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 35/167 for batch 1.
2026-10-10 10:43:53,576 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 36/167 for batch 1.
2026-10-10 10:43:53,685 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 37/167 for batch 1.
2026-10-10 10:43:53,701 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 38/167 for batch 1.
2026-10-10 10:43:53,718 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 39/167 for batch 1.
2026-10-10 10:43:53,735 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 40/167 for batch 1.
2026-10-10 10:43:53,751 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 41/167 for batch 1.
2026-10-10 10:43:53,766 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 42/167 for batch 1.
2026-10-10 10:43:53,782 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 43/167 for batch 1.
2026-10-10 10:43:53,799 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 44/167 for batch 1.
2026-10-10 10:43:53,814 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 45/167 for batch 1.
2026-10-10 10:43:53,831 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 46/167 for batch 1.
2026-10-10 10:43:53,847 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 47/167 for batch 1.
2026-10-10 10:43:53,864 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 48/167 for batch 1.
2026-10-10 10:43:53,880 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 49/167 for batch 1.
2026-10-10 10:43:53,896 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 50/167 for batch 1.
2026-10-10 10:43:53,913 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 51/167 for batch 1.
2026-10-10 10:43:54,025 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 52/167 for batch 1.
2026-10-10 10:43:54,041 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 53/167 for batch 1.
2026-10-10 10:43:54,091 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 54/167 for batch 1.
2026-10-10 10:43:54,108 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 55/167 for batch 1.
2026-10-10 10:43:54,124 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 56/167 for batch 1.
2026-10-10 10:43:54,141 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 57/167 for batch 1.
2026-10-10 10:43:54,157 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 58/167 for batch 1.
2026-10-10 10:43:54,173 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 59/167 for batch 1.
2026-10-10 10:43:54,189 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 60/167 for batch 1.
2026-10-10 10:43:54,301 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 61/167 for batch 1.
2026-10-10 10:43:54,411 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 62/167 for batch 1.
2026-10-10 10:43:54,427 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 63/167 for batch 1.
2026-10-10 10:43:54,444 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 64/167 for batch 1.
2026-10-10 10:43:54,460 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 65/167 for batch 1.
2026-10-10 10:43:54,477 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 66/167 for batch 1.
2026-10-10 10:43:54,588 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 67/167 for batch 1.
2026-10-10 10:43:54,604 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 68/167 for batch 1.
2026-10-10 10:43:54,620 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 69/167 for batch 1.
2026-10-10 10:43:54,637 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 70/167 for batch 1.
2026-10-10 10:43:54,653 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 71/167 for batch 1.
2026-10-10 10:43:54,737 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 72/167 for batch 1.
2026-10-10 10:43:54,753 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 73/167 for batch 1.
2026-10-10 10:43:54,801 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 74/167 for batch 1.
2026-10-10 10:43:54,817 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 75/167 for batch 1.
2026-10-10 10:43:54,833 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 76/167 for batch 1.
2026-10-10 10:43:54,848 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 77/167 for batch 1.
2026-10-10 10:43:54,958 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 78/167 for batch 1.
2026-10-10 10:43:54,974 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 79/167 for batch 1.
2026-10-10 10:43:54,990 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 80/167 for batch 1.
2026-10-10 10:43:55,007 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 81/167 for batch 1.
2026-10-10 10:43:55,023 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 82/167 for batch 1.
2026-10-10 10:43:55,039 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 83/167 for batch 1.
2026-10-10 10:43:55,054 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 84/167 for batch 1.
2026-10-10 10:43:55,070 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 85/167 for batch 1.
2026-10-10 10:43:55,183 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 86/167 for batch 1.
2026-10-10 10:43:55,198 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 87/167 for batch 1.
2026-10-10 10:43:55,216 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 88/167 for batch 1.
2026-10-10 10:43:55,232 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 89/167 for batch 1.
2026-10-10 10:43:55,248 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 90/167 for batch 1.
2026-10-10 10:43:55,263 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 91/167 for batch 1.
2026-10-10 10:43:55,375 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 92/167 for batch 1.
2026-10-10 10:43:55,402 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 93/167 for batch 1.
2026-10-10 10:43:55,418 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 94/167 for batch 1.
2026-10-10 10:43:55,434 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 95/167 for batch 1.
2026-10-10 10:43:55,458 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 96/167 for batch 1.
2026-10-10 10:43:55,473 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 97/167 for batch 1.
2026-10-10 10:43:55,489 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 98/167 for batch 1.
2026-10-10 10:43:55,504 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 99/167 for batch 1.
2026-10-10 10:43:55,520 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 100/167 for batch 1.
2026-10-10 10:43:55,535 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 101/167 for batch 1.
2026-10-10 10:43:55,552 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 102/167 for batch 1.
2026-10-10 10:43:55,577 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 103/167 for batch 1.
2026-10-10 10:43:55,599 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 104/167 for batch 1.
2026-10-10 10:43:55,615 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 105/167 for batch 1.
2026-10-10 10:43:55,629 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 106/167 for batch 1.
2026-10-10 10:43:55,645 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 107/167 for batch 1.
2026-10-10 10:43:55,660 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 108/167 for batch 1.
2026-10-10 10:43:55,675 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 109/167 for batch 1.
2026-10-10 10:43:55,691 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 110/167 for batch 1.
2026-10-10 10:43:55,707 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 111/167 for batch 1.
2026-10-10 10:43:55,723 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 112/167 for batch 1.
2026-10-10 10:43:55,741 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 113/167 for batch 1.
2026-10-10 10:43:55,757 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 114/167 for batch 1.
2026-10-10 10:43:55,772 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 115/167 for batch 1.
2026-10-10 10:43:55,788 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 116/167 for batch 1.
2026-10-10 10:43:55,803 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 117/167 for batch 1.
2026-10-10 10:43:55,819 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 118/167 for batch 1.
2026-10-10 10:43:55,834 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 119/167 for batch 1.
2026-10-10 10:43:55,860 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 120/167 for batch 1.
2026-10-10 10:43:55,875 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 121/167 for batch 1.
2026-10-10 10:43:55,891 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 122/167 for batch 1.
2026-10-10 10:43:55,907 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 123/167 for batch 1.
2026-10-10 10:43:55,923 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 124/167 for batch 1.
2026-10-10 10:43:55,939 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Cleaned acquisition 125/167 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_2/monthly_cubes/cfb44e2e2f8823a5-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:43:57,131 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 10/167.
2026-10-10 10:43:57,450 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 20/167.
2026-10-10 10:43:57,757 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 30/167.
2026-10-10 10:43:58,065 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 40/167.
2026-10-10 10:43:58,363 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 50/167.
2026-10-10 10:43:58,682 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 60/167.
2026-10-10 10:43:58,990 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 70/167.
2026-10-10 10:43:59,290 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 80/167.
2026-10-10 10:43:59,576 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 90/167.
2026-10-10 10:43:59,854 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 100/167.
2026-10-10 10:44:00,138 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 110/167.
2026-10-10 10:44:00,425 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 120/167.
2026-10-10 10:44:00,703 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 130/167.
2026-10-10 10:44:00,980 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 140/167.
2026-10-10 10:44:01,264 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 150/167.
2026-10-10 10:44:01,560 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 160/167.
2026-10-10 10:44:01,767 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Saved output indices for acquisition 167/167.
2026-10-10 10:44:02,203 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\monthly_cubes\cfb44e2e2f8823a5-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_2/monthly_cubes/cfb44e2e2f8823a5-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:44:05,032 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 3 parcels from batch_00001_monthly.nc.
2026-10-10 10:44:05,592 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00003_monthly.nc.
2026-10-10 10:44:06,566 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 10/156 for batch 3.
2026-10-10 10:44:07,508 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 20/156 for batch 3.

Created job j-2610100744084dc4832273d3afe6150a: partition 20, batch 2, user esagovhub3@gmail.com.

2026-10-10 10:44:08,411 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 30/156 for batch 3.
2026-10-10 10:44:09,295 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 40/156 for batch 3.
2026-10-10 10:44:10,179 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 50/156 for batch 3.
2026-10-10 10:44:11,101 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 60/156 for batch 3.
2026-10-10 10:44:11,993 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 70/156 for batch 3.
2026-10-10 10:44:12,897 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 80/156 for batch 3.
2026-10-10 10:44:13,826 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 90/156 for batch 3.
2026-10-10 10:44:14,736 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 100/156 for batch 3.
2026-10-10 10:44:15,691 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 110/156 for batch 3.
2026-10-10 10:44:16,678 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 120/156 for batch 3.
2026-10-10 10:44:17,623 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 130/156 for batch 3.
2026-10-10 10:44:18,582 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 140/156 for batch 3.
2026-10-10 10:44:19,536 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 150/156 for batch 3.
2026-10-10 10:44:20,094 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 156/156 for batch 3.
2026-10-10 10:44:20,094 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 1/9 in strips of 18 rows.
2026-10-10 10:44:23,415 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 2/9 in strips of 18 rows.
2026-10-10 10:44:26,777 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 3/9 in strips of 18 rows.
2026-10-10 10:44:30,177 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 4/9 in strips of 18 rows.
2026-10-10 10:44:33,646 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 5/9 in strips of 18 rows.
2026-10-10 10:44:37,001 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 6/9 in strips of 18 rows.
2026-10-10 10:44:40,338 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 7/9 in strips of 18 rows.
2026-10-10 10:44:43,714 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 8/9 in strips of 18 rows.
2026-10-10 10:44:46,983 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 9/9 in strips of 18 rows.
2026-10-10 10:44:50,353 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 1/156 for batch 3.
2026-10-10 10:44:50,403 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 2/156 for batch 3.
2026-10-10 10:44:50,452 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 3/156 for batch 3.
2026-10-10 10:44:50,508 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 4/156 for batch 3.
2026-10-10 10:44:50,556 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 5/156 for batch 3.
2026-10-10 10:44:50,603 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 6/156 for batch 3.
2026-10-10 10:44:50,653 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 7/156 for batch 3.
2026-10-10 10:44:51,144 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 8/156 for batch 3.
2026-10-10 10:44:51,200 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 9/156 for batch 3.
2026-10-10 10:44:51,712 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 10/156 for batch 3.
2026-10-10 10:44:52,209 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 11/156 for batch 3.
2026-10-10 10:44:52,259 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 12/156 for batch 3.
2026-10-10 10:44:52,306 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 13/156 for batch 3.
2026-10-10 10:44:52,817 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 14/156 for batch 3.
2026-10-10 10:44:53,317 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 15/156 for batch 3.
2026-10-10 10:44:53,821 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 16/156 for batch 3.
2026-10-10 10:44:54,320 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 17/156 for batch 3.
2026-10-10 10:44:54,368 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 18/156 for batch 3.
2026-10-10 10:44:54,416 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 19/156 for batch 3.
2026-10-10 10:44:54,904 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 20/156 for batch 3.
2026-10-10 10:44:55,398 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 21/156 for batch 3.
2026-10-10 10:44:55,455 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 22/156 for batch 3.
2026-10-10 10:44:55,503 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 23/156 for batch 3.
2026-10-10 10:44:55,551 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 24/156 for batch 3.
2026-10-10 10:44:56,048 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 25/156 for batch 3.
2026-10-10 10:44:56,104 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 26/156 for batch 3.
2026-10-10 10:44:56,159 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 27/156 for batch 3.
2026-10-10 10:44:56,207 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 28/156 for batch 3.
2026-10-10 10:44:56,254 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 29/156 for batch 3.
2026-10-10 10:44:56,311 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 30/156 for batch 3.
2026-10-10 10:44:56,360 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 31/156 for batch 3.
2026-10-10 10:44:56,415 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 32/156 for batch 3.
2026-10-10 10:44:56,466 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 33/156 for batch 3.
2026-10-10 10:44:56,514 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 34/156 for batch 3.
2026-10-10 10:44:56,571 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 35/156 for batch 3.
2026-10-10 10:44:56,620 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 36/156 for batch 3.
2026-10-10 10:44:56,673 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 37/156 for batch 3.
2026-10-10 10:44:56,722 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 38/156 for batch 3.
2026-10-10 10:44:56,780 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 39/156 for batch 3.
2026-10-10 10:44:56,830 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 40/156 for batch 3.
2026-10-10 10:44:56,878 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 41/156 for batch 3.
2026-10-10 10:44:56,927 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 42/156 for batch 3.
2026-10-10 10:44:56,976 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 43/156 for batch 3.
2026-10-10 10:44:57,033 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 44/156 for batch 3.
2026-10-10 10:44:57,082 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 45/156 for batch 3.
2026-10-10 10:44:57,578 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 46/156 for batch 3.
2026-10-10 10:44:57,634 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 47/156 for batch 3.
2026-10-10 10:44:58,143 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 48/156 for batch 3.
2026-10-10 10:44:58,212 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 49/156 for batch 3.
2026-10-10 10:44:58,259 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 50/156 for batch 3.
2026-10-10 10:44:58,307 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 51/156 for batch 3.
2026-10-10 10:44:58,353 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 52/156 for batch 3.
2026-10-10 10:44:58,409 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 53/156 for batch 3.
2026-10-10 10:44:58,454 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 54/156 for batch 3.
2026-10-10 10:44:58,501 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 55/156 for batch 3.
2026-10-10 10:44:58,548 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 56/156 for batch 3.
2026-10-10 10:44:59,066 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 57/156 for batch 3.
2026-10-10 10:44:59,121 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 58/156 for batch 3.
2026-10-10 10:44:59,168 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 59/156 for batch 3.
2026-10-10 10:44:59,214 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 60/156 for batch 3.
2026-10-10 10:44:59,261 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 61/156 for batch 3.
2026-10-10 10:44:59,308 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 62/156 for batch 3.
2026-10-10 10:44:59,811 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 63/156 for batch 3.
2026-10-10 10:44:59,868 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 64/156 for batch 3.
2026-10-10 10:44:59,915 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 65/156 for batch 3.
2026-10-10 10:44:59,960 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 66/156 for batch 3.
2026-10-10 10:45:00,019 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 67/156 for batch 3.
2026-10-10 10:45:00,508 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 68/156 for batch 3.
2026-10-10 10:45:01,002 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 69/156 for batch 3.
2026-10-10 10:45:01,058 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 70/156 for batch 3.
2026-10-10 10:45:01,548 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 71/156 for batch 3.
2026-10-10 10:45:02,046 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 72/156 for batch 3.
2026-10-10 10:45:02,107 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 73/156 for batch 3.
2026-10-10 10:45:02,154 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 74/156 for batch 3.
2026-10-10 10:45:02,203 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 75/156 for batch 3.
2026-10-10 10:45:02,257 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 76/156 for batch 3.
2026-10-10 10:45:02,755 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 77/156 for batch 3.
2026-10-10 10:45:02,811 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 78/156 for batch 3.
2026-10-10 10:45:02,857 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 79/156 for batch 3.
2026-10-10 10:45:02,912 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 80/156 for batch 3.
2026-10-10 10:45:02,966 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 81/156 for batch 3.
2026-10-10 10:45:03,012 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 82/156 for batch 3.
2026-10-10 10:45:03,059 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 83/156 for batch 3.
2026-10-10 10:45:03,114 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 84/156 for batch 3.
2026-10-10 10:45:03,162 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 85/156 for batch 3.
2026-10-10 10:45:03,208 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 86/156 for batch 3.
2026-10-10 10:45:03,262 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 87/156 for batch 3.
2026-10-10 10:45:03,634 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 88/156 for batch 3.
2026-10-10 10:45:03,682 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 89/156 for batch 3.
2026-10-10 10:45:03,729 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 90/156 for batch 3.
2026-10-10 10:45:03,784 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 91/156 for batch 3.
2026-10-10 10:45:03,832 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 92/156 for batch 3.
2026-10-10 10:45:03,878 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 93/156 for batch 3.
2026-10-10 10:45:03,925 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 94/156 for batch 3.
2026-10-10 10:45:03,980 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 95/156 for batch 3.
2026-10-10 10:45:04,474 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 96/156 for batch 3.
2026-10-10 10:45:04,528 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 97/156 for batch 3.
2026-10-10 10:45:04,582 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 98/156 for batch 3.
2026-10-10 10:45:04,629 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 99/156 for batch 3.
2026-10-10 10:45:04,676 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 100/156 for batch 3.
2026-10-10 10:45:04,721 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 101/156 for batch 3.
2026-10-10 10:45:04,776 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 102/156 for batch 3.
2026-10-10 10:45:04,824 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 103/156 for batch 3.
2026-10-10 10:45:04,872 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 104/156 for batch 3.
2026-10-10 10:45:04,926 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 105/156 for batch 3.
2026-10-10 10:45:04,976 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 106/156 for batch 3.
2026-10-10 10:45:05,020 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 107/156 for batch 3.
2026-10-10 10:45:05,066 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 108/156 for batch 3.
2026-10-10 10:45:05,121 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 109/156 for batch 3.
2026-10-10 10:45:05,168 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 110/156 for batch 3.
2026-10-10 10:45:05,214 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 111/156 for batch 3.
2026-10-10 10:45:05,261 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 112/156 for batch 3.
2026-10-10 10:45:05,316 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 113/156 for batch 3.
2026-10-10 10:45:05,362 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 114/156 for batch 3.
2026-10-10 10:45:05,409 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 115/156 for batch 3.
2026-10-10 10:45:05,464 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 116/156 for batch 3.
2026-10-10 10:45:05,511 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 117/156 for batch 3.
2026-10-10 10:45:05,558 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 118/156 for batch 3.
2026-10-10 10:45:05,612 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 119/156 for batch 3.
2026-10-10 10:45:05,673 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 120/156 for batch 3.
2026-10-10 10:45:05,718 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 121/156 for batch 3.
2026-10-10 10:45:06,208 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 122/156 for batch 3.
2026-10-10 10:45:06,266 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 123/156 for batch 3.
2026-10-10 10:45:06,312 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 124/156 for batch 3.
2026-10-10 10:45:06,359 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 125/156 for batch 3.
2026-10-10 10:45:06,859 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 126/156 for batch 3.
2026-10-10 10:45:06,915 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 127/156 for batch 3.
2026-10-10 10:45:06,963 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 128/156 for batch 3.
2026-10-10 10:45:07,011 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 129/156 for batch 3.
2026-10-10 10:45:07,058 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 130/156 for batch 3.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00003_monthly_cleaning_report.partial.parquet

2026-10-10 10:45:09,679 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 10/156.
2026-10-10 10:45:10,874 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 20/156.
2026-10-10 10:45:12,075 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 30/156.
2026-10-10 10:45:13,262 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 40/156.
2026-10-10 10:45:14,414 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 50/156.
2026-10-10 10:45:15,531 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 60/156.
2026-10-10 10:45:16,667 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 70/156.
2026-10-10 10:45:17,800 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 80/156.
2026-10-10 10:45:18,916 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 90/156.
2026-10-10 10:45:20,035 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 100/156.
2026-10-10 10:45:21,250 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 110/156.
2026-10-10 10:45:22,379 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 120/156.
2026-10-10 10:45:23,500 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 130/156.
2026-10-10 10:45:24,620 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 140/156.
2026-10-10 10:45:25,749 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 150/156.
2026-10-10 10:45:26,456 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 156/156.
2026-10-10 10:45:26,772 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00003_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00003_monthly_cleaning_report.parquet

2026-10-10 10:45:42,683 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 18 parcels from batch_00003_monthly.nc.

Created job j-261010074546444283a8e8aeb704afe4: partition 20, batch 3, user esagovhub2@gmail.com.

2026-10-10 10:47:00,129 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\monthly_cubes\8761d661959b732e-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:47:00,506 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 10/146 for batch 1.
2026-10-10 10:47:00,859 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 20/146 for batch 1.
2026-10-10 10:47:01,191 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 30/146 for batch 1.
2026-10-10 10:47:01,530 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 40/146 for batch 1.
2026-10-10 10:47:01,855 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 50/146 for batch 1.
2026-10-10 10:47:02,179 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 60/146 for batch 1.
2026-10-10 10:47:02,528 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 70/146 for batch 1.
2026-10-10 10:47:02,866 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 80/146 for batch 1.
2026-10-10 10:47:03,214 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 90/146 for batch 1.
2026-10-10 10:47:03,555 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 100/146 for batch 1.
2026-10-10 10:47:03,894 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 110/146 for batch 1.
2026-10-10 10:47:04,245 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 120/146 for batch 1.
2026-10-10 10:47:04,586 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 130/146 for batch 1.
2026-10-10 10:47:04,934 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 140/146 for batch 1.
2026-10-10 10:47:05,144 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 146/146 for batch 1.
2026-10-10 10:47:05,145 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 1/9 in strips of 45 rows.
2026-10-10 10:47:05,722 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 2/9 in strips of 45 rows.
2026-10-10 10:47:06,289 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 3/9 in strips of 45 rows.
2026-10-10 10:47:06,858 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 4/9 in strips of 45 rows.
2026-10-10 10:47:07,428 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 5/9 in strips of 45 rows.
2026-10-10 10:47:07,999 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 6/9 in strips of 45 rows.
2026-10-10 10:47:08,576 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 7/9 in strips of 45 rows.
2026-10-10 10:47:09,139 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 8/9 in strips of 45 rows.
2026-10-10 10:47:09,688 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 9/9 in strips of 45 rows.
2026-10-10 10:47:10,345 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 1/146 for batch 1.
2026-10-10 10:47:10,362 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 2/146 for batch 1.
2026-10-10 10:47:10,455 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 3/146 for batch 1.
2026-10-10 10:47:10,471 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 4/146 for batch 1.
2026-10-10 10:47:10,488 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 5/146 for batch 1.
2026-10-10 10:47:10,503 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 6/146 for batch 1.
2026-10-10 10:47:10,519 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 7/146 for batch 1.
2026-10-10 10:47:10,535 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 8/146 for batch 1.
2026-10-10 10:47:10,552 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 9/146 for batch 1.
2026-10-10 10:47:10,642 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 10/146 for batch 1.
2026-10-10 10:47:10,658 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 11/146 for batch 1.
2026-10-10 10:47:10,674 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 12/146 for batch 1.
2026-10-10 10:47:10,691 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 13/146 for batch 1.
2026-10-10 10:47:10,706 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 14/146 for batch 1.
2026-10-10 10:47:10,722 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 15/146 for batch 1.
2026-10-10 10:47:10,739 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 16/146 for batch 1.
2026-10-10 10:47:10,758 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 17/146 for batch 1.
2026-10-10 10:47:10,851 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 18/146 for batch 1.
2026-10-10 10:47:10,866 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 19/146 for batch 1.
2026-10-10 10:47:10,882 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 20/146 for batch 1.
2026-10-10 10:47:10,898 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 21/146 for batch 1.
2026-10-10 10:47:10,915 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 22/146 for batch 1.
2026-10-10 10:47:10,932 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 23/146 for batch 1.
2026-10-10 10:47:10,948 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 24/146 for batch 1.
2026-10-10 10:47:10,964 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 25/146 for batch 1.
2026-10-10 10:47:10,980 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 26/146 for batch 1.
2026-10-10 10:47:10,997 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 27/146 for batch 1.
2026-10-10 10:47:11,013 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 28/146 for batch 1.
2026-10-10 10:47:11,030 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 29/146 for batch 1.
2026-10-10 10:47:11,046 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 30/146 for batch 1.
2026-10-10 10:47:11,062 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 31/146 for batch 1.
2026-10-10 10:47:11,081 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 32/146 for batch 1.
2026-10-10 10:47:11,111 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 33/146 for batch 1.
2026-10-10 10:47:11,133 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 34/146 for batch 1.
2026-10-10 10:47:11,240 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 35/146 for batch 1.
2026-10-10 10:47:11,257 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 36/146 for batch 1.
2026-10-10 10:47:11,348 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 37/146 for batch 1.
2026-10-10 10:47:11,365 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 38/146 for batch 1.
2026-10-10 10:47:11,381 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 39/146 for batch 1.
2026-10-10 10:47:11,397 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 40/146 for batch 1.
2026-10-10 10:47:11,495 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 41/146 for batch 1.
2026-10-10 10:47:11,510 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 42/146 for batch 1.
2026-10-10 10:47:11,527 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 43/146 for batch 1.
2026-10-10 10:47:11,543 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 44/146 for batch 1.
2026-10-10 10:47:11,559 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 45/146 for batch 1.
2026-10-10 10:47:11,576 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 46/146 for batch 1.
2026-10-10 10:47:11,592 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 47/146 for batch 1.
2026-10-10 10:47:11,609 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 48/146 for batch 1.
2026-10-10 10:47:11,625 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 49/146 for batch 1.
2026-10-10 10:47:11,643 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 50/146 for batch 1.
2026-10-10 10:47:11,659 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 51/146 for batch 1.
2026-10-10 10:47:11,676 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 52/146 for batch 1.
2026-10-10 10:47:11,772 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 53/146 for batch 1.
2026-10-10 10:47:11,786 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 54/146 for batch 1.
2026-10-10 10:47:11,802 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 55/146 for batch 1.
2026-10-10 10:47:11,819 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 56/146 for batch 1.
2026-10-10 10:47:11,836 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 57/146 for batch 1.
2026-10-10 10:47:11,851 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 58/146 for batch 1.
2026-10-10 10:47:11,867 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 59/146 for batch 1.
2026-10-10 10:47:11,890 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 60/146 for batch 1.
2026-10-10 10:47:11,904 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 61/146 for batch 1.
2026-10-10 10:47:11,922 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 62/146 for batch 1.
2026-10-10 10:47:11,940 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 63/146 for batch 1.
2026-10-10 10:47:11,957 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 64/146 for batch 1.
2026-10-10 10:47:11,974 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 65/146 for batch 1.
2026-10-10 10:47:11,992 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 66/146 for batch 1.
2026-10-10 10:47:12,080 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 67/146 for batch 1.
2026-10-10 10:47:12,095 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 68/146 for batch 1.
2026-10-10 10:47:12,115 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 69/146 for batch 1.
2026-10-10 10:47:12,132 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 70/146 for batch 1.
2026-10-10 10:47:12,149 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 71/146 for batch 1.
2026-10-10 10:47:12,165 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 72/146 for batch 1.
2026-10-10 10:47:12,258 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 73/146 for batch 1.
2026-10-10 10:47:12,273 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 74/146 for batch 1.
2026-10-10 10:47:12,289 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 75/146 for batch 1.
2026-10-10 10:47:12,304 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 76/146 for batch 1.
2026-10-10 10:47:12,395 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 77/146 for batch 1.
2026-10-10 10:47:12,410 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 78/146 for batch 1.
2026-10-10 10:47:12,426 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 79/146 for batch 1.
2026-10-10 10:47:12,442 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 80/146 for batch 1.
2026-10-10 10:47:12,458 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 81/146 for batch 1.
2026-10-10 10:47:12,473 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 82/146 for batch 1.
2026-10-10 10:47:12,490 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 83/146 for batch 1.
2026-10-10 10:47:12,506 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 84/146 for batch 1.
2026-10-10 10:47:12,522 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 85/146 for batch 1.
2026-10-10 10:47:12,538 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 86/146 for batch 1.
2026-10-10 10:47:12,553 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 87/146 for batch 1.
2026-10-10 10:47:12,568 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 88/146 for batch 1.
2026-10-10 10:47:12,584 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 89/146 for batch 1.
2026-10-10 10:47:12,599 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 90/146 for batch 1.
2026-10-10 10:47:12,615 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 91/146 for batch 1.
2026-10-10 10:47:12,631 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 92/146 for batch 1.
2026-10-10 10:47:12,648 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 93/146 for batch 1.
2026-10-10 10:47:12,663 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 94/146 for batch 1.
2026-10-10 10:47:12,679 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 95/146 for batch 1.
2026-10-10 10:47:12,695 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 96/146 for batch 1.
2026-10-10 10:47:12,711 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 97/146 for batch 1.
2026-10-10 10:47:12,729 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 98/146 for batch 1.
2026-10-10 10:47:12,745 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 99/146 for batch 1.
2026-10-10 10:47:12,760 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 100/146 for batch 1.
2026-10-10 10:47:12,776 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 101/146 for batch 1.
2026-10-10 10:47:12,792 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 102/146 for batch 1.
2026-10-10 10:47:12,808 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 103/146 for batch 1.
2026-10-10 10:47:12,825 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 104/146 for batch 1.
2026-10-10 10:47:12,840 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 105/146 for batch 1.
2026-10-10 10:47:12,857 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 106/146 for batch 1.
2026-10-10 10:47:12,872 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 107/146 for batch 1.
2026-10-10 10:47:12,888 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 108/146 for batch 1.
2026-10-10 10:47:12,930 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 109/146 for batch 1.
2026-10-10 10:47:12,945 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 110/146 for batch 1.
2026-10-10 10:47:12,961 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 111/146 for batch 1.
2026-10-10 10:47:12,984 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 112/146 for batch 1.
2026-10-10 10:47:13,005 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 113/146 for batch 1.
2026-10-10 10:47:13,020 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 114/146 for batch 1.
2026-10-10 10:47:13,036 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 115/146 for batch 1.
2026-10-10 10:47:13,051 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 116/146 for batch 1.
2026-10-10 10:47:13,070 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 117/146 for batch 1.
2026-10-10 10:47:13,086 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 118/146 for batch 1.
2026-10-10 10:47:13,101 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 119/146 for batch 1.
2026-10-10 10:47:13,116 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 120/146 for batch 1.
2026-10-10 10:47:13,132 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 121/146 for batch 1.
2026-10-10 10:47:13,148 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 122/146 for batch 1.
2026-10-10 10:47:13,164 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 123/146 for batch 1.
2026-10-10 10:47:13,180 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 124/146 for batch 1.
2026-10-10 10:47:13,196 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 125/146 for batch 1.
2026-10-10 10:47:13,214 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 126/146 for batch 1.
2026-10-10 10:47:13,284 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 127/146 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/monthly_cubes/8761d661959b732e-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:47:13,968 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 10/146.
2026-10-10 10:47:14,256 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 20/146.
2026-10-10 10:47:14,539 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 30/146.
2026-10-10 10:47:14,812 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 40/146.
2026-10-10 10:47:15,081 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 50/146.
2026-10-10 10:47:15,359 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 60/146.
2026-10-10 10:47:15,629 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 70/146.
2026-10-10 10:47:15,900 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 80/146.
2026-10-10 10:47:16,167 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 90/146.
2026-10-10 10:47:16,439 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 100/146.
2026-10-10 10:47:16,700 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 110/146.
2026-10-10 10:47:16,968 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 120/146.
2026-10-10 10:47:17,236 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 130/146.
2026-10-10 10:47:17,511 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 140/146.
2026-10-10 10:47:17,716 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 146/146.
2026-10-10 10:47:17,866 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\monthly_cubes\8761d661959b732e-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/monthly_cubes/8761d661959b732e-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:47:20,505 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 3 parcels from batch_00001_monthly.nc.

Created job j-2610100747244c7e904edcd5896f6080: partition 20, batch 4, user farfarasmpoytos@gmail.com.

2026-10-10 10:48:25,611 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\monthly_cubes\651f62b14ac1117d-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:48:26,465 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 10/147 for batch 1.
2026-10-10 10:48:27,223 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 20/147 for batch 1.
2026-10-10 10:48:27,942 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 30/147 for batch 1.
2026-10-10 10:48:28,661 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 40/147 for batch 1.
2026-10-10 10:48:29,444 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 50/147 for batch 1.
2026-10-10 10:48:30,209 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 60/147 for batch 1.
2026-10-10 10:48:30,978 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 70/147 for batch 1.
2026-10-10 10:48:31,780 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 80/147 for batch 1.
2026-10-10 10:48:32,576 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 90/147 for batch 1.
2026-10-10 10:48:33,499 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 100/147 for batch 1.
2026-10-10 10:48:34,431 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 110/147 for batch 1.
2026-10-10 10:48:35,293 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 120/147 for batch 1.
2026-10-10 10:48:36,087 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 130/147 for batch 1.
2026-10-10 10:48:36,827 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 140/147 for batch 1.
2026-10-10 10:48:37,397 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Stored observations 147/147 for batch 1.
2026-10-10 10:48:37,397 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 1/9 in strips of 24 rows.
2026-10-10 10:48:39,826 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 2/9 in strips of 24 rows.
2026-10-10 10:48:42,278 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 3/9 in strips of 24 rows.
2026-10-10 10:48:44,718 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 4/9 in strips of 24 rows.
2026-10-10 10:48:47,137 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 5/9 in strips of 24 rows.
2026-10-10 10:48:49,554 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 6/9 in strips of 24 rows.
2026-10-10 10:48:51,976 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 7/9 in strips of 24 rows.
2026-10-10 10:48:54,391 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 8/9 in strips of 24 rows.
2026-10-10 10:48:56,806 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Temporal filling band 9/9 in strips of 24 rows.
2026-10-10 10:48:59,407 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 1/147 for batch 1.
2026-10-10 10:48:59,453 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 2/147 for batch 1.
2026-10-10 10:48:59,498 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 3/147 for batch 1.
2026-10-10 10:48:59,541 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 4/147 for batch 1.
2026-10-10 10:48:59,586 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 5/147 for batch 1.
2026-10-10 10:48:59,644 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 6/147 for batch 1.
2026-10-10 10:48:59,689 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 7/147 for batch 1.
2026-10-10 10:48:59,733 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 8/147 for batch 1.
2026-10-10 10:48:59,783 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 9/147 for batch 1.
2026-10-10 10:48:59,833 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 10/147 for batch 1.
2026-10-10 10:49:00,240 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 11/147 for batch 1.
2026-10-10 10:49:00,298 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 12/147 for batch 1.
2026-10-10 10:49:00,681 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 13/147 for batch 1.
2026-10-10 10:49:00,724 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 14/147 for batch 1.
2026-10-10 10:49:00,768 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 15/147 for batch 1.
2026-10-10 10:49:00,813 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 16/147 for batch 1.
2026-10-10 10:49:00,980 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 17/147 for batch 1.
2026-10-10 10:49:01,022 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 18/147 for batch 1.
2026-10-10 10:49:01,067 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 19/147 for batch 1.
2026-10-10 10:49:01,112 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 20/147 for batch 1.
2026-10-10 10:49:01,167 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 21/147 for batch 1.
2026-10-10 10:49:01,577 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 22/147 for batch 1.
2026-10-10 10:49:01,621 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 23/147 for batch 1.
2026-10-10 10:49:01,668 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 24/147 for batch 1.
2026-10-10 10:49:01,712 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 25/147 for batch 1.
2026-10-10 10:49:01,757 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 26/147 for batch 1.
2026-10-10 10:49:01,808 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 27/147 for batch 1.
2026-10-10 10:49:01,852 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 28/147 for batch 1.
2026-10-10 10:49:01,896 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 29/147 for batch 1.
2026-10-10 10:49:01,939 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 30/147 for batch 1.
2026-10-10 10:49:01,983 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 31/147 for batch 1.
2026-10-10 10:49:02,026 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 32/147 for batch 1.
2026-10-10 10:49:02,077 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 33/147 for batch 1.
2026-10-10 10:49:02,474 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 34/147 for batch 1.
2026-10-10 10:49:02,517 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 35/147 for batch 1.
2026-10-10 10:49:02,560 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 36/147 for batch 1.
2026-10-10 10:49:02,612 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 37/147 for batch 1.
2026-10-10 10:49:02,658 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 38/147 for batch 1.
2026-10-10 10:49:02,702 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 39/147 for batch 1.
2026-10-10 10:49:02,745 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 40/147 for batch 1.
2026-10-10 10:49:03,136 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 41/147 for batch 1.
2026-10-10 10:49:03,182 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 42/147 for batch 1.
2026-10-10 10:49:03,225 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 43/147 for batch 1.
2026-10-10 10:49:03,269 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 44/147 for batch 1.
2026-10-10 10:49:03,313 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 45/147 for batch 1.
2026-10-10 10:49:03,364 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 46/147 for batch 1.
2026-10-10 10:49:03,756 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 47/147 for batch 1.
2026-10-10 10:49:03,801 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 48/147 for batch 1.
2026-10-10 10:49:04,085 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 49/147 for batch 1.
2026-10-10 10:49:04,135 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 50/147 for batch 1.
2026-10-10 10:49:04,526 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 51/147 for batch 1.
2026-10-10 10:49:04,911 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 52/147 for batch 1.
2026-10-10 10:49:04,954 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 53/147 for batch 1.
2026-10-10 10:49:04,999 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 54/147 for batch 1.
2026-10-10 10:49:05,042 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 55/147 for batch 1.
2026-10-10 10:49:05,086 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 56/147 for batch 1.
2026-10-10 10:49:05,129 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 57/147 for batch 1.
2026-10-10 10:49:05,176 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 58/147 for batch 1.
2026-10-10 10:49:05,222 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 59/147 for batch 1.
2026-10-10 10:49:05,266 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 60/147 for batch 1.
2026-10-10 10:49:05,309 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 61/147 for batch 1.
2026-10-10 10:49:05,354 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 62/147 for batch 1.
2026-10-10 10:49:05,398 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 63/147 for batch 1.
2026-10-10 10:49:05,443 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 64/147 for batch 1.
2026-10-10 10:49:05,487 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 65/147 for batch 1.
2026-10-10 10:49:05,532 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 66/147 for batch 1.
2026-10-10 10:49:05,576 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 67/147 for batch 1.
2026-10-10 10:49:05,619 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 68/147 for batch 1.
2026-10-10 10:49:05,663 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 69/147 for batch 1.
2026-10-10 10:49:05,706 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 70/147 for batch 1.
2026-10-10 10:49:05,749 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 71/147 for batch 1.
2026-10-10 10:49:05,791 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 72/147 for batch 1.
2026-10-10 10:49:06,181 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 73/147 for batch 1.
2026-10-10 10:49:06,222 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 74/147 for batch 1.
2026-10-10 10:49:06,265 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 75/147 for batch 1.
2026-10-10 10:49:06,647 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 76/147 for batch 1.
2026-10-10 10:49:06,691 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 77/147 for batch 1.
2026-10-10 10:49:07,074 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 78/147 for batch 1.
2026-10-10 10:49:07,118 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 79/147 for batch 1.
2026-10-10 10:49:07,163 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 80/147 for batch 1.
2026-10-10 10:49:07,558 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 81/147 for batch 1.
2026-10-10 10:49:07,941 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 82/147 for batch 1.
2026-10-10 10:49:07,985 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 83/147 for batch 1.
2026-10-10 10:49:08,028 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 84/147 for batch 1.
2026-10-10 10:49:08,071 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 85/147 for batch 1.
2026-10-10 10:49:08,115 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 86/147 for batch 1.
2026-10-10 10:49:08,158 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 87/147 for batch 1.
2026-10-10 10:49:08,200 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 88/147 for batch 1.
2026-10-10 10:49:08,242 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 89/147 for batch 1.
2026-10-10 10:49:08,284 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 90/147 for batch 1.
2026-10-10 10:49:08,666 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 91/147 for batch 1.
2026-10-10 10:49:09,051 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 92/147 for batch 1.
2026-10-10 10:49:09,094 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 93/147 for batch 1.
2026-10-10 10:49:09,137 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 94/147 for batch 1.
2026-10-10 10:49:09,181 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 95/147 for batch 1.
2026-10-10 10:49:09,223 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 96/147 for batch 1.
2026-10-10 10:49:09,266 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 97/147 for batch 1.
2026-10-10 10:49:09,310 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 98/147 for batch 1.
2026-10-10 10:49:09,353 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 99/147 for batch 1.
2026-10-10 10:49:09,396 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 100/147 for batch 1.
2026-10-10 10:49:09,438 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 101/147 for batch 1.
2026-10-10 10:49:09,480 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 102/147 for batch 1.
2026-10-10 10:49:09,524 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 103/147 for batch 1.
2026-10-10 10:49:09,565 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 104/147 for batch 1.
2026-10-10 10:49:09,607 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 105/147 for batch 1.
2026-10-10 10:49:09,651 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 106/147 for batch 1.
2026-10-10 10:49:09,692 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 107/147 for batch 1.
2026-10-10 10:49:09,735 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 108/147 for batch 1.
2026-10-10 10:49:09,777 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 109/147 for batch 1.
2026-10-10 10:49:09,819 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 110/147 for batch 1.
2026-10-10 10:49:09,862 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 111/147 for batch 1.
2026-10-10 10:49:09,904 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 112/147 for batch 1.
2026-10-10 10:49:09,947 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 113/147 for batch 1.
2026-10-10 10:49:09,989 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 114/147 for batch 1.
2026-10-10 10:49:10,032 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 115/147 for batch 1.
2026-10-10 10:49:10,075 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 116/147 for batch 1.
2026-10-10 10:49:10,118 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 117/147 for batch 1.
2026-10-10 10:49:10,161 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 118/147 for batch 1.
2026-10-10 10:49:10,203 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 119/147 for batch 1.
2026-10-10 10:49:10,584 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 120/147 for batch 1.
2026-10-10 10:49:10,633 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 121/147 for batch 1.
2026-10-10 10:49:10,679 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 122/147 for batch 1.
2026-10-10 10:49:10,722 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 123/147 for batch 1.
2026-10-10 10:49:10,763 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 124/147 for batch 1.
2026-10-10 10:49:10,807 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 125/147 for batch 1.
2026-10-10 10:49:10,849 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 126/147 for batch 1.
2026-10-10 10:49:10,892 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Cleaned acquisition 127/147 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_18/monthly_cubes/651f62b14ac1117d-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:49:13,628 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 10/147.
2026-10-10 10:49:14,613 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 20/147.
2026-10-10 10:49:15,587 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 30/147.
2026-10-10 10:49:16,556 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 40/147.
2026-10-10 10:49:17,525 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 50/147.
2026-10-10 10:49:18,488 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 60/147.
2026-10-10 10:49:19,604 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 70/147.
2026-10-10 10:49:20,719 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 80/147.
2026-10-10 10:49:21,678 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 90/147.
2026-10-10 10:49:22,636 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 100/147.
2026-10-10 10:49:23,578 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 110/147.
2026-10-10 10:49:24,515 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 120/147.
2026-10-10 10:49:25,482 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 130/147.
2026-10-10 10:49:26,440 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 140/147.
2026-10-10 10:49:27,100 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Saved output indices for acquisition 147/147.
2026-10-10 10:49:27,428 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\monthly_cubes\651f62b14ac1117d-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_18/monthly_cubes/651f62b14ac1117d-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:49:41,640 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 16 parcels from batch_00001_monthly.nc.

Created job j-2610100749454178b4309646585966c6: partition 20, batch 5, user esagovhub3@gmail.com.

2026-10-10 10:50:30,761 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\monthly_cubes\f163b9d8bd4e61be-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:50:31,228 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 10/153 for batch 1.
2026-10-10 10:50:31,625 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 20/153 for batch 1.
2026-10-10 10:50:32,035 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 30/153 for batch 1.
2026-10-10 10:50:32,451 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 40/153 for batch 1.
2026-10-10 10:50:32,901 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 50/153 for batch 1.
2026-10-10 10:50:33,371 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 60/153 for batch 1.
2026-10-10 10:50:33,870 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 70/153 for batch 1.
2026-10-10 10:50:34,264 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 80/153 for batch 1.
2026-10-10 10:50:34,668 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 90/153 for batch 1.
2026-10-10 10:50:35,085 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 100/153 for batch 1.
2026-10-10 10:50:35,501 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 110/153 for batch 1.
2026-10-10 10:50:35,909 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 120/153 for batch 1.
2026-10-10 10:50:36,303 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 130/153 for batch 1.
2026-10-10 10:50:36,697 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 140/153 for batch 1.
2026-10-10 10:50:37,112 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 150/153 for batch 1.
2026-10-10 10:50:37,230 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Stored observations 153/153 for batch 1.
2026-10-10 10:50:37,231 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 1/9 in strips of 38 rows.
2026-10-10 10:50:38,208 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 2/9 in strips of 38 rows.
2026-10-10 10:50:39,186 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 3/9 in strips of 38 rows.
2026-10-10 10:50:40,187 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 4/9 in strips of 38 rows.
2026-10-10 10:50:41,183 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 5/9 in strips of 38 rows.
2026-10-10 10:50:42,180 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 6/9 in strips of 38 rows.
2026-10-10 10:50:43,171 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 7/9 in strips of 38 rows.
2026-10-10 10:50:44,177 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 8/9 in strips of 38 rows.
2026-10-10 10:50:45,200 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Temporal filling band 9/9 in strips of 38 rows.
2026-10-10 10:50:46,227 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 1/153 for batch 1.
2026-10-10 10:50:46,249 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 2/153 for batch 1.
2026-10-10 10:50:46,268 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 3/153 for batch 1.
2026-10-10 10:50:46,290 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 4/153 for batch 1.
2026-10-10 10:50:46,310 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 5/153 for batch 1.
2026-10-10 10:50:46,331 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 6/153 for batch 1.
2026-10-10 10:50:46,353 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 7/153 for batch 1.
2026-10-10 10:50:46,372 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 8/153 for batch 1.
2026-10-10 10:50:46,391 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 9/153 for batch 1.
2026-10-10 10:50:46,409 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 10/153 for batch 1.
2026-10-10 10:50:46,427 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 11/153 for batch 1.
2026-10-10 10:50:46,460 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 12/153 for batch 1.
2026-10-10 10:50:46,479 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 13/153 for batch 1.
2026-10-10 10:50:46,497 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 14/153 for batch 1.
2026-10-10 10:50:46,518 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 15/153 for batch 1.
2026-10-10 10:50:46,536 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 16/153 for batch 1.
2026-10-10 10:50:46,557 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 17/153 for batch 1.
2026-10-10 10:50:46,734 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 18/153 for batch 1.
2026-10-10 10:50:46,751 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 19/153 for batch 1.
2026-10-10 10:50:46,771 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 20/153 for batch 1.
2026-10-10 10:50:46,917 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 21/153 for batch 1.
2026-10-10 10:50:47,058 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 22/153 for batch 1.
2026-10-10 10:50:47,084 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 23/153 for batch 1.
2026-10-10 10:50:47,270 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 24/153 for batch 1.
2026-10-10 10:50:47,449 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 25/153 for batch 1.
2026-10-10 10:50:47,469 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 26/153 for batch 1.
2026-10-10 10:50:47,647 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 27/153 for batch 1.
2026-10-10 10:50:47,833 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 28/153 for batch 1.
2026-10-10 10:50:48,009 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 29/153 for batch 1.
2026-10-10 10:50:48,035 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 30/153 for batch 1.
2026-10-10 10:50:48,212 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 31/153 for batch 1.
2026-10-10 10:50:48,393 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 32/153 for batch 1.
2026-10-10 10:50:48,581 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 33/153 for batch 1.
2026-10-10 10:50:48,603 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 34/153 for batch 1.
2026-10-10 10:50:48,787 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 35/153 for batch 1.
2026-10-10 10:50:48,974 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 36/153 for batch 1.
2026-10-10 10:50:48,995 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 37/153 for batch 1.
2026-10-10 10:50:49,015 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 38/153 for batch 1.
2026-10-10 10:50:49,198 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 39/153 for batch 1.
2026-10-10 10:50:49,377 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 40/153 for batch 1.
2026-10-10 10:50:49,397 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 41/153 for batch 1.
2026-10-10 10:50:49,416 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 42/153 for batch 1.
2026-10-10 10:50:49,546 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 43/153 for batch 1.
2026-10-10 10:50:49,677 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 44/153 for batch 1.
2026-10-10 10:50:49,811 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 45/153 for batch 1.
2026-10-10 10:50:49,948 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 46/153 for batch 1.
2026-10-10 10:50:50,081 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 47/153 for batch 1.
2026-10-10 10:50:50,099 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 48/153 for batch 1.
2026-10-10 10:50:50,122 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 49/153 for batch 1.
2026-10-10 10:50:50,260 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 50/153 for batch 1.
2026-10-10 10:50:50,390 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 51/153 for batch 1.
2026-10-10 10:50:50,411 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 52/153 for batch 1.
2026-10-10 10:50:50,592 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 53/153 for batch 1.
2026-10-10 10:50:50,617 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 54/153 for batch 1.
2026-10-10 10:50:50,637 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 55/153 for batch 1.
2026-10-10 10:50:50,656 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 56/153 for batch 1.
2026-10-10 10:50:50,682 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 57/153 for batch 1.
2026-10-10 10:50:50,700 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 58/153 for batch 1.
2026-10-10 10:50:50,721 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 59/153 for batch 1.
2026-10-10 10:50:50,902 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 60/153 for batch 1.
2026-10-10 10:50:51,032 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 61/153 for batch 1.
2026-10-10 10:50:51,163 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 62/153 for batch 1.
2026-10-10 10:50:51,295 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 63/153 for batch 1.
2026-10-10 10:50:51,475 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 64/153 for batch 1.
2026-10-10 10:50:51,497 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 65/153 for batch 1.
2026-10-10 10:50:51,515 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 66/153 for batch 1.
2026-10-10 10:50:51,534 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 67/153 for batch 1.
2026-10-10 10:50:51,553 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 68/153 for batch 1.
2026-10-10 10:50:51,571 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 69/153 for batch 1.
2026-10-10 10:50:51,590 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 70/153 for batch 1.
2026-10-10 10:50:51,608 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 71/153 for batch 1.
2026-10-10 10:50:51,627 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 72/153 for batch 1.
2026-10-10 10:50:51,651 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 73/153 for batch 1.
2026-10-10 10:50:51,669 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 74/153 for batch 1.
2026-10-10 10:50:51,847 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 75/153 for batch 1.
2026-10-10 10:50:51,978 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 76/153 for batch 1.
2026-10-10 10:50:52,153 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 77/153 for batch 1.
2026-10-10 10:50:52,172 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 78/153 for batch 1.
2026-10-10 10:50:52,192 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 79/153 for batch 1.
2026-10-10 10:50:52,212 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 80/153 for batch 1.
2026-10-10 10:50:52,234 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 81/153 for batch 1.
2026-10-10 10:50:52,253 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 82/153 for batch 1.
2026-10-10 10:50:52,275 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 83/153 for batch 1.
2026-10-10 10:50:52,293 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 84/153 for batch 1.
2026-10-10 10:50:52,468 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 85/153 for batch 1.
2026-10-10 10:50:52,492 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 86/153 for batch 1.
2026-10-10 10:50:52,512 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 87/153 for batch 1.
2026-10-10 10:50:52,530 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 88/153 for batch 1.
2026-10-10 10:50:52,549 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 89/153 for batch 1.
2026-10-10 10:50:52,571 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 90/153 for batch 1.
2026-10-10 10:50:52,591 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 91/153 for batch 1.
2026-10-10 10:50:52,610 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 92/153 for batch 1.
2026-10-10 10:50:52,634 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 93/153 for batch 1.
2026-10-10 10:50:52,653 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 94/153 for batch 1.
2026-10-10 10:50:52,675 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 95/153 for batch 1.
2026-10-10 10:50:52,693 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 96/153 for batch 1.
2026-10-10 10:50:52,713 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 97/153 for batch 1.
2026-10-10 10:50:52,731 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 98/153 for batch 1.
2026-10-10 10:50:52,749 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 99/153 for batch 1.
2026-10-10 10:50:52,769 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 100/153 for batch 1.
2026-10-10 10:50:52,946 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 101/153 for batch 1.
2026-10-10 10:50:53,018 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 102/153 for batch 1.
2026-10-10 10:50:53,199 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 103/153 for batch 1.
2026-10-10 10:50:53,221 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 104/153 for batch 1.
2026-10-10 10:50:53,241 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 105/153 for batch 1.
2026-10-10 10:50:53,259 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 106/153 for batch 1.
2026-10-10 10:50:53,280 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 107/153 for batch 1.
2026-10-10 10:50:53,309 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 108/153 for batch 1.
2026-10-10 10:50:53,331 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 109/153 for batch 1.
2026-10-10 10:50:53,351 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 110/153 for batch 1.
2026-10-10 10:50:53,373 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 111/153 for batch 1.
2026-10-10 10:50:53,550 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 112/153 for batch 1.
2026-10-10 10:50:53,566 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 113/153 for batch 1.
2026-10-10 10:50:53,585 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 114/153 for batch 1.
2026-10-10 10:50:53,607 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 115/153 for batch 1.
2026-10-10 10:50:53,625 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 116/153 for batch 1.
2026-10-10 10:50:53,642 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 117/153 for batch 1.
2026-10-10 10:50:53,664 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 118/153 for batch 1.
2026-10-10 10:50:53,684 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 119/153 for batch 1.
2026-10-10 10:50:53,701 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 120/153 for batch 1.
2026-10-10 10:50:53,874 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 121/153 for batch 1.
2026-10-10 10:50:53,896 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 122/153 for batch 1.
2026-10-10 10:50:53,914 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 123/153 for batch 1.
2026-10-10 10:50:53,932 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 124/153 for batch 1.
2026-10-10 10:50:53,952 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 125/153 for batch 1.
2026-10-10 10:50:53,976 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Cleaned acquisition 126/153 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_19/monthly_cubes/f163b9d8bd4e61be-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:50:55,304 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 10/153.
2026-10-10 10:50:55,678 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 20/153.
2026-10-10 10:50:56,059 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 30/153.
2026-10-10 10:50:56,428 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 40/153.
2026-10-10 10:50:56,797 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 50/153.
2026-10-10 10:50:57,194 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 60/153.
2026-10-10 10:50:57,556 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 70/153.
2026-10-10 10:50:57,929 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 80/153.
2026-10-10 10:50:58,289 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 90/153.
2026-10-10 10:50:58,658 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 100/153.
2026-10-10 10:50:59,021 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 110/153.
2026-10-10 10:50:59,371 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 120/153.
2026-10-10 10:50:59,733 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 130/153.
2026-10-10 10:51:00,101 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 140/153.
2026-10-10 10:51:00,450 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 150/153.
2026-10-10 10:51:00,556 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Saved output indices for acquisition 153/153.
2026-10-10 10:51:00,705 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\monthly_cubes\f163b9d8bd4e61be-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_19/monthly_cubes/f163b9d8bd4e61be-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:51:03,435 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 3 parcels from batch_00001_monthly.nc.

Created job j-26101007510644cb8b2767b1d15256dd: partition 20, batch 6, user louvarieleni@gmail.com.

2026-10-10 10:51:21,378 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:51:22,928 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 10/183 for batch 1.
2026-10-10 10:51:24,357 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 20/183 for batch 1.
2026-10-10 10:51:25,726 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 30/183 for batch 1.
2026-10-10 10:51:27,157 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 40/183 for batch 1.
2026-10-10 10:51:28,583 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 50/183 for batch 1.
2026-10-10 10:51:29,955 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 60/183 for batch 1.
2026-10-10 10:51:31,526 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 70/183 for batch 1.
2026-10-10 10:51:33,651 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 80/183 for batch 1.
2026-10-10 10:51:35,108 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 90/183 for batch 1.
2026-10-10 10:51:36,514 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 100/183 for batch 1.
2026-10-10 10:51:37,950 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 110/183 for batch 1.
2026-10-10 10:51:39,478 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 120/183 for batch 1.
2026-10-10 10:51:41,034 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 130/183 for batch 1.
2026-10-10 10:51:42,677 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 140/183 for batch 1.
2026-10-10 10:51:44,164 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 150/183 for batch 1.
2026-10-10 10:51:46,261 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 160/183 for batch 1.
2026-10-10 10:51:47,803 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 170/183 for batch 1.
2026-10-10 10:51:49,313 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 180/183 for batch 1.
2026-10-10 10:51:49,713 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 183/183 for batch 1.
2026-10-10 10:51:49,713 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 1/9 in strips of 11 rows.
2026-10-10 10:51:59,588 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 2/9 in strips of 11 rows.
2026-10-10 10:52:09,581 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 3/9 in strips of 11 rows.
2026-10-10 10:52:19,774 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 4/9 in strips of 11 rows.
2026-10-10 10:52:30,281 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 5/9 in strips of 11 rows.
2026-10-10 10:52:40,694 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 6/9 in strips of 11 rows.
2026-10-10 10:52:50,717 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 7/9 in strips of 11 rows.
2026-10-10 10:53:01,103 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 8/9 in strips of 11 rows.
2026-10-10 10:53:11,356 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 9/9 in strips of 11 rows.
2026-10-10 10:53:21,824 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 1/183 for batch 1.
2026-10-10 10:53:21,911 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 2/183 for batch 1.
2026-10-10 10:53:21,998 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 3/183 for batch 1.
2026-10-10 10:53:22,102 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 4/183 for batch 1.
2026-10-10 10:53:22,193 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 5/183 for batch 1.
2026-10-10 10:53:22,279 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 6/183 for batch 1.
2026-10-10 10:53:22,619 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 7/183 for batch 1.
2026-10-10 10:53:22,703 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 8/183 for batch 1.
2026-10-10 10:53:23,695 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 9/183 for batch 1.
2026-10-10 10:53:23,799 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 10/183 for batch 1.
2026-10-10 10:53:23,883 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 11/183 for batch 1.
2026-10-10 10:53:25,168 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 12/183 for batch 1.
2026-10-10 10:53:25,251 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 13/183 for batch 1.
2026-10-10 10:53:25,345 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 14/183 for batch 1.
2026-10-10 10:53:25,448 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 15/183 for batch 1.
2026-10-10 10:53:25,532 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 16/183 for batch 1.
2026-10-10 10:53:25,870 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 17/183 for batch 1.
2026-10-10 10:53:26,881 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 18/183 for batch 1.
2026-10-10 10:53:26,970 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 19/183 for batch 1.
2026-10-10 10:53:27,077 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 20/183 for batch 1.
2026-10-10 10:53:27,180 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 21/183 for batch 1.
2026-10-10 10:53:28,193 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 22/183 for batch 1.
2026-10-10 10:53:29,235 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 23/183 for batch 1.
2026-10-10 10:53:29,340 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 24/183 for batch 1.
2026-10-10 10:53:29,425 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 25/183 for batch 1.
2026-10-10 10:53:29,517 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 26/183 for batch 1.
2026-10-10 10:53:29,879 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 27/183 for batch 1.
2026-10-10 10:53:29,964 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 28/183 for batch 1.
2026-10-10 10:53:30,067 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 29/183 for batch 1.
2026-10-10 10:53:30,149 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 30/183 for batch 1.
2026-10-10 10:53:30,232 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 31/183 for batch 1.
2026-10-10 10:53:30,566 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 32/183 for batch 1.
2026-10-10 10:53:30,661 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 33/183 for batch 1.
2026-10-10 10:53:30,762 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 34/183 for batch 1.
2026-10-10 10:53:30,872 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 35/183 for batch 1.
2026-10-10 10:53:31,861 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 36/183 for batch 1.
2026-10-10 10:53:32,892 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 37/183 for batch 1.
2026-10-10 10:53:34,090 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 38/183 for batch 1.
2026-10-10 10:53:34,454 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 39/183 for batch 1.
2026-10-10 10:53:35,458 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 40/183 for batch 1.
2026-10-10 10:53:35,559 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 41/183 for batch 1.
2026-10-10 10:53:35,661 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 42/183 for batch 1.
2026-10-10 10:53:35,743 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 43/183 for batch 1.
2026-10-10 10:53:36,722 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 44/183 for batch 1.
2026-10-10 10:53:37,655 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 45/183 for batch 1.
2026-10-10 10:53:37,743 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 46/183 for batch 1.
2026-10-10 10:53:38,619 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 47/183 for batch 1.
2026-10-10 10:53:38,919 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 48/183 for batch 1.
2026-10-10 10:53:39,791 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 49/183 for batch 1.
2026-10-10 10:53:40,659 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 50/183 for batch 1.
2026-10-10 10:53:40,733 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 51/183 for batch 1.
2026-10-10 10:53:40,819 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 52/183 for batch 1.
2026-10-10 10:53:40,905 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 53/183 for batch 1.
2026-10-10 10:53:40,976 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 54/183 for batch 1.
2026-10-10 10:53:41,854 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 55/183 for batch 1.
2026-10-10 10:53:41,941 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 56/183 for batch 1.
2026-10-10 10:53:42,028 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 57/183 for batch 1.
2026-10-10 10:53:42,918 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 58/183 for batch 1.
2026-10-10 10:53:43,008 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 59/183 for batch 1.
2026-10-10 10:53:43,903 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 60/183 for batch 1.
2026-10-10 10:53:43,977 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 61/183 for batch 1.
2026-10-10 10:53:44,048 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 62/183 for batch 1.
2026-10-10 10:53:44,135 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 63/183 for batch 1.
2026-10-10 10:53:44,207 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 64/183 for batch 1.
2026-10-10 10:53:44,280 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 65/183 for batch 1.
2026-10-10 10:53:44,584 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 66/183 for batch 1.
2026-10-10 10:53:45,487 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 67/183 for batch 1.
2026-10-10 10:53:45,575 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 68/183 for batch 1.
2026-10-10 10:53:46,446 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 69/183 for batch 1.
2026-10-10 10:53:47,321 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 70/183 for batch 1.
2026-10-10 10:53:47,410 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 71/183 for batch 1.
2026-10-10 10:53:48,340 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 72/183 for batch 1.
2026-10-10 10:53:48,429 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 73/183 for batch 1.
2026-10-10 10:53:48,517 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 74/183 for batch 1.
2026-10-10 10:53:48,589 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 75/183 for batch 1.
2026-10-10 10:53:48,676 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 76/183 for batch 1.
2026-10-10 10:53:48,765 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 77/183 for batch 1.
2026-10-10 10:53:49,631 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 78/183 for batch 1.
2026-10-10 10:53:49,717 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 79/183 for batch 1.
2026-10-10 10:53:49,804 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 80/183 for batch 1.
2026-10-10 10:53:50,677 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 81/183 for batch 1.
2026-10-10 10:53:50,983 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 82/183 for batch 1.
2026-10-10 10:53:51,874 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 83/183 for batch 1.
2026-10-10 10:53:51,980 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 84/183 for batch 1.
2026-10-10 10:53:52,067 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 85/183 for batch 1.
2026-10-10 10:53:52,141 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 86/183 for batch 1.
2026-10-10 10:53:52,228 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 87/183 for batch 1.
2026-10-10 10:53:52,316 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 88/183 for batch 1.
2026-10-10 10:53:53,192 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 89/183 for batch 1.
2026-10-10 10:53:54,067 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 90/183 for batch 1.
2026-10-10 10:53:54,181 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 91/183 for batch 1.
2026-10-10 10:53:54,297 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 92/183 for batch 1.
2026-10-10 10:53:54,377 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 93/183 for batch 1.
2026-10-10 10:53:54,463 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 94/183 for batch 1.
2026-10-10 10:53:55,350 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 95/183 for batch 1.
2026-10-10 10:53:56,216 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 96/183 for batch 1.
2026-10-10 10:53:56,303 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 97/183 for batch 1.
2026-10-10 10:53:56,392 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 98/183 for batch 1.
2026-10-10 10:53:56,463 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 99/183 for batch 1.
2026-10-10 10:53:56,533 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 100/183 for batch 1.
2026-10-10 10:53:56,603 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 101/183 for batch 1.
2026-10-10 10:53:56,692 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 102/183 for batch 1.
2026-10-10 10:53:56,779 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 103/183 for batch 1.
2026-10-10 10:53:56,856 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 104/183 for batch 1.
2026-10-10 10:53:56,944 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 105/183 for batch 1.
2026-10-10 10:53:57,031 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 106/183 for batch 1.
2026-10-10 10:53:57,102 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 107/183 for batch 1.
2026-10-10 10:53:57,280 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 108/183 for batch 1.
2026-10-10 10:53:57,458 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 109/183 for batch 1.
2026-10-10 10:53:57,546 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 110/183 for batch 1.
2026-10-10 10:53:57,633 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 111/183 for batch 1.
2026-10-10 10:53:57,706 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 112/183 for batch 1.
2026-10-10 10:53:57,778 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 113/183 for batch 1.
2026-10-10 10:53:57,866 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 114/183 for batch 1.
2026-10-10 10:53:58,764 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 115/183 for batch 1.
2026-10-10 10:53:58,837 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 116/183 for batch 1.
2026-10-10 10:53:58,926 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 117/183 for batch 1.
2026-10-10 10:53:59,017 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 118/183 for batch 1.
2026-10-10 10:53:59,089 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 119/183 for batch 1.
2026-10-10 10:53:59,163 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 120/183 for batch 1.
2026-10-10 10:53:59,235 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 121/183 for batch 1.
2026-10-10 10:53:59,323 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 122/183 for batch 1.
2026-10-10 10:53:59,415 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 123/183 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:54:11,691 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 10/183.
2026-10-10 10:54:13,927 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 20/183.
2026-10-10 10:54:16,172 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 30/183.
2026-10-10 10:54:18,457 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 40/183.
2026-10-10 10:54:20,747 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 50/183.
2026-10-10 10:54:22,995 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 60/183.
2026-10-10 10:54:25,423 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 70/183.
2026-10-10 10:54:27,769 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 80/183.
2026-10-10 10:54:30,188 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 90/183.
2026-10-10 10:54:32,482 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 100/183.
2026-10-10 10:54:35,011 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 110/183.
2026-10-10 10:54:37,326 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 120/183.
2026-10-10 10:54:39,545 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 130/183.
2026-10-10 10:54:41,806 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 140/183.
2026-10-10 10:54:44,013 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 150/183.
2026-10-10 10:54:46,687 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 160/183.
2026-10-10 10:54:48,960 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 170/183.
2026-10-10 10:54:51,248 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 180/183.
2026-10-10 10:54:51,926 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 183/183.
2026-10-10 10:54:52,601 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:55:02,003 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 9 parcels from batch_00001_monthly.nc.
2026-10-10 10:55:03,715 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\monthly_cubes\dfc028bb33fc50ae-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:55:04,512 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 10/118 for batch 1.
2026-10-10 10:55:05,207 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 20/118 for batch 1.
2026-10-10 10:55:05,906 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 30/118 for batch 1.

Created job j-2610100755064d1798b6c72e949e4cef: partition 20, batch 7, user esagovhub1@gmail.com.

2026-10-10 10:55:06,670 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 40/118 for batch 1.
2026-10-10 10:55:07,355 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 50/118 for batch 1.
2026-10-10 10:55:08,028 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 60/118 for batch 1.
2026-10-10 10:55:08,770 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 70/118 for batch 1.
2026-10-10 10:55:09,521 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 80/118 for batch 1.
2026-10-10 10:55:10,263 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 90/118 for batch 1.
2026-10-10 10:55:10,991 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 100/118 for batch 1.
2026-10-10 10:55:11,722 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 110/118 for batch 1.
2026-10-10 10:55:12,329 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Stored observations 118/118 for batch 1.
2026-10-10 10:55:12,329 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 1/9 in strips of 21 rows.
2026-10-10 10:55:14,049 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 2/9 in strips of 21 rows.
2026-10-10 10:55:15,782 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 3/9 in strips of 21 rows.
2026-10-10 10:55:17,482 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 4/9 in strips of 21 rows.
2026-10-10 10:55:19,221 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 5/9 in strips of 21 rows.
2026-10-10 10:55:20,956 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 6/9 in strips of 21 rows.
2026-10-10 10:55:22,669 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 7/9 in strips of 21 rows.
2026-10-10 10:55:24,391 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 8/9 in strips of 21 rows.
2026-10-10 10:55:26,105 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Temporal filling band 9/9 in strips of 21 rows.
2026-10-10 10:55:28,015 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 1/118 for batch 1.
2026-10-10 10:55:28,151 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 2/118 for batch 1.
2026-10-10 10:55:28,191 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 3/118 for batch 1.
2026-10-10 10:55:28,228 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 4/118 for batch 1.
2026-10-10 10:55:28,264 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 5/118 for batch 1.
2026-10-10 10:55:28,303 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 6/118 for batch 1.
2026-10-10 10:55:28,351 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 7/118 for batch 1.
2026-10-10 10:55:28,386 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 8/118 for batch 1.
2026-10-10 10:55:28,692 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 9/118 for batch 1.
2026-10-10 10:55:29,008 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 10/118 for batch 1.
2026-10-10 10:55:29,051 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 11/118 for batch 1.
2026-10-10 10:55:29,087 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 12/118 for batch 1.
2026-10-10 10:55:29,123 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 13/118 for batch 1.
2026-10-10 10:55:29,162 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 14/118 for batch 1.
2026-10-10 10:55:29,203 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 15/118 for batch 1.
2026-10-10 10:55:29,507 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 16/118 for batch 1.
2026-10-10 10:55:29,545 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 17/118 for batch 1.
2026-10-10 10:55:29,587 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 18/118 for batch 1.
2026-10-10 10:55:29,623 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 19/118 for batch 1.
2026-10-10 10:55:29,660 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 20/118 for batch 1.
2026-10-10 10:55:29,702 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 21/118 for batch 1.
2026-10-10 10:55:29,741 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 22/118 for batch 1.
2026-10-10 10:55:29,779 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 23/118 for batch 1.
2026-10-10 10:55:29,821 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 24/118 for batch 1.
2026-10-10 10:55:29,859 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 25/118 for batch 1.
2026-10-10 10:55:29,904 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 26/118 for batch 1.
2026-10-10 10:55:29,940 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 27/118 for batch 1.
2026-10-10 10:55:29,979 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 28/118 for batch 1.
2026-10-10 10:55:30,290 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 29/118 for batch 1.
2026-10-10 10:55:30,335 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 30/118 for batch 1.
2026-10-10 10:55:30,371 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 31/118 for batch 1.
2026-10-10 10:55:30,407 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 32/118 for batch 1.
2026-10-10 10:55:30,450 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 33/118 for batch 1.
2026-10-10 10:55:30,486 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 34/118 for batch 1.
2026-10-10 10:55:30,522 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 35/118 for batch 1.
2026-10-10 10:55:30,559 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 36/118 for batch 1.
2026-10-10 10:55:30,603 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 37/118 for batch 1.
2026-10-10 10:55:30,640 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 38/118 for batch 1.
2026-10-10 10:55:30,683 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 39/118 for batch 1.
2026-10-10 10:55:30,993 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 40/118 for batch 1.
2026-10-10 10:55:31,030 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 41/118 for batch 1.
2026-10-10 10:55:31,070 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 42/118 for batch 1.
2026-10-10 10:55:31,106 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 43/118 for batch 1.
2026-10-10 10:55:31,143 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 44/118 for batch 1.
2026-10-10 10:55:31,464 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 45/118 for batch 1.
2026-10-10 10:55:31,781 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 46/118 for batch 1.
2026-10-10 10:55:31,819 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 47/118 for batch 1.
2026-10-10 10:55:31,856 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 48/118 for batch 1.
2026-10-10 10:55:31,892 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 49/118 for batch 1.
2026-10-10 10:55:32,206 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 50/118 for batch 1.
2026-10-10 10:55:32,522 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 51/118 for batch 1.
2026-10-10 10:55:32,560 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 52/118 for batch 1.
2026-10-10 10:55:32,599 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 53/118 for batch 1.
2026-10-10 10:55:32,639 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 54/118 for batch 1.
2026-10-10 10:55:32,679 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 55/118 for batch 1.
2026-10-10 10:55:33,036 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 56/118 for batch 1.
2026-10-10 10:55:33,080 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 57/118 for batch 1.
2026-10-10 10:55:33,441 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 58/118 for batch 1.
2026-10-10 10:55:33,489 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 59/118 for batch 1.
2026-10-10 10:55:33,537 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 60/118 for batch 1.
2026-10-10 10:55:33,581 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 61/118 for batch 1.
2026-10-10 10:55:33,624 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 62/118 for batch 1.
2026-10-10 10:55:33,664 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 63/118 for batch 1.
2026-10-10 10:55:33,706 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 64/118 for batch 1.
2026-10-10 10:55:33,752 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 65/118 for batch 1.
2026-10-10 10:55:33,789 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 66/118 for batch 1.
2026-10-10 10:55:33,826 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 67/118 for batch 1.
2026-10-10 10:55:33,865 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 68/118 for batch 1.
2026-10-10 10:55:33,906 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 69/118 for batch 1.
2026-10-10 10:55:33,945 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 70/118 for batch 1.
2026-10-10 10:55:33,986 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 71/118 for batch 1.
2026-10-10 10:55:34,026 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 72/118 for batch 1.
2026-10-10 10:55:34,066 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 73/118 for batch 1.
2026-10-10 10:55:34,106 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 74/118 for batch 1.
2026-10-10 10:55:34,146 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 75/118 for batch 1.
2026-10-10 10:55:34,190 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 76/118 for batch 1.
2026-10-10 10:55:34,234 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 77/118 for batch 1.
2026-10-10 10:55:34,569 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 78/118 for batch 1.
2026-10-10 10:55:34,881 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 79/118 for batch 1.
2026-10-10 10:55:34,917 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 80/118 for batch 1.
2026-10-10 10:55:34,956 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 81/118 for batch 1.
2026-10-10 10:55:34,993 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 82/118 for batch 1.
2026-10-10 10:55:35,031 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 83/118 for batch 1.
2026-10-10 10:55:35,353 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 84/118 for batch 1.
2026-10-10 10:55:35,391 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 85/118 for batch 1.
2026-10-10 10:55:35,429 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 86/118 for batch 1.
2026-10-10 10:55:35,468 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 87/118 for batch 1.
2026-10-10 10:55:35,505 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 88/118 for batch 1.
2026-10-10 10:55:35,542 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 89/118 for batch 1.
2026-10-10 10:55:35,581 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 90/118 for batch 1.
2026-10-10 10:55:35,621 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 91/118 for batch 1.
2026-10-10 10:55:35,657 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 92/118 for batch 1.
2026-10-10 10:55:35,694 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 93/118 for batch 1.
2026-10-10 10:55:35,731 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 94/118 for batch 1.
2026-10-10 10:55:35,769 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 95/118 for batch 1.
2026-10-10 10:55:35,806 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 96/118 for batch 1.
2026-10-10 10:55:35,843 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 97/118 for batch 1.
2026-10-10 10:55:35,882 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 98/118 for batch 1.
2026-10-10 10:55:35,920 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 99/118 for batch 1.
2026-10-10 10:55:35,957 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 100/118 for batch 1.
2026-10-10 10:55:35,997 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 101/118 for batch 1.
2026-10-10 10:55:36,034 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 102/118 for batch 1.
2026-10-10 10:55:36,072 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 103/118 for batch 1.
2026-10-10 10:55:36,109 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 104/118 for batch 1.
2026-10-10 10:55:36,148 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 105/118 for batch 1.
2026-10-10 10:55:36,191 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 106/118 for batch 1.
2026-10-10 10:55:36,230 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 107/118 for batch 1.
2026-10-10 10:55:36,267 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 108/118 for batch 1.
2026-10-10 10:55:36,305 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 109/118 for batch 1.
2026-10-10 10:55:36,626 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 110/118 for batch 1.
2026-10-10 10:55:36,671 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 111/118 for batch 1.
2026-10-10 10:55:36,710 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 112/118 for batch 1.
2026-10-10 10:55:36,751 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 113/118 for batch 1.
2026-10-10 10:55:36,790 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 114/118 for batch 1.
2026-10-10 10:55:36,828 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 115/118 for batch 1.
2026-10-10 10:55:36,868 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 116/118 for batch 1.
2026-10-10 10:55:37,201 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 117/118 for batch 1.
2026-10-10 10:55:37,523 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Cleaned acquisition 118/118 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_17/monthly_cubes/dfc028bb33fc50ae-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:55:38,489 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 10/118.
2026-10-10 10:55:39,357 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 20/118.
2026-10-10 10:55:40,196 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 30/118.
2026-10-10 10:55:41,055 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 40/118.
2026-10-10 10:55:41,882 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 50/118.
2026-10-10 10:55:42,740 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 60/118.
2026-10-10 10:55:43,576 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 70/118.
2026-10-10 10:55:44,429 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 80/118.
2026-10-10 10:55:45,291 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 90/118.
2026-10-10 10:55:46,180 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 100/118.
2026-10-10 10:55:47,022 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 110/118.
2026-10-10 10:55:48,083 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Saved output indices for acquisition 118/118.
2026-10-10 10:55:48,350 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\monthly_cubes\dfc028bb33fc50ae-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_17/monthly_cubes/dfc028bb33fc50ae-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\rasterio\features.py:382: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  _rasterize(valid_shapes, out, transform, all_touched, merge_alg)
2026-10-10 10:55:50,082 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 2 parcels from batch_00001_monthly.nc.
2026-10-10 10:55:50,824 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\monthly_cubes\f5ddfff5ad2ac99c-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 10:55:52,383 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 10/108 for batch 1.
2026-10-10 10:55:53,722 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 20/108 for batch 1.

Created job j-26101007555441a8a6fe644054cad30b: partition 20, batch 8, user esagovhub4@gmail.com.

2026-10-10 10:55:55,038 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 30/108 for batch 1.
2026-10-10 10:55:56,393 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 40/108 for batch 1.
2026-10-10 10:55:57,665 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 50/108 for batch 1.
2026-10-10 10:55:58,987 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 60/108 for batch 1.
2026-10-10 10:56:00,414 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 70/108 for batch 1.
2026-10-10 10:56:01,845 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 80/108 for batch 1.
2026-10-10 10:56:03,321 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 90/108 for batch 1.
2026-10-10 10:56:04,693 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 100/108 for batch 1.
2026-10-10 10:56:05,830 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Stored observations 108/108 for batch 1.
2026-10-10 10:56:05,831 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 1/9 in strips of 27 rows.
2026-10-10 10:56:08,951 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 2/9 in strips of 27 rows.
2026-10-10 10:56:12,043 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 3/9 in strips of 27 rows.
2026-10-10 10:56:15,139 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 4/9 in strips of 27 rows.
2026-10-10 10:56:18,240 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 5/9 in strips of 27 rows.
2026-10-10 10:56:21,333 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 6/9 in strips of 27 rows.
2026-10-10 10:56:24,426 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 7/9 in strips of 27 rows.
2026-10-10 10:56:27,581 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 8/9 in strips of 27 rows.
2026-10-10 10:56:30,664 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Temporal filling band 9/9 in strips of 27 rows.
2026-10-10 10:56:34,775 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 1/108 for batch 1.
2026-10-10 10:56:34,858 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 2/108 for batch 1.
2026-10-10 10:56:34,937 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 3/108 for batch 1.
2026-10-10 10:56:35,020 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 4/108 for batch 1.
2026-10-10 10:56:35,097 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 5/108 for batch 1.
2026-10-10 10:56:35,175 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 6/108 for batch 1.
2026-10-10 10:56:35,257 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 7/108 for batch 1.
2026-10-10 10:56:35,327 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 8/108 for batch 1.
2026-10-10 10:56:35,400 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 9/108 for batch 1.
2026-10-10 10:56:35,483 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 10/108 for batch 1.
2026-10-10 10:56:35,562 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 11/108 for batch 1.
2026-10-10 10:56:35,645 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 12/108 for batch 1.
2026-10-10 10:56:35,967 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 13/108 for batch 1.
2026-10-10 10:56:36,285 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 14/108 for batch 1.
2026-10-10 10:56:36,358 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 15/108 for batch 1.
2026-10-10 10:56:36,431 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 16/108 for batch 1.
2026-10-10 10:56:37,200 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 17/108 for batch 1.
2026-10-10 10:56:37,269 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 18/108 for batch 1.
2026-10-10 10:56:37,339 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 19/108 for batch 1.
2026-10-10 10:56:37,423 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 20/108 for batch 1.
2026-10-10 10:56:37,508 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 21/108 for batch 1.
2026-10-10 10:56:37,595 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 22/108 for batch 1.
2026-10-10 10:56:37,678 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 23/108 for batch 1.
2026-10-10 10:56:37,747 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 24/108 for batch 1.
2026-10-10 10:56:37,817 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 25/108 for batch 1.
2026-10-10 10:56:37,902 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 26/108 for batch 1.
2026-10-10 10:56:37,971 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 27/108 for batch 1.
2026-10-10 10:56:38,300 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 28/108 for batch 1.
2026-10-10 10:56:38,386 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 29/108 for batch 1.
2026-10-10 10:56:38,470 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 30/108 for batch 1.
2026-10-10 10:56:39,047 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 31/108 for batch 1.
2026-10-10 10:56:39,136 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 32/108 for batch 1.
2026-10-10 10:56:39,205 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 33/108 for batch 1.
2026-10-10 10:56:39,276 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 34/108 for batch 1.
2026-10-10 10:56:39,362 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 35/108 for batch 1.
2026-10-10 10:56:39,432 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 36/108 for batch 1.
2026-10-10 10:56:39,502 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 37/108 for batch 1.
2026-10-10 10:56:39,573 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 38/108 for batch 1.
2026-10-10 10:56:39,657 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 39/108 for batch 1.
2026-10-10 10:56:40,431 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 40/108 for batch 1.
2026-10-10 10:56:40,502 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 41/108 for batch 1.
2026-10-10 10:56:41,294 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 42/108 for batch 1.
2026-10-10 10:56:41,378 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 43/108 for batch 1.
2026-10-10 10:56:42,153 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 44/108 for batch 1.
2026-10-10 10:56:42,244 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 45/108 for batch 1.
2026-10-10 10:56:42,312 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 46/108 for batch 1.
2026-10-10 10:56:42,395 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 47/108 for batch 1.
2026-10-10 10:56:42,464 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 48/108 for batch 1.
2026-10-10 10:56:42,535 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 49/108 for batch 1.
2026-10-10 10:56:42,609 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 50/108 for batch 1.
2026-10-10 10:56:43,378 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 51/108 for batch 1.
2026-10-10 10:56:43,466 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 52/108 for batch 1.
2026-10-10 10:56:44,244 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 53/108 for batch 1.
2026-10-10 10:56:44,315 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 54/108 for batch 1.
2026-10-10 10:56:45,085 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 55/108 for batch 1.
2026-10-10 10:56:45,169 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 56/108 for batch 1.
2026-10-10 10:56:45,948 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 57/108 for batch 1.
2026-10-10 10:56:46,018 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 58/108 for batch 1.
2026-10-10 10:56:46,800 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 59/108 for batch 1.
2026-10-10 10:56:47,585 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 60/108 for batch 1.
2026-10-10 10:56:47,670 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 61/108 for batch 1.
2026-10-10 10:56:47,747 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 62/108 for batch 1.
2026-10-10 10:56:47,831 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 63/108 for batch 1.
2026-10-10 10:56:47,901 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 64/108 for batch 1.
2026-10-10 10:56:47,984 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 65/108 for batch 1.
2026-10-10 10:56:48,767 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 66/108 for batch 1.
2026-10-10 10:56:49,579 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 67/108 for batch 1.
2026-10-10 10:56:49,660 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 68/108 for batch 1.
2026-10-10 10:56:49,728 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 69/108 for batch 1.
2026-10-10 10:56:49,809 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 70/108 for batch 1.
2026-10-10 10:56:49,877 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 71/108 for batch 1.
2026-10-10 10:56:49,947 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 72/108 for batch 1.
2026-10-10 10:56:50,030 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 73/108 for batch 1.
2026-10-10 10:56:50,103 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 74/108 for batch 1.
2026-10-10 10:56:50,186 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 75/108 for batch 1.
2026-10-10 10:56:50,255 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 76/108 for batch 1.
2026-10-10 10:56:50,338 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 77/108 for batch 1.
2026-10-10 10:56:50,411 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 78/108 for batch 1.
2026-10-10 10:56:50,483 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 79/108 for batch 1.
2026-10-10 10:56:50,570 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 80/108 for batch 1.
2026-10-10 10:56:50,888 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 81/108 for batch 1.
2026-10-10 10:56:50,972 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 82/108 for batch 1.
2026-10-10 10:56:51,043 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 83/108 for batch 1.
2026-10-10 10:56:51,114 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 84/108 for batch 1.
2026-10-10 10:56:51,196 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 85/108 for batch 1.
2026-10-10 10:56:51,266 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 86/108 for batch 1.
2026-10-10 10:56:51,349 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 87/108 for batch 1.
2026-10-10 10:56:51,419 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 88/108 for batch 1.
2026-10-10 10:56:51,488 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 89/108 for batch 1.
2026-10-10 10:56:51,558 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 90/108 for batch 1.
2026-10-10 10:56:51,641 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 91/108 for batch 1.
2026-10-10 10:56:51,712 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 92/108 for batch 1.
2026-10-10 10:56:51,795 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 93/108 for batch 1.
2026-10-10 10:56:51,865 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 94/108 for batch 1.
2026-10-10 10:56:51,933 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 95/108 for batch 1.
2026-10-10 10:56:52,022 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 96/108 for batch 1.
2026-10-10 10:56:52,098 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 97/108 for batch 1.
2026-10-10 10:56:52,184 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 98/108 for batch 1.
2026-10-10 10:56:52,257 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 99/108 for batch 1.
2026-10-10 10:56:52,343 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 100/108 for batch 1.
2026-10-10 10:56:52,414 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 101/108 for batch 1.
2026-10-10 10:56:53,363 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 102/108 for batch 1.
2026-10-10 10:56:53,471 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 103/108 for batch 1.
2026-10-10 10:56:53,551 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 104/108 for batch 1.
2026-10-10 10:56:53,632 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 105/108 for batch 1.
2026-10-10 10:56:53,701 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 106/108 for batch 1.
2026-10-10 10:56:53,771 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 107/108 for batch 1.
2026-10-10 10:56:53,855 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Cleaned acquisition 108/108 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_16/monthly_cubes/f5ddfff5ad2ac99c-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 10:56:55,863 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 10/108.
2026-10-10 10:56:57,793 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 20/108.
2026-10-10 10:56:59,656 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 30/108.
2026-10-10 10:57:01,560 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 40/108.
2026-10-10 10:57:03,389 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 50/108.
2026-10-10 10:57:05,353 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 60/108.
2026-10-10 10:57:07,218 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 70/108.
2026-10-10 10:57:09,029 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 80/108.
2026-10-10 10:57:10,934 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 90/108.
2026-10-10 10:57:12,930 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 100/108.
2026-10-10 10:57:14,534 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Saved output indices for acquisition 108/108.
2026-10-10 10:57:14,968 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\monthly_cubes\f5ddfff5ad2ac99c-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_16/monthly_cubes/f5ddfff5ad2ac99c-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 10:57:30,668 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 19 parcels from batch_00001_monthly.nc.
2026-10-10 10:57:31,749 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00004_monthly.nc.
2026-10-10 10:57:33,340 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 10/156 for batch 4.
2026-10-10 10:57:34,857 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 20/156 for batch 4.

Created job j-26101007573647eb823bb6221afaf2f8: partition 20, batch 9, user katrinporo@gmail.com.

2026-10-10 10:57:36,288 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 30/156 for batch 4.
2026-10-10 10:57:37,805 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 40/156 for batch 4.
2026-10-10 10:57:39,239 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 50/156 for batch 4.
2026-10-10 10:57:40,746 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 60/156 for batch 4.
2026-10-10 10:57:42,330 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 70/156 for batch 4.
2026-10-10 10:57:43,840 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 80/156 for batch 4.
2026-10-10 10:57:45,404 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 90/156 for batch 4.
2026-10-10 10:57:46,925 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 100/156 for batch 4.
2026-10-10 10:57:48,538 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 110/156 for batch 4.
2026-10-10 10:57:50,228 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 120/156 for batch 4.
2026-10-10 10:57:51,775 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 130/156 for batch 4.
2026-10-10 10:57:53,453 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 140/156 for batch 4.
2026-10-10 10:57:55,098 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 150/156 for batch 4.
2026-10-10 10:57:56,047 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 156/156 for batch 4.
2026-10-10 10:57:56,048 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 1/9 in strips of 11 rows.
2026-10-10 10:58:05,054 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 2/9 in strips of 11 rows.
2026-10-10 10:58:13,926 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 3/9 in strips of 11 rows.
2026-10-10 10:58:22,850 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 4/9 in strips of 11 rows.
2026-10-10 10:58:31,841 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 5/9 in strips of 11 rows.
2026-10-10 10:58:41,164 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 6/9 in strips of 11 rows.
2026-10-10 10:58:50,126 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 7/9 in strips of 11 rows.
2026-10-10 10:58:58,998 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 8/9 in strips of 11 rows.
2026-10-10 10:59:07,879 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 9/9 in strips of 11 rows.
2026-10-10 10:59:16,811 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 1/156 for batch 4.
2026-10-10 10:59:16,890 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 2/156 for batch 4.
2026-10-10 10:59:16,965 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 3/156 for batch 4.
2026-10-10 10:59:17,080 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 4/156 for batch 4.
2026-10-10 10:59:17,159 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 5/156 for batch 4.
2026-10-10 10:59:17,233 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 6/156 for batch 4.
2026-10-10 10:59:17,307 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 7/156 for batch 4.
2026-10-10 10:59:18,177 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 8/156 for batch 4.
2026-10-10 10:59:18,296 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 9/156 for batch 4.
2026-10-10 10:59:19,170 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 10/156 for batch 4.
2026-10-10 10:59:20,043 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 11/156 for batch 4.
2026-10-10 10:59:20,123 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 12/156 for batch 4.
2026-10-10 10:59:20,314 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 13/156 for batch 4.
2026-10-10 10:59:21,019 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 14/156 for batch 4.
2026-10-10 10:59:21,096 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 15/156 for batch 4.
2026-10-10 10:59:21,178 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 16/156 for batch 4.
2026-10-10 10:59:22,062 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 17/156 for batch 4.
2026-10-10 10:59:22,139 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 18/156 for batch 4.
2026-10-10 10:59:22,230 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 19/156 for batch 4.
2026-10-10 10:59:23,134 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 20/156 for batch 4.
2026-10-10 10:59:23,210 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 21/156 for batch 4.
2026-10-10 10:59:23,327 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 22/156 for batch 4.
2026-10-10 10:59:23,403 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 23/156 for batch 4.
2026-10-10 10:59:23,478 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 24/156 for batch 4.
2026-10-10 10:59:24,352 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 25/156 for batch 4.
2026-10-10 10:59:24,447 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 26/156 for batch 4.
2026-10-10 10:59:24,524 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 27/156 for batch 4.
2026-10-10 10:59:24,600 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 28/156 for batch 4.
2026-10-10 10:59:24,674 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 29/156 for batch 4.
2026-10-10 10:59:24,765 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 30/156 for batch 4.
2026-10-10 10:59:24,838 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 31/156 for batch 4.
2026-10-10 10:59:24,928 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 32/156 for batch 4.
2026-10-10 10:59:25,004 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 33/156 for batch 4.
2026-10-10 10:59:25,876 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 34/156 for batch 4.
2026-10-10 10:59:25,967 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 35/156 for batch 4.
2026-10-10 10:59:26,041 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 36/156 for batch 4.
2026-10-10 10:59:26,116 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 37/156 for batch 4.
2026-10-10 10:59:26,190 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 38/156 for batch 4.
2026-10-10 10:59:26,279 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 39/156 for batch 4.
2026-10-10 10:59:26,356 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 40/156 for batch 4.
2026-10-10 10:59:26,431 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 41/156 for batch 4.
2026-10-10 10:59:26,506 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 42/156 for batch 4.
2026-10-10 10:59:26,585 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 43/156 for batch 4.
2026-10-10 10:59:26,683 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 44/156 for batch 4.
2026-10-10 10:59:26,765 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 45/156 for batch 4.
2026-10-10 10:59:27,645 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 46/156 for batch 4.
2026-10-10 10:59:27,740 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 47/156 for batch 4.
2026-10-10 10:59:28,622 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 48/156 for batch 4.
2026-10-10 10:59:28,716 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 49/156 for batch 4.
2026-10-10 10:59:28,793 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 50/156 for batch 4.
2026-10-10 10:59:28,871 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 51/156 for batch 4.
2026-10-10 10:59:28,947 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 52/156 for batch 4.
2026-10-10 10:59:29,039 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 53/156 for batch 4.
2026-10-10 10:59:29,117 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 54/156 for batch 4.
2026-10-10 10:59:29,192 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 55/156 for batch 4.
2026-10-10 10:59:29,267 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 56/156 for batch 4.
2026-10-10 10:59:30,156 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 57/156 for batch 4.
2026-10-10 10:59:30,263 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 58/156 for batch 4.
2026-10-10 10:59:30,338 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 59/156 for batch 4.
2026-10-10 10:59:30,413 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 60/156 for batch 4.
2026-10-10 10:59:31,084 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 61/156 for batch 4.
2026-10-10 10:59:31,176 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 62/156 for batch 4.
2026-10-10 10:59:31,254 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 63/156 for batch 4.
2026-10-10 10:59:31,371 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 64/156 for batch 4.
2026-10-10 10:59:31,448 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 65/156 for batch 4.
2026-10-10 10:59:31,523 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 66/156 for batch 4.
2026-10-10 10:59:31,656 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 67/156 for batch 4.
2026-10-10 10:59:31,733 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 68/156 for batch 4.
2026-10-10 10:59:31,812 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 69/156 for batch 4.
2026-10-10 10:59:31,904 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 70/156 for batch 4.
2026-10-10 10:59:31,979 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 71/156 for batch 4.
2026-10-10 10:59:32,057 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 72/156 for batch 4.
2026-10-10 10:59:32,150 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 73/156 for batch 4.
2026-10-10 10:59:33,082 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 74/156 for batch 4.
2026-10-10 10:59:34,044 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 75/156 for batch 4.
2026-10-10 10:59:34,163 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 76/156 for batch 4.
2026-10-10 10:59:35,077 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 77/156 for batch 4.
2026-10-10 10:59:35,170 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 78/156 for batch 4.
2026-10-10 10:59:35,251 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 79/156 for batch 4.
2026-10-10 10:59:35,369 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 80/156 for batch 4.
2026-10-10 10:59:35,445 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 81/156 for batch 4.
2026-10-10 10:59:35,521 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 82/156 for batch 4.
2026-10-10 10:59:35,597 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 83/156 for batch 4.
2026-10-10 10:59:35,690 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 84/156 for batch 4.
2026-10-10 10:59:35,766 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 85/156 for batch 4.
2026-10-10 10:59:35,843 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 86/156 for batch 4.
2026-10-10 10:59:35,938 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 87/156 for batch 4.
2026-10-10 10:59:36,015 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 88/156 for batch 4.
2026-10-10 10:59:36,091 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 89/156 for batch 4.
2026-10-10 10:59:36,170 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 90/156 for batch 4.
2026-10-10 10:59:36,264 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 91/156 for batch 4.
2026-10-10 10:59:36,341 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 92/156 for batch 4.
2026-10-10 10:59:36,436 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 93/156 for batch 4.
2026-10-10 10:59:36,512 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 94/156 for batch 4.
2026-10-10 10:59:36,610 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 95/156 for batch 4.
2026-10-10 10:59:36,689 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 96/156 for batch 4.
2026-10-10 10:59:36,770 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 97/156 for batch 4.
2026-10-10 10:59:36,867 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 98/156 for batch 4.
2026-10-10 10:59:36,945 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 99/156 for batch 4.
2026-10-10 10:59:37,024 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 100/156 for batch 4.
2026-10-10 10:59:37,102 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 101/156 for batch 4.
2026-10-10 10:59:37,200 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 102/156 for batch 4.
2026-10-10 10:59:37,281 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 103/156 for batch 4.
2026-10-10 10:59:37,357 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 104/156 for batch 4.
2026-10-10 10:59:37,450 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 105/156 for batch 4.
2026-10-10 10:59:37,526 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 106/156 for batch 4.
2026-10-10 10:59:37,603 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 107/156 for batch 4.
2026-10-10 10:59:37,681 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 108/156 for batch 4.
2026-10-10 10:59:37,780 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 109/156 for batch 4.
2026-10-10 10:59:37,858 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 110/156 for batch 4.
2026-10-10 10:59:37,937 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 111/156 for batch 4.
2026-10-10 10:59:38,015 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 112/156 for batch 4.
2026-10-10 10:59:38,108 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 113/156 for batch 4.
2026-10-10 10:59:38,186 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 114/156 for batch 4.
2026-10-10 10:59:38,263 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 115/156 for batch 4.
2026-10-10 10:59:38,354 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 116/156 for batch 4.
2026-10-10 10:59:38,433 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 117/156 for batch 4.
2026-10-10 10:59:38,512 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 118/156 for batch 4.
2026-10-10 10:59:38,588 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 119/156 for batch 4.
2026-10-10 10:59:38,684 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 120/156 for batch 4.
2026-10-10 10:59:38,763 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 121/156 for batch 4.
2026-10-10 10:59:39,661 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 122/156 for batch 4.
2026-10-10 10:59:39,756 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 123/156 for batch 4.
2026-10-10 10:59:39,833 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 124/156 for batch 4.
2026-10-10 10:59:39,911 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 125/156 for batch 4.
2026-10-10 10:59:40,813 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 126/156 for batch 4.
2026-10-10 10:59:40,910 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 127/156 for batch 4.
2026-10-10 10:59:40,988 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 128/156 for batch 4.
2026-10-10 10:59:41,069 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 129/156 for batch 4.
2026-10-10 10:59:41,146 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 130/156 for batch 4.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00004_monthly_cleaning_report.partial.parquet

2026-10-10 10:59:46,157 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 10/156.
2026-10-10 10:59:48,277 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 20/156.
2026-10-10 10:59:50,384 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 30/156.
2026-10-10 10:59:52,526 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 40/156.
2026-10-10 10:59:54,617 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 50/156.
2026-10-10 10:59:56,691 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 60/156.
2026-10-10 10:59:59,063 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 70/156.
2026-10-10 11:00:01,090 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 80/156.
2026-10-10 11:00:03,133 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 90/156.
2026-10-10 11:00:05,194 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 100/156.
2026-10-10 11:00:07,271 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 110/156.
2026-10-10 11:00:09,393 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 120/156.
2026-10-10 11:00:11,432 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 130/156.
2026-10-10 11:00:13,481 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 140/156.
2026-10-10 11:00:15,494 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 150/156.
2026-10-10 11:00:16,751 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 156/156.
2026-10-10 11:00:17,316 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00004_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00004_monthly_cleaning_report.parquet

2026-10-10 11:00:19,174 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 2 parcels from batch_00004_monthly.nc.
2026-10-10 11:00:20,634 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\monthly_cubes\39e1ea790e35dd81-tiles-669b4d35\batch_00002_monthly.nc.
2026-10-10 11:00:22,415 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 10/147 for batch 2.
2026-10-10 11:00:24,063 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 20/147 for batch 2.
2026-10-10 11:00:25,774 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 30/147 for batch 2.
2026-10-10 11:00:27,298 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 40/147 for batch 2.
2026-10-10 11:00:29,042 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 50/147 for batch 2.
2026-10-10 11:00:30,653 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 60/147 for batch 2.
2026-10-10 11:00:32,241 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 70/147 for batch 2.
2026-10-10 11:00:33,984 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 80/147 for batch 2.
2026-10-10 11:00:35,814 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 90/147 for batch 2.
2026-10-10 11:00:37,568 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 100/147 for batch 2.

Created job j-2610100800394e90a2ed8ee8a2cd3ba2: partition 20, batch 10, user esagovhub2@gmail.com.

2026-10-10 11:00:39,392 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 110/147 for batch 2.
2026-10-10 11:00:41,092 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 120/147 for batch 2.
2026-10-10 11:00:42,710 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 130/147 for batch 2.
2026-10-10 11:00:44,390 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 140/147 for batch 2.
2026-10-10 11:00:45,538 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 147/147 for batch 2.
2026-10-10 11:00:45,539 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 1/9 in strips of 14 rows.
2026-10-10 11:00:52,846 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 2/9 in strips of 14 rows.
2026-10-10 11:01:00,067 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 3/9 in strips of 14 rows.
2026-10-10 11:01:07,241 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 4/9 in strips of 14 rows.
2026-10-10 11:01:14,496 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 5/9 in strips of 14 rows.
2026-10-10 11:01:21,750 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 6/9 in strips of 14 rows.
2026-10-10 11:01:28,950 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 7/9 in strips of 14 rows.
2026-10-10 11:01:36,317 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 8/9 in strips of 14 rows.
2026-10-10 11:01:43,418 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 9/9 in strips of 14 rows.
2026-10-10 11:01:50,697 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 1/147 for batch 2.
2026-10-10 11:01:50,784 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 2/147 for batch 2.
2026-10-10 11:01:50,865 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 3/147 for batch 2.
2026-10-10 11:01:50,944 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 4/147 for batch 2.
2026-10-10 11:01:51,045 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 5/147 for batch 2.
2026-10-10 11:01:51,127 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 6/147 for batch 2.
2026-10-10 11:01:51,211 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 7/147 for batch 2.
2026-10-10 11:01:51,326 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 8/147 for batch 2.
2026-10-10 11:01:51,408 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 9/147 for batch 2.
2026-10-10 11:01:51,488 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 10/147 for batch 2.
2026-10-10 11:01:51,568 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 11/147 for batch 2.
2026-10-10 11:01:51,649 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 12/147 for batch 2.
2026-10-10 11:01:51,746 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 13/147 for batch 2.
2026-10-10 11:01:51,826 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 14/147 for batch 2.
2026-10-10 11:01:51,907 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 15/147 for batch 2.
2026-10-10 11:01:52,006 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 16/147 for batch 2.
2026-10-10 11:01:52,085 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 17/147 for batch 2.
2026-10-10 11:01:52,165 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 18/147 for batch 2.
2026-10-10 11:01:52,244 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 19/147 for batch 2.
2026-10-10 11:01:52,325 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 20/147 for batch 2.
2026-10-10 11:01:52,422 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 21/147 for batch 2.
2026-10-10 11:01:53,376 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 22/147 for batch 2.
2026-10-10 11:01:53,481 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 23/147 for batch 2.
2026-10-10 11:01:53,562 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 24/147 for batch 2.
2026-10-10 11:01:53,648 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 25/147 for batch 2.
2026-10-10 11:01:53,728 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 26/147 for batch 2.
2026-10-10 11:01:53,827 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 27/147 for batch 2.
2026-10-10 11:01:53,911 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 28/147 for batch 2.
2026-10-10 11:01:53,993 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 29/147 for batch 2.
2026-10-10 11:01:54,075 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 30/147 for batch 2.
2026-10-10 11:01:54,173 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 31/147 for batch 2.
2026-10-10 11:01:55,128 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 32/147 for batch 2.
2026-10-10 11:01:55,230 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 33/147 for batch 2.
2026-10-10 11:01:55,312 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 34/147 for batch 2.
2026-10-10 11:01:55,395 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 35/147 for batch 2.
2026-10-10 11:01:55,477 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 36/147 for batch 2.
2026-10-10 11:01:55,559 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 37/147 for batch 2.
2026-10-10 11:01:55,640 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 38/147 for batch 2.
2026-10-10 11:01:55,740 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 39/147 for batch 2.
2026-10-10 11:01:55,821 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 40/147 for batch 2.
2026-10-10 11:01:55,902 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 41/147 for batch 2.
2026-10-10 11:01:56,000 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 42/147 for batch 2.
2026-10-10 11:01:56,402 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 43/147 for batch 2.
2026-10-10 11:01:56,498 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 44/147 for batch 2.
2026-10-10 11:01:57,447 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 45/147 for batch 2.
2026-10-10 11:01:57,549 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 46/147 for batch 2.
2026-10-10 11:01:57,632 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 47/147 for batch 2.
2026-10-10 11:01:57,725 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 48/147 for batch 2.
2026-10-10 11:01:57,824 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 49/147 for batch 2.
2026-10-10 11:01:58,778 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 50/147 for batch 2.
2026-10-10 11:01:58,877 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 51/147 for batch 2.
2026-10-10 11:01:59,588 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 52/147 for batch 2.
2026-10-10 11:01:59,989 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 53/147 for batch 2.
2026-10-10 11:02:00,391 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 54/147 for batch 2.
2026-10-10 11:02:00,472 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 55/147 for batch 2.
2026-10-10 11:02:00,554 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 56/147 for batch 2.
2026-10-10 11:02:01,287 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 57/147 for batch 2.
2026-10-10 11:02:02,004 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 58/147 for batch 2.
2026-10-10 11:02:02,719 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 59/147 for batch 2.
2026-10-10 11:02:03,696 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 60/147 for batch 2.
2026-10-10 11:02:03,794 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 61/147 for batch 2.
2026-10-10 11:02:03,877 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 62/147 for batch 2.
2026-10-10 11:02:03,957 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 63/147 for batch 2.
2026-10-10 11:02:04,911 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 64/147 for batch 2.
2026-10-10 11:02:04,992 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 65/147 for batch 2.
2026-10-10 11:02:05,073 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 66/147 for batch 2.
2026-10-10 11:02:05,154 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 67/147 for batch 2.
2026-10-10 11:02:05,234 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 68/147 for batch 2.
2026-10-10 11:02:05,331 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 69/147 for batch 2.
2026-10-10 11:02:06,293 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 70/147 for batch 2.
2026-10-10 11:02:07,258 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 71/147 for batch 2.
2026-10-10 11:02:07,341 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 72/147 for batch 2.
2026-10-10 11:02:08,306 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 73/147 for batch 2.
2026-10-10 11:02:08,406 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 74/147 for batch 2.
2026-10-10 11:02:08,800 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 75/147 for batch 2.
2026-10-10 11:02:08,891 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 76/147 for batch 2.
2026-10-10 11:02:08,973 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 77/147 for batch 2.
2026-10-10 11:02:09,072 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 78/147 for batch 2.
2026-10-10 11:02:10,030 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 79/147 for batch 2.
2026-10-10 11:02:10,113 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 80/147 for batch 2.
2026-10-10 11:02:10,198 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 81/147 for batch 2.
2026-10-10 11:02:10,285 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 82/147 for batch 2.
2026-10-10 11:02:10,368 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 83/147 for batch 2.
2026-10-10 11:02:10,474 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 84/147 for batch 2.
2026-10-10 11:02:10,563 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 85/147 for batch 2.
2026-10-10 11:02:10,644 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 86/147 for batch 2.
2026-10-10 11:02:10,745 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 87/147 for batch 2.
2026-10-10 11:02:10,827 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 88/147 for batch 2.
2026-10-10 11:02:10,909 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 89/147 for batch 2.
2026-10-10 11:02:10,991 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 90/147 for batch 2.
2026-10-10 11:02:11,090 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 91/147 for batch 2.
2026-10-10 11:02:11,171 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 92/147 for batch 2.
2026-10-10 11:02:11,252 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 93/147 for batch 2.
2026-10-10 11:02:11,351 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 94/147 for batch 2.
2026-10-10 11:02:12,330 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 95/147 for batch 2.
2026-10-10 11:02:13,285 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 96/147 for batch 2.
2026-10-10 11:02:14,248 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 97/147 for batch 2.
2026-10-10 11:02:14,352 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 98/147 for batch 2.
2026-10-10 11:02:14,431 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 99/147 for batch 2.
2026-10-10 11:02:14,514 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 100/147 for batch 2.
2026-10-10 11:02:14,600 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 101/147 for batch 2.
2026-10-10 11:02:14,700 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 102/147 for batch 2.
2026-10-10 11:02:14,781 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 103/147 for batch 2.
2026-10-10 11:02:14,864 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 104/147 for batch 2.
2026-10-10 11:02:14,963 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 105/147 for batch 2.
2026-10-10 11:02:15,063 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 106/147 for batch 2.
2026-10-10 11:02:15,143 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 107/147 for batch 2.
2026-10-10 11:02:15,224 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 108/147 for batch 2.
2026-10-10 11:02:15,323 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 109/147 for batch 2.
2026-10-10 11:02:15,404 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 110/147 for batch 2.
2026-10-10 11:02:15,486 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 111/147 for batch 2.
2026-10-10 11:02:15,585 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 112/147 for batch 2.
2026-10-10 11:02:15,676 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 113/147 for batch 2.
2026-10-10 11:02:15,761 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 114/147 for batch 2.
2026-10-10 11:02:15,860 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 115/147 for batch 2.
2026-10-10 11:02:15,942 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 116/147 for batch 2.
2026-10-10 11:02:16,026 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 117/147 for batch 2.
2026-10-10 11:02:16,123 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 118/147 for batch 2.
2026-10-10 11:02:16,206 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 119/147 for batch 2.
2026-10-10 11:02:16,289 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 120/147 for batch 2.
2026-10-10 11:02:16,388 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 121/147 for batch 2.
2026-10-10 11:02:17,372 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 122/147 for batch 2.
2026-10-10 11:02:17,455 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 123/147 for batch 2.
2026-10-10 11:02:17,536 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 124/147 for batch 2.
2026-10-10 11:02:17,635 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 125/147 for batch 2.
2026-10-10 11:02:17,717 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 126/147 for batch 2.
2026-10-10 11:02:17,799 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 127/147 for batch 2.
2026-10-10 11:02:17,897 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 128/147 for batch 2.
2026-10-10 11:02:17,979 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 129/147 for batch 2.
2026-10-10 11:02:18,060 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 130/147 for batch 2.
2026-10-10 11:02:18,141 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 131/147 for batch 2.
2026-10-10 11:02:18,239 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 132/147 for batch 2.
2026-10-10 11:02:18,321 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 133/147 for batch 2.
2026-10-10 11:02:18,410 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 134/147 for batch 2.
2026-10-10 11:02:18,498 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 135/147 for batch 2.
2026-10-10 11:02:18,595 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 136/147 for batch 2.
2026-10-10 11:02:18,675 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 137/147 for batch 2.
2026-10-10 11:02:18,755 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 138/147 for batch 2.
2026-10-10 11:02:18,853 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 139/147 for batch 2.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/monthly_cubes/39e1ea790e35dd81-tiles-669b4d35/batch_00002_monthly_cleaning_report.partial.parquet

2026-10-10 11:02:21,990 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 10/147.
2026-10-10 11:02:24,278 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 20/147.
2026-10-10 11:02:26,507 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 30/147.
2026-10-10 11:02:28,795 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 40/147.
2026-10-10 11:02:31,091 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 50/147.
2026-10-10 11:02:33,599 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 60/147.
2026-10-10 11:02:35,758 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 70/147.
2026-10-10 11:02:38,130 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 80/147.
2026-10-10 11:02:40,327 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 90/147.
2026-10-10 11:02:42,541 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 100/147.
2026-10-10 11:02:44,767 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 110/147.
2026-10-10 11:02:46,990 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 120/147.
2026-10-10 11:02:49,198 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 130/147.
2026-10-10 11:02:51,403 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 140/147.
2026-10-10 11:02:52,959 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 147/147.
2026-10-10 11:02:53,532 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\monthly_cubes\39e1ea790e35dd81-tiles-669b4d35\batch_00002_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/monthly_cubes/39e1ea790e35dd81-tiles-669b4d35/batch_00002_monthly_cleaning_report.parquet

2026-10-10 11:03:31,087 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 42 parcels from batch_00002_monthly.nc.
2026-10-10 11:03:32,540 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\monthly_cubes\2bd3fd9c29a04c5a-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 11:03:34,090 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 10/104 for batch 1.
2026-10-10 11:03:35,422 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 20/104 for batch 1.

Created job j-2610100803364926a37ecd6b836c7734: partition 20, batch 11, user sofiaargirou03@gmail.com.

2026-10-10 11:03:36,737 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 30/104 for batch 1.
2026-10-10 11:03:37,969 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 40/104 for batch 1.
2026-10-10 11:03:39,240 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 50/104 for batch 1.
2026-10-10 11:03:40,500 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 60/104 for batch 1.
2026-10-10 11:03:41,804 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 70/104 for batch 1.
2026-10-10 11:03:43,093 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 80/104 for batch 1.
2026-10-10 11:03:44,330 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 90/104 for batch 1.
2026-10-10 11:03:45,623 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 100/104 for batch 1.
2026-10-10 11:03:46,112 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Stored observations 104/104 for batch 1.
2026-10-10 11:03:46,112 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 1/9 in strips of 29 rows.
2026-10-10 11:03:48,856 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 2/9 in strips of 29 rows.
2026-10-10 11:03:51,591 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 3/9 in strips of 29 rows.
2026-10-10 11:03:54,385 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 4/9 in strips of 29 rows.
2026-10-10 11:03:57,113 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 5/9 in strips of 29 rows.
2026-10-10 11:03:59,860 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 6/9 in strips of 29 rows.
2026-10-10 11:04:02,645 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 7/9 in strips of 29 rows.
2026-10-10 11:04:05,407 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 8/9 in strips of 29 rows.
2026-10-10 11:04:08,149 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Temporal filling band 9/9 in strips of 29 rows.
2026-10-10 11:04:11,259 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 1/104 for batch 1.
2026-10-10 11:04:11,343 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 2/104 for batch 1.
2026-10-10 11:04:12,060 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 3/104 for batch 1.
2026-10-10 11:04:12,777 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 4/104 for batch 1.
2026-10-10 11:04:12,854 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 5/104 for batch 1.
2026-10-10 11:04:13,378 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 6/104 for batch 1.
2026-10-10 11:04:13,911 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 7/104 for batch 1.
2026-10-10 11:04:13,991 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 8/104 for batch 1.
2026-10-10 11:04:14,059 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 9/104 for batch 1.
2026-10-10 11:04:14,142 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 10/104 for batch 1.
2026-10-10 11:04:14,851 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 11/104 for batch 1.
2026-10-10 11:04:15,557 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 12/104 for batch 1.
2026-10-10 11:04:15,622 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 13/104 for batch 1.
2026-10-10 11:04:15,686 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 14/104 for batch 1.
2026-10-10 11:04:15,749 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 15/104 for batch 1.
2026-10-10 11:04:15,831 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 16/104 for batch 1.
2026-10-10 11:04:15,896 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 17/104 for batch 1.
2026-10-10 11:04:15,972 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 18/104 for batch 1.
2026-10-10 11:04:16,676 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 19/104 for batch 1.
2026-10-10 11:04:16,753 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 20/104 for batch 1.
2026-10-10 11:04:17,045 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 21/104 for batch 1.
2026-10-10 11:04:17,342 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 22/104 for batch 1.
2026-10-10 11:04:17,419 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 23/104 for batch 1.
2026-10-10 11:04:17,483 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 24/104 for batch 1.
2026-10-10 11:04:17,546 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 25/104 for batch 1.
2026-10-10 11:04:17,626 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 26/104 for batch 1.
2026-10-10 11:04:17,690 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 27/104 for batch 1.
2026-10-10 11:04:17,756 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 28/104 for batch 1.
2026-10-10 11:04:17,831 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 29/104 for batch 1.
2026-10-10 11:04:18,537 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 30/104 for batch 1.
2026-10-10 11:04:18,616 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 31/104 for batch 1.
2026-10-10 11:04:18,911 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 32/104 for batch 1.
2026-10-10 11:04:18,991 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 33/104 for batch 1.
2026-10-10 11:04:19,293 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 34/104 for batch 1.
2026-10-10 11:04:19,590 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 35/104 for batch 1.
2026-10-10 11:04:19,667 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 36/104 for batch 1.
2026-10-10 11:04:20,391 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 37/104 for batch 1.
2026-10-10 11:04:20,457 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 38/104 for batch 1.
2026-10-10 11:04:20,522 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 39/104 for batch 1.
2026-10-10 11:04:21,228 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 40/104 for batch 1.
2026-10-10 11:04:21,937 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 41/104 for batch 1.
2026-10-10 11:04:22,002 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 42/104 for batch 1.
2026-10-10 11:04:22,067 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 43/104 for batch 1.
2026-10-10 11:04:22,187 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 44/104 for batch 1.
2026-10-10 11:04:22,251 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 45/104 for batch 1.
2026-10-10 11:04:22,324 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 46/104 for batch 1.
2026-10-10 11:04:22,392 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 47/104 for batch 1.
2026-10-10 11:04:22,468 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 48/104 for batch 1.
2026-10-10 11:04:22,529 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 49/104 for batch 1.
2026-10-10 11:04:22,594 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 50/104 for batch 1.
2026-10-10 11:04:23,295 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 51/104 for batch 1.
2026-10-10 11:04:23,374 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 52/104 for batch 1.
2026-10-10 11:04:23,438 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 53/104 for batch 1.
2026-10-10 11:04:23,502 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 54/104 for batch 1.
2026-10-10 11:04:23,566 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 55/104 for batch 1.
2026-10-10 11:04:23,630 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 56/104 for batch 1.
2026-10-10 11:04:23,706 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 57/104 for batch 1.
2026-10-10 11:04:23,773 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 58/104 for batch 1.
2026-10-10 11:04:23,837 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 59/104 for batch 1.
2026-10-10 11:04:24,563 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 60/104 for batch 1.
2026-10-10 11:04:24,631 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 61/104 for batch 1.
2026-10-10 11:04:24,699 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 62/104 for batch 1.
2026-10-10 11:04:24,774 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 63/104 for batch 1.
2026-10-10 11:04:24,842 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 64/104 for batch 1.
2026-10-10 11:04:25,579 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 65/104 for batch 1.
2026-10-10 11:04:25,657 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 66/104 for batch 1.
2026-10-10 11:04:25,720 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 67/104 for batch 1.
2026-10-10 11:04:25,788 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 68/104 for batch 1.
2026-10-10 11:04:25,864 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 69/104 for batch 1.
2026-10-10 11:04:25,929 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 70/104 for batch 1.
2026-10-10 11:04:26,006 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 71/104 for batch 1.
2026-10-10 11:04:26,075 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 72/104 for batch 1.
2026-10-10 11:04:26,158 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 73/104 for batch 1.
2026-10-10 11:04:26,221 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 74/104 for batch 1.
2026-10-10 11:04:26,288 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 75/104 for batch 1.
2026-10-10 11:04:26,364 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 76/104 for batch 1.
2026-10-10 11:04:27,114 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 77/104 for batch 1.
2026-10-10 11:04:27,874 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 78/104 for batch 1.
2026-10-10 11:04:27,939 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 79/104 for batch 1.
2026-10-10 11:04:28,008 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 80/104 for batch 1.
2026-10-10 11:04:28,091 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 81/104 for batch 1.
2026-10-10 11:04:28,158 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 82/104 for batch 1.
2026-10-10 11:04:28,232 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 83/104 for batch 1.
2026-10-10 11:04:28,300 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 84/104 for batch 1.
2026-10-10 11:04:28,365 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 85/104 for batch 1.
2026-10-10 11:04:28,439 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 86/104 for batch 1.
2026-10-10 11:04:28,505 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 87/104 for batch 1.
2026-10-10 11:04:28,582 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 88/104 for batch 1.
2026-10-10 11:04:29,327 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 89/104 for batch 1.
2026-10-10 11:04:30,124 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 90/104 for batch 1.
2026-10-10 11:04:30,203 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 91/104 for batch 1.
2026-10-10 11:04:30,268 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 92/104 for batch 1.
2026-10-10 11:04:30,347 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 93/104 for batch 1.
2026-10-10 11:04:30,411 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 94/104 for batch 1.
2026-10-10 11:04:30,479 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 95/104 for batch 1.
2026-10-10 11:04:31,236 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 96/104 for batch 1.
2026-10-10 11:04:31,314 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 97/104 for batch 1.
2026-10-10 11:04:31,391 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 98/104 for batch 1.
2026-10-10 11:04:31,469 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 99/104 for batch 1.
2026-10-10 11:04:31,534 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 100/104 for batch 1.
2026-10-10 11:04:31,604 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 101/104 for batch 1.
2026-10-10 11:04:31,691 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 102/104 for batch 1.
2026-10-10 11:04:32,473 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 103/104 for batch 1.
2026-10-10 11:04:32,568 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Cleaned acquisition 104/104 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_15/monthly_cubes/2bd3fd9c29a04c5a-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 11:04:34,666 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 10/104.
2026-10-10 11:04:36,478 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 20/104.
2026-10-10 11:04:38,308 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 30/104.
2026-10-10 11:04:40,163 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 40/104.
2026-10-10 11:04:42,025 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 50/104.
2026-10-10 11:04:43,756 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 60/104.
2026-10-10 11:04:46,095 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 70/104.
2026-10-10 11:04:47,795 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 80/104.
2026-10-10 11:04:49,540 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 90/104.
2026-10-10 11:04:51,302 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 100/104.
2026-10-10 11:04:52,001 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Saved output indices for acquisition 104/104.
2026-10-10 11:04:52,337 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\monthly_cubes\2bd3fd9c29a04c5a-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_15/monthly_cubes/2bd3fd9c29a04c5a-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 11:05:16,069 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 27 parcels from batch_00001_monthly.nc.
2026-10-10 11:05:16,950 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\monthly_cubes\39e1ea790e35dd81-tiles-669b4d35\batch_00001_monthly.nc.

Created job j-2610100805204c3ab1ad629afa7953ad: partition 20, batch 12, user esagovhub4@gmail.com.

2026-10-10 11:05:19,876 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 10/147 for batch 1.
2026-10-10 11:05:22,627 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 20/147 for batch 1.
2026-10-10 11:05:25,518 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 30/147 for batch 1.
2026-10-10 11:05:28,097 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 40/147 for batch 1.
2026-10-10 11:05:30,966 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 50/147 for batch 1.
2026-10-10 11:05:33,660 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 60/147 for batch 1.
2026-10-10 11:05:36,503 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 70/147 for batch 1.
2026-10-10 11:05:39,042 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 80/147 for batch 1.
2026-10-10 11:05:41,987 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 90/147 for batch 1.
2026-10-10 11:05:44,776 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 100/147 for batch 1.
2026-10-10 11:05:47,794 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 110/147 for batch 1.
2026-10-10 11:05:50,520 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 120/147 for batch 1.
2026-10-10 11:05:53,108 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 130/147 for batch 1.
2026-10-10 11:05:55,801 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 140/147 for batch 1.
2026-10-10 11:05:57,708 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Stored observations 147/147 for batch 1.
2026-10-10 11:05:57,709 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-10 11:06:13,532 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-10 11:06:29,285 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-10 11:06:45,299 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-10 11:07:01,271 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-10 11:07:16,973 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-10 11:07:32,826 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-10 11:07:48,887 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-10 11:08:04,356 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-10 11:08:20,091 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 1/147 for batch 1.
2026-10-10 11:08:20,226 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 2/147 for batch 1.
2026-10-10 11:08:20,356 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 3/147 for batch 1.
2026-10-10 11:08:20,491 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 4/147 for batch 1.
2026-10-10 11:08:20,694 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 5/147 for batch 1.
2026-10-10 11:08:20,823 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 6/147 for batch 1.
2026-10-10 11:08:20,949 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 7/147 for batch 1.
2026-10-10 11:08:21,112 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 8/147 for batch 1.
2026-10-10 11:08:21,243 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 9/147 for batch 1.
2026-10-10 11:08:22,427 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 10/147 for batch 1.
2026-10-10 11:08:22,565 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 11/147 for batch 1.
2026-10-10 11:08:22,699 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 12/147 for batch 1.
2026-10-10 11:08:22,862 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 13/147 for batch 1.
2026-10-10 11:08:22,995 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 14/147 for batch 1.
2026-10-10 11:08:23,125 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 15/147 for batch 1.
2026-10-10 11:08:23,284 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 16/147 for batch 1.
2026-10-10 11:08:24,994 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 17/147 for batch 1.
2026-10-10 11:08:25,132 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 18/147 for batch 1.
2026-10-10 11:08:25,274 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 19/147 for batch 1.
2026-10-10 11:08:25,411 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 20/147 for batch 1.
2026-10-10 11:08:25,605 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 21/147 for batch 1.
2026-10-10 11:08:27,345 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 22/147 for batch 1.
2026-10-10 11:08:29,040 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 23/147 for batch 1.
2026-10-10 11:08:30,733 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 24/147 for batch 1.
2026-10-10 11:08:32,403 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 25/147 for batch 1.
2026-10-10 11:08:34,358 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 26/147 for batch 1.
2026-10-10 11:08:34,534 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 27/147 for batch 1.
2026-10-10 11:08:36,259 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 28/147 for batch 1.
2026-10-10 11:08:37,920 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 29/147 for batch 1.
2026-10-10 11:08:39,608 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 30/147 for batch 1.
2026-10-10 11:08:39,769 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 31/147 for batch 1.
2026-10-10 11:08:41,500 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 32/147 for batch 1.
2026-10-10 11:08:41,663 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 33/147 for batch 1.
2026-10-10 11:08:41,802 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 34/147 for batch 1.
2026-10-10 11:08:41,936 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 35/147 for batch 1.
2026-10-10 11:08:43,626 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 36/147 for batch 1.
2026-10-10 11:08:45,322 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 37/147 for batch 1.
2026-10-10 11:08:47,019 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 38/147 for batch 1.
2026-10-10 11:08:47,178 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 39/147 for batch 1.
2026-10-10 11:08:47,315 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 40/147 for batch 1.
2026-10-10 11:08:48,998 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 41/147 for batch 1.
2026-10-10 11:08:50,712 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 42/147 for batch 1.
2026-10-10 11:08:52,398 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 43/147 for batch 1.
2026-10-10 11:08:52,563 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 44/147 for batch 1.
2026-10-10 11:08:54,229 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 45/147 for batch 1.
2026-10-10 11:08:54,415 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 46/147 for batch 1.
2026-10-10 11:08:56,071 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 47/147 for batch 1.
2026-10-10 11:08:57,807 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 48/147 for batch 1.
2026-10-10 11:08:59,456 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 49/147 for batch 1.
2026-10-10 11:09:01,143 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 50/147 for batch 1.
2026-10-10 11:09:01,308 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 51/147 for batch 1.
2026-10-10 11:09:02,980 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 52/147 for batch 1.
2026-10-10 11:09:04,632 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 53/147 for batch 1.
2026-10-10 11:09:06,283 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 54/147 for batch 1.
2026-10-10 11:09:06,417 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 55/147 for batch 1.
2026-10-10 11:09:06,549 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 56/147 for batch 1.
2026-10-10 11:09:06,683 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 57/147 for batch 1.
2026-10-10 11:09:08,371 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 58/147 for batch 1.
2026-10-10 11:09:10,049 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 59/147 for batch 1.
2026-10-10 11:09:10,235 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 60/147 for batch 1.
2026-10-10 11:09:10,397 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 61/147 for batch 1.
2026-10-10 11:09:10,528 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 62/147 for batch 1.
2026-10-10 11:09:10,660 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 63/147 for batch 1.
2026-10-10 11:09:12,289 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 64/147 for batch 1.
2026-10-10 11:09:12,427 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 65/147 for batch 1.
2026-10-10 11:09:12,566 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 66/147 for batch 1.
2026-10-10 11:09:12,748 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 67/147 for batch 1.
2026-10-10 11:09:13,977 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 68/147 for batch 1.
2026-10-10 11:09:14,138 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 69/147 for batch 1.
2026-10-10 11:09:15,828 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 70/147 for batch 1.
2026-10-10 11:09:15,961 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 71/147 for batch 1.
2026-10-10 11:09:16,116 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 72/147 for batch 1.
2026-10-10 11:09:16,248 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 73/147 for batch 1.
2026-10-10 11:09:16,412 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 74/147 for batch 1.
2026-10-10 11:09:18,103 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 75/147 for batch 1.
2026-10-10 11:09:19,765 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 76/147 for batch 1.
2026-10-10 11:09:21,433 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 77/147 for batch 1.
2026-10-10 11:09:21,591 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 78/147 for batch 1.
2026-10-10 11:09:21,727 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 79/147 for batch 1.
2026-10-10 11:09:21,890 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 80/147 for batch 1.
2026-10-10 11:09:23,535 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 81/147 for batch 1.
2026-10-10 11:09:23,672 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 82/147 for batch 1.
2026-10-10 11:09:23,805 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 83/147 for batch 1.
2026-10-10 11:09:23,965 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 84/147 for batch 1.
2026-10-10 11:09:24,100 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 85/147 for batch 1.
2026-10-10 11:09:24,231 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 86/147 for batch 1.
2026-10-10 11:09:24,397 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 87/147 for batch 1.
2026-10-10 11:09:24,547 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 88/147 for batch 1.
2026-10-10 11:09:24,680 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 89/147 for batch 1.
2026-10-10 11:09:24,822 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 90/147 for batch 1.
2026-10-10 11:09:24,982 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 91/147 for batch 1.
2026-10-10 11:09:25,116 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 92/147 for batch 1.
2026-10-10 11:09:25,249 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 93/147 for batch 1.
2026-10-10 11:09:25,410 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 94/147 for batch 1.
2026-10-10 11:09:25,544 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 95/147 for batch 1.
2026-10-10 11:09:27,241 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 96/147 for batch 1.
2026-10-10 11:09:28,915 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 97/147 for batch 1.
2026-10-10 11:09:29,112 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 98/147 for batch 1.
2026-10-10 11:09:29,265 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 99/147 for batch 1.
2026-10-10 11:09:29,409 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 100/147 for batch 1.
2026-10-10 11:09:29,552 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 101/147 for batch 1.
2026-10-10 11:09:30,776 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 102/147 for batch 1.
2026-10-10 11:09:32,422 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 103/147 for batch 1.
2026-10-10 11:09:34,365 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 104/147 for batch 1.
2026-10-10 11:09:34,531 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 105/147 for batch 1.
2026-10-10 11:09:36,153 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 106/147 for batch 1.
2026-10-10 11:09:37,759 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 107/147 for batch 1.
2026-10-10 11:09:37,888 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 108/147 for batch 1.
2026-10-10 11:09:38,041 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 109/147 for batch 1.
2026-10-10 11:09:38,171 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 110/147 for batch 1.
2026-10-10 11:09:38,297 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 111/147 for batch 1.
2026-10-10 11:09:38,454 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 112/147 for batch 1.
2026-10-10 11:09:38,579 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 113/147 for batch 1.
2026-10-10 11:09:38,705 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 114/147 for batch 1.
2026-10-10 11:09:38,860 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 115/147 for batch 1.
2026-10-10 11:09:40,522 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 116/147 for batch 1.
2026-10-10 11:09:42,203 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 117/147 for batch 1.
2026-10-10 11:09:42,364 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 118/147 for batch 1.
2026-10-10 11:09:42,494 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 119/147 for batch 1.
2026-10-10 11:09:42,659 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 120/147 for batch 1.
2026-10-10 11:09:42,812 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 121/147 for batch 1.
2026-10-10 11:09:44,446 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 122/147 for batch 1.
2026-10-10 11:09:46,143 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 123/147 for batch 1.
2026-10-10 11:09:46,269 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 124/147 for batch 1.
2026-10-10 11:09:47,934 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 125/147 for batch 1.
2026-10-10 11:09:48,101 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 126/147 for batch 1.
2026-10-10 11:09:48,223 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 127/147 for batch 1.
2026-10-10 11:09:48,376 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 128/147 for batch 1.
2026-10-10 11:09:48,502 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Cleaned acquisition 129/147 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/monthly_cubes/39e1ea790e35dd81-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 11:09:58,359 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 10/147.
2026-10-10 11:10:02,607 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 20/147.
2026-10-10 11:10:06,771 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 30/147.
2026-10-10 11:10:10,862 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 40/147.
2026-10-10 11:10:14,940 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 50/147.
2026-10-10 11:10:18,887 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 60/147.
2026-10-10 11:10:23,499 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 70/147.
2026-10-10 11:10:28,129 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 80/147.
2026-10-10 11:10:32,830 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 90/147.
2026-10-10 11:10:37,774 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 100/147.
2026-10-10 11:10:42,507 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 110/147.
2026-10-10 11:10:47,617 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 120/147.
2026-10-10 11:10:52,340 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 130/147.
2026-10-10 11:10:57,305 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 140/147.
2026-10-10 11:11:00,980 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Saved output indices for acquisition 147/147.
2026-10-10 11:11:02,043 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\monthly_cubes\39e1ea790e35dd81-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/monthly_cubes/39e1ea790e35dd81-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 11:11:55,205 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 56 parcels from batch_00001_monthly.nc.
2026-10-10 11:11:57,731 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00002_monthly.nc.

Created job j-2610100812014251af0c4ef8f4a1f043: partition 20, batch 13, user sofiaargirou03@gmail.com.

2026-10-10 11:12:01,132 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 10/183 for batch 2.
2026-10-10 11:12:04,389 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 20/183 for batch 2.
2026-10-10 11:12:07,350 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 30/183 for batch 2.
2026-10-10 11:12:10,523 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 40/183 for batch 2.
2026-10-10 11:12:13,428 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 50/183 for batch 2.
2026-10-10 11:12:16,226 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 60/183 for batch 2.
2026-10-10 11:12:19,554 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 70/183 for batch 2.
2026-10-10 11:12:22,561 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 80/183 for batch 2.
2026-10-10 11:12:25,639 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 90/183 for batch 2.
2026-10-10 11:12:28,609 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 100/183 for batch 2.
2026-10-10 11:12:32,204 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 110/183 for batch 2.
2026-10-10 11:12:35,987 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 120/183 for batch 2.
2026-10-10 11:12:39,399 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 130/183 for batch 2.
2026-10-10 11:12:42,908 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 140/183 for batch 2.
2026-10-10 11:12:46,081 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 150/183 for batch 2.
2026-10-10 11:12:49,663 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 160/183 for batch 2.
2026-10-10 11:12:53,122 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 170/183 for batch 2.
2026-10-10 11:12:56,504 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 180/183 for batch 2.
2026-10-10 11:12:57,450 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Stored observations 183/183 for batch 2.
2026-10-10 11:12:57,451 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 11:13:27,287 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 11:13:57,216 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 11:14:26,618 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 11:14:56,548 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 11:15:26,028 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 11:15:55,854 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 11:16:25,116 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 11:16:54,804 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 11:17:24,101 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 1/183 for batch 2.
2026-10-10 11:17:24,253 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 2/183 for batch 2.
2026-10-10 11:17:24,404 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 3/183 for batch 2.
2026-10-10 11:17:24,643 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 4/183 for batch 2.
2026-10-10 11:17:24,792 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 5/183 for batch 2.
2026-10-10 11:17:24,941 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 6/183 for batch 2.
2026-10-10 11:17:25,627 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 7/183 for batch 2.
2026-10-10 11:17:25,778 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 8/183 for batch 2.
2026-10-10 11:17:25,929 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 9/183 for batch 2.
2026-10-10 11:17:26,114 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 10/183 for batch 2.
2026-10-10 11:17:28,157 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 11/183 for batch 2.
2026-10-10 11:17:30,730 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 12/183 for batch 2.
2026-10-10 11:17:31,512 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 13/183 for batch 2.
2026-10-10 11:17:33,009 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 14/183 for batch 2.
2026-10-10 11:17:33,216 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 15/183 for batch 2.
2026-10-10 11:17:33,427 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 16/183 for batch 2.
2026-10-10 11:17:34,289 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 17/183 for batch 2.
2026-10-10 11:17:36,385 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 18/183 for batch 2.
2026-10-10 11:17:36,537 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 19/183 for batch 2.
2026-10-10 11:17:36,689 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 20/183 for batch 2.
2026-10-10 11:17:36,838 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 21/183 for batch 2.
2026-10-10 11:17:38,849 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 22/183 for batch 2.
2026-10-10 11:17:39,037 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 23/183 for batch 2.
2026-10-10 11:17:39,222 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 24/183 for batch 2.
2026-10-10 11:17:39,372 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 25/183 for batch 2.
2026-10-10 11:17:39,522 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 26/183 for batch 2.
2026-10-10 11:17:40,197 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 27/183 for batch 2.
2026-10-10 11:17:40,352 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 28/183 for batch 2.
2026-10-10 11:17:40,534 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 29/183 for batch 2.
2026-10-10 11:17:40,683 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 30/183 for batch 2.
2026-10-10 11:17:40,837 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 31/183 for batch 2.
2026-10-10 11:17:41,512 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 32/183 for batch 2.
2026-10-10 11:17:41,664 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 33/183 for batch 2.
2026-10-10 11:17:41,849 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 34/183 for batch 2.
2026-10-10 11:17:42,037 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 35/183 for batch 2.
2026-10-10 11:17:42,190 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 36/183 for batch 2.
2026-10-10 11:17:42,374 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 37/183 for batch 2.
2026-10-10 11:17:42,526 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 38/183 for batch 2.
2026-10-10 11:17:43,211 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 39/183 for batch 2.
2026-10-10 11:17:45,327 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 40/183 for batch 2.
2026-10-10 11:17:45,511 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 41/183 for batch 2.
2026-10-10 11:17:45,696 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 42/183 for batch 2.
2026-10-10 11:17:45,852 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 43/183 for batch 2.
2026-10-10 11:17:46,003 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 44/183 for batch 2.
2026-10-10 11:17:46,158 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 45/183 for batch 2.
2026-10-10 11:17:46,359 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 46/183 for batch 2.
2026-10-10 11:17:46,517 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 47/183 for batch 2.
2026-10-10 11:17:47,238 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 48/183 for batch 2.
2026-10-10 11:17:47,394 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 49/183 for batch 2.
2026-10-10 11:17:47,553 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 50/183 for batch 2.
2026-10-10 11:17:47,714 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 51/183 for batch 2.
2026-10-10 11:17:47,908 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 52/183 for batch 2.
2026-10-10 11:17:48,103 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 53/183 for batch 2.
2026-10-10 11:17:48,260 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 54/183 for batch 2.
2026-10-10 11:17:48,415 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 55/183 for batch 2.
2026-10-10 11:17:48,611 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 56/183 for batch 2.
2026-10-10 11:17:48,807 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 57/183 for batch 2.
2026-10-10 11:17:50,978 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 58/183 for batch 2.
2026-10-10 11:17:51,165 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 59/183 for batch 2.
2026-10-10 11:17:51,357 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 60/183 for batch 2.
2026-10-10 11:17:51,514 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 61/183 for batch 2.
2026-10-10 11:17:51,673 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 62/183 for batch 2.
2026-10-10 11:17:51,870 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 63/183 for batch 2.
2026-10-10 11:17:52,026 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 64/183 for batch 2.
2026-10-10 11:17:52,187 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 65/183 for batch 2.
2026-10-10 11:17:52,900 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 66/183 for batch 2.
2026-10-10 11:17:53,058 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 67/183 for batch 2.
2026-10-10 11:17:53,257 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 68/183 for batch 2.
2026-10-10 11:17:54,823 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 69/183 for batch 2.
2026-10-10 11:17:56,355 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 70/183 for batch 2.
2026-10-10 11:17:56,544 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 71/183 for batch 2.
2026-10-10 11:17:56,738 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 72/183 for batch 2.
2026-10-10 11:17:56,889 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 73/183 for batch 2.
2026-10-10 11:17:57,077 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 74/183 for batch 2.
2026-10-10 11:17:59,142 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 75/183 for batch 2.
2026-10-10 11:17:59,327 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 76/183 for batch 2.
2026-10-10 11:17:59,514 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 77/183 for batch 2.
2026-10-10 11:18:01,600 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 78/183 for batch 2.
2026-10-10 11:18:03,650 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 79/183 for batch 2.
2026-10-10 11:18:03,839 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 80/183 for batch 2.
2026-10-10 11:18:03,996 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 81/183 for batch 2.
2026-10-10 11:18:04,664 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 82/183 for batch 2.
2026-10-10 11:18:04,816 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 83/183 for batch 2.
2026-10-10 11:18:05,000 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 84/183 for batch 2.
2026-10-10 11:18:05,184 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 85/183 for batch 2.
2026-10-10 11:18:05,340 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 86/183 for batch 2.
2026-10-10 11:18:05,528 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 87/183 for batch 2.
2026-10-10 11:18:05,712 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 88/183 for batch 2.
2026-10-10 11:18:05,865 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 89/183 for batch 2.
2026-10-10 11:18:07,910 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 90/183 for batch 2.
2026-10-10 11:18:08,091 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 91/183 for batch 2.
2026-10-10 11:18:08,273 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 92/183 for batch 2.
2026-10-10 11:18:10,253 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 93/183 for batch 2.
2026-10-10 11:18:10,439 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 94/183 for batch 2.
2026-10-10 11:18:12,489 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 95/183 for batch 2.
2026-10-10 11:18:14,553 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 96/183 for batch 2.
2026-10-10 11:18:14,740 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 97/183 for batch 2.
2026-10-10 11:18:14,931 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 98/183 for batch 2.
2026-10-10 11:18:15,133 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 99/183 for batch 2.
2026-10-10 11:18:15,283 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 100/183 for batch 2.
2026-10-10 11:18:15,433 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 101/183 for batch 2.
2026-10-10 11:18:15,620 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 102/183 for batch 2.
2026-10-10 11:18:15,801 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 103/183 for batch 2.
2026-10-10 11:18:15,951 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 104/183 for batch 2.
2026-10-10 11:18:16,137 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 105/183 for batch 2.
2026-10-10 11:18:16,323 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 106/183 for batch 2.
2026-10-10 11:18:16,473 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 107/183 for batch 2.
2026-10-10 11:18:16,627 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 108/183 for batch 2.
2026-10-10 11:18:16,784 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 109/183 for batch 2.
2026-10-10 11:18:16,944 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 110/183 for batch 2.
2026-10-10 11:18:17,099 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 111/183 for batch 2.
2026-10-10 11:18:17,264 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 112/183 for batch 2.
2026-10-10 11:18:17,417 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 113/183 for batch 2.
2026-10-10 11:18:17,605 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 114/183 for batch 2.
2026-10-10 11:18:18,431 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 115/183 for batch 2.
2026-10-10 11:18:18,579 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 116/183 for batch 2.
2026-10-10 11:18:18,765 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 117/183 for batch 2.
2026-10-10 11:18:18,947 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 118/183 for batch 2.
2026-10-10 11:18:19,105 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 119/183 for batch 2.
2026-10-10 11:18:19,289 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 120/183 for batch 2.
2026-10-10 11:18:19,434 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 121/183 for batch 2.
2026-10-10 11:18:19,615 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 122/183 for batch 2.
2026-10-10 11:18:19,795 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 123/183 for batch 2.
2026-10-10 11:18:19,940 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 124/183 for batch 2.
2026-10-10 11:18:20,119 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Cleaned acquisition 125/183 for batch 2.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00002_monthly_cleaning_report.partial.parquet

2026-10-10 11:18:45,113 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 10/183.
2026-10-10 11:18:49,974 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 20/183.
2026-10-10 11:18:54,715 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 30/183.
2026-10-10 11:18:59,440 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 40/183.
2026-10-10 11:19:04,780 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 50/183.
2026-10-10 11:19:10,351 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 60/183.
2026-10-10 11:19:16,012 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 70/183.
2026-10-10 11:19:22,778 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 80/183.
2026-10-10 11:19:28,232 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 90/183.
2026-10-10 11:19:34,107 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 100/183.
2026-10-10 11:19:39,712 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 110/183.
2026-10-10 11:19:46,085 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 120/183.
2026-10-10 11:19:52,504 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 130/183.
2026-10-10 11:19:58,827 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 140/183.
2026-10-10 11:20:05,110 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 150/183.
2026-10-10 11:20:11,519 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 160/183.
2026-10-10 11:20:18,014 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 170/183.
2026-10-10 11:20:24,566 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 180/183.
2026-10-10 11:20:26,467 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Saved output indices for acquisition 183/183.
2026-10-10 11:20:27,467 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\monthly_cubes\8d9b762aaf10cca6-tiles-669b4d35\batch_00002_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/monthly_cubes/8d9b762aaf10cca6-tiles-669b4d35/batch_00002_monthly_cleaning_report.parquet

2026-10-10 11:20:43,029 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 11 parcels from batch_00002_monthly.nc.
2026-10-10 11:20:45,319 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\monthly_cubes\8761d661959b732e-tiles-669b4d35\batch_00002_monthly.nc.

Created job j-26101008204845fa8429033dc25abf8b: partition 20, batch 14, user esagovhub1@gmail.com.

2026-10-10 11:20:48,817 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 10/146 for batch 2.
2026-10-10 11:20:52,125 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 20/146 for batch 2.
2026-10-10 11:20:55,490 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 30/146 for batch 2.
2026-10-10 11:20:58,961 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 40/146 for batch 2.
2026-10-10 11:21:02,193 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 50/146 for batch 2.
2026-10-10 11:21:05,466 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 60/146 for batch 2.
2026-10-10 11:21:08,943 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 70/146 for batch 2.
2026-10-10 11:21:12,121 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 80/146 for batch 2.
2026-10-10 11:21:16,106 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 90/146 for batch 2.
2026-10-10 11:21:19,652 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 100/146 for batch 2.
2026-10-10 11:21:23,157 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 110/146 for batch 2.
2026-10-10 11:21:26,833 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 120/146 for batch 2.
2026-10-10 11:21:30,137 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 130/146 for batch 2.
2026-10-10 11:21:33,747 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 140/146 for batch 2.
2026-10-10 11:21:35,856 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Stored observations 146/146 for batch 2.
2026-10-10 11:21:35,857 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 11:22:02,375 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 11:22:28,834 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 11:22:55,691 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 11:23:22,301 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 11:23:49,185 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 11:24:15,835 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 11:24:42,892 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 11:25:09,799 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 11:25:39,173 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 1/146 for batch 2.
2026-10-10 11:25:39,385 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 2/146 for batch 2.
2026-10-10 11:25:39,553 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 3/146 for batch 2.
2026-10-10 11:25:40,334 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 4/146 for batch 2.
2026-10-10 11:25:42,732 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 5/146 for batch 2.
2026-10-10 11:25:42,943 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 6/146 for batch 2.
2026-10-10 11:25:43,156 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 7/146 for batch 2.
2026-10-10 11:25:43,322 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 8/146 for batch 2.
2026-10-10 11:25:43,599 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 9/146 for batch 2.
2026-10-10 11:25:45,943 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 10/146 for batch 2.
2026-10-10 11:25:46,727 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 11/146 for batch 2.
2026-10-10 11:25:46,893 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 12/146 for batch 2.
2026-10-10 11:25:47,111 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 13/146 for batch 2.
2026-10-10 11:25:47,320 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 14/146 for batch 2.
2026-10-10 11:25:47,491 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 15/146 for batch 2.
2026-10-10 11:25:47,663 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 16/146 for batch 2.
2026-10-10 11:25:47,871 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 17/146 for batch 2.
2026-10-10 11:25:48,043 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 18/146 for batch 2.
2026-10-10 11:25:48,254 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 19/146 for batch 2.
2026-10-10 11:25:48,462 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 20/146 for batch 2.
2026-10-10 11:25:48,631 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 21/146 for batch 2.
2026-10-10 11:25:49,409 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 22/146 for batch 2.
2026-10-10 11:25:49,585 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 23/146 for batch 2.
2026-10-10 11:25:49,796 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 24/146 for batch 2.
2026-10-10 11:25:50,002 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 25/146 for batch 2.
2026-10-10 11:25:50,942 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 26/146 for batch 2.
2026-10-10 11:25:51,152 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 27/146 for batch 2.
2026-10-10 11:25:51,324 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 28/146 for batch 2.
2026-10-10 11:25:51,530 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 29/146 for batch 2.
2026-10-10 11:25:51,740 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 30/146 for batch 2.
2026-10-10 11:25:51,948 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 31/146 for batch 2.
2026-10-10 11:25:52,119 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 32/146 for batch 2.
2026-10-10 11:25:52,287 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 33/146 for batch 2.
2026-10-10 11:25:52,497 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 34/146 for batch 2.
2026-10-10 11:25:54,871 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 35/146 for batch 2.
2026-10-10 11:25:55,672 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 36/146 for batch 2.
2026-10-10 11:25:57,981 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 37/146 for batch 2.
2026-10-10 11:25:58,229 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 38/146 for batch 2.
2026-10-10 11:25:58,396 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 39/146 for batch 2.
2026-10-10 11:25:59,171 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 40/146 for batch 2.
2026-10-10 11:26:01,577 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 41/146 for batch 2.
2026-10-10 11:26:01,786 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 42/146 for batch 2.
2026-10-10 11:26:04,176 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 43/146 for batch 2.
2026-10-10 11:26:04,348 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 44/146 for batch 2.
2026-10-10 11:26:04,555 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 45/146 for batch 2.
2026-10-10 11:26:04,765 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 46/146 for batch 2.
2026-10-10 11:26:05,703 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 47/146 for batch 2.
2026-10-10 11:26:05,958 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 48/146 for batch 2.
2026-10-10 11:26:08,362 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 49/146 for batch 2.
2026-10-10 11:26:09,153 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 50/146 for batch 2.
2026-10-10 11:26:10,093 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 51/146 for batch 2.
2026-10-10 11:26:10,345 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 52/146 for batch 2.
2026-10-10 11:26:12,765 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 53/146 for batch 2.
2026-10-10 11:26:12,979 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 54/146 for batch 2.
2026-10-10 11:26:13,186 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 55/146 for batch 2.
2026-10-10 11:26:13,360 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 56/146 for batch 2.
2026-10-10 11:26:13,567 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 57/146 for batch 2.
2026-10-10 11:26:13,738 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 58/146 for batch 2.
2026-10-10 11:26:16,090 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 59/146 for batch 2.
2026-10-10 11:26:16,307 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 60/146 for batch 2.
2026-10-10 11:26:16,513 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 61/146 for batch 2.
2026-10-10 11:26:16,689 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 62/146 for batch 2.
2026-10-10 11:26:16,899 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 63/146 for batch 2.
2026-10-10 11:26:17,117 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 64/146 for batch 2.
2026-10-10 11:26:17,298 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 65/146 for batch 2.
2026-10-10 11:26:18,070 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 66/146 for batch 2.
2026-10-10 11:26:18,239 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 67/146 for batch 2.
2026-10-10 11:26:18,450 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 68/146 for batch 2.
2026-10-10 11:26:18,668 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 69/146 for batch 2.
2026-10-10 11:26:18,838 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 70/146 for batch 2.
2026-10-10 11:26:19,045 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 71/146 for batch 2.
2026-10-10 11:26:19,249 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 72/146 for batch 2.
2026-10-10 11:26:19,420 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 73/146 for batch 2.
2026-10-10 11:26:19,592 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 74/146 for batch 2.
2026-10-10 11:26:19,808 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 75/146 for batch 2.
2026-10-10 11:26:20,016 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 76/146 for batch 2.
2026-10-10 11:26:22,411 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 77/146 for batch 2.
2026-10-10 11:26:22,620 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 78/146 for batch 2.
2026-10-10 11:26:22,832 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 79/146 for batch 2.
2026-10-10 11:26:23,002 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 80/146 for batch 2.
2026-10-10 11:26:23,234 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 81/146 for batch 2.
2026-10-10 11:26:23,468 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 82/146 for batch 2.
2026-10-10 11:26:25,859 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 83/146 for batch 2.
2026-10-10 11:26:26,073 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 84/146 for batch 2.
2026-10-10 11:26:28,482 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 85/146 for batch 2.
2026-10-10 11:26:30,886 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 86/146 for batch 2.
2026-10-10 11:26:31,098 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 87/146 for batch 2.
2026-10-10 11:26:31,323 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 88/146 for batch 2.
2026-10-10 11:26:31,492 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 89/146 for batch 2.
2026-10-10 11:26:31,665 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 90/146 for batch 2.
2026-10-10 11:26:31,881 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 91/146 for batch 2.
2026-10-10 11:26:32,087 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 92/146 for batch 2.
2026-10-10 11:26:34,961 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 93/146 for batch 2.
2026-10-10 11:26:35,170 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 94/146 for batch 2.
2026-10-10 11:26:35,390 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 95/146 for batch 2.
2026-10-10 11:26:35,568 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 96/146 for batch 2.
2026-10-10 11:26:35,776 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 97/146 for batch 2.
2026-10-10 11:26:35,982 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 98/146 for batch 2.
2026-10-10 11:26:36,146 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 99/146 for batch 2.
2026-10-10 11:26:36,354 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 100/146 for batch 2.
2026-10-10 11:26:38,708 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 101/146 for batch 2.
2026-10-10 11:26:41,107 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 102/146 for batch 2.
2026-10-10 11:26:41,320 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 103/146 for batch 2.
2026-10-10 11:26:41,536 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 104/146 for batch 2.
2026-10-10 11:26:41,710 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 105/146 for batch 2.
2026-10-10 11:26:41,882 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 106/146 for batch 2.
2026-10-10 11:26:42,091 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 107/146 for batch 2.
2026-10-10 11:26:42,307 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 108/146 for batch 2.
2026-10-10 11:26:44,710 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 109/146 for batch 2.
2026-10-10 11:26:44,919 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 110/146 for batch 2.
2026-10-10 11:26:45,132 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 111/146 for batch 2.
2026-10-10 11:26:45,304 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 112/146 for batch 2.
2026-10-10 11:26:45,522 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 113/146 for batch 2.
2026-10-10 11:26:45,741 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 114/146 for batch 2.
2026-10-10 11:26:45,910 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 115/146 for batch 2.
2026-10-10 11:26:46,119 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 116/146 for batch 2.
2026-10-10 11:26:46,332 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 117/146 for batch 2.
2026-10-10 11:26:46,553 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 118/146 for batch 2.
2026-10-10 11:26:46,759 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 119/146 for batch 2.
2026-10-10 11:26:47,696 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 120/146 for batch 2.
2026-10-10 11:26:47,906 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 121/146 for batch 2.
2026-10-10 11:26:48,117 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 122/146 for batch 2.
2026-10-10 11:26:48,284 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 123/146 for batch 2.
2026-10-10 11:26:48,563 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 124/146 for batch 2.
2026-10-10 11:26:51,115 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 125/146 for batch 2.
2026-10-10 11:26:53,796 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 126/146 for batch 2.
2026-10-10 11:26:56,346 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 127/146 for batch 2.
2026-10-10 11:26:56,563 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 128/146 for batch 2.
2026-10-10 11:26:56,778 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Cleaned acquisition 129/146 for batch 2.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/monthly_cubes/8761d661959b732e-tiles-669b4d35/batch_00002_monthly_cleaning_report.partial.parquet

2026-10-10 11:27:16,122 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 10/146.
2026-10-10 11:27:21,604 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 20/146.
2026-10-10 11:27:26,871 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 30/146.
2026-10-10 11:27:32,576 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 40/146.
2026-10-10 11:27:38,033 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 50/146.
2026-10-10 11:27:43,134 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 60/146.
2026-10-10 11:27:48,558 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 70/146.
2026-10-10 11:27:54,606 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 80/146.
2026-10-10 11:28:01,031 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 90/146.
2026-10-10 11:28:07,582 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 100/146.
2026-10-10 11:28:14,064 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 110/146.
2026-10-10 11:28:20,466 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 120/146.
2026-10-10 11:28:26,890 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 130/146.
2026-10-10 11:28:33,519 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 140/146.
2026-10-10 11:28:37,494 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Saved output indices for acquisition 146/146.
2026-10-10 11:28:38,590 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\monthly_cubes\8761d661959b732e-tiles-669b4d35\batch_00002_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/monthly_cubes/8761d661959b732e-tiles-669b4d35/batch_00002_monthly_cleaning_report.parquet

2026-10-10 11:28:44,887 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 4 parcels from batch_00002_monthly.nc.
2026-10-10 11:28:47,612 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 11:28:50,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/147 for batch 1.

Created job j-26101008285144e99bc61b527006b4ff: partition 20, batch 15, user katrinporo@gmail.com.

2026-10-10 11:28:53,699 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/147 for batch 1.
2026-10-10 11:28:56,564 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/147 for batch 1.
2026-10-10 11:28:59,319 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/147 for batch 1.
2026-10-10 11:29:02,138 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/147 for batch 1.
2026-10-10 11:29:04,822 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/147 for batch 1.
2026-10-10 11:29:07,815 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/147 for batch 1.
2026-10-10 11:29:10,768 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/147 for batch 1.
2026-10-10 11:29:13,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/147 for batch 1.
2026-10-10 11:29:17,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/147 for batch 1.
2026-10-10 11:29:20,437 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/147 for batch 1.
2026-10-10 11:29:23,637 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/147 for batch 1.
2026-10-10 11:29:26,706 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/147 for batch 1.
2026-10-10 11:29:29,610 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/147 for batch 1.
2026-10-10 11:29:31,887 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 147/147 for batch 1.
2026-10-10 11:29:31,888 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 12 rows.
2026-10-10 11:29:47,834 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 12 rows.
2026-10-10 11:30:03,453 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 12 rows.
2026-10-10 11:30:18,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 12 rows.
2026-10-10 11:30:34,834 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 12 rows.
2026-10-10 11:30:50,513 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 12 rows.
2026-10-10 11:31:06,231 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 12 rows.
2026-10-10 11:31:22,006 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 12 rows.
2026-10-10 11:31:37,933 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 12 rows.
2026-10-10 11:31:55,770 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/147 for batch 1.
2026-10-10 11:31:56,044 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/147 for batch 1.
2026-10-10 11:31:58,153 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/147 for batch 1.
2026-10-10 11:31:58,397 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/147 for batch 1.
2026-10-10 11:31:58,636 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/147 for batch 1.
2026-10-10 11:32:00,687 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/147 for batch 1.
2026-10-10 11:32:01,518 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/147 for batch 1.
2026-10-10 11:32:02,383 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/147 for batch 1.
2026-10-10 11:32:02,534 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/147 for batch 1.
2026-10-10 11:32:02,809 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/147 for batch 1.
2026-10-10 11:32:04,872 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/147 for batch 1.
2026-10-10 11:32:05,141 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/147 for batch 1.
2026-10-10 11:32:07,186 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/147 for batch 1.
2026-10-10 11:32:07,364 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/147 for batch 1.
2026-10-10 11:32:07,542 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/147 for batch 1.
2026-10-10 11:32:07,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/147 for batch 1.
2026-10-10 11:32:09,808 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/147 for batch 1.
2026-10-10 11:32:09,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/147 for batch 1.
2026-10-10 11:32:10,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/147 for batch 1.
2026-10-10 11:32:12,216 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/147 for batch 1.
2026-10-10 11:32:12,487 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/147 for batch 1.
2026-10-10 11:32:14,588 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/147 for batch 1.
2026-10-10 11:32:14,770 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/147 for batch 1.
2026-10-10 11:32:14,960 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/147 for batch 1.
2026-10-10 11:32:15,140 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/147 for batch 1.
2026-10-10 11:32:17,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/147 for batch 1.
2026-10-10 11:32:17,513 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/147 for batch 1.
2026-10-10 11:32:19,550 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/147 for batch 1.
2026-10-10 11:32:19,781 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/147 for batch 1.
2026-10-10 11:32:19,955 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/147 for batch 1.
2026-10-10 11:32:20,137 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/147 for batch 1.
2026-10-10 11:32:22,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/147 for batch 1.
2026-10-10 11:32:22,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/147 for batch 1.
2026-10-10 11:32:24,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/147 for batch 1.
2026-10-10 11:32:24,740 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/147 for batch 1.
2026-10-10 11:32:24,890 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/147 for batch 1.
2026-10-10 11:32:25,167 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/147 for batch 1.
2026-10-10 11:32:27,248 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/147 for batch 1.
2026-10-10 11:32:27,432 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/147 for batch 1.
2026-10-10 11:32:27,611 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/147 for batch 1.
2026-10-10 11:32:27,790 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/147 for batch 1.
2026-10-10 11:32:27,974 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/147 for batch 1.
2026-10-10 11:32:28,769 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/147 for batch 1.
2026-10-10 11:32:29,040 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/147 for batch 1.
2026-10-10 11:32:31,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/147 for batch 1.
2026-10-10 11:32:31,310 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/147 for batch 1.
2026-10-10 11:32:31,456 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/147 for batch 1.
2026-10-10 11:32:31,728 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/147 for batch 1.
2026-10-10 11:32:33,996 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/147 for batch 1.
2026-10-10 11:32:34,375 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/147 for batch 1.
2026-10-10 11:32:34,521 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/147 for batch 1.
2026-10-10 11:32:36,540 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/147 for batch 1.
2026-10-10 11:32:36,719 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/147 for batch 1.
2026-10-10 11:32:36,905 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/147 for batch 1.
2026-10-10 11:32:38,978 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/147 for batch 1.
2026-10-10 11:32:39,157 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/147 for batch 1.
2026-10-10 11:32:39,334 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/147 for batch 1.
2026-10-10 11:32:41,404 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/147 for batch 1.
2026-10-10 11:32:41,655 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/147 for batch 1.
2026-10-10 11:32:41,887 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/147 for batch 1.
2026-10-10 11:32:43,924 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/147 for batch 1.
2026-10-10 11:32:44,194 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/147 for batch 1.
2026-10-10 11:32:46,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/147 for batch 1.
2026-10-10 11:32:46,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/147 for batch 1.
2026-10-10 11:32:46,621 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/147 for batch 1.
2026-10-10 11:32:46,806 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/147 for batch 1.
2026-10-10 11:32:46,946 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/147 for batch 1.
2026-10-10 11:32:47,121 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/147 for batch 1.
2026-10-10 11:32:47,296 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/147 for batch 1.
2026-10-10 11:32:48,071 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/147 for batch 1.
2026-10-10 11:32:48,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/147 for batch 1.
2026-10-10 11:32:48,507 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/147 for batch 1.
2026-10-10 11:32:50,529 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/147 for batch 1.
2026-10-10 11:32:50,705 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/147 for batch 1.
2026-10-10 11:32:50,882 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/147 for batch 1.
2026-10-10 11:32:52,953 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/147 for batch 1.
2026-10-10 11:32:53,130 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/147 for batch 1.
2026-10-10 11:32:53,967 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/147 for batch 1.
2026-10-10 11:32:54,786 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/147 for batch 1.
2026-10-10 11:32:54,959 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/147 for batch 1.
2026-10-10 11:32:56,965 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/147 for batch 1.
2026-10-10 11:32:59,053 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/147 for batch 1.
2026-10-10 11:32:59,235 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/147 for batch 1.
2026-10-10 11:32:59,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/147 for batch 1.
2026-10-10 11:32:59,559 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/147 for batch 1.
2026-10-10 11:32:59,772 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/147 for batch 1.
2026-10-10 11:32:59,985 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/147 for batch 1.
2026-10-10 11:33:00,133 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/147 for batch 1.
2026-10-10 11:33:00,311 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/147 for batch 1.
2026-10-10 11:33:00,497 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/147 for batch 1.
2026-10-10 11:33:02,491 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/147 for batch 1.
2026-10-10 11:33:04,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/147 for batch 1.
2026-10-10 11:33:04,678 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/147 for batch 1.
2026-10-10 11:33:04,867 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/147 for batch 1.
2026-10-10 11:33:05,068 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/147 for batch 1.
2026-10-10 11:33:05,242 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/147 for batch 1.
2026-10-10 11:33:06,007 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/147 for batch 1.
2026-10-10 11:33:06,786 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/147 for batch 1.
2026-10-10 11:33:06,964 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/147 for batch 1.
2026-10-10 11:33:07,144 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/147 for batch 1.
2026-10-10 11:33:07,288 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/147 for batch 1.
2026-10-10 11:33:07,501 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/147 for batch 1.
2026-10-10 11:33:07,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/147 for batch 1.
2026-10-10 11:33:08,489 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/147 for batch 1.
2026-10-10 11:33:08,665 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/147 for batch 1.
2026-10-10 11:33:08,842 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/147 for batch 1.
2026-10-10 11:33:08,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/147 for batch 1.
2026-10-10 11:33:09,140 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/147 for batch 1.
2026-10-10 11:33:09,315 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/147 for batch 1.
2026-10-10 11:33:09,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/147 for batch 1.
2026-10-10 11:33:09,677 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/147 for batch 1.
2026-10-10 11:33:09,856 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/147 for batch 1.
2026-10-10 11:33:09,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/147 for batch 1.
2026-10-10 11:33:10,143 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/147 for batch 1.
2026-10-10 11:33:10,325 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/147 for batch 1.
2026-10-10 11:33:10,505 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/147 for batch 1.
2026-10-10 11:33:10,655 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/147 for batch 1.
2026-10-10 11:33:10,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/147 for batch 1.
2026-10-10 11:33:11,080 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/147 for batch 1.
2026-10-10 11:33:13,133 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/147 for batch 1.
2026-10-10 11:33:13,380 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/147 for batch 1.
2026-10-10 11:33:14,161 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/147 for batch 1.
2026-10-10 11:33:14,956 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/147 for batch 1.
2026-10-10 11:33:15,134 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 124/147 for batch 1.
2026-10-10 11:33:15,313 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 125/147 for batch 1.
2026-10-10 11:33:15,488 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 126/147 for batch 1.
2026-10-10 11:33:15,668 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 127/147 for batch 1.
2026-10-10 11:33:15,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 128/147 for batch 1.
2026-10-10 11:33:15,956 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 129/147 for batch 1.
2026-10-10 11:33:16,133 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 130/147 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 11:33:34,314 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/147.
2026-10-10 11:33:38,840 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/147.
2026-10-10 11:33:43,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/147.
2026-10-10 11:33:48,029 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/147.
2026-10-10 11:33:52,577 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/147.
2026-10-10 11:33:57,150 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/147.
2026-10-10 11:34:01,646 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/147.
2026-10-10 11:34:06,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/147.
2026-10-10 11:34:10,948 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/147.
2026-10-10 11:34:16,323 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/147.
2026-10-10 11:34:21,724 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/147.
2026-10-10 11:34:27,250 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/147.
2026-10-10 11:34:33,002 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/147.
2026-10-10 11:34:38,675 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/147.
2026-10-10 11:34:42,718 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 147/147.
2026-10-10 11:34:43,867 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 11:35:11,102 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 24 parcels from batch_00001_monthly.nc.
2026-10-10 11:35:13,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00003_monthly.nc.
2026-10-10 11:35:16,629 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/189 for batch 3.

Created job j-26101008351745bf9a74cbd64eb6c312: partition 20, batch 16, user louvarieleni@gmail.com.

2026-10-10 11:35:19,847 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/189 for batch 3.
2026-10-10 11:35:22,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/189 for batch 3.
2026-10-10 11:35:25,507 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/189 for batch 3.
2026-10-10 11:35:28,179 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/189 for batch 3.
2026-10-10 11:35:30,826 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/189 for batch 3.
2026-10-10 11:35:33,887 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/189 for batch 3.
2026-10-10 11:35:36,609 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/189 for batch 3.
2026-10-10 11:35:39,659 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/189 for batch 3.
2026-10-10 11:35:42,602 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/189 for batch 3.
2026-10-10 11:35:45,644 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/189 for batch 3.
2026-10-10 11:35:48,752 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/189 for batch 3.
2026-10-10 11:35:51,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/189 for batch 3.
2026-10-10 11:35:55,071 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/189 for batch 3.
2026-10-10 11:35:58,201 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/189 for batch 3.
2026-10-10 11:36:01,384 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/189 for batch 3.
2026-10-10 11:36:04,407 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/189 for batch 3.
2026-10-10 11:36:07,528 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/189 for batch 3.
2026-10-10 11:36:10,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 189/189 for batch 3.
2026-10-10 11:36:10,130 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 11:36:40,009 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 11:37:10,549 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 11:37:40,851 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 11:38:10,728 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 11:38:40,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 11:39:09,379 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 11:39:40,059 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 11:40:10,262 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 11:40:44,071 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/189 for batch 3.
2026-10-10 11:40:44,421 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/189 for batch 3.
2026-10-10 11:40:44,574 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/189 for batch 3.
2026-10-10 11:40:46,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/189 for batch 3.
2026-10-10 11:40:46,944 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/189 for batch 3.
2026-10-10 11:40:47,236 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/189 for batch 3.
2026-10-10 11:40:49,315 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/189 for batch 3.
2026-10-10 11:40:49,603 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/189 for batch 3.
2026-10-10 11:40:51,910 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/189 for batch 3.
2026-10-10 11:40:52,068 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/189 for batch 3.
2026-10-10 11:40:54,394 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/189 for batch 3.
2026-10-10 11:40:54,552 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/189 for batch 3.
2026-10-10 11:40:55,486 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/189 for batch 3.
2026-10-10 11:40:55,636 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/189 for batch 3.
2026-10-10 11:40:57,889 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/189 for batch 3.
2026-10-10 11:40:58,170 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/189 for batch 3.
2026-10-10 11:40:58,960 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/189 for batch 3.
2026-10-10 11:40:59,247 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/189 for batch 3.
2026-10-10 11:41:01,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/189 for batch 3.
2026-10-10 11:41:01,467 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/189 for batch 3.
2026-10-10 11:41:01,654 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/189 for batch 3.
2026-10-10 11:41:01,807 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/189 for batch 3.
2026-10-10 11:41:01,963 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/189 for batch 3.
2026-10-10 11:41:02,156 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/189 for batch 3.
2026-10-10 11:41:02,346 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/189 for batch 3.
2026-10-10 11:41:04,423 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/189 for batch 3.
2026-10-10 11:41:04,712 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/189 for batch 3.
2026-10-10 11:41:06,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/189 for batch 3.
2026-10-10 11:41:06,950 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/189 for batch 3.
2026-10-10 11:41:07,195 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/189 for batch 3.
2026-10-10 11:41:07,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/189 for batch 3.
2026-10-10 11:41:09,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/189 for batch 3.
2026-10-10 11:41:09,637 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/189 for batch 3.
2026-10-10 11:41:09,822 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/189 for batch 3.
2026-10-10 11:41:11,338 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/189 for batch 3.
2026-10-10 11:41:11,678 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/189 for batch 3.
2026-10-10 11:41:11,834 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/189 for batch 3.
2026-10-10 11:41:12,115 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/189 for batch 3.
2026-10-10 11:41:12,312 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/189 for batch 3.
2026-10-10 11:41:12,495 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/189 for batch 3.
2026-10-10 11:41:12,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/189 for batch 3.
2026-10-10 11:41:14,745 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/189 for batch 3.
2026-10-10 11:41:14,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/189 for batch 3.
2026-10-10 11:41:16,964 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/189 for batch 3.
2026-10-10 11:41:17,259 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/189 for batch 3.
2026-10-10 11:41:17,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/189 for batch 3.
2026-10-10 11:41:19,489 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/189 for batch 3.
2026-10-10 11:41:19,764 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/189 for batch 3.
2026-10-10 11:41:19,929 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/189 for batch 3.
2026-10-10 11:41:20,082 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/189 for batch 3.
2026-10-10 11:41:20,234 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/189 for batch 3.
2026-10-10 11:41:20,523 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/189 for batch 3.
2026-10-10 11:41:22,592 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/189 for batch 3.
2026-10-10 11:41:22,748 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/189 for batch 3.
2026-10-10 11:41:23,089 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/189 for batch 3.
2026-10-10 11:41:23,243 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/189 for batch 3.
2026-10-10 11:41:23,395 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/189 for batch 3.
2026-10-10 11:41:23,673 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/189 for batch 3.
2026-10-10 11:41:23,823 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/189 for batch 3.
2026-10-10 11:41:25,953 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/189 for batch 3.
2026-10-10 11:41:26,142 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/189 for batch 3.
2026-10-10 11:41:27,010 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/189 for batch 3.
2026-10-10 11:41:27,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/189 for batch 3.
2026-10-10 11:41:29,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/189 for batch 3.
2026-10-10 11:41:29,681 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/189 for batch 3.
2026-10-10 11:41:29,836 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/189 for batch 3.
2026-10-10 11:41:30,116 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/189 for batch 3.
2026-10-10 11:41:32,244 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/189 for batch 3.
2026-10-10 11:41:32,402 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/189 for batch 3.
2026-10-10 11:41:32,756 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/189 for batch 3.
2026-10-10 11:41:33,007 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/189 for batch 3.
2026-10-10 11:41:33,286 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/189 for batch 3.
2026-10-10 11:41:33,560 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/189 for batch 3.
2026-10-10 11:41:33,771 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/189 for batch 3.
2026-10-10 11:41:33,947 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/189 for batch 3.
2026-10-10 11:41:36,102 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/189 for batch 3.
2026-10-10 11:41:36,287 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/189 for batch 3.
2026-10-10 11:41:36,439 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/189 for batch 3.
2026-10-10 11:41:36,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/189 for batch 3.
2026-10-10 11:41:36,786 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/189 for batch 3.
2026-10-10 11:41:36,967 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/189 for batch 3.
2026-10-10 11:41:39,014 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/189 for batch 3.
2026-10-10 11:41:39,205 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/189 for batch 3.
2026-10-10 11:41:41,363 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/189 for batch 3.
2026-10-10 11:41:41,519 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/189 for batch 3.
2026-10-10 11:41:41,674 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/189 for batch 3.
2026-10-10 11:41:41,863 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/189 for batch 3.
2026-10-10 11:41:42,051 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/189 for batch 3.
2026-10-10 11:41:42,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/189 for batch 3.
2026-10-10 11:41:43,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/189 for batch 3.
2026-10-10 11:41:43,959 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/189 for batch 3.
2026-10-10 11:41:44,176 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/189 for batch 3.
2026-10-10 11:41:44,330 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/189 for batch 3.
2026-10-10 11:41:45,155 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/189 for batch 3.
2026-10-10 11:41:46,119 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/189 for batch 3.
2026-10-10 11:41:46,307 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/189 for batch 3.
2026-10-10 11:41:48,365 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/189 for batch 3.
2026-10-10 11:41:48,523 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/189 for batch 3.
2026-10-10 11:41:48,710 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/189 for batch 3.
2026-10-10 11:41:48,911 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/189 for batch 3.
2026-10-10 11:41:49,069 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/189 for batch 3.
2026-10-10 11:41:49,257 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/189 for batch 3.
2026-10-10 11:41:51,354 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/189 for batch 3.
2026-10-10 11:41:51,509 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/189 for batch 3.
2026-10-10 11:41:51,665 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/189 for batch 3.
2026-10-10 11:41:53,813 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/189 for batch 3.
2026-10-10 11:41:54,005 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/189 for batch 3.
2026-10-10 11:41:56,128 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/189 for batch 3.
2026-10-10 11:41:58,166 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/189 for batch 3.
2026-10-10 11:41:58,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/189 for batch 3.
2026-10-10 11:41:58,550 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/189 for batch 3.
2026-10-10 11:41:58,790 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/189 for batch 3.
2026-10-10 11:41:58,948 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/189 for batch 3.
2026-10-10 11:41:59,133 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/189 for batch 3.
2026-10-10 11:41:59,314 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/189 for batch 3.
2026-10-10 11:42:00,099 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/189 for batch 3.
2026-10-10 11:42:00,257 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/189 for batch 3.
2026-10-10 11:42:00,439 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/189 for batch 3.
2026-10-10 11:42:00,626 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/189 for batch 3.
2026-10-10 11:42:02,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/189 for batch 3.
2026-10-10 11:42:02,906 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/189 for batch 3.
2026-10-10 11:42:03,099 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/189 for batch 3.
2026-10-10 11:42:05,199 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/189 for batch 3.
2026-10-10 11:42:05,350 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 124/189 for batch 3.
2026-10-10 11:42:05,502 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 125/189 for batch 3.
2026-10-10 11:42:07,599 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 126/189 for batch 3.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00003_monthly_cleaning_report.partial.parquet

2026-10-10 11:42:49,878 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/189.
2026-10-10 11:42:54,698 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/189.
2026-10-10 11:42:59,419 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/189.
2026-10-10 11:43:03,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/189.
2026-10-10 11:43:08,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/189.
2026-10-10 11:43:14,674 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/189.
2026-10-10 11:43:20,216 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/189.
2026-10-10 11:43:25,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/189.
2026-10-10 11:43:31,580 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/189.
2026-10-10 11:43:37,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/189.
2026-10-10 11:43:43,401 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/189.
2026-10-10 11:43:49,197 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/189.
2026-10-10 11:43:55,179 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/189.
2026-10-10 11:44:01,530 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/189.
2026-10-10 11:44:07,734 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/189.
2026-10-10 11:44:14,105 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/189.
2026-10-10 11:44:20,185 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/189.
2026-10-10 11:44:26,248 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/189.
2026-10-10 11:44:31,779 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 189/189.
2026-10-10 11:44:32,869 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00003_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00003_monthly_cleaning_report.parquet

2026-10-10 11:44:38,881 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 5 parcels from batch_00003_monthly.nc.
2026-10-10 11:44:41,845 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\monthly_cubes\664a5569c84adf2d-tiles-669b4d35\batch_00001_monthly.nc.
2026-10-10 11:44:44,491 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 10/188 for batch 1.

Created job j-2610100844454414aedd74a689c61eea: partition 20, batch 17, user esagovhub2@gmail.com.

2026-10-10 11:44:47,579 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 20/188 for batch 1.
2026-10-10 11:44:50,225 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 30/188 for batch 1.
2026-10-10 11:44:52,839 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 40/188 for batch 1.
2026-10-10 11:44:55,355 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 50/188 for batch 1.
2026-10-10 11:44:57,858 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 60/188 for batch 1.
2026-10-10 11:45:00,735 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 70/188 for batch 1.
2026-10-10 11:45:03,450 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 80/188 for batch 1.
2026-10-10 11:45:06,096 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 90/188 for batch 1.
2026-10-10 11:45:08,836 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 100/188 for batch 1.
2026-10-10 11:45:11,542 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 110/188 for batch 1.
2026-10-10 11:45:15,089 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 120/188 for batch 1.
2026-10-10 11:45:17,979 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 130/188 for batch 1.
2026-10-10 11:45:20,988 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 140/188 for batch 1.
2026-10-10 11:45:23,858 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 150/188 for batch 1.
2026-10-10 11:45:26,710 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 160/188 for batch 1.
2026-10-10 11:45:29,641 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 170/188 for batch 1.
2026-10-10 11:45:32,509 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 180/188 for batch 1.
2026-10-10 11:45:34,859 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Stored observations 188/188 for batch 1.
2026-10-10 11:45:34,859 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 11:46:01,531 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 11:46:28,000 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 11:46:55,095 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 11:47:21,724 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 11:47:48,700 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 11:48:15,308 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 11:48:42,292 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 11:49:08,579 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 11:49:36,774 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 1/188 for batch 1.
2026-10-10 11:49:36,929 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 2/188 for batch 1.
2026-10-10 11:49:37,254 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 3/188 for batch 1.
2026-10-10 11:49:37,573 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 4/188 for batch 1.
2026-10-10 11:49:37,799 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 5/188 for batch 1.
2026-10-10 11:49:37,925 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 6/188 for batch 1.
2026-10-10 11:49:38,050 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 7/188 for batch 1.
2026-10-10 11:49:38,205 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 8/188 for batch 1.
2026-10-10 11:49:39,830 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 9/188 for batch 1.
2026-10-10 11:49:41,416 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 10/188 for batch 1.
2026-10-10 11:49:42,709 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 11/188 for batch 1.
2026-10-10 11:49:44,310 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 12/188 for batch 1.
2026-10-10 11:49:46,020 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 13/188 for batch 1.
2026-10-10 11:49:47,617 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 14/188 for batch 1.
2026-10-10 11:49:49,230 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 15/188 for batch 1.
2026-10-10 11:49:49,464 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 16/188 for batch 1.
2026-10-10 11:49:49,593 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 17/188 for batch 1.
2026-10-10 11:49:49,751 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 18/188 for batch 1.
2026-10-10 11:49:49,881 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 19/188 for batch 1.
2026-10-10 11:49:50,111 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 20/188 for batch 1.
2026-10-10 11:49:50,239 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 21/188 for batch 1.
2026-10-10 11:49:50,424 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 22/188 for batch 1.
2026-10-10 11:49:50,642 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 23/188 for batch 1.
2026-10-10 11:49:50,854 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 24/188 for batch 1.
2026-10-10 11:49:51,085 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 25/188 for batch 1.
2026-10-10 11:49:52,265 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 26/188 for batch 1.
2026-10-10 11:49:52,429 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 27/188 for batch 1.
2026-10-10 11:49:54,060 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 28/188 for batch 1.
2026-10-10 11:49:54,291 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 29/188 for batch 1.
2026-10-10 11:49:55,917 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 30/188 for batch 1.
2026-10-10 11:49:56,153 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 31/188 for batch 1.
2026-10-10 11:49:56,309 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 32/188 for batch 1.
2026-10-10 11:49:56,533 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 33/188 for batch 1.
2026-10-10 11:49:58,136 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 34/188 for batch 1.
2026-10-10 11:49:58,295 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 35/188 for batch 1.
2026-10-10 11:49:58,427 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 36/188 for batch 1.
2026-10-10 11:49:58,679 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 37/188 for batch 1.
2026-10-10 11:49:58,913 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 38/188 for batch 1.
2026-10-10 11:49:59,143 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 39/188 for batch 1.
2026-10-10 11:50:00,783 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 40/188 for batch 1.
2026-10-10 11:50:01,019 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 41/188 for batch 1.
2026-10-10 11:50:02,705 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 42/188 for batch 1.
2026-10-10 11:50:02,865 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 43/188 for batch 1.
2026-10-10 11:50:03,079 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 44/188 for batch 1.
2026-10-10 11:50:03,210 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 45/188 for batch 1.
2026-10-10 11:50:03,439 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 46/188 for batch 1.
2026-10-10 11:50:03,593 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 47/188 for batch 1.
2026-10-10 11:50:03,751 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 48/188 for batch 1.
2026-10-10 11:50:03,909 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 49/188 for batch 1.
2026-10-10 11:50:05,559 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 50/188 for batch 1.
2026-10-10 11:50:07,228 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 51/188 for batch 1.
2026-10-10 11:50:08,839 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 52/188 for batch 1.
2026-10-10 11:50:09,068 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 53/188 for batch 1.
2026-10-10 11:50:09,198 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 54/188 for batch 1.
2026-10-10 11:50:09,370 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 55/188 for batch 1.
2026-10-10 11:50:10,963 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 56/188 for batch 1.
2026-10-10 11:50:11,193 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 57/188 for batch 1.
2026-10-10 11:50:12,836 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 58/188 for batch 1.
2026-10-10 11:50:14,489 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 59/188 for batch 1.
2026-10-10 11:50:14,646 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 60/188 for batch 1.
2026-10-10 11:50:14,774 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 61/188 for batch 1.
2026-10-10 11:50:14,931 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 62/188 for batch 1.
2026-10-10 11:50:15,060 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 63/188 for batch 1.
2026-10-10 11:50:15,293 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 64/188 for batch 1.
2026-10-10 11:50:15,420 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 65/188 for batch 1.
2026-10-10 11:50:15,579 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 66/188 for batch 1.
2026-10-10 11:50:16,241 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 67/188 for batch 1.
2026-10-10 11:50:16,898 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 68/188 for batch 1.
2026-10-10 11:50:17,136 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 69/188 for batch 1.
2026-10-10 11:50:18,801 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 70/188 for batch 1.
2026-10-10 11:50:18,960 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 71/188 for batch 1.
2026-10-10 11:50:19,123 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 72/188 for batch 1.
2026-10-10 11:50:20,735 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 73/188 for batch 1.
2026-10-10 11:50:22,367 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 74/188 for batch 1.
2026-10-10 11:50:22,526 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 75/188 for batch 1.
2026-10-10 11:50:24,154 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 76/188 for batch 1.
2026-10-10 11:50:25,791 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 77/188 for batch 1.
2026-10-10 11:50:25,945 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 78/188 for batch 1.
2026-10-10 11:50:26,133 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 79/188 for batch 1.
2026-10-10 11:50:26,263 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 80/188 for batch 1.
2026-10-10 11:50:26,393 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 81/188 for batch 1.
2026-10-10 11:50:26,548 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 82/188 for batch 1.
2026-10-10 11:50:26,707 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 83/188 for batch 1.
2026-10-10 11:50:26,837 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 84/188 for batch 1.
2026-10-10 11:50:26,993 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 85/188 for batch 1.
2026-10-10 11:50:27,148 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 86/188 for batch 1.
2026-10-10 11:50:27,310 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 87/188 for batch 1.
2026-10-10 11:50:28,948 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 88/188 for batch 1.
2026-10-10 11:50:29,077 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 89/188 for batch 1.
2026-10-10 11:50:29,232 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 90/188 for batch 1.
2026-10-10 11:50:29,388 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 91/188 for batch 1.
2026-10-10 11:50:29,523 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 92/188 for batch 1.
2026-10-10 11:50:29,652 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 93/188 for batch 1.
2026-10-10 11:50:29,812 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 94/188 for batch 1.
2026-10-10 11:50:29,975 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 95/188 for batch 1.
2026-10-10 11:50:30,134 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 96/188 for batch 1.
2026-10-10 11:50:30,289 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 97/188 for batch 1.
2026-10-10 11:50:30,450 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 98/188 for batch 1.
2026-10-10 11:50:30,580 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 99/188 for batch 1.
2026-10-10 11:50:30,712 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 100/188 for batch 1.
2026-10-10 11:50:30,872 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 101/188 for batch 1.
2026-10-10 11:50:32,579 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 102/188 for batch 1.
2026-10-10 11:50:34,625 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 103/188 for batch 1.
2026-10-10 11:50:36,241 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 104/188 for batch 1.
2026-10-10 11:50:37,933 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 105/188 for batch 1.
2026-10-10 11:50:38,091 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 106/188 for batch 1.
2026-10-10 11:50:39,732 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 107/188 for batch 1.
2026-10-10 11:50:41,341 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 108/188 for batch 1.
2026-10-10 11:50:41,522 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 109/188 for batch 1.
2026-10-10 11:50:43,252 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 110/188 for batch 1.
2026-10-10 11:50:43,387 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 111/188 for batch 1.
2026-10-10 11:50:43,520 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 112/188 for batch 1.
2026-10-10 11:50:43,660 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 113/188 for batch 1.
2026-10-10 11:50:43,795 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 114/188 for batch 1.
2026-10-10 11:50:43,928 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 115/188 for batch 1.
2026-10-10 11:50:44,060 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 116/188 for batch 1.
2026-10-10 11:50:44,220 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 117/188 for batch 1.
2026-10-10 11:50:44,379 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 118/188 for batch 1.
2026-10-10 11:50:44,512 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 119/188 for batch 1.
2026-10-10 11:50:44,643 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 120/188 for batch 1.
2026-10-10 11:50:44,799 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 121/188 for batch 1.
2026-10-10 11:50:45,500 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 122/188 for batch 1.
2026-10-10 11:50:45,631 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 123/188 for batch 1.
2026-10-10 11:50:45,762 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 124/188 for batch 1.
2026-10-10 11:50:45,921 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 125/188 for batch 1.
2026-10-10 11:50:46,081 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Cleaned acquisition 126/188 for batch 1.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_14/monthly_cubes/664a5569c84adf2d-tiles-669b4d35/batch_00001_monthly_cleaning_report.partial.parquet

2026-10-10 11:51:05,751 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 10/188.
2026-10-10 11:51:09,968 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 20/188.
2026-10-10 11:51:14,002 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 30/188.
2026-10-10 11:51:18,302 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 40/188.
2026-10-10 11:51:22,475 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 50/188.
2026-10-10 11:51:26,657 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 60/188.
2026-10-10 11:51:30,739 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 70/188.
2026-10-10 11:51:35,030 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 80/188.
2026-10-10 11:51:39,211 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 90/188.
2026-10-10 11:51:43,378 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 100/188.
2026-10-10 11:51:47,635 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 110/188.
2026-10-10 11:51:51,866 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 120/188.
2026-10-10 11:51:55,955 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 130/188.
2026-10-10 11:51:59,957 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 140/188.
2026-10-10 11:52:04,705 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 150/188.
2026-10-10 11:52:09,579 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 160/188.
2026-10-10 11:52:14,328 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 170/188.
2026-10-10 11:52:19,400 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 180/188.
2026-10-10 11:52:23,643 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Saved output indices for acquisition 188/188.
2026-10-10 11:52:24,740 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\monthly_cubes\664a5569c84adf2d-tiles-669b4d35\batch_00001_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_14/monthly_cubes/664a5569c84adf2d-tiles-669b4d35/batch_00001_monthly_cleaning_report.parquet

2026-10-10 11:52:28,838 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 3 parcels from batch_00001_monthly.nc.
2026-10-10 11:52:31,354 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00008_monthly.nc.
2026-10-10 11:52:33,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/189 for batch 8.
2026-10-10 11:52:35,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/189 for batch 8.
2026-10-10 11:52:36,958 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/189 for batch 8.
2026-10-10 11:52:38,675 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/189 for batch 8.
2026-10-10 11:52:40,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/189 for batch 8.
2026-10-10 11:52:42,081 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/189 for batch 8.
2026-10-10 11:52:43,940 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/189 for batch 8.
2026-10-10 11:52:45,573 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/189 for batch 8.
2026-10-10 11:52:47,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/189 for batch 8.
2026-10-10 11:52:49,099 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/189 for batch 8.
2026-10-10 11:52:50,773 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/189 for batch 8.
2026-10-10 11:52:52,773 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/189 for batch 8.
2026-10-10 11:52:54,669 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/189 for batch 8.
2026-10-10 11:52:56,632 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/189 for batch 8.
2026-10-10 11:52:58,788 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/189 for batch 8.
2026-10-10 11:53:01,029 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/189 for batch 8.
2026-10-10 11:53:03,042 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/189 for batch 8.
2026-10-10 11:53:04,886 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/189 for batch 8.
2026-10-10 11:53:06,488 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 189/189 for batch 8.
2026-10-10 11:53:06,489 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-10 11:53:19,885 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-10 11:53:33,322 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-10 11:53:47,199 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-10 11:54:00,825 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-10 11:54:14,981 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-10 11:54:28,698 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-10 11:54:42,070 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-10 11:54:55,599 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-10 11:55:10,086 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/189 for batch 8.
2026-10-10 11:55:10,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/189 for batch 8.
2026-10-10 11:55:11,158 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/189 for batch 8.
2026-10-10 11:55:12,067 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/189 for batch 8.
2026-10-10 11:55:13,056 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/189 for batch 8.
2026-10-10 11:55:13,228 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/189 for batch 8.
2026-10-10 11:55:14,294 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/189 for batch 8.
2026-10-10 11:55:14,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/189 for batch 8.
2026-10-10 11:55:15,374 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/189 for batch 8.
2026-10-10 11:55:15,459 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/189 for batch 8.
2026-10-10 11:55:15,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/189 for batch 8.
2026-10-10 11:55:15,679 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/189 for batch 8.
2026-10-10 11:55:15,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/189 for batch 8.
2026-10-10 11:55:15,862 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/189 for batch 8.
2026-10-10 11:55:16,772 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/189 for batch 8.
2026-10-10 11:55:17,722 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/189 for batch 8.
2026-10-10 11:55:18,624 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/189 for batch 8.
2026-10-10 11:55:18,741 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/189 for batch 8.
2026-10-10 11:55:19,734 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/189 for batch 8.
2026-10-10 11:55:19,823 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/189 for batch 8.
2026-10-10 11:55:19,908 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/189 for batch 8.
2026-10-10 11:55:19,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/189 for batch 8.
2026-10-10 11:55:20,078 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/189 for batch 8.
2026-10-10 11:55:20,163 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/189 for batch 8.
2026-10-10 11:55:20,280 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/189 for batch 8.
2026-10-10 11:55:21,221 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/189 for batch 8.
2026-10-10 11:55:21,346 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/189 for batch 8.
2026-10-10 11:55:22,248 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/189 for batch 8.
2026-10-10 11:55:23,153 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/189 for batch 8.
2026-10-10 11:55:23,253 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/189 for batch 8.
2026-10-10 11:55:24,203 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/189 for batch 8.
2026-10-10 11:55:24,323 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/189 for batch 8.
2026-10-10 11:55:25,222 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/189 for batch 8.
2026-10-10 11:55:25,319 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/189 for batch 8.
2026-10-10 11:55:25,399 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/189 for batch 8.
2026-10-10 11:55:25,535 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/189 for batch 8.
2026-10-10 11:55:25,620 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/189 for batch 8.
2026-10-10 11:55:25,725 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/189 for batch 8.
2026-10-10 11:55:25,811 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/189 for batch 8.
2026-10-10 11:55:25,913 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/189 for batch 8.
2026-10-10 11:55:26,012 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/189 for batch 8.
2026-10-10 11:55:26,905 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/189 for batch 8.
2026-10-10 11:55:27,704 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/189 for batch 8.
2026-10-10 11:55:28,622 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/189 for batch 8.
2026-10-10 11:55:28,762 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/189 for batch 8.
2026-10-10 11:55:29,697 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/189 for batch 8.
2026-10-10 11:55:29,794 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/189 for batch 8.
2026-10-10 11:55:29,906 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/189 for batch 8.
2026-10-10 11:55:30,817 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/189 for batch 8.
2026-10-10 11:55:30,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/189 for batch 8.
2026-10-10 11:55:31,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/189 for batch 8.
2026-10-10 11:55:31,903 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/189 for batch 8.
2026-10-10 11:55:31,988 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/189 for batch 8.
2026-10-10 11:55:32,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/189 for batch 8.
2026-10-10 11:55:32,177 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/189 for batch 8.
2026-10-10 11:55:32,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/189 for batch 8.
2026-10-10 11:55:33,203 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/189 for batch 8.
2026-10-10 11:55:33,338 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/189 for batch 8.
2026-10-10 11:55:34,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/189 for batch 8.
2026-10-10 11:55:35,176 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/189 for batch 8.
2026-10-10 11:55:35,281 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/189 for batch 8.
2026-10-10 11:55:35,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/189 for batch 8.
2026-10-10 11:55:35,460 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/189 for batch 8.
2026-10-10 11:55:36,379 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/189 for batch 8.
2026-10-10 11:55:37,369 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/189 for batch 8.
2026-10-10 11:55:37,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/189 for batch 8.
2026-10-10 11:55:37,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/189 for batch 8.
2026-10-10 11:55:38,475 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/189 for batch 8.
2026-10-10 11:55:39,396 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/189 for batch 8.
2026-10-10 11:55:39,538 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/189 for batch 8.
2026-10-10 11:55:39,622 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/189 for batch 8.
2026-10-10 11:55:39,707 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/189 for batch 8.
2026-10-10 11:55:39,811 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/189 for batch 8.
2026-10-10 11:55:39,914 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/189 for batch 8.
2026-10-10 11:55:40,850 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/189 for batch 8.
2026-10-10 11:55:40,936 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/189 for batch 8.
2026-10-10 11:55:41,021 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/189 for batch 8.
2026-10-10 11:55:41,109 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/189 for batch 8.
2026-10-10 11:55:42,008 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/189 for batch 8.
2026-10-10 11:55:42,108 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/189 for batch 8.
2026-10-10 11:55:42,209 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/189 for batch 8.
2026-10-10 11:55:43,109 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/189 for batch 8.
2026-10-10 11:55:43,212 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/189 for batch 8.
2026-10-10 11:55:43,311 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/189 for batch 8.
2026-10-10 11:55:44,221 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/189 for batch 8.
2026-10-10 11:55:45,114 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/189 for batch 8.
2026-10-10 11:55:45,211 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/189 for batch 8.
2026-10-10 11:55:45,308 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/189 for batch 8.
2026-10-10 11:55:45,397 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/189 for batch 8.
2026-10-10 11:55:45,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/189 for batch 8.
2026-10-10 11:55:45,565 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/189 for batch 8.
2026-10-10 11:55:46,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/189 for batch 8.
2026-10-10 11:55:46,562 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/189 for batch 8.
2026-10-10 11:55:46,646 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/189 for batch 8.
2026-10-10 11:55:46,744 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/189 for batch 8.
2026-10-10 11:55:46,841 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/189 for batch 8.
2026-10-10 11:55:47,744 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/189 for batch 8.
2026-10-10 11:55:47,827 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/189 for batch 8.
2026-10-10 11:55:47,923 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/189 for batch 8.
2026-10-10 11:55:48,019 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/189 for batch 8.
2026-10-10 11:55:48,101 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/189 for batch 8.
2026-10-10 11:55:48,199 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/189 for batch 8.
2026-10-10 11:55:49,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/189 for batch 8.
2026-10-10 11:55:49,976 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/189 for batch 8.
2026-10-10 11:55:50,865 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/189 for batch 8.
2026-10-10 11:55:51,773 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/189 for batch 8.
2026-10-10 11:55:51,874 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/189 for batch 8.
2026-10-10 11:55:51,960 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/189 for batch 8.
2026-10-10 11:55:52,041 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/189 for batch 8.
2026-10-10 11:55:52,140 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/189 for batch 8.
2026-10-10 11:55:53,043 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/189 for batch 8.
2026-10-10 11:55:53,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/189 for batch 8.
2026-10-10 11:55:54,080 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/189 for batch 8.
2026-10-10 11:55:54,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/189 for batch 8.
2026-10-10 11:55:54,297 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/189 for batch 8.
2026-10-10 11:55:54,383 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/189 for batch 8.
2026-10-10 11:55:54,476 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/189 for batch 8.
2026-10-10 11:55:54,580 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/189 for batch 8.
2026-10-10 11:55:54,694 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/189 for batch 8.
2026-10-10 11:55:54,785 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/189 for batch 8.
2026-10-10 11:55:55,671 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/189 for batch 8.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00008_monthly_cleaning_report.partial.parquet

2026-10-10 11:56:15,974 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/189.
2026-10-10 11:56:18,289 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/189.
2026-10-10 11:56:20,519 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/189.
2026-10-10 11:56:22,832 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/189.
2026-10-10 11:56:25,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/189.
2026-10-10 11:56:27,237 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/189.
2026-10-10 11:56:29,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/189.
2026-10-10 11:56:31,629 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/189.
2026-10-10 11:56:34,146 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/189.
2026-10-10 11:56:36,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/189.
2026-10-10 11:56:38,525 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/189.
2026-10-10 11:56:40,673 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/189.
2026-10-10 11:56:42,869 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/189.
2026-10-10 11:56:45,084 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/189.
2026-10-10 11:56:47,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/189.
2026-10-10 11:56:49,752 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/189.
2026-10-10 11:56:52,184 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/189.
2026-10-10 11:56:54,970 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/189.
2026-10-10 11:56:57,177 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 189/189.
2026-10-10 11:56:58,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00008_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00008_monthly_cleaning_report.parquet

2026-10-10 11:59:13,558 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 135 parcels from batch_00008_monthly.nc.
2026-10-10 11:59:15,800 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00004_monthly.nc.
2026-10-10 11:59:19,026 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/189 for batch 4.
2026-10-10 11:59:22,709 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/189 for batch 4.
2026-10-10 11:59:25,954 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/189 for batch 4.
2026-10-10 11:59:29,018 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/189 for batch 4.
2026-10-10 11:59:32,135 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/189 for batch 4.
2026-10-10 11:59:35,105 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/189 for batch 4.
2026-10-10 11:59:38,564 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/189 for batch 4.
2026-10-10 11:59:41,582 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/189 for batch 4.
2026-10-10 11:59:44,847 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/189 for batch 4.
2026-10-10 11:59:48,162 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/189 for batch 4.
2026-10-10 11:59:51,506 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/189 for batch 4.
2026-10-10 11:59:54,967 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/189 for batch 4.
2026-10-10 11:59:58,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/189 for batch 4.
2026-10-10 12:00:02,039 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/189 for batch 4.
2026-10-10 12:00:05,507 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/189 for batch 4.
2026-10-10 12:00:09,015 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/189 for batch 4.
2026-10-10 12:00:12,253 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/189 for batch 4.
2026-10-10 12:00:15,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/189 for batch 4.
2026-10-10 12:00:18,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 189/189 for batch 4.
2026-10-10 12:00:18,442 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 6 rows.
2026-10-10 12:00:55,876 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 6 rows.
2026-10-10 12:01:33,619 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 6 rows.
2026-10-10 12:02:11,227 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 6 rows.
2026-10-10 12:02:49,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 6 rows.
2026-10-10 12:03:26,661 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 6 rows.
2026-10-10 12:04:04,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 6 rows.
2026-10-10 12:04:41,396 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 6 rows.
2026-10-10 12:05:18,586 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 6 rows.
2026-10-10 12:05:58,260 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/189 for batch 4.
2026-10-10 12:05:58,470 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/189 for batch 4.
2026-10-10 12:05:58,716 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/189 for batch 4.
2026-10-10 12:06:01,182 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/189 for batch 4.
2026-10-10 12:06:01,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/189 for batch 4.
2026-10-10 12:06:01,577 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/189 for batch 4.
2026-10-10 12:06:03,898 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/189 for batch 4.
2026-10-10 12:06:04,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/189 for batch 4.
2026-10-10 12:06:06,482 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/189 for batch 4.
2026-10-10 12:06:06,653 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/189 for batch 4.
2026-10-10 12:06:09,019 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/189 for batch 4.
2026-10-10 12:06:09,204 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/189 for batch 4.
2026-10-10 12:06:09,505 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/189 for batch 4.
2026-10-10 12:06:09,677 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/189 for batch 4.
2026-10-10 12:06:12,137 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/189 for batch 4.
2026-10-10 12:06:12,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/189 for batch 4.
2026-10-10 12:06:14,805 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/189 for batch 4.
2026-10-10 12:06:15,019 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/189 for batch 4.
2026-10-10 12:06:17,403 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/189 for batch 4.
2026-10-10 12:06:17,575 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/189 for batch 4.
2026-10-10 12:06:17,749 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/189 for batch 4.
2026-10-10 12:06:17,963 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/189 for batch 4.
2026-10-10 12:06:18,131 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/189 for batch 4.
2026-10-10 12:06:18,300 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/189 for batch 4.
2026-10-10 12:06:18,469 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/189 for batch 4.
2026-10-10 12:06:20,856 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/189 for batch 4.
2026-10-10 12:06:21,070 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/189 for batch 4.
2026-10-10 12:06:23,534 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/189 for batch 4.
2026-10-10 12:06:23,739 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/189 for batch 4.
2026-10-10 12:06:23,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/189 for batch 4.
2026-10-10 12:06:24,082 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/189 for batch 4.
2026-10-10 12:06:24,288 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/189 for batch 4.
2026-10-10 12:06:24,459 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/189 for batch 4.
2026-10-10 12:06:24,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/189 for batch 4.
2026-10-10 12:06:26,349 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/189 for batch 4.
2026-10-10 12:06:26,556 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/189 for batch 4.
2026-10-10 12:06:26,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/189 for batch 4.
2026-10-10 12:06:26,939 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/189 for batch 4.
2026-10-10 12:06:27,110 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/189 for batch 4.
2026-10-10 12:06:27,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/189 for batch 4.
2026-10-10 12:06:27,450 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/189 for batch 4.
2026-10-10 12:06:29,818 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/189 for batch 4.
2026-10-10 12:06:30,037 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/189 for batch 4.
2026-10-10 12:06:32,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/189 for batch 4.
2026-10-10 12:06:32,990 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/189 for batch 4.
2026-10-10 12:06:33,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/189 for batch 4.
2026-10-10 12:06:33,351 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/189 for batch 4.
2026-10-10 12:06:33,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/189 for batch 4.
2026-10-10 12:06:33,775 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/189 for batch 4.
2026-10-10 12:06:33,945 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/189 for batch 4.
2026-10-10 12:06:34,116 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/189 for batch 4.
2026-10-10 12:06:34,325 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/189 for batch 4.
2026-10-10 12:06:36,653 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/189 for batch 4.
2026-10-10 12:06:36,828 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/189 for batch 4.
2026-10-10 12:06:37,036 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/189 for batch 4.
2026-10-10 12:06:37,205 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/189 for batch 4.
2026-10-10 12:06:37,378 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/189 for batch 4.
2026-10-10 12:06:37,593 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/189 for batch 4.
2026-10-10 12:06:37,766 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/189 for batch 4.
2026-10-10 12:06:40,110 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/189 for batch 4.
2026-10-10 12:06:40,300 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/189 for batch 4.
2026-10-10 12:06:40,550 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/189 for batch 4.
2026-10-10 12:06:40,763 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/189 for batch 4.
2026-10-10 12:06:43,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/189 for batch 4.
2026-10-10 12:06:43,433 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/189 for batch 4.
2026-10-10 12:06:45,869 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/189 for batch 4.
2026-10-10 12:06:46,082 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/189 for batch 4.
2026-10-10 12:06:48,436 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/189 for batch 4.
2026-10-10 12:06:48,611 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/189 for batch 4.
2026-10-10 12:06:48,835 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/189 for batch 4.
2026-10-10 12:06:49,018 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/189 for batch 4.
2026-10-10 12:06:49,200 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/189 for batch 4.
2026-10-10 12:06:49,383 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/189 for batch 4.
2026-10-10 12:06:49,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/189 for batch 4.
2026-10-10 12:06:51,968 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/189 for batch 4.
2026-10-10 12:06:52,163 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/189 for batch 4.
2026-10-10 12:06:52,343 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/189 for batch 4.
2026-10-10 12:06:55,189 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/189 for batch 4.
2026-10-10 12:06:55,358 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/189 for batch 4.
2026-10-10 12:06:55,529 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/189 for batch 4.
2026-10-10 12:06:55,702 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/189 for batch 4.
2026-10-10 12:06:58,122 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/189 for batch 4.
2026-10-10 12:06:58,297 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/189 for batch 4.
2026-10-10 12:06:58,475 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/189 for batch 4.
2026-10-10 12:06:58,643 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/189 for batch 4.
2026-10-10 12:06:58,816 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/189 for batch 4.
2026-10-10 12:06:58,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/189 for batch 4.
2026-10-10 12:06:59,163 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/189 for batch 4.
2026-10-10 12:06:59,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/189 for batch 4.
2026-10-10 12:06:59,510 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/189 for batch 4.
2026-10-10 12:06:59,683 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/189 for batch 4.
2026-10-10 12:06:59,859 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/189 for batch 4.
2026-10-10 12:07:00,033 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/189 for batch 4.
2026-10-10 12:07:00,205 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/189 for batch 4.
2026-10-10 12:07:00,381 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/189 for batch 4.
2026-10-10 12:07:00,553 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/189 for batch 4.
2026-10-10 12:07:03,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/189 for batch 4.
2026-10-10 12:07:03,197 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/189 for batch 4.
2026-10-10 12:07:03,374 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/189 for batch 4.
2026-10-10 12:07:03,544 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/189 for batch 4.
2026-10-10 12:07:03,718 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/189 for batch 4.
2026-10-10 12:07:03,891 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/189 for batch 4.
2026-10-10 12:07:06,283 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/189 for batch 4.
2026-10-10 12:07:06,456 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/189 for batch 4.
2026-10-10 12:07:06,633 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/189 for batch 4.
2026-10-10 12:07:09,080 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/189 for batch 4.
2026-10-10 12:07:09,254 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/189 for batch 4.
2026-10-10 12:07:11,639 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/189 for batch 4.
2026-10-10 12:07:14,005 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/189 for batch 4.
2026-10-10 12:07:14,226 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/189 for batch 4.
2026-10-10 12:07:14,398 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/189 for batch 4.
2026-10-10 12:07:14,568 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/189 for batch 4.
2026-10-10 12:07:14,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/189 for batch 4.
2026-10-10 12:07:14,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/189 for batch 4.
2026-10-10 12:07:15,075 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/189 for batch 4.
2026-10-10 12:07:15,246 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/189 for batch 4.
2026-10-10 12:07:15,414 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/189 for batch 4.
2026-10-10 12:07:15,585 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/189 for batch 4.
2026-10-10 12:07:15,768 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/189 for batch 4.
2026-10-10 12:07:18,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/189 for batch 4.
2026-10-10 12:07:20,418 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/189 for batch 4.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00004_monthly_cleaning_report.partial.parquet

2026-10-10 12:08:02,821 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/189.
2026-10-10 12:08:08,144 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/189.
2026-10-10 12:08:13,377 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/189.
2026-10-10 12:08:18,538 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/189.
2026-10-10 12:08:23,851 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/189.
2026-10-10 12:08:30,008 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/189.
2026-10-10 12:08:36,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/189.
2026-10-10 12:08:42,444 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/189.
2026-10-10 12:08:48,871 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/189.
2026-10-10 12:08:55,838 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/189.
2026-10-10 12:09:02,940 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/189.
2026-10-10 12:09:09,852 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/189.
2026-10-10 12:09:16,912 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/189.
2026-10-10 12:09:23,915 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/189.
2026-10-10 12:09:30,852 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/189.
2026-10-10 12:09:38,399 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/189.
2026-10-10 12:09:46,232 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/189.
2026-10-10 12:09:53,760 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/189.
2026-10-10 12:10:00,128 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 189/189.
2026-10-10 12:10:01,148 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00004_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00004_monthly_cleaning_report.parquet

2026-10-10 12:12:45,719 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 165 parcels from batch_00004_monthly.nc.
2026-10-10 12:12:48,668 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00005_monthly.nc.
2026-10-10 12:12:51,371 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 5.
2026-10-10 12:12:54,373 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 5.
2026-10-10 12:12:56,825 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 5.
2026-10-10 12:12:59,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 5.
2026-10-10 12:13:01,891 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 5.
2026-10-10 12:13:04,489 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 5.
2026-10-10 12:13:06,851 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 5.
2026-10-10 12:13:09,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 5.
2026-10-10 12:13:12,272 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 5.
2026-10-10 12:13:14,919 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 5.
2026-10-10 12:13:17,536 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 5.
2026-10-10 12:13:20,430 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 5.
2026-10-10 12:13:23,189 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 5.
2026-10-10 12:13:25,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 5.
2026-10-10 12:13:28,862 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 5.
2026-10-10 12:13:31,682 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 5.
2026-10-10 12:13:34,530 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 5.
2026-10-10 12:13:37,185 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 5.
2026-10-10 12:13:37,463 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 5.
2026-10-10 12:13:37,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-10 12:13:54,889 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-10 12:14:12,399 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-10 12:14:29,965 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-10 12:14:47,715 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-10 12:15:05,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-10 12:15:22,864 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-10 12:15:40,515 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-10 12:15:58,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-10 12:16:17,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 5.
2026-10-10 12:16:17,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 5.
2026-10-10 12:16:17,459 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 5.
2026-10-10 12:16:17,577 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 5.
2026-10-10 12:16:17,694 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 5.
2026-10-10 12:16:17,913 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 5.
2026-10-10 12:16:19,511 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 5.
2026-10-10 12:16:19,723 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 5.
2026-10-10 12:16:19,846 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 5.
2026-10-10 12:16:19,967 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 5.
2026-10-10 12:16:20,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 5.
2026-10-10 12:16:21,803 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 5.
2026-10-10 12:16:23,488 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 5.
2026-10-10 12:16:25,095 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 5.
2026-10-10 12:16:26,707 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 5.
2026-10-10 12:16:28,397 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 5.
2026-10-10 12:16:29,963 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 5.
2026-10-10 12:16:31,615 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 5.
2026-10-10 12:16:33,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 5.
2026-10-10 12:16:33,414 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 5.
2026-10-10 12:16:33,618 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 5.
2026-10-10 12:16:33,760 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 5.
2026-10-10 12:16:33,942 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 5.
2026-10-10 12:16:34,101 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 5.
2026-10-10 12:16:35,848 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 5.
2026-10-10 12:16:36,104 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 5.
2026-10-10 12:16:36,226 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 5.
2026-10-10 12:16:36,343 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 5.
2026-10-10 12:16:36,539 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 5.
2026-10-10 12:16:36,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 5.
2026-10-10 12:16:36,910 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 5.
2026-10-10 12:16:37,031 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 5.
2026-10-10 12:16:37,183 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 5.
2026-10-10 12:16:37,304 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 5.
2026-10-10 12:16:37,524 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 5.
2026-10-10 12:16:38,265 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 5.
2026-10-10 12:16:38,394 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 5.
2026-10-10 12:16:38,551 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 5.
2026-10-10 12:16:38,707 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 5.
2026-10-10 12:16:39,363 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 5.
2026-10-10 12:16:40,004 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 5.
2026-10-10 12:16:41,655 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 5.
2026-10-10 12:16:41,875 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 5.
2026-10-10 12:16:42,501 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 5.
2026-10-10 12:16:42,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 5.
2026-10-10 12:16:42,854 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 5.
2026-10-10 12:16:44,448 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 5.
2026-10-10 12:16:45,622 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 5.
2026-10-10 12:16:47,203 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 5.
2026-10-10 12:16:47,415 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 5.
2026-10-10 12:16:48,019 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 5.
2026-10-10 12:16:48,208 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 5.
2026-10-10 12:16:48,329 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 5.
2026-10-10 12:16:48,451 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 5.
2026-10-10 12:16:48,644 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 5.
2026-10-10 12:16:50,232 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 5.
2026-10-10 12:16:51,826 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 5.
2026-10-10 12:16:52,013 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 5.
2026-10-10 12:16:52,638 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 5.
2026-10-10 12:16:53,078 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 5.
2026-10-10 12:16:54,415 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 5.
2026-10-10 12:16:54,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 5.
2026-10-10 12:16:54,700 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 5.
2026-10-10 12:16:56,280 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 5.
2026-10-10 12:16:57,879 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 5.
2026-10-10 12:16:58,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 5.
2026-10-10 12:16:58,170 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 5.
2026-10-10 12:16:58,313 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 5.
2026-10-10 12:16:58,432 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 5.
2026-10-10 12:16:58,578 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 5.
2026-10-10 12:16:58,730 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 5.
2026-10-10 12:16:58,850 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 5.
2026-10-10 12:17:00,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 5.
2026-10-10 12:17:00,612 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 5.
2026-10-10 12:17:02,192 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 5.
2026-10-10 12:17:03,768 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 5.
2026-10-10 12:17:03,912 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 5.
2026-10-10 12:17:04,057 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 5.
2026-10-10 12:17:04,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 5.
2026-10-10 12:17:04,293 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 5.
2026-10-10 12:17:04,446 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 5.
2026-10-10 12:17:04,590 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 5.
2026-10-10 12:17:04,722 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 5.
2026-10-10 12:17:04,840 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 5.
2026-10-10 12:17:04,988 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 5.
2026-10-10 12:17:05,135 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 5.
2026-10-10 12:17:05,256 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 5.
2026-10-10 12:17:05,374 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 5.
2026-10-10 12:17:05,520 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 5.
2026-10-10 12:17:05,666 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 5.
2026-10-10 12:17:07,201 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 5.
2026-10-10 12:17:08,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 5.
2026-10-10 12:17:08,927 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 5.
2026-10-10 12:17:09,076 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 5.
2026-10-10 12:17:10,668 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 5.
2026-10-10 12:17:10,814 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 5.
2026-10-10 12:17:12,004 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 5.
2026-10-10 12:17:12,600 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 5.
2026-10-10 12:17:12,721 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 5.
2026-10-10 12:17:14,347 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 5.
2026-10-10 12:17:14,539 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 5.
2026-10-10 12:17:16,101 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 5.
2026-10-10 12:17:16,224 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 5.
2026-10-10 12:17:16,371 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 5.
2026-10-10 12:17:18,009 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 5.
2026-10-10 12:17:18,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 5.
2026-10-10 12:17:18,748 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 5.
2026-10-10 12:17:18,898 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 5.
2026-10-10 12:17:19,049 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 5.
2026-10-10 12:17:19,212 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 5.
2026-10-10 12:17:19,327 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 5.
2026-10-10 12:17:19,467 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 5.
2026-10-10 12:17:20,086 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 5.
2026-10-10 12:17:20,206 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 5.
2026-10-10 12:17:21,756 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 5.
2026-10-10 12:17:21,907 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 5.
2026-10-10 12:17:22,056 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 5.
2026-10-10 12:17:22,189 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 5.
2026-10-10 12:17:22,310 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 5.
2026-10-10 12:17:22,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 5.
2026-10-10 12:17:22,604 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/181 for batch 5.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00005_monthly_cleaning_report.partial.parquet

2026-10-10 12:18:10,149 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 12:18:14,032 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 12:18:17,885 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 12:18:21,610 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 12:18:25,320 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 12:18:29,090 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 12:18:33,462 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 12:18:37,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 12:18:41,132 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 12:18:45,208 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 12:18:48,891 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 12:18:52,607 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 12:18:56,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 12:19:01,241 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 12:19:05,864 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 12:19:10,693 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 12:19:15,801 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 12:19:20,945 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 12:19:21,454 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 12:19:22,467 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00005_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00005_monthly_cleaning_report.parquet

2026-10-10 12:19:57,267 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 33 parcels from batch_00005_monthly.nc.
2026-10-10 12:19:59,802 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00002_monthly.nc.
2026-10-10 12:20:05,445 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/147 for batch 2.
2026-10-10 12:20:10,533 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/147 for batch 2.
2026-10-10 12:20:15,473 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/147 for batch 2.
2026-10-10 12:20:20,211 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/147 for batch 2.
2026-10-10 12:20:25,297 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/147 for batch 2.
2026-10-10 12:20:29,953 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/147 for batch 2.
2026-10-10 12:20:35,364 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/147 for batch 2.
2026-10-10 12:20:40,530 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/147 for batch 2.
2026-10-10 12:20:45,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/147 for batch 2.
2026-10-10 12:20:51,285 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/147 for batch 2.
2026-10-10 12:20:56,627 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/147 for batch 2.
2026-10-10 12:21:02,156 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/147 for batch 2.
2026-10-10 12:21:07,549 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/147 for batch 2.
2026-10-10 12:21:12,425 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/147 for batch 2.
2026-10-10 12:21:16,240 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 147/147 for batch 2.
2026-10-10 12:21:16,241 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 12:21:57,272 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 12:22:38,251 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 12:23:19,045 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 12:24:00,306 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 12:24:41,436 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 12:25:22,517 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 12:26:04,225 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 12:26:45,719 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 12:27:31,141 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/147 for batch 2.
2026-10-10 12:27:31,621 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/147 for batch 2.
2026-10-10 12:27:35,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/147 for batch 2.
2026-10-10 12:27:36,314 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/147 for batch 2.
2026-10-10 12:27:36,632 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/147 for batch 2.
2026-10-10 12:27:40,695 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/147 for batch 2.
2026-10-10 12:27:41,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/147 for batch 2.
2026-10-10 12:27:41,353 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/147 for batch 2.
2026-10-10 12:27:44,320 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/147 for batch 2.
2026-10-10 12:27:45,663 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/147 for batch 2.
2026-10-10 12:27:49,747 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/147 for batch 2.
2026-10-10 12:27:50,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/147 for batch 2.
2026-10-10 12:27:54,245 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/147 for batch 2.
2026-10-10 12:27:54,568 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/147 for batch 2.
2026-10-10 12:27:54,884 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/147 for batch 2.
2026-10-10 12:27:55,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/147 for batch 2.
2026-10-10 12:27:59,242 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/147 for batch 2.
2026-10-10 12:27:59,497 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/147 for batch 2.
2026-10-10 12:27:59,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/147 for batch 2.
2026-10-10 12:28:03,809 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/147 for batch 2.
2026-10-10 12:28:05,164 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/147 for batch 2.
2026-10-10 12:28:09,304 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/147 for batch 2.
2026-10-10 12:28:09,627 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/147 for batch 2.
2026-10-10 12:28:09,877 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/147 for batch 2.
2026-10-10 12:28:10,193 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/147 for batch 2.
2026-10-10 12:28:11,771 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/147 for batch 2.
2026-10-10 12:28:13,219 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/147 for batch 2.
2026-10-10 12:28:17,231 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/147 for batch 2.
2026-10-10 12:28:17,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/147 for batch 2.
2026-10-10 12:28:17,809 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/147 for batch 2.
2026-10-10 12:28:18,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/147 for batch 2.
2026-10-10 12:28:18,614 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/147 for batch 2.
2026-10-10 12:28:19,931 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/147 for batch 2.
2026-10-10 12:28:20,186 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/147 for batch 2.
2026-10-10 12:28:20,505 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/147 for batch 2.
2026-10-10 12:28:20,757 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/147 for batch 2.
2026-10-10 12:28:22,145 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/147 for batch 2.
2026-10-10 12:28:26,221 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/147 for batch 2.
2026-10-10 12:28:26,546 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/147 for batch 2.
2026-10-10 12:28:26,795 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/147 for batch 2.
2026-10-10 12:28:30,912 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/147 for batch 2.
2026-10-10 12:28:31,233 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/147 for batch 2.
2026-10-10 12:28:32,779 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/147 for batch 2.
2026-10-10 12:28:33,103 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/147 for batch 2.
2026-10-10 12:28:37,483 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/147 for batch 2.
2026-10-10 12:28:38,821 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/147 for batch 2.
2026-10-10 12:28:39,081 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/147 for batch 2.
2026-10-10 12:28:39,401 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/147 for batch 2.
2026-10-10 12:28:43,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/147 for batch 2.
2026-10-10 12:28:44,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/147 for batch 2.
2026-10-10 12:28:49,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/147 for batch 2.
2026-10-10 12:28:49,315 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/147 for batch 2.
2026-10-10 12:28:49,637 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/147 for batch 2.
2026-10-10 12:28:49,968 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/147 for batch 2.
2026-10-10 12:28:54,176 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/147 for batch 2.
2026-10-10 12:28:54,486 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/147 for batch 2.
2026-10-10 12:28:54,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/147 for batch 2.
2026-10-10 12:28:58,952 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/147 for batch 2.
2026-10-10 12:28:59,276 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/147 for batch 2.
2026-10-10 12:28:59,595 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/147 for batch 2.
2026-10-10 12:29:03,642 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/147 for batch 2.
2026-10-10 12:29:04,013 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/147 for batch 2.
2026-10-10 12:29:08,061 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/147 for batch 2.
2026-10-10 12:29:08,389 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/147 for batch 2.
2026-10-10 12:29:08,711 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/147 for batch 2.
2026-10-10 12:29:08,979 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/147 for batch 2.
2026-10-10 12:29:09,236 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/147 for batch 2.
2026-10-10 12:29:09,562 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/147 for batch 2.
2026-10-10 12:29:09,887 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/147 for batch 2.
2026-10-10 12:29:10,141 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/147 for batch 2.
2026-10-10 12:29:10,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/147 for batch 2.
2026-10-10 12:29:10,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/147 for batch 2.
2026-10-10 12:29:15,028 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/147 for batch 2.
2026-10-10 12:29:15,283 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/147 for batch 2.
2026-10-10 12:29:15,538 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/147 for batch 2.
2026-10-10 12:29:19,617 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/147 for batch 2.
2026-10-10 12:29:19,936 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/147 for batch 2.
2026-10-10 12:29:24,036 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/147 for batch 2.
2026-10-10 12:29:28,121 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/147 for batch 2.
2026-10-10 12:29:28,456 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/147 for batch 2.
2026-10-10 12:29:32,592 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/147 for batch 2.
2026-10-10 12:29:36,918 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/147 for batch 2.
2026-10-10 12:29:37,244 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/147 for batch 2.
2026-10-10 12:29:37,568 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/147 for batch 2.
2026-10-10 12:29:37,820 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/147 for batch 2.
2026-10-10 12:29:38,072 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/147 for batch 2.
2026-10-10 12:29:38,323 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/147 for batch 2.
2026-10-10 12:29:38,577 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/147 for batch 2.
2026-10-10 12:29:38,900 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/147 for batch 2.
2026-10-10 12:29:39,224 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/147 for batch 2.
2026-10-10 12:29:43,363 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/147 for batch 2.
2026-10-10 12:29:43,627 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/147 for batch 2.
2026-10-10 12:29:43,954 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/147 for batch 2.
2026-10-10 12:29:44,217 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/147 for batch 2.
2026-10-10 12:29:44,477 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/147 for batch 2.
2026-10-10 12:29:44,808 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/147 for batch 2.
2026-10-10 12:29:45,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/147 for batch 2.
2026-10-10 12:29:45,341 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/147 for batch 2.
2026-10-10 12:29:45,663 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/147 for batch 2.
2026-10-10 12:29:45,987 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/147 for batch 2.
2026-10-10 12:29:46,250 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/147 for batch 2.
2026-10-10 12:29:46,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/147 for batch 2.
2026-10-10 12:29:46,921 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/147 for batch 2.
2026-10-10 12:29:47,183 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/147 for batch 2.
2026-10-10 12:29:47,509 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/147 for batch 2.
2026-10-10 12:29:47,832 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/147 for batch 2.
2026-10-10 12:29:48,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/147 for batch 2.
2026-10-10 12:29:48,356 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/147 for batch 2.
2026-10-10 12:29:48,677 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/147 for batch 2.
2026-10-10 12:29:48,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/147 for batch 2.
2026-10-10 12:29:49,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/147 for batch 2.
2026-10-10 12:29:49,518 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/147 for batch 2.
2026-10-10 12:29:49,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/147 for batch 2.
2026-10-10 12:29:50,035 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/147 for batch 2.
2026-10-10 12:29:50,357 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/147 for batch 2.
2026-10-10 12:29:50,681 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/147 for batch 2.
2026-10-10 12:29:50,942 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/147 for batch 2.
2026-10-10 12:29:51,270 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/147 for batch 2.
2026-10-10 12:29:51,589 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/147 for batch 2.
2026-10-10 12:29:55,632 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/147 for batch 2.
2026-10-10 12:29:56,962 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/147 for batch 2.
2026-10-10 12:29:57,225 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/147 for batch 2.
2026-10-10 12:29:57,480 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/147 for batch 2.
2026-10-10 12:29:57,800 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 124/147 for batch 2.
2026-10-10 12:29:58,121 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 125/147 for batch 2.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00002_monthly_cleaning_report.partial.parquet

2026-10-10 12:30:28,162 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/147.
2026-10-10 12:30:36,249 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/147.
2026-10-10 12:30:44,536 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/147.
2026-10-10 12:30:52,751 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/147.
2026-10-10 12:31:02,262 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/147.
2026-10-10 12:31:11,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/147.
2026-10-10 12:31:22,116 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/147.
2026-10-10 12:31:32,692 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/147.
2026-10-10 12:31:43,210 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/147.
2026-10-10 12:31:53,389 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/147.
2026-10-10 12:32:03,646 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/147.
2026-10-10 12:32:14,031 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/147.
2026-10-10 12:32:24,624 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/147.
2026-10-10 12:32:35,333 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/147.
2026-10-10 12:32:42,964 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 147/147.
2026-10-10 12:32:43,951 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00002_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00002_monthly_cleaning_report.parquet

2026-10-10 12:33:04,140 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 16 parcels from batch_00002_monthly.nc.
2026-10-10 12:33:06,950 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00010_monthly.nc.
2026-10-10 12:33:09,445 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 10.
2026-10-10 12:33:12,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 10.
2026-10-10 12:33:14,788 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 10.
2026-10-10 12:33:17,301 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 10.
2026-10-10 12:33:19,585 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 10.
2026-10-10 12:33:22,132 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 10.
2026-10-10 12:33:24,541 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 10.
2026-10-10 12:33:27,085 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 10.
2026-10-10 12:33:29,657 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 10.
2026-10-10 12:33:32,178 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 10.
2026-10-10 12:33:34,624 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 10.
2026-10-10 12:33:37,309 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 10.
2026-10-10 12:33:39,990 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 10.
2026-10-10 12:33:42,629 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 10.
2026-10-10 12:33:45,548 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 10.
2026-10-10 12:33:47,996 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 10.
2026-10-10 12:33:50,412 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 10.
2026-10-10 12:33:52,819 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 10.
2026-10-10 12:33:53,080 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 10.
2026-10-10 12:33:53,081 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 12 rows.
2026-10-10 12:34:06,889 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 12 rows.
2026-10-10 12:34:21,052 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 12 rows.
2026-10-10 12:34:35,043 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 12 rows.
2026-10-10 12:34:49,214 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 12 rows.
2026-10-10 12:35:03,167 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 12 rows.
2026-10-10 12:35:17,050 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 12 rows.
2026-10-10 12:35:31,067 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 12 rows.
2026-10-10 12:35:45,244 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 12 rows.
2026-10-10 12:35:59,342 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 10.
2026-10-10 12:35:59,510 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 10.
2026-10-10 12:36:01,013 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 10.
2026-10-10 12:36:01,125 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 10.
2026-10-10 12:36:01,234 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 10.
2026-10-10 12:36:01,431 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 10.
2026-10-10 12:36:01,539 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 10.
2026-10-10 12:36:01,739 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 10.
2026-10-10 12:36:01,852 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 10.
2026-10-10 12:36:01,965 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 10.
2026-10-10 12:36:02,172 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 10.
2026-10-10 12:36:02,285 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 10.
2026-10-10 12:36:02,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 10.
2026-10-10 12:36:02,577 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 10.
2026-10-10 12:36:02,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 10.
2026-10-10 12:36:02,894 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 10.
2026-10-10 12:36:03,009 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 10.
2026-10-10 12:36:03,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 10.
2026-10-10 12:36:03,788 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 10.
2026-10-10 12:36:03,927 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 10.
2026-10-10 12:36:04,067 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 10.
2026-10-10 12:36:04,640 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 10.
2026-10-10 12:36:04,781 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 10.
2026-10-10 12:36:04,921 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 10.
2026-10-10 12:36:06,422 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 10.
2026-10-10 12:36:06,556 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 10.
2026-10-10 12:36:07,122 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 10.
2026-10-10 12:36:07,698 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 10.
2026-10-10 12:36:07,861 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 10.
2026-10-10 12:36:07,973 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 10.
2026-10-10 12:36:08,138 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 10.
2026-10-10 12:36:08,253 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 10.
2026-10-10 12:36:08,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 10.
2026-10-10 12:36:08,506 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 10.
2026-10-10 12:36:08,645 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 10.
2026-10-10 12:36:08,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 10.
2026-10-10 12:36:08,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 10.
2026-10-10 12:36:09,053 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 10.
2026-10-10 12:36:09,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 10.
2026-10-10 12:36:10,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 10.
2026-10-10 12:36:12,116 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 10.
2026-10-10 12:36:13,611 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 10.
2026-10-10 12:36:13,807 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 10.
2026-10-10 12:36:13,968 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 10.
2026-10-10 12:36:14,124 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 10.
2026-10-10 12:36:14,286 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 10.
2026-10-10 12:36:15,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 10.
2026-10-10 12:36:15,910 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 10.
2026-10-10 12:36:16,475 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 10.
2026-10-10 12:36:16,674 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 10.
2026-10-10 12:36:16,784 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 10.
2026-10-10 12:36:16,943 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 10.
2026-10-10 12:36:18,374 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 10.
2026-10-10 12:36:19,843 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 10.
2026-10-10 12:36:20,001 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 10.
2026-10-10 12:36:21,015 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 10.
2026-10-10 12:36:22,057 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 10.
2026-10-10 12:36:22,194 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 10.
2026-10-10 12:36:22,305 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 10.
2026-10-10 12:36:22,485 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 10.
2026-10-10 12:36:22,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 10.
2026-10-10 12:36:22,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 10.
2026-10-10 12:36:22,873 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 10.
2026-10-10 12:36:22,985 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 10.
2026-10-10 12:36:23,094 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 10.
2026-10-10 12:36:23,227 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 10.
2026-10-10 12:36:23,339 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 10.
2026-10-10 12:36:23,475 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 10.
2026-10-10 12:36:24,948 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 10.
2026-10-10 12:36:25,091 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 10.
2026-10-10 12:36:25,233 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 10.
2026-10-10 12:36:26,687 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 10.
2026-10-10 12:36:28,172 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 10.
2026-10-10 12:36:28,310 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 10.
2026-10-10 12:36:28,447 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 10.
2026-10-10 12:36:28,561 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 10.
2026-10-10 12:36:28,698 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 10.
2026-10-10 12:36:30,155 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 10.
2026-10-10 12:36:30,270 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 10.
2026-10-10 12:36:30,384 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 10.
2026-10-10 12:36:30,522 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 10.
2026-10-10 12:36:30,661 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 10.
2026-10-10 12:36:32,138 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 10.
2026-10-10 12:36:33,552 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 10.
2026-10-10 12:36:33,691 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 10.
2026-10-10 12:36:33,826 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 10.
2026-10-10 12:36:33,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 10.
2026-10-10 12:36:34,045 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 10.
2026-10-10 12:36:35,083 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 10.
2026-10-10 12:36:35,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 10.
2026-10-10 12:36:36,681 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 10.
2026-10-10 12:36:38,116 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 10.
2026-10-10 12:36:38,256 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 10.
2026-10-10 12:36:38,394 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 10.
2026-10-10 12:36:40,152 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 10.
2026-10-10 12:36:40,312 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 10.
2026-10-10 12:36:40,455 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 10.
2026-10-10 12:36:40,573 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 10.
2026-10-10 12:36:40,688 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 10.
2026-10-10 12:36:40,853 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 10.
2026-10-10 12:36:40,992 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 10.
2026-10-10 12:36:42,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 10.
2026-10-10 12:36:42,581 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 10.
2026-10-10 12:36:42,718 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 10.
2026-10-10 12:36:44,161 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 10.
2026-10-10 12:36:44,274 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 10.
2026-10-10 12:36:44,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 10.
2026-10-10 12:36:44,555 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 10.
2026-10-10 12:36:44,697 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 10.
2026-10-10 12:36:44,806 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 10.
2026-10-10 12:36:44,919 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 10.
2026-10-10 12:36:45,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 10.
2026-10-10 12:36:45,192 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 10.
2026-10-10 12:36:45,302 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 10.
2026-10-10 12:36:45,414 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 10.
2026-10-10 12:36:45,553 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 10.
2026-10-10 12:36:45,695 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 10.
2026-10-10 12:36:45,808 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 10.
2026-10-10 12:36:45,922 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 10.
2026-10-10 12:36:46,059 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 10.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00010_monthly_cleaning_report.partial.parquet

2026-10-10 12:37:01,683 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 12:37:05,319 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 12:37:08,966 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 12:37:12,570 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 12:37:16,275 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 12:37:19,880 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 12:37:23,372 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 12:37:26,899 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 12:37:30,437 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 12:37:33,963 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 12:37:37,458 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 12:37:41,294 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 12:37:44,719 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 12:37:48,179 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 12:37:51,819 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 12:37:55,796 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 12:37:59,854 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 12:38:04,102 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 12:38:04,583 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 12:38:05,634 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00010_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00010_monthly_cleaning_report.parquet

2026-10-10 12:38:39,846 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 30 parcels from batch_00010_monthly.nc.
2026-10-10 12:38:42,369 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00012_monthly.nc.
2026-10-10 12:38:44,247 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 12.
2026-10-10 12:38:46,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 12.
2026-10-10 12:38:48,244 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 12.
2026-10-10 12:38:50,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 12.
2026-10-10 12:38:51,933 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 12.
2026-10-10 12:38:53,877 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 12.
2026-10-10 12:38:55,673 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 12.
2026-10-10 12:38:57,528 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 12.
2026-10-10 12:38:59,494 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 12.
2026-10-10 12:39:01,264 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 12.
2026-10-10 12:39:03,065 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 12.
2026-10-10 12:39:05,054 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 12.
2026-10-10 12:39:06,970 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 12.
2026-10-10 12:39:08,899 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 12.
2026-10-10 12:39:10,835 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 12.
2026-10-10 12:39:12,768 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 12.
2026-10-10 12:39:14,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 12.
2026-10-10 12:39:16,390 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 12.
2026-10-10 12:39:16,580 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 12.
2026-10-10 12:39:16,581 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 16 rows.
2026-10-10 12:39:25,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 16 rows.
2026-10-10 12:39:33,316 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 16 rows.
2026-10-10 12:39:41,708 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 16 rows.
2026-10-10 12:39:49,865 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 16 rows.
2026-10-10 12:39:58,005 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 16 rows.
2026-10-10 12:40:06,147 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 16 rows.
2026-10-10 12:40:14,471 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 16 rows.
2026-10-10 12:40:22,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 16 rows.
2026-10-10 12:40:30,724 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 12.
2026-10-10 12:40:30,848 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 12.
2026-10-10 12:40:30,933 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 12.
2026-10-10 12:40:31,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 12.
2026-10-10 12:40:31,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 12.
2026-10-10 12:40:31,208 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 12.
2026-10-10 12:40:31,297 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 12.
2026-10-10 12:40:31,419 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 12.
2026-10-10 12:40:31,511 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 12.
2026-10-10 12:40:31,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 12.
2026-10-10 12:40:31,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 12.
2026-10-10 12:40:31,829 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 12.
2026-10-10 12:40:31,951 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 12.
2026-10-10 12:40:32,036 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 12.
2026-10-10 12:40:32,120 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 12.
2026-10-10 12:40:32,220 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 12.
2026-10-10 12:40:32,307 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 12.
2026-10-10 12:40:32,429 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 12.
2026-10-10 12:40:32,829 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 12.
2026-10-10 12:40:32,914 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 12.
2026-10-10 12:40:32,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 12.
2026-10-10 12:40:33,086 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 12.
2026-10-10 12:40:33,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 12.
2026-10-10 12:40:33,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 12.
2026-10-10 12:40:34,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 12.
2026-10-10 12:40:34,471 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 12.
2026-10-10 12:40:35,440 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 12.
2026-10-10 12:40:36,416 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 12.
2026-10-10 12:40:36,537 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 12.
2026-10-10 12:40:36,638 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 12.
2026-10-10 12:40:36,776 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 12.
2026-10-10 12:40:37,794 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 12.
2026-10-10 12:40:37,921 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 12.
2026-10-10 12:40:38,010 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 12.
2026-10-10 12:40:38,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 12.
2026-10-10 12:40:38,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 12.
2026-10-10 12:40:39,277 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 12.
2026-10-10 12:40:39,431 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 12.
2026-10-10 12:40:39,518 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 12.
2026-10-10 12:40:39,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 12.
2026-10-10 12:40:39,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 12.
2026-10-10 12:40:40,764 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 12.
2026-10-10 12:40:40,874 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 12.
2026-10-10 12:40:40,960 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 12.
2026-10-10 12:40:41,047 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 12.
2026-10-10 12:40:41,169 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 12.
2026-10-10 12:40:42,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 12.
2026-10-10 12:40:42,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 12.
2026-10-10 12:40:43,317 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 12.
2026-10-10 12:40:43,435 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 12.
2026-10-10 12:40:44,424 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 12.
2026-10-10 12:40:44,531 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 12.
2026-10-10 12:40:45,263 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 12.
2026-10-10 12:40:45,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 12.
2026-10-10 12:40:46,112 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 12.
2026-10-10 12:40:46,834 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 12.
2026-10-10 12:40:47,565 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 12.
2026-10-10 12:40:47,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 12.
2026-10-10 12:40:47,739 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 12.
2026-10-10 12:40:47,842 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 12.
2026-10-10 12:40:47,929 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 12.
2026-10-10 12:40:48,033 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 12.
2026-10-10 12:40:48,134 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 12.
2026-10-10 12:40:48,221 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 12.
2026-10-10 12:40:48,308 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 12.
2026-10-10 12:40:48,410 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 12.
2026-10-10 12:40:48,497 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 12.
2026-10-10 12:40:48,582 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 12.
2026-10-10 12:40:49,569 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 12.
2026-10-10 12:40:49,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 12.
2026-10-10 12:40:49,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 12.
2026-10-10 12:40:50,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 12.
2026-10-10 12:40:51,756 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 12.
2026-10-10 12:40:51,860 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 12.
2026-10-10 12:40:51,970 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 12.
2026-10-10 12:40:52,054 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 12.
2026-10-10 12:40:52,155 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 12.
2026-10-10 12:40:52,257 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 12.
2026-10-10 12:40:52,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 12.
2026-10-10 12:40:52,431 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 12.
2026-10-10 12:40:52,537 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 12.
2026-10-10 12:40:52,640 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 12.
2026-10-10 12:40:53,620 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 12.
2026-10-10 12:40:54,595 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 12.
2026-10-10 12:40:54,700 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 12.
2026-10-10 12:40:54,802 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 12.
2026-10-10 12:40:54,896 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 12.
2026-10-10 12:40:54,982 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 12.
2026-10-10 12:40:55,086 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 12.
2026-10-10 12:40:55,189 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 12.
2026-10-10 12:40:56,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 12.
2026-10-10 12:40:57,185 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 12.
2026-10-10 12:40:57,301 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 12.
2026-10-10 12:40:57,394 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 12.
2026-10-10 12:40:58,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 12.
2026-10-10 12:40:58,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 12.
2026-10-10 12:40:59,511 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 12.
2026-10-10 12:40:59,603 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 12.
2026-10-10 12:41:00,588 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 12.
2026-10-10 12:41:01,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 12.
2026-10-10 12:41:01,670 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 12.
2026-10-10 12:41:02,646 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 12.
2026-10-10 12:41:02,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 12.
2026-10-10 12:41:02,833 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 12.
2026-10-10 12:41:03,821 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 12.
2026-10-10 12:41:03,919 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 12.
2026-10-10 12:41:04,003 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 12.
2026-10-10 12:41:04,089 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 12.
2026-10-10 12:41:04,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 12.
2026-10-10 12:41:04,259 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 12.
2026-10-10 12:41:04,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 12.
2026-10-10 12:41:04,433 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 12.
2026-10-10 12:41:04,519 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 12.
2026-10-10 12:41:04,604 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 12.
2026-10-10 12:41:05,562 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 12.
2026-10-10 12:41:05,646 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 12.
2026-10-10 12:41:05,730 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 12.
2026-10-10 12:41:05,815 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 12.
2026-10-10 12:41:05,902 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 12.
2026-10-10 12:41:06,004 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 12.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00012_monthly_cleaning_report.partial.parquet

2026-10-10 12:41:15,966 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 12:41:18,390 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 12:41:20,789 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 12:41:23,210 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 12:41:25,534 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 12:41:28,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 12:41:30,796 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 12:41:33,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 12:41:35,602 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 12:41:37,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 12:41:40,535 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 12:41:42,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 12:41:45,181 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 12:41:47,531 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 12:41:49,899 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 12:41:52,190 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 12:41:54,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 12:41:56,726 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 12:41:56,953 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 12:41:57,762 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00012_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00012_monthly_cleaning_report.parquet

2026-10-10 12:42:09,179 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 12 parcels from batch_00012_monthly.nc.
2026-10-10 12:42:11,064 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00011_monthly.nc.
2026-10-10 12:42:13,823 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 11.
2026-10-10 12:42:16,981 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 11.
2026-10-10 12:42:19,541 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 11.
2026-10-10 12:42:22,265 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 11.
2026-10-10 12:42:24,853 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 11.
2026-10-10 12:42:27,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 11.
2026-10-10 12:42:30,272 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 11.
2026-10-10 12:42:33,031 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 11.
2026-10-10 12:42:35,955 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 11.
2026-10-10 12:42:38,687 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 11.
2026-10-10 12:42:41,565 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 11.
2026-10-10 12:42:44,588 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 11.
2026-10-10 12:42:47,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 11.
2026-10-10 12:42:50,356 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 11.
2026-10-10 12:42:53,337 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 11.
2026-10-10 12:42:56,143 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 11.
2026-10-10 12:42:58,822 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 11.
2026-10-10 12:43:01,449 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 11.
2026-10-10 12:43:01,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 11.
2026-10-10 12:43:01,754 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 6 rows.
2026-10-10 12:43:28,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 6 rows.
2026-10-10 12:43:55,072 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 6 rows.
2026-10-10 12:44:21,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 6 rows.
2026-10-10 12:44:48,301 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 6 rows.
2026-10-10 12:45:14,985 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 6 rows.
2026-10-10 12:45:41,772 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 6 rows.
2026-10-10 12:46:08,534 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 6 rows.
2026-10-10 12:46:35,099 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 6 rows.
2026-10-10 12:47:02,344 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 11.
2026-10-10 12:47:02,516 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 11.
2026-10-10 12:47:04,018 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 11.
2026-10-10 12:47:04,147 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 11.
2026-10-10 12:47:05,772 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 11.
2026-10-10 12:47:05,927 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 11.
2026-10-10 12:47:06,051 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 11.
2026-10-10 12:47:06,200 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 11.
2026-10-10 12:47:06,325 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 11.
2026-10-10 12:47:06,449 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 11.
2026-10-10 12:47:06,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 11.
2026-10-10 12:47:06,723 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 11.
2026-10-10 12:47:06,874 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 11.
2026-10-10 12:47:07,003 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 11.
2026-10-10 12:47:07,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 11.
2026-10-10 12:47:07,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 11.
2026-10-10 12:47:07,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 11.
2026-10-10 12:47:07,569 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 11.
2026-10-10 12:47:08,683 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 11.
2026-10-10 12:47:08,858 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 11.
2026-10-10 12:47:08,982 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 11.
2026-10-10 12:47:10,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 11.
2026-10-10 12:47:10,620 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 11.
2026-10-10 12:47:10,753 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 11.
2026-10-10 12:47:10,890 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 11.
2026-10-10 12:47:11,054 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 11.
2026-10-10 12:47:12,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 11.
2026-10-10 12:47:14,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 11.
2026-10-10 12:47:14,561 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 11.
2026-10-10 12:47:14,696 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 11.
2026-10-10 12:47:14,855 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 11.
2026-10-10 12:47:14,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 11.
2026-10-10 12:47:15,120 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 11.
2026-10-10 12:47:15,256 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 11.
2026-10-10 12:47:15,388 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 11.
2026-10-10 12:47:15,581 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 11.
2026-10-10 12:47:15,721 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 11.
2026-10-10 12:47:15,865 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 11.
2026-10-10 12:47:16,003 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 11.
2026-10-10 12:47:16,138 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 11.
2026-10-10 12:47:16,271 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 11.
2026-10-10 12:47:17,914 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 11.
2026-10-10 12:47:18,084 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 11.
2026-10-10 12:47:18,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 11.
2026-10-10 12:47:18,357 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 11.
2026-10-10 12:47:18,522 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 11.
2026-10-10 12:47:20,153 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 11.
2026-10-10 12:47:20,314 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 11.
2026-10-10 12:47:21,947 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 11.
2026-10-10 12:47:22,114 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 11.
2026-10-10 12:47:22,248 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 11.
2026-10-10 12:47:22,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 11.
2026-10-10 12:47:24,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 11.
2026-10-10 12:47:25,821 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 11.
2026-10-10 12:47:26,012 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 11.
2026-10-10 12:47:27,655 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 11.
2026-10-10 12:47:29,324 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 11.
2026-10-10 12:47:29,455 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 11.
2026-10-10 12:47:30,079 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 11.
2026-10-10 12:47:30,241 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 11.
2026-10-10 12:47:30,374 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 11.
2026-10-10 12:47:30,509 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 11.
2026-10-10 12:47:30,648 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 11.
2026-10-10 12:47:31,306 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 11.
2026-10-10 12:47:31,945 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 11.
2026-10-10 12:47:32,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 11.
2026-10-10 12:47:32,204 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 11.
2026-10-10 12:47:32,331 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 11.
2026-10-10 12:47:33,964 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 11.
2026-10-10 12:47:34,091 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 11.
2026-10-10 12:47:34,216 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 11.
2026-10-10 12:47:34,350 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 11.
2026-10-10 12:47:35,892 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 11.
2026-10-10 12:47:36,020 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 11.
2026-10-10 12:47:37,642 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 11.
2026-10-10 12:47:39,318 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 11.
2026-10-10 12:47:39,476 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 11.
2026-10-10 12:47:39,712 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 11.
2026-10-10 12:47:39,864 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 11.
2026-10-10 12:47:40,001 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 11.
2026-10-10 12:47:40,132 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 11.
2026-10-10 12:47:40,262 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 11.
2026-10-10 12:47:41,805 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 11.
2026-10-10 12:47:43,696 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 11.
2026-10-10 12:47:43,828 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 11.
2026-10-10 12:47:43,972 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 11.
2026-10-10 12:47:44,105 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 11.
2026-10-10 12:47:44,235 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 11.
2026-10-10 12:47:44,366 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 11.
2026-10-10 12:47:44,494 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 11.
2026-10-10 12:47:46,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 11.
2026-10-10 12:47:47,560 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 11.
2026-10-10 12:47:47,696 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 11.
2026-10-10 12:47:47,825 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 11.
2026-10-10 12:47:49,363 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 11.
2026-10-10 12:47:49,497 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 11.
2026-10-10 12:47:51,020 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 11.
2026-10-10 12:47:52,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 11.
2026-10-10 12:47:54,220 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 11.
2026-10-10 12:47:55,747 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 11.
2026-10-10 12:47:55,880 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 11.
2026-10-10 12:47:57,456 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 11.
2026-10-10 12:47:57,584 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 11.
2026-10-10 12:47:57,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 11.
2026-10-10 12:47:59,260 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 11.
2026-10-10 12:48:00,801 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 11.
2026-10-10 12:48:00,933 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 11.
2026-10-10 12:48:01,063 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 11.
2026-10-10 12:48:01,192 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 11.
2026-10-10 12:48:01,321 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 11.
2026-10-10 12:48:01,456 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 11.
2026-10-10 12:48:01,587 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 11.
2026-10-10 12:48:01,722 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 11.
2026-10-10 12:48:01,854 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 11.
2026-10-10 12:48:03,422 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 11.
2026-10-10 12:48:03,551 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 11.
2026-10-10 12:48:03,680 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 11.
2026-10-10 12:48:03,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 11.
2026-10-10 12:48:03,944 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 11.
2026-10-10 12:48:04,076 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 11.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00011_monthly_cleaning_report.partial.parquet

2026-10-10 12:48:22,678 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 12:48:26,890 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 12:48:30,966 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 12:48:34,994 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 12:48:39,002 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 12:48:43,324 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 12:48:47,262 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 12:48:51,234 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 12:48:55,038 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 12:48:58,892 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 12:49:02,874 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 12:49:07,285 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 12:49:11,842 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 12:49:16,436 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 12:49:21,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 12:49:26,882 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 12:49:32,163 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 12:49:37,530 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 12:49:38,063 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 12:49:39,201 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00011_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00011_monthly_cleaning_report.parquet

2026-10-10 12:50:19,095 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 32 parcels from batch_00011_monthly.nc.
2026-10-10 12:50:21,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00006_monthly.nc.
2026-10-10 12:50:26,175 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 6.
2026-10-10 12:50:31,115 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 6.
2026-10-10 12:50:35,231 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 6.
2026-10-10 12:50:39,550 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 6.
2026-10-10 12:50:43,596 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 6.
2026-10-10 12:50:48,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 6.
2026-10-10 12:50:52,266 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 6.
2026-10-10 12:50:56,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 6.
2026-10-10 12:51:00,963 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 6.
2026-10-10 12:51:05,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 6.
2026-10-10 12:51:09,737 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 6.
2026-10-10 12:51:14,438 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 6.
2026-10-10 12:51:18,893 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 6.
2026-10-10 12:51:23,391 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 6.
2026-10-10 12:51:28,256 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 6.
2026-10-10 12:51:32,882 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 6.
2026-10-10 12:51:37,176 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 6.
2026-10-10 12:51:41,518 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 6.
2026-10-10 12:51:41,938 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 6.
2026-10-10 12:51:41,939 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 6 rows.
2026-10-10 12:52:27,790 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 6 rows.
2026-10-10 12:53:14,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 6 rows.
2026-10-10 12:54:01,301 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 6 rows.
2026-10-10 12:54:47,032 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 6 rows.
2026-10-10 12:55:32,931 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 6 rows.
2026-10-10 12:56:18,903 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 6 rows.
2026-10-10 12:57:05,178 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 6 rows.
2026-10-10 12:57:51,044 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 6 rows.
2026-10-10 12:58:39,423 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 6.
2026-10-10 12:58:39,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 6.
2026-10-10 12:58:42,858 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 6.
2026-10-10 12:58:43,749 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 6.
2026-10-10 12:58:46,680 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 6.
2026-10-10 12:58:47,082 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 6.
2026-10-10 12:58:50,175 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 6.
2026-10-10 12:58:50,428 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 6.
2026-10-10 12:58:51,325 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 6.
2026-10-10 12:58:51,529 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 6.
2026-10-10 12:58:51,918 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 6.
2026-10-10 12:58:52,127 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 6.
2026-10-10 12:58:52,384 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 6.
2026-10-10 12:58:52,595 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 6.
2026-10-10 12:58:52,806 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 6.
2026-10-10 12:58:53,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 6.
2026-10-10 12:58:53,401 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 6.
2026-10-10 12:58:53,657 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 6.
2026-10-10 12:58:56,589 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 6.
2026-10-10 12:58:56,792 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 6.
2026-10-10 12:58:56,994 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 6.
2026-10-10 12:58:57,206 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 6.
2026-10-10 12:58:57,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 6.
2026-10-10 12:58:57,614 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 6.
2026-10-10 12:59:00,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 6.
2026-10-10 12:59:00,876 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 6.
2026-10-10 12:59:03,845 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 6.
2026-10-10 12:59:06,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 6.
2026-10-10 12:59:07,038 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 6.
2026-10-10 12:59:09,952 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 6.
2026-10-10 12:59:10,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 6.
2026-10-10 12:59:13,228 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 6.
2026-10-10 12:59:13,480 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 6.
2026-10-10 12:59:13,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 6.
2026-10-10 12:59:13,938 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 6.
2026-10-10 12:59:16,985 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 6.
2026-10-10 12:59:17,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 6.
2026-10-10 12:59:17,436 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 6.
2026-10-10 12:59:17,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 6.
2026-10-10 12:59:20,626 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 6.
2026-10-10 12:59:23,657 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 6.
2026-10-10 12:59:26,661 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 6.
2026-10-10 12:59:27,048 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 6.
2026-10-10 12:59:30,011 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 6.
2026-10-10 12:59:30,218 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 6.
2026-10-10 12:59:30,520 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 6.
2026-10-10 12:59:33,494 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 6.
2026-10-10 12:59:33,702 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 6.
2026-10-10 12:59:36,687 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 6.
2026-10-10 12:59:36,949 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 6.
2026-10-10 12:59:40,168 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 6.
2026-10-10 12:59:40,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 6.
2026-10-10 12:59:40,639 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 6.
2026-10-10 12:59:43,602 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 6.
2026-10-10 12:59:43,944 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 6.
2026-10-10 12:59:46,907 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 6.
2026-10-10 12:59:49,898 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 6.
2026-10-10 12:59:50,151 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 6.
2026-10-10 12:59:50,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 6.
2026-10-10 12:59:50,614 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 6.
2026-10-10 12:59:53,617 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 6.
2026-10-10 12:59:56,648 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 6.
2026-10-10 12:59:56,899 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 6.
2026-10-10 12:59:57,102 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 6.
2026-10-10 12:59:57,308 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 6.
2026-10-10 12:59:57,566 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 6.
2026-10-10 12:59:57,769 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 6.
2026-10-10 12:59:58,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 6.
2026-10-10 13:00:01,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 6.
2026-10-10 13:00:01,230 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 6.
2026-10-10 13:00:01,435 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 6.
2026-10-10 13:00:01,638 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 6.
2026-10-10 13:00:04,612 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 6.
2026-10-10 13:00:04,875 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 6.
2026-10-10 13:00:07,966 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 6.
2026-10-10 13:00:11,134 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 6.
2026-10-10 13:00:11,401 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 6.
2026-10-10 13:00:14,406 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 6.
2026-10-10 13:00:14,611 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 6.
2026-10-10 13:00:14,814 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 6.
2026-10-10 13:00:15,069 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 6.
2026-10-10 13:00:15,322 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 6.
2026-10-10 13:00:16,521 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 6.
2026-10-10 13:00:17,666 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 6.
2026-10-10 13:00:17,867 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 6.
2026-10-10 13:00:18,072 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 6.
2026-10-10 13:00:18,277 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 6.
2026-10-10 13:00:18,484 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 6.
2026-10-10 13:00:18,743 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 6.
2026-10-10 13:00:18,998 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 6.
2026-10-10 13:00:21,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 6.
2026-10-10 13:00:24,893 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 6.
2026-10-10 13:00:25,155 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 6.
2026-10-10 13:00:25,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 6.
2026-10-10 13:00:28,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 6.
2026-10-10 13:00:28,683 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 6.
2026-10-10 13:00:31,818 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 6.
2026-10-10 13:00:32,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 6.
2026-10-10 13:00:32,227 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 6.
2026-10-10 13:00:35,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 6.
2026-10-10 13:00:35,548 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 6.
2026-10-10 13:00:38,564 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 6.
2026-10-10 13:00:38,785 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 6.
2026-10-10 13:00:39,095 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 6.
2026-10-10 13:00:42,413 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 6.
2026-10-10 13:00:42,621 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 6.
2026-10-10 13:00:42,829 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 6.
2026-10-10 13:00:43,083 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 6.
2026-10-10 13:00:43,337 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 6.
2026-10-10 13:00:43,537 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 6.
2026-10-10 13:00:43,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 6.
2026-10-10 13:00:43,998 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 6.
2026-10-10 13:00:44,250 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 6.
2026-10-10 13:00:44,454 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 6.
2026-10-10 13:00:47,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 6.
2026-10-10 13:00:47,666 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 6.
2026-10-10 13:00:47,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 6.
2026-10-10 13:00:48,122 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 6.
2026-10-10 13:00:50,270 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 6.
2026-10-10 13:00:52,423 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 6.
2026-10-10 13:00:52,679 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/181 for batch 6.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00006_monthly_cleaning_report.partial.parquet

2026-10-10 13:01:35,816 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 13:01:42,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 13:01:48,836 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 13:01:55,245 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 13:02:02,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 13:02:09,893 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 13:02:17,506 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 13:02:25,507 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 13:02:33,965 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 13:02:42,910 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 13:02:51,354 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 13:02:59,791 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 13:03:08,101 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 13:03:16,390 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 13:03:24,944 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 13:03:33,445 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 13:03:42,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 13:03:50,439 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 13:03:51,285 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 13:03:52,346 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00006_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00006_monthly_cleaning_report.parquet

2026-10-10 13:04:36,916 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 35 parcels from batch_00006_monthly.nc.
2026-10-10 13:04:39,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00013_monthly.nc.
2026-10-10 13:04:42,614 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 13.
2026-10-10 13:04:45,540 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 13.
2026-10-10 13:04:47,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 13.
2026-10-10 13:04:50,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 13.
2026-10-10 13:04:52,707 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 13.
2026-10-10 13:04:55,272 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 13.
2026-10-10 13:04:57,740 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 13.
2026-10-10 13:05:00,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 13.
2026-10-10 13:05:03,027 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 13.
2026-10-10 13:05:05,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 13.
2026-10-10 13:05:07,901 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 13.
2026-10-10 13:05:10,487 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 13.
2026-10-10 13:05:13,051 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 13.
2026-10-10 13:05:15,588 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 13.
2026-10-10 13:05:18,204 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 13.
2026-10-10 13:05:20,783 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 13.
2026-10-10 13:05:23,154 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 13.
2026-10-10 13:05:25,556 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 13.
2026-10-10 13:05:25,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 13.
2026-10-10 13:05:25,813 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 9 rows.
2026-10-10 13:05:43,212 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 9 rows.
2026-10-10 13:06:00,605 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 9 rows.
2026-10-10 13:06:17,848 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 9 rows.
2026-10-10 13:06:35,006 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 9 rows.
2026-10-10 13:06:52,458 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 9 rows.
2026-10-10 13:07:09,802 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 9 rows.
2026-10-10 13:07:27,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 9 rows.
2026-10-10 13:07:44,555 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 9 rows.
2026-10-10 13:08:01,971 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 13.
2026-10-10 13:08:02,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 13.
2026-10-10 13:08:03,921 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 13.
2026-10-10 13:08:04,029 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 13.
2026-10-10 13:08:04,140 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 13.
2026-10-10 13:08:04,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 13.
2026-10-10 13:08:04,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 13.
2026-10-10 13:08:04,930 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 13.
2026-10-10 13:08:05,042 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 13.
2026-10-10 13:08:05,155 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 13.
2026-10-10 13:08:05,290 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 13.
2026-10-10 13:08:05,404 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 13.
2026-10-10 13:08:05,872 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 13.
2026-10-10 13:08:05,986 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 13.
2026-10-10 13:08:06,100 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 13.
2026-10-10 13:08:06,237 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 13.
2026-10-10 13:08:06,347 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 13.
2026-10-10 13:08:06,830 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 13.
2026-10-10 13:08:06,947 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 13.
2026-10-10 13:08:07,087 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 13.
2026-10-10 13:08:07,225 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 13.
2026-10-10 13:08:07,363 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 13.
2026-10-10 13:08:07,527 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 13.
2026-10-10 13:08:07,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 13.
2026-10-10 13:08:09,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 13.
2026-10-10 13:08:09,298 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 13.
2026-10-10 13:08:10,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 13.
2026-10-10 13:08:12,157 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 13.
2026-10-10 13:08:12,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 13.
2026-10-10 13:08:12,740 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 13.
2026-10-10 13:08:12,879 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 13.
2026-10-10 13:08:12,990 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 13.
2026-10-10 13:08:13,463 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 13.
2026-10-10 13:08:13,573 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 13.
2026-10-10 13:08:13,712 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 13.
2026-10-10 13:08:13,850 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 13.
2026-10-10 13:08:15,333 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 13.
2026-10-10 13:08:15,475 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 13.
2026-10-10 13:08:15,618 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 13.
2026-10-10 13:08:17,035 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 13.
2026-10-10 13:08:17,159 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 13.
2026-10-10 13:08:18,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 13.
2026-10-10 13:08:18,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 13.
2026-10-10 13:08:20,337 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 13.
2026-10-10 13:08:21,791 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 13.
2026-10-10 13:08:22,265 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 13.
2026-10-10 13:08:23,685 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 13.
2026-10-10 13:08:23,810 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 13.
2026-10-10 13:08:25,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 13.
2026-10-10 13:08:25,554 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 13.
2026-10-10 13:08:27,020 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 13.
2026-10-10 13:08:27,488 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 13.
2026-10-10 13:08:28,915 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 13.
2026-10-10 13:08:30,408 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 13.
2026-10-10 13:08:30,543 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 13.
2026-10-10 13:08:30,654 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 13.
2026-10-10 13:08:30,795 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 13.
2026-10-10 13:08:30,944 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 13.
2026-10-10 13:08:31,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 13.
2026-10-10 13:08:31,533 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 13.
2026-10-10 13:08:31,647 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 13.
2026-10-10 13:08:31,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 13.
2026-10-10 13:08:31,929 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 13.
2026-10-10 13:08:32,962 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 13.
2026-10-10 13:08:34,012 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 13.
2026-10-10 13:08:34,154 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 13.
2026-10-10 13:08:34,268 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 13.
2026-10-10 13:08:34,406 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 13.
2026-10-10 13:08:35,932 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 13.
2026-10-10 13:08:36,069 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 13.
2026-10-10 13:08:36,205 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 13.
2026-10-10 13:08:37,634 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 13.
2026-10-10 13:08:39,109 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 13.
2026-10-10 13:08:39,260 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 13.
2026-10-10 13:08:39,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 13.
2026-10-10 13:08:39,652 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 13.
2026-10-10 13:08:39,923 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 13.
2026-10-10 13:08:40,180 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 13.
2026-10-10 13:08:40,316 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 13.
2026-10-10 13:08:40,457 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 13.
2026-10-10 13:08:40,625 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 13.
2026-10-10 13:08:40,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 13.
2026-10-10 13:08:40,903 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 13.
2026-10-10 13:08:41,016 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 13.
2026-10-10 13:08:41,221 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 13.
2026-10-10 13:08:41,431 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 13.
2026-10-10 13:08:41,541 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 13.
2026-10-10 13:08:41,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 13.
2026-10-10 13:08:41,793 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 13.
2026-10-10 13:08:41,933 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 13.
2026-10-10 13:08:43,368 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 13.
2026-10-10 13:08:44,790 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 13.
2026-10-10 13:08:44,958 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 13.
2026-10-10 13:08:45,125 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 13.
2026-10-10 13:08:46,644 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 13.
2026-10-10 13:08:46,779 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 13.
2026-10-10 13:08:48,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 13.
2026-10-10 13:08:48,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 13.
2026-10-10 13:08:49,368 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 13.
2026-10-10 13:08:50,427 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 13.
2026-10-10 13:08:50,648 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 13.
2026-10-10 13:08:52,102 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 13.
2026-10-10 13:08:52,216 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 13.
2026-10-10 13:08:52,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 13.
2026-10-10 13:08:53,837 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 13.
2026-10-10 13:08:53,959 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 13.
2026-10-10 13:08:54,077 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 13.
2026-10-10 13:08:54,218 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 13.
2026-10-10 13:08:54,365 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 13.
2026-10-10 13:08:54,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 13.
2026-10-10 13:08:54,592 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 13.
2026-10-10 13:08:54,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 13.
2026-10-10 13:08:54,879 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 13.
2026-10-10 13:08:54,996 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 13.
2026-10-10 13:08:56,466 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 13.
2026-10-10 13:08:56,639 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 13.
2026-10-10 13:08:56,820 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 13.
2026-10-10 13:08:56,936 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 13.
2026-10-10 13:08:57,053 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 13.
2026-10-10 13:08:57,201 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 13.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00013_monthly_cleaning_report.partial.parquet

2026-10-10 13:09:11,090 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 13:09:14,785 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 13:09:18,448 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 13:09:22,043 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 13:09:25,607 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 13:09:29,186 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 13:09:32,691 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 13:09:36,207 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 13:09:39,992 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 13:09:43,601 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 13:09:47,097 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 13:09:50,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 13:09:54,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 13:09:57,547 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 13:10:01,555 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 13:10:05,616 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 13:10:09,787 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 13:10:14,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 13:10:15,011 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 13:10:16,017 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00013_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00013_monthly_cleaning_report.parquet

2026-10-10 13:11:05,081 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 43 parcels from batch_00013_monthly.nc.
2026-10-10 13:11:07,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00014_monthly.nc.
2026-10-10 13:11:10,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/152 for batch 14.
2026-10-10 13:11:13,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/152 for batch 14.
2026-10-10 13:11:15,740 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/152 for batch 14.
2026-10-10 13:11:18,154 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/152 for batch 14.
2026-10-10 13:11:20,689 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/152 for batch 14.
2026-10-10 13:11:23,291 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/152 for batch 14.
2026-10-10 13:11:26,165 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/152 for batch 14.
2026-10-10 13:11:28,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/152 for batch 14.
2026-10-10 13:11:31,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/152 for batch 14.
2026-10-10 13:11:34,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/152 for batch 14.
2026-10-10 13:11:37,299 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/152 for batch 14.
2026-10-10 13:11:40,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/152 for batch 14.
2026-10-10 13:11:42,890 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/152 for batch 14.
2026-10-10 13:11:45,610 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/152 for batch 14.
2026-10-10 13:11:48,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/152 for batch 14.
2026-10-10 13:11:48,848 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 152/152 for batch 14.
2026-10-10 13:11:48,849 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 12 rows.
2026-10-10 13:12:01,280 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 12 rows.
2026-10-10 13:12:13,643 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 12 rows.
2026-10-10 13:12:26,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 12 rows.
2026-10-10 13:12:38,479 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 12 rows.
2026-10-10 13:12:51,160 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 12 rows.
2026-10-10 13:13:03,493 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 12 rows.
2026-10-10 13:13:15,872 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 12 rows.
2026-10-10 13:13:28,321 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 12 rows.
2026-10-10 13:13:41,161 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/152 for batch 14.
2026-10-10 13:13:41,278 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/152 for batch 14.
2026-10-10 13:13:41,393 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/152 for batch 14.
2026-10-10 13:13:41,506 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/152 for batch 14.
2026-10-10 13:13:41,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/152 for batch 14.
2026-10-10 13:13:41,829 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/152 for batch 14.
2026-10-10 13:13:41,957 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/152 for batch 14.
2026-10-10 13:13:42,075 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/152 for batch 14.
2026-10-10 13:13:42,290 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/152 for batch 14.
2026-10-10 13:13:42,414 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/152 for batch 14.
2026-10-10 13:13:42,531 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/152 for batch 14.
2026-10-10 13:13:42,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/152 for batch 14.
2026-10-10 13:13:42,773 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/152 for batch 14.
2026-10-10 13:13:42,918 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/152 for batch 14.
2026-10-10 13:13:43,040 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/152 for batch 14.
2026-10-10 13:13:43,158 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/152 for batch 14.
2026-10-10 13:13:43,281 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/152 for batch 14.
2026-10-10 13:13:43,453 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/152 for batch 14.
2026-10-10 13:13:43,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/152 for batch 14.
2026-10-10 13:13:43,743 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/152 for batch 14.
2026-10-10 13:13:45,364 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/152 for batch 14.
2026-10-10 13:13:45,524 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/152 for batch 14.
2026-10-10 13:13:47,009 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/152 for batch 14.
2026-10-10 13:13:47,150 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/152 for batch 14.
2026-10-10 13:13:47,268 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/152 for batch 14.
2026-10-10 13:13:47,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/152 for batch 14.
2026-10-10 13:13:47,584 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/152 for batch 14.
2026-10-10 13:13:47,703 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/152 for batch 14.
2026-10-10 13:13:47,846 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/152 for batch 14.
2026-10-10 13:13:47,964 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/152 for batch 14.
2026-10-10 13:13:49,501 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/152 for batch 14.
2026-10-10 13:13:49,645 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/152 for batch 14.
2026-10-10 13:13:51,239 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/152 for batch 14.
2026-10-10 13:13:51,413 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/152 for batch 14.
2026-10-10 13:13:51,523 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/152 for batch 14.
2026-10-10 13:13:51,683 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/152 for batch 14.
2026-10-10 13:13:53,151 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/152 for batch 14.
2026-10-10 13:13:54,637 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/152 for batch 14.
2026-10-10 13:13:56,135 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/152 for batch 14.
2026-10-10 13:13:56,252 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/152 for batch 14.
2026-10-10 13:13:57,745 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/152 for batch 14.
2026-10-10 13:13:57,918 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/152 for batch 14.
2026-10-10 13:13:59,413 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/152 for batch 14.
2026-10-10 13:14:00,938 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/152 for batch 14.
2026-10-10 13:14:02,428 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/152 for batch 14.
2026-10-10 13:14:02,571 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/152 for batch 14.
2026-10-10 13:14:02,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/152 for batch 14.
2026-10-10 13:14:02,802 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/152 for batch 14.
2026-10-10 13:14:02,986 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/152 for batch 14.
2026-10-10 13:14:03,106 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/152 for batch 14.
2026-10-10 13:14:03,225 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/152 for batch 14.
2026-10-10 13:14:03,339 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/152 for batch 14.
2026-10-10 13:14:03,545 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/152 for batch 14.
2026-10-10 13:14:03,661 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/152 for batch 14.
2026-10-10 13:14:04,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/152 for batch 14.
2026-10-10 13:14:04,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/152 for batch 14.
2026-10-10 13:14:05,011 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/152 for batch 14.
2026-10-10 13:14:06,484 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/152 for batch 14.
2026-10-10 13:14:06,625 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/152 for batch 14.
2026-10-10 13:14:06,741 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/152 for batch 14.
2026-10-10 13:14:06,857 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/152 for batch 14.
2026-10-10 13:14:06,997 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/152 for batch 14.
2026-10-10 13:14:07,112 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/152 for batch 14.
2026-10-10 13:14:07,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/152 for batch 14.
2026-10-10 13:14:07,492 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/152 for batch 14.
2026-10-10 13:14:07,613 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/152 for batch 14.
2026-10-10 13:14:07,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/152 for batch 14.
2026-10-10 13:14:07,894 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/152 for batch 14.
2026-10-10 13:14:08,008 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/152 for batch 14.
2026-10-10 13:14:08,124 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/152 for batch 14.
2026-10-10 13:14:08,330 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/152 for batch 14.
2026-10-10 13:14:08,448 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/152 for batch 14.
2026-10-10 13:14:08,563 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/152 for batch 14.
2026-10-10 13:14:08,682 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/152 for batch 14.
2026-10-10 13:14:08,824 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/152 for batch 14.
2026-10-10 13:14:08,941 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/152 for batch 14.
2026-10-10 13:14:09,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/152 for batch 14.
2026-10-10 13:14:09,250 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/152 for batch 14.
2026-10-10 13:14:10,739 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/152 for batch 14.
2026-10-10 13:14:12,239 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/152 for batch 14.
2026-10-10 13:14:12,360 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/152 for batch 14.
2026-10-10 13:14:12,946 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/152 for batch 14.
2026-10-10 13:14:13,546 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/152 for batch 14.
2026-10-10 13:14:13,689 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/152 for batch 14.
2026-10-10 13:14:15,183 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/152 for batch 14.
2026-10-10 13:14:15,301 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/152 for batch 14.
2026-10-10 13:14:16,816 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/152 for batch 14.
2026-10-10 13:14:16,939 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/152 for batch 14.
2026-10-10 13:14:17,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/152 for batch 14.
2026-10-10 13:14:17,681 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/152 for batch 14.
2026-10-10 13:14:17,823 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/152 for batch 14.
2026-10-10 13:14:17,955 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/152 for batch 14.
2026-10-10 13:14:18,075 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/152 for batch 14.
2026-10-10 13:14:18,214 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/152 for batch 14.
2026-10-10 13:14:18,333 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/152 for batch 14.
2026-10-10 13:14:19,840 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/152 for batch 14.
2026-10-10 13:14:21,376 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/152 for batch 14.
2026-10-10 13:14:22,885 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/152 for batch 14.
2026-10-10 13:14:23,000 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/152 for batch 14.
2026-10-10 13:14:23,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/152 for batch 14.
2026-10-10 13:14:23,251 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/152 for batch 14.
2026-10-10 13:14:23,368 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/152 for batch 14.
2026-10-10 13:14:23,552 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/152 for batch 14.
2026-10-10 13:14:23,668 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/152 for batch 14.
2026-10-10 13:14:23,786 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/152 for batch 14.
2026-10-10 13:14:23,903 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/152 for batch 14.
2026-10-10 13:14:24,044 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/152 for batch 14.
2026-10-10 13:14:24,158 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/152 for batch 14.
2026-10-10 13:14:24,273 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/152 for batch 14.
2026-10-10 13:14:24,459 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/152 for batch 14.
2026-10-10 13:14:24,575 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/152 for batch 14.
2026-10-10 13:14:24,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/152 for batch 14.
2026-10-10 13:14:24,837 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/152 for batch 14.
2026-10-10 13:14:24,951 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/152 for batch 14.
2026-10-10 13:14:25,066 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/152 for batch 14.
2026-10-10 13:14:25,182 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/152 for batch 14.
2026-10-10 13:14:25,365 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/152 for batch 14.
2026-10-10 13:14:25,483 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/152 for batch 14.
2026-10-10 13:14:25,600 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/152 for batch 14.
2026-10-10 13:14:25,741 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/152 for batch 14.
2026-10-10 13:14:25,859 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/152 for batch 14.
2026-10-10 13:14:25,980 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/152 for batch 14.
2026-10-10 13:14:26,096 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/152 for batch 14.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00014_monthly_cleaning_report.partial.parquet

2026-10-10 13:14:36,429 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/152.
2026-10-10 13:14:40,400 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/152.
2026-10-10 13:14:44,416 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/152.
2026-10-10 13:14:48,207 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/152.
2026-10-10 13:14:52,177 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/152.
2026-10-10 13:14:55,886 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/152.
2026-10-10 13:14:59,537 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/152.
2026-10-10 13:15:03,236 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/152.
2026-10-10 13:15:06,898 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/152.
2026-10-10 13:15:10,517 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/152.
2026-10-10 13:15:14,169 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/152.
2026-10-10 13:15:17,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/152.
2026-10-10 13:15:21,479 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/152.
2026-10-10 13:15:25,052 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/152.
2026-10-10 13:15:28,612 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/152.
2026-10-10 13:15:29,351 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 152/152.
2026-10-10 13:15:30,330 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00014_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00014_monthly_cleaning_report.parquet

2026-10-10 13:16:56,199 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 96 parcels from batch_00014_monthly.nc.
2026-10-10 13:16:58,395 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00015_monthly.nc.
2026-10-10 13:16:59,638 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 15.
2026-10-10 13:17:01,027 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 15.
2026-10-10 13:17:02,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 15.
2026-10-10 13:17:03,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 15.
2026-10-10 13:17:04,496 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 15.
2026-10-10 13:17:05,745 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 15.
2026-10-10 13:17:06,887 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 15.
2026-10-10 13:17:08,123 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 15.
2026-10-10 13:17:09,380 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 15.
2026-10-10 13:17:10,538 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 15.
2026-10-10 13:17:11,756 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 15.
2026-10-10 13:17:12,980 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 15.
2026-10-10 13:17:14,263 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 15.
2026-10-10 13:17:15,512 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 15.
2026-10-10 13:17:16,758 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 15.
2026-10-10 13:17:17,969 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 15.
2026-10-10 13:17:19,205 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 15.
2026-10-10 13:17:20,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 15.
2026-10-10 13:17:20,481 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 15.
2026-10-10 13:17:20,482 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 12 rows.
2026-10-10 13:17:26,460 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 12 rows.
2026-10-10 13:17:32,468 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 12 rows.
2026-10-10 13:17:38,434 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 12 rows.
2026-10-10 13:17:44,419 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 12 rows.
2026-10-10 13:17:50,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 12 rows.
2026-10-10 13:17:56,487 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 12 rows.
2026-10-10 13:18:02,548 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 12 rows.
2026-10-10 13:18:08,484 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 12 rows.
2026-10-10 13:18:14,534 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 15.
2026-10-10 13:18:14,629 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 15.
2026-10-10 13:18:14,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 15.
2026-10-10 13:18:14,740 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 15.
2026-10-10 13:18:14,795 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 15.
2026-10-10 13:18:14,859 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 15.
2026-10-10 13:18:14,915 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 15.
2026-10-10 13:18:14,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 15.
2026-10-10 13:18:15,043 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 15.
2026-10-10 13:18:15,097 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 15.
2026-10-10 13:18:15,162 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 15.
2026-10-10 13:18:15,215 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 15.
2026-10-10 13:18:15,293 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 15.
2026-10-10 13:18:15,347 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 15.
2026-10-10 13:18:15,407 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 15.
2026-10-10 13:18:15,487 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 15.
2026-10-10 13:18:15,542 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 15.
2026-10-10 13:18:15,616 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 15.
2026-10-10 13:18:15,670 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 15.
2026-10-10 13:18:15,737 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 15.
2026-10-10 13:18:15,801 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 15.
2026-10-10 13:18:16,035 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 15.
2026-10-10 13:18:16,090 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 15.
2026-10-10 13:18:16,144 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 15.
2026-10-10 13:18:16,715 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 15.
2026-10-10 13:18:16,793 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 15.
2026-10-10 13:18:17,367 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 15.
2026-10-10 13:18:17,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 15.
2026-10-10 13:18:18,012 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 15.
2026-10-10 13:18:18,064 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 15.
2026-10-10 13:18:18,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 15.
2026-10-10 13:18:18,194 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 15.
2026-10-10 13:18:18,270 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 15.
2026-10-10 13:18:18,326 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 15.
2026-10-10 13:18:18,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 15.
2026-10-10 13:18:18,461 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 15.
2026-10-10 13:18:19,024 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 15.
2026-10-10 13:18:19,081 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 15.
2026-10-10 13:18:19,136 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 15.
2026-10-10 13:18:19,701 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 15.
2026-10-10 13:18:19,756 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 15.
2026-10-10 13:18:20,320 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 15.
2026-10-10 13:18:20,386 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 15.
2026-10-10 13:18:20,442 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 15.
2026-10-10 13:18:20,495 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 15.
2026-10-10 13:18:20,569 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 15.
2026-10-10 13:18:21,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 15.
2026-10-10 13:18:21,186 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 15.
2026-10-10 13:18:21,767 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 15.
2026-10-10 13:18:21,840 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 15.
2026-10-10 13:18:22,412 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 15.
2026-10-10 13:18:22,491 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 15.
2026-10-10 13:18:23,049 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 15.
2026-10-10 13:18:23,610 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 15.
2026-10-10 13:18:23,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 15.
2026-10-10 13:18:23,745 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 15.
2026-10-10 13:18:23,810 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 15.
2026-10-10 13:18:23,875 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 15.
2026-10-10 13:18:23,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 15.
2026-10-10 13:18:23,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 15.
2026-10-10 13:18:24,056 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 15.
2026-10-10 13:18:24,120 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 15.
2026-10-10 13:18:24,184 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 15.
2026-10-10 13:18:24,240 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 15.
2026-10-10 13:18:24,295 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 15.
2026-10-10 13:18:24,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 15.
2026-10-10 13:18:24,417 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 15.
2026-10-10 13:18:24,471 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 15.
2026-10-10 13:18:24,526 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 15.
2026-10-10 13:18:24,581 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 15.
2026-10-10 13:18:24,636 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 15.
2026-10-10 13:18:25,197 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 15.
2026-10-10 13:18:25,255 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 15.
2026-10-10 13:18:25,320 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 15.
2026-10-10 13:18:25,386 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 15.
2026-10-10 13:18:25,442 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 15.
2026-10-10 13:18:25,508 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 15.
2026-10-10 13:18:25,574 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 15.
2026-10-10 13:18:25,629 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 15.
2026-10-10 13:18:25,684 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 15.
2026-10-10 13:18:25,750 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 15.
2026-10-10 13:18:25,814 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 15.
2026-10-10 13:18:25,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 15.
2026-10-10 13:18:25,926 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 15.
2026-10-10 13:18:25,993 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 15.
2026-10-10 13:18:26,060 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 15.
2026-10-10 13:18:26,119 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 15.
2026-10-10 13:18:26,202 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 15.
2026-10-10 13:18:26,287 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 15.
2026-10-10 13:18:26,353 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 15.
2026-10-10 13:18:26,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 15.
2026-10-10 13:18:27,495 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 15.
2026-10-10 13:18:27,548 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 15.
2026-10-10 13:18:27,605 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 15.
2026-10-10 13:18:28,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 15.
2026-10-10 13:18:28,285 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 15.
2026-10-10 13:18:28,861 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 15.
2026-10-10 13:18:28,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 15.
2026-10-10 13:18:28,975 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 15.
2026-10-10 13:18:29,040 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 15.
2026-10-10 13:18:29,105 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 15.
2026-10-10 13:18:29,678 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 15.
2026-10-10 13:18:29,735 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 15.
2026-10-10 13:18:29,800 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 15.
2026-10-10 13:18:30,376 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 15.
2026-10-10 13:18:30,439 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 15.
2026-10-10 13:18:30,495 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 15.
2026-10-10 13:18:30,560 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 15.
2026-10-10 13:18:30,624 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 15.
2026-10-10 13:18:30,680 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 15.
2026-10-10 13:18:30,737 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 15.
2026-10-10 13:18:30,794 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 15.
2026-10-10 13:18:30,851 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 15.
2026-10-10 13:18:30,912 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 15.
2026-10-10 13:18:31,480 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 15.
2026-10-10 13:18:31,537 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 15.
2026-10-10 13:18:31,592 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 15.
2026-10-10 13:18:31,647 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 15.
2026-10-10 13:18:31,703 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 15.
2026-10-10 13:18:31,768 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 15.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00015_monthly_cleaning_report.partial.parquet

2026-10-10 13:18:38,401 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 13:18:39,897 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 13:18:41,371 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 13:18:42,821 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 13:18:44,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 13:18:45,725 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 13:18:47,127 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 13:18:48,711 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 13:18:50,171 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 13:18:51,676 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 13:18:53,162 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 13:18:54,627 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 13:18:56,118 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 13:18:57,660 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 13:18:59,066 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 13:19:00,506 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 13:19:01,949 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 13:19:03,389 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 13:19:03,528 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 13:19:04,065 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00015_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00015_monthly_cleaning_report.parquet

2026-10-10 13:19:41,074 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 36 parcels from batch_00015_monthly.nc.
2026-10-10 13:19:42,488 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00009_monthly.nc.
2026-10-10 13:19:46,290 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 9.
2026-10-10 13:19:50,750 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 9.
2026-10-10 13:19:54,546 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 9.
2026-10-10 13:19:58,483 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 9.
2026-10-10 13:20:02,256 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 9.
2026-10-10 13:20:06,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 9.
2026-10-10 13:20:10,222 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 9.
2026-10-10 13:20:14,300 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 9.
2026-10-10 13:20:18,379 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 9.
2026-10-10 13:20:22,461 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 9.
2026-10-10 13:20:26,378 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 9.
2026-10-10 13:20:30,641 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 9.
2026-10-10 13:20:34,718 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 9.
2026-10-10 13:20:38,830 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 9.
2026-10-10 13:20:43,040 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 9.
2026-10-10 13:20:47,060 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 9.
2026-10-10 13:20:51,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 9.
2026-10-10 13:20:55,386 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 9.
2026-10-10 13:20:55,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 9.
2026-10-10 13:20:55,813 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 7 rows.
2026-10-10 13:21:34,947 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 7 rows.
2026-10-10 13:22:14,123 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 7 rows.
2026-10-10 13:22:52,406 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 7 rows.
2026-10-10 13:23:30,280 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 7 rows.
2026-10-10 13:24:08,290 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 7 rows.
2026-10-10 13:24:46,075 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 7 rows.
2026-10-10 13:25:24,297 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 7 rows.
2026-10-10 13:26:02,381 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 7 rows.
2026-10-10 13:26:43,443 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 9.
2026-10-10 13:26:43,714 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 9.
2026-10-10 13:26:43,895 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 9.
2026-10-10 13:26:44,078 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 9.
2026-10-10 13:26:44,260 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 9.
2026-10-10 13:26:44,612 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 9.
2026-10-10 13:26:44,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 9.
2026-10-10 13:26:45,029 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 9.
2026-10-10 13:26:45,216 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 9.
2026-10-10 13:26:45,402 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 9.
2026-10-10 13:26:45,759 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 9.
2026-10-10 13:26:45,947 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 9.
2026-10-10 13:26:46,226 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 9.
2026-10-10 13:26:46,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 9.
2026-10-10 13:26:46,599 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 9.
2026-10-10 13:26:46,973 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 9.
2026-10-10 13:26:47,160 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 9.
2026-10-10 13:26:47,442 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 9.
2026-10-10 13:26:50,181 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 9.
2026-10-10 13:26:50,415 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 9.
2026-10-10 13:26:50,645 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 9.
2026-10-10 13:26:53,799 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 9.
2026-10-10 13:26:54,034 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 9.
2026-10-10 13:26:54,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 9.
2026-10-10 13:26:56,938 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 9.
2026-10-10 13:26:57,213 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 9.
2026-10-10 13:26:57,402 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 9.
2026-10-10 13:26:57,589 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 9.
2026-10-10 13:26:57,867 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 9.
2026-10-10 13:26:58,100 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 9.
2026-10-10 13:26:58,455 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 9.
2026-10-10 13:27:01,180 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 9.
2026-10-10 13:27:01,413 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 9.
2026-10-10 13:27:01,600 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 9.
2026-10-10 13:27:01,832 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 9.
2026-10-10 13:27:02,153 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 9.
2026-10-10 13:27:02,340 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 9.
2026-10-10 13:27:02,571 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 9.
2026-10-10 13:27:02,802 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 9.
2026-10-10 13:27:05,562 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 9.
2026-10-10 13:27:08,275 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 9.
2026-10-10 13:27:10,980 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 9.
2026-10-10 13:27:11,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 9.
2026-10-10 13:27:11,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 9.
2026-10-10 13:27:11,643 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 9.
2026-10-10 13:27:11,921 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 9.
2026-10-10 13:27:14,630 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 9.
2026-10-10 13:27:14,820 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 9.
2026-10-10 13:27:17,509 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 9.
2026-10-10 13:27:17,866 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 9.
2026-10-10 13:27:20,609 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 9.
2026-10-10 13:27:20,896 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 9.
2026-10-10 13:27:21,087 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 9.
2026-10-10 13:27:21,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 9.
2026-10-10 13:27:21,563 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 9.
2026-10-10 13:27:21,750 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 9.
2026-10-10 13:27:21,982 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 9.
2026-10-10 13:27:22,212 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 9.
2026-10-10 13:27:22,400 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 9.
2026-10-10 13:27:22,718 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 9.
2026-10-10 13:27:22,909 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 9.
2026-10-10 13:27:23,142 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 9.
2026-10-10 13:27:23,369 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 9.
2026-10-10 13:27:23,557 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 9.
2026-10-10 13:27:23,744 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 9.
2026-10-10 13:27:23,985 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 9.
2026-10-10 13:27:24,171 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 9.
2026-10-10 13:27:24,403 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 9.
2026-10-10 13:27:27,158 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 9.
2026-10-10 13:27:27,378 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 9.
2026-10-10 13:27:27,558 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 9.
2026-10-10 13:27:30,267 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 9.
2026-10-10 13:27:33,003 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 9.
2026-10-10 13:27:33,230 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 9.
2026-10-10 13:27:33,461 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 9.
2026-10-10 13:27:33,649 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 9.
2026-10-10 13:27:33,879 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 9.
2026-10-10 13:27:34,112 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 9.
2026-10-10 13:27:34,298 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 9.
2026-10-10 13:27:34,483 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 9.
2026-10-10 13:27:34,714 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 9.
2026-10-10 13:27:34,948 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 9.
2026-10-10 13:27:37,648 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 9.
2026-10-10 13:27:40,395 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 9.
2026-10-10 13:27:40,625 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 9.
2026-10-10 13:27:40,860 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 9.
2026-10-10 13:27:41,047 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 9.
2026-10-10 13:27:41,233 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 9.
2026-10-10 13:27:42,349 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 9.
2026-10-10 13:27:42,578 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 9.
2026-10-10 13:27:45,281 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 9.
2026-10-10 13:27:48,077 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 9.
2026-10-10 13:27:48,303 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 9.
2026-10-10 13:27:48,527 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 9.
2026-10-10 13:27:51,241 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 9.
2026-10-10 13:27:51,484 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 9.
2026-10-10 13:27:51,713 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 9.
2026-10-10 13:27:51,897 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 9.
2026-10-10 13:27:52,088 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 9.
2026-10-10 13:27:54,847 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 9.
2026-10-10 13:27:55,082 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 9.
2026-10-10 13:27:55,275 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 9.
2026-10-10 13:27:55,462 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 9.
2026-10-10 13:27:55,699 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 9.
2026-10-10 13:27:58,440 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 9.
2026-10-10 13:28:01,147 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 9.
2026-10-10 13:28:01,337 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 9.
2026-10-10 13:28:01,570 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 9.
2026-10-10 13:28:01,809 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 9.
2026-10-10 13:28:01,996 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 9.
2026-10-10 13:28:02,189 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 9.
2026-10-10 13:28:02,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 9.
2026-10-10 13:28:02,660 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 9.
2026-10-10 13:28:02,847 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 9.
2026-10-10 13:28:03,038 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 9.
2026-10-10 13:28:03,270 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 9.
2026-10-10 13:28:03,503 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 9.
2026-10-10 13:28:03,691 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 9.
2026-10-10 13:28:03,884 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 9.
2026-10-10 13:28:04,114 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 9.
2026-10-10 13:28:04,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/181 for batch 9.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00009_monthly_cleaning_report.partial.parquet

2026-10-10 13:28:36,882 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 13:28:42,999 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 13:28:48,830 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 13:28:54,635 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 13:29:00,351 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 13:29:06,043 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 13:29:12,693 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 13:29:19,600 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 13:29:26,702 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 13:29:34,469 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 13:29:42,373 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 13:29:50,321 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 13:29:58,133 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 13:30:06,066 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 13:30:14,083 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 13:30:21,925 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 13:30:29,700 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 13:30:37,885 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 13:30:38,696 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 13:30:39,715 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00009_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00009_monthly_cleaning_report.parquet

2026-10-10 13:30:59,319 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 15 parcels from batch_00009_monthly.nc.
2026-10-10 13:31:02,007 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00016_monthly.nc.
2026-10-10 13:31:02,440 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/145 for batch 16.
2026-10-10 13:31:02,852 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/145 for batch 16.
2026-10-10 13:31:03,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/145 for batch 16.
2026-10-10 13:31:03,666 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/145 for batch 16.
2026-10-10 13:31:04,073 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/145 for batch 16.
2026-10-10 13:31:04,476 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/145 for batch 16.
2026-10-10 13:31:04,895 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/145 for batch 16.
2026-10-10 13:31:05,299 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/145 for batch 16.
2026-10-10 13:31:05,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/145 for batch 16.
2026-10-10 13:31:06,177 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/145 for batch 16.
2026-10-10 13:31:06,603 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/145 for batch 16.
2026-10-10 13:31:06,992 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/145 for batch 16.
2026-10-10 13:31:07,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/145 for batch 16.
2026-10-10 13:31:07,815 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/145 for batch 16.
2026-10-10 13:31:08,005 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 145/145 for batch 16.
2026-10-10 13:31:08,006 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 47 rows.
2026-10-10 13:31:08,541 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 47 rows.
2026-10-10 13:31:09,083 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 47 rows.
2026-10-10 13:31:09,618 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 47 rows.
2026-10-10 13:31:10,178 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 47 rows.
2026-10-10 13:31:10,725 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 47 rows.
2026-10-10 13:31:11,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 47 rows.
2026-10-10 13:31:11,805 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 47 rows.
2026-10-10 13:31:12,348 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 47 rows.
2026-10-10 13:31:12,916 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/145 for batch 16.
2026-10-10 13:31:12,932 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/145 for batch 16.
2026-10-10 13:31:12,950 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/145 for batch 16.
2026-10-10 13:31:12,969 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/145 for batch 16.
2026-10-10 13:31:12,986 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/145 for batch 16.
2026-10-10 13:31:13,003 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/145 for batch 16.
2026-10-10 13:31:13,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/145 for batch 16.
2026-10-10 13:31:13,040 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/145 for batch 16.
2026-10-10 13:31:13,057 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/145 for batch 16.
2026-10-10 13:31:13,074 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/145 for batch 16.
2026-10-10 13:31:13,095 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/145 for batch 16.
2026-10-10 13:31:13,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/145 for batch 16.
2026-10-10 13:31:13,131 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/145 for batch 16.
2026-10-10 13:31:13,149 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/145 for batch 16.
2026-10-10 13:31:13,166 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/145 for batch 16.
2026-10-10 13:31:13,184 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/145 for batch 16.
2026-10-10 13:31:13,264 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/145 for batch 16.
2026-10-10 13:31:13,282 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/145 for batch 16.
2026-10-10 13:31:13,299 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/145 for batch 16.
2026-10-10 13:31:13,318 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/145 for batch 16.
2026-10-10 13:31:13,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/145 for batch 16.
2026-10-10 13:31:13,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/145 for batch 16.
2026-10-10 13:31:13,373 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/145 for batch 16.
2026-10-10 13:31:13,392 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/145 for batch 16.
2026-10-10 13:31:13,413 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/145 for batch 16.
2026-10-10 13:31:13,433 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/145 for batch 16.
2026-10-10 13:31:13,451 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/145 for batch 16.
2026-10-10 13:31:13,470 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/145 for batch 16.
2026-10-10 13:31:13,491 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/145 for batch 16.
2026-10-10 13:31:13,512 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/145 for batch 16.
2026-10-10 13:31:13,529 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/145 for batch 16.
2026-10-10 13:31:13,548 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/145 for batch 16.
2026-10-10 13:31:13,565 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/145 for batch 16.
2026-10-10 13:31:13,582 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/145 for batch 16.
2026-10-10 13:31:13,599 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/145 for batch 16.
2026-10-10 13:31:13,616 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/145 for batch 16.
2026-10-10 13:31:13,635 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/145 for batch 16.
2026-10-10 13:31:13,709 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/145 for batch 16.
2026-10-10 13:31:13,726 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/145 for batch 16.
2026-10-10 13:31:13,824 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/145 for batch 16.
2026-10-10 13:31:13,845 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/145 for batch 16.
2026-10-10 13:31:13,890 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/145 for batch 16.
2026-10-10 13:31:13,953 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/145 for batch 16.
2026-10-10 13:31:13,971 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/145 for batch 16.
2026-10-10 13:31:13,990 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/145 for batch 16.
2026-10-10 13:31:14,006 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/145 for batch 16.
2026-10-10 13:31:14,023 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/145 for batch 16.
2026-10-10 13:31:14,041 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/145 for batch 16.
2026-10-10 13:31:14,060 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/145 for batch 16.
2026-10-10 13:31:14,077 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/145 for batch 16.
2026-10-10 13:31:14,094 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/145 for batch 16.
2026-10-10 13:31:14,112 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/145 for batch 16.
2026-10-10 13:31:14,129 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/145 for batch 16.
2026-10-10 13:31:14,146 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/145 for batch 16.
2026-10-10 13:31:14,165 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/145 for batch 16.
2026-10-10 13:31:14,182 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/145 for batch 16.
2026-10-10 13:31:14,198 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/145 for batch 16.
2026-10-10 13:31:14,218 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/145 for batch 16.
2026-10-10 13:31:14,236 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/145 for batch 16.
2026-10-10 13:31:14,254 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/145 for batch 16.
2026-10-10 13:31:14,271 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/145 for batch 16.
2026-10-10 13:31:14,289 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/145 for batch 16.
2026-10-10 13:31:14,307 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/145 for batch 16.
2026-10-10 13:31:14,326 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/145 for batch 16.
2026-10-10 13:31:14,345 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/145 for batch 16.
2026-10-10 13:31:14,361 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/145 for batch 16.
2026-10-10 13:31:14,381 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/145 for batch 16.
2026-10-10 13:31:14,398 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/145 for batch 16.
2026-10-10 13:31:14,416 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/145 for batch 16.
2026-10-10 13:31:14,433 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/145 for batch 16.
2026-10-10 13:31:14,452 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/145 for batch 16.
2026-10-10 13:31:14,551 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/145 for batch 16.
2026-10-10 13:31:14,651 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/145 for batch 16.
2026-10-10 13:31:14,669 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/145 for batch 16.
2026-10-10 13:31:14,686 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/145 for batch 16.
2026-10-10 13:31:14,705 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/145 for batch 16.
2026-10-10 13:31:14,723 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/145 for batch 16.
2026-10-10 13:31:14,741 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/145 for batch 16.
2026-10-10 13:31:14,758 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/145 for batch 16.
2026-10-10 13:31:14,776 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/145 for batch 16.
2026-10-10 13:31:14,875 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/145 for batch 16.
2026-10-10 13:31:14,971 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/145 for batch 16.
2026-10-10 13:31:15,068 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/145 for batch 16.
2026-10-10 13:31:15,084 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/145 for batch 16.
2026-10-10 13:31:15,101 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/145 for batch 16.
2026-10-10 13:31:15,118 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/145 for batch 16.
2026-10-10 13:31:15,139 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/145 for batch 16.
2026-10-10 13:31:15,157 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/145 for batch 16.
2026-10-10 13:31:15,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/145 for batch 16.
2026-10-10 13:31:15,196 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/145 for batch 16.
2026-10-10 13:31:15,212 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/145 for batch 16.
2026-10-10 13:31:15,228 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/145 for batch 16.
2026-10-10 13:31:15,246 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/145 for batch 16.
2026-10-10 13:31:15,263 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/145 for batch 16.
2026-10-10 13:31:15,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/145 for batch 16.
2026-10-10 13:31:15,296 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/145 for batch 16.
2026-10-10 13:31:15,316 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/145 for batch 16.
2026-10-10 13:31:15,334 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/145 for batch 16.
2026-10-10 13:31:15,352 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/145 for batch 16.
2026-10-10 13:31:15,369 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/145 for batch 16.
2026-10-10 13:31:15,385 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/145 for batch 16.
2026-10-10 13:31:15,402 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/145 for batch 16.
2026-10-10 13:31:15,420 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/145 for batch 16.
2026-10-10 13:31:15,437 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/145 for batch 16.
2026-10-10 13:31:15,454 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/145 for batch 16.
2026-10-10 13:31:15,472 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/145 for batch 16.
2026-10-10 13:31:15,490 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/145 for batch 16.
2026-10-10 13:31:15,507 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/145 for batch 16.
2026-10-10 13:31:15,526 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/145 for batch 16.
2026-10-10 13:31:15,545 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/145 for batch 16.
2026-10-10 13:31:15,561 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/145 for batch 16.
2026-10-10 13:31:15,579 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/145 for batch 16.
2026-10-10 13:31:15,603 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/145 for batch 16.
2026-10-10 13:31:15,620 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/145 for batch 16.
2026-10-10 13:31:15,636 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/145 for batch 16.
2026-10-10 13:31:15,655 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/145 for batch 16.
2026-10-10 13:31:15,673 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/145 for batch 16.
2026-10-10 13:31:15,690 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/145 for batch 16.
2026-10-10 13:31:15,707 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/145 for batch 16.
2026-10-10 13:31:15,725 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/145 for batch 16.
2026-10-10 13:31:15,742 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/145 for batch 16.
2026-10-10 13:31:15,761 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/145 for batch 16.
2026-10-10 13:31:15,778 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/145 for batch 16.
2026-10-10 13:31:15,794 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 124/145 for batch 16.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00016_monthly_cleaning_report.partial.parquet

2026-10-10 13:31:16,769 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/145.
2026-10-10 13:31:17,104 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/145.
2026-10-10 13:31:17,427 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/145.
2026-10-10 13:31:17,743 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/145.
2026-10-10 13:31:18,059 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/145.
2026-10-10 13:31:18,372 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/145.
2026-10-10 13:31:18,688 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/145.
2026-10-10 13:31:19,002 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/145.
2026-10-10 13:31:19,306 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/145.
2026-10-10 13:31:19,602 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/145.
2026-10-10 13:31:19,957 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/145.
2026-10-10 13:31:20,252 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/145.
2026-10-10 13:31:20,544 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/145.
2026-10-10 13:31:20,837 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/145.
2026-10-10 13:31:20,992 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 145/145.
2026-10-10 13:31:21,165 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00016_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00016_monthly_cleaning_report.parquet

2026-10-10 13:31:22,131 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00016_monthly.nc.
2026-10-10 13:31:22,681 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00007_monthly.nc.
2026-10-10 13:31:29,478 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/181 for batch 7.
2026-10-10 13:31:37,318 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/181 for batch 7.
2026-10-10 13:31:43,905 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/181 for batch 7.
2026-10-10 13:31:50,812 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/181 for batch 7.
2026-10-10 13:31:57,080 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/181 for batch 7.
2026-10-10 13:32:03,889 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/181 for batch 7.
2026-10-10 13:32:10,469 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/181 for batch 7.
2026-10-10 13:32:17,725 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/181 for batch 7.
2026-10-10 13:32:24,832 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/181 for batch 7.
2026-10-10 13:32:32,022 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/181 for batch 7.
2026-10-10 13:32:38,752 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/181 for batch 7.
2026-10-10 13:32:46,128 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/181 for batch 7.
2026-10-10 13:32:53,236 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/181 for batch 7.
2026-10-10 13:33:00,197 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/181 for batch 7.
2026-10-10 13:33:07,362 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/181 for batch 7.
2026-10-10 13:33:14,811 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 160/181 for batch 7.
2026-10-10 13:33:22,343 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 170/181 for batch 7.
2026-10-10 13:33:29,846 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 180/181 for batch 7.
2026-10-10 13:33:30,658 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 181/181 for batch 7.
2026-10-10 13:33:30,659 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 6 rows.
2026-10-10 13:34:46,974 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 6 rows.
2026-10-10 13:36:03,138 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 6 rows.
2026-10-10 13:37:19,091 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 6 rows.
2026-10-10 13:38:33,373 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 6 rows.
2026-10-10 13:39:48,341 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 6 rows.
2026-10-10 13:41:03,326 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 6 rows.
2026-10-10 13:42:18,689 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 6 rows.
2026-10-10 13:43:34,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 6 rows.
2026-10-10 13:44:54,580 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/181 for batch 7.
2026-10-10 13:44:55,240 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/181 for batch 7.
2026-10-10 13:44:55,583 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/181 for batch 7.
2026-10-10 13:44:55,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/181 for batch 7.
2026-10-10 13:44:56,258 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/181 for batch 7.
2026-10-10 13:44:56,956 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/181 for batch 7.
2026-10-10 13:45:02,459 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/181 for batch 7.
2026-10-10 13:45:03,183 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/181 for batch 7.
2026-10-10 13:45:03,570 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/181 for batch 7.
2026-10-10 13:45:03,968 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/181 for batch 7.
2026-10-10 13:45:04,724 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/181 for batch 7.
2026-10-10 13:45:05,109 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/181 for batch 7.
2026-10-10 13:45:05,870 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/181 for batch 7.
2026-10-10 13:45:06,271 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/181 for batch 7.
2026-10-10 13:45:06,669 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/181 for batch 7.
2026-10-10 13:45:07,440 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/181 for batch 7.
2026-10-10 13:45:07,805 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/181 for batch 7.
2026-10-10 13:45:10,449 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/181 for batch 7.
2026-10-10 13:45:15,949 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/181 for batch 7.
2026-10-10 13:45:16,376 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/181 for batch 7.
2026-10-10 13:45:16,797 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/181 for batch 7.
2026-10-10 13:45:21,920 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/181 for batch 7.
2026-10-10 13:45:22,370 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/181 for batch 7.
2026-10-10 13:45:22,808 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/181 for batch 7.
2026-10-10 13:45:28,495 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/181 for batch 7.
2026-10-10 13:45:29,264 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/181 for batch 7.
2026-10-10 13:45:31,556 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/181 for batch 7.
2026-10-10 13:45:33,872 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/181 for batch 7.
2026-10-10 13:45:34,370 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/181 for batch 7.
2026-10-10 13:45:36,666 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/181 for batch 7.
2026-10-10 13:45:37,431 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/181 for batch 7.
2026-10-10 13:45:43,206 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/181 for batch 7.
2026-10-10 13:45:43,697 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/181 for batch 7.
2026-10-10 13:45:49,336 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/181 for batch 7.
2026-10-10 13:45:53,633 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/181 for batch 7.
2026-10-10 13:45:59,427 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/181 for batch 7.
2026-10-10 13:45:59,832 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/181 for batch 7.
2026-10-10 13:46:00,331 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/181 for batch 7.
2026-10-10 13:46:00,800 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/181 for batch 7.
2026-10-10 13:46:06,426 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/181 for batch 7.
2026-10-10 13:46:06,827 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/181 for batch 7.
2026-10-10 13:46:12,635 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/181 for batch 7.
2026-10-10 13:46:13,393 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/181 for batch 7.
2026-10-10 13:46:18,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/181 for batch 7.
2026-10-10 13:46:19,335 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/181 for batch 7.
2026-10-10 13:46:19,993 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/181 for batch 7.
2026-10-10 13:46:25,538 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/181 for batch 7.
2026-10-10 13:46:25,991 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/181 for batch 7.
2026-10-10 13:46:32,290 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/181 for batch 7.
2026-10-10 13:46:33,106 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/181 for batch 7.
2026-10-10 13:46:38,849 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/181 for batch 7.
2026-10-10 13:46:39,568 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/181 for batch 7.
2026-10-10 13:46:39,957 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/181 for batch 7.
2026-10-10 13:46:40,354 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/181 for batch 7.
2026-10-10 13:46:41,105 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/181 for batch 7.
2026-10-10 13:46:43,185 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/181 for batch 7.
2026-10-10 13:46:45,310 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/181 for batch 7.
2026-10-10 13:46:45,881 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/181 for batch 7.
2026-10-10 13:46:46,349 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/181 for batch 7.
2026-10-10 13:46:47,331 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/181 for batch 7.
2026-10-10 13:46:49,587 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/181 for batch 7.
2026-10-10 13:46:55,137 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/181 for batch 7.
2026-10-10 13:46:55,594 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/181 for batch 7.
2026-10-10 13:46:55,937 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/181 for batch 7.
2026-10-10 13:46:56,279 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/181 for batch 7.
2026-10-10 13:46:56,703 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/181 for batch 7.
2026-10-10 13:46:57,135 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/181 for batch 7.
2026-10-10 13:46:57,565 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/181 for batch 7.
2026-10-10 13:46:57,913 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/181 for batch 7.
2026-10-10 13:46:58,353 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/181 for batch 7.
2026-10-10 13:46:58,769 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/181 for batch 7.
2026-10-10 13:47:03,801 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/181 for batch 7.
2026-10-10 13:47:09,211 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/181 for batch 7.
2026-10-10 13:47:09,712 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/181 for batch 7.
2026-10-10 13:47:14,977 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/181 for batch 7.
2026-10-10 13:47:20,098 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/181 for batch 7.
2026-10-10 13:47:20,519 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/181 for batch 7.
2026-10-10 13:47:20,970 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/181 for batch 7.
2026-10-10 13:47:21,323 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/181 for batch 7.
2026-10-10 13:47:21,672 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/181 for batch 7.
2026-10-10 13:47:22,117 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/181 for batch 7.
2026-10-10 13:47:22,536 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/181 for batch 7.
2026-10-10 13:47:27,598 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/181 for batch 7.
2026-10-10 13:47:32,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/181 for batch 7.
2026-10-10 13:47:33,152 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/181 for batch 7.
2026-10-10 13:47:33,586 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/181 for batch 7.
2026-10-10 13:47:33,935 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/181 for batch 7.
2026-10-10 13:47:34,299 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/181 for batch 7.
2026-10-10 13:47:36,615 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/181 for batch 7.
2026-10-10 13:47:37,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/181 for batch 7.
2026-10-10 13:47:42,332 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/181 for batch 7.
2026-10-10 13:47:47,640 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/181 for batch 7.
2026-10-10 13:47:48,074 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/181 for batch 7.
2026-10-10 13:47:48,517 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/181 for batch 7.
2026-10-10 13:47:54,289 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/181 for batch 7.
2026-10-10 13:47:54,755 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/181 for batch 7.
2026-10-10 13:47:55,250 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/181 for batch 7.
2026-10-10 13:47:55,662 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/181 for batch 7.
2026-10-10 13:47:56,067 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/181 for batch 7.
2026-10-10 13:48:01,662 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/181 for batch 7.
2026-10-10 13:48:02,163 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/181 for batch 7.
2026-10-10 13:48:08,172 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/181 for batch 7.
2026-10-10 13:48:13,391 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/181 for batch 7.
2026-10-10 13:48:13,815 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/181 for batch 7.
2026-10-10 13:48:18,956 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/181 for batch 7.
2026-10-10 13:48:24,092 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/181 for batch 7.
2026-10-10 13:48:24,427 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/181 for batch 7.
2026-10-10 13:48:24,839 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/181 for batch 7.
2026-10-10 13:48:25,304 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/181 for batch 7.
2026-10-10 13:48:25,652 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/181 for batch 7.
2026-10-10 13:48:25,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/181 for batch 7.
2026-10-10 13:48:26,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/181 for batch 7.
2026-10-10 13:48:31,992 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/181 for batch 7.
2026-10-10 13:48:32,365 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/181 for batch 7.
2026-10-10 13:48:32,748 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/181 for batch 7.
2026-10-10 13:48:33,232 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/181 for batch 7.
2026-10-10 13:48:37,526 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/181 for batch 7.
2026-10-10 13:48:37,914 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/181 for batch 7.
2026-10-10 13:48:38,309 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/181 for batch 7.
2026-10-10 13:48:38,818 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/181 for batch 7.
2026-10-10 13:48:39,291 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/181 for batch 7.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00007_monthly_cleaning_report.partial.parquet

2026-10-10 13:50:05,036 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/181.
2026-10-10 13:50:18,233 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/181.
2026-10-10 13:50:31,886 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/181.
2026-10-10 13:50:45,049 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/181.
2026-10-10 13:50:57,667 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/181.
2026-10-10 13:51:10,780 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/181.
2026-10-10 13:51:24,335 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/181.
2026-10-10 13:51:38,430 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/181.
2026-10-10 13:51:51,906 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/181.
2026-10-10 13:52:05,203 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/181.
2026-10-10 13:52:18,411 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/181.
2026-10-10 13:52:31,487 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/181.
2026-10-10 13:52:44,814 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/181.
2026-10-10 13:52:58,520 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/181.
2026-10-10 13:53:11,682 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/181.
2026-10-10 13:53:26,011 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 160/181.
2026-10-10 13:53:42,042 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 170/181.
2026-10-10 13:53:56,661 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 180/181.
2026-10-10 13:53:58,334 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 181/181.
2026-10-10 13:53:59,298 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00007_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00007_monthly_cleaning_report.parquet

2026-10-10 13:54:53,351 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 40 parcels from batch_00007_monthly.nc.
2026-10-10 13:54:56,504 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00017_monthly.nc.
2026-10-10 13:55:00,406 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 10/155 for batch 17.
2026-10-10 13:55:04,273 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 20/155 for batch 17.
2026-10-10 13:55:08,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 30/155 for batch 17.
2026-10-10 13:55:11,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 40/155 for batch 17.
2026-10-10 13:55:14,943 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 50/155 for batch 17.
2026-10-10 13:55:19,124 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 60/155 for batch 17.
2026-10-10 13:55:23,126 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 70/155 for batch 17.
2026-10-10 13:55:27,259 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 80/155 for batch 17.
2026-10-10 13:55:31,055 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 90/155 for batch 17.
2026-10-10 13:55:36,141 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 100/155 for batch 17.
2026-10-10 13:55:39,896 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 110/155 for batch 17.
2026-10-10 13:55:43,765 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 120/155 for batch 17.
2026-10-10 13:55:48,174 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 130/155 for batch 17.
2026-10-10 13:55:52,147 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 140/155 for batch 17.
2026-10-10 13:55:56,137 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 150/155 for batch 17.
2026-10-10 13:55:57,983 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Stored observations 155/155 for batch 17.
2026-10-10 13:55:57,983 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-10 13:56:19,955 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-10 13:56:41,675 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-10 13:57:04,239 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-10 13:57:26,241 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-10 13:57:48,509 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-10 13:58:09,990 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-10 13:58:31,498 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-10 13:58:53,663 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-10 13:59:15,571 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 1/155 for batch 17.
2026-10-10 13:59:15,794 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 2/155 for batch 17.
2026-10-10 13:59:15,951 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 3/155 for batch 17.
2026-10-10 13:59:16,107 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 4/155 for batch 17.
2026-10-10 13:59:16,353 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 5/155 for batch 17.
2026-10-10 13:59:16,508 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 6/155 for batch 17.
2026-10-10 13:59:18,124 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 7/155 for batch 17.
2026-10-10 13:59:18,282 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 8/155 for batch 17.
2026-10-10 13:59:18,571 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 9/155 for batch 17.
2026-10-10 13:59:18,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 10/155 for batch 17.
2026-10-10 13:59:18,885 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 11/155 for batch 17.
2026-10-10 13:59:19,041 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 12/155 for batch 17.
2026-10-10 13:59:19,198 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 13/155 for batch 17.
2026-10-10 13:59:19,489 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 14/155 for batch 17.
2026-10-10 13:59:19,645 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 15/155 for batch 17.
2026-10-10 13:59:19,803 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 16/155 for batch 17.
2026-10-10 13:59:19,960 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 17/155 for batch 17.
2026-10-10 13:59:20,199 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 18/155 for batch 17.
2026-10-10 13:59:20,355 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 19/155 for batch 17.
2026-10-10 13:59:22,045 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 20/155 for batch 17.
2026-10-10 13:59:22,338 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 21/155 for batch 17.
2026-10-10 13:59:24,519 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 22/155 for batch 17.
2026-10-10 13:59:24,814 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 23/155 for batch 17.
2026-10-10 13:59:27,029 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 24/155 for batch 17.
2026-10-10 13:59:27,193 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 25/155 for batch 17.
2026-10-10 13:59:27,357 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 26/155 for batch 17.
2026-10-10 13:59:27,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 27/155 for batch 17.
2026-10-10 13:59:27,818 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 28/155 for batch 17.
2026-10-10 13:59:27,978 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 29/155 for batch 17.
2026-10-10 13:59:28,274 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 30/155 for batch 17.
2026-10-10 13:59:28,441 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 31/155 for batch 17.
2026-10-10 13:59:30,749 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 32/155 for batch 17.
2026-10-10 13:59:31,058 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 33/155 for batch 17.
2026-10-10 13:59:31,215 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 34/155 for batch 17.
2026-10-10 13:59:33,435 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 35/155 for batch 17.
2026-10-10 13:59:33,597 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 36/155 for batch 17.
2026-10-10 13:59:33,762 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 37/155 for batch 17.
2026-10-10 13:59:34,052 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 38/155 for batch 17.
2026-10-10 13:59:36,223 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 39/155 for batch 17.
2026-10-10 13:59:38,530 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 40/155 for batch 17.
2026-10-10 13:59:38,693 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 41/155 for batch 17.
2026-10-10 13:59:38,856 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 42/155 for batch 17.
2026-10-10 13:59:39,015 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 43/155 for batch 17.
2026-10-10 13:59:39,312 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 44/155 for batch 17.
2026-10-10 13:59:41,566 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 45/155 for batch 17.
2026-10-10 13:59:41,732 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 46/155 for batch 17.
2026-10-10 13:59:44,014 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 47/155 for batch 17.
2026-10-10 13:59:44,255 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 48/155 for batch 17.
2026-10-10 13:59:46,183 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 49/155 for batch 17.
2026-10-10 13:59:47,760 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 50/155 for batch 17.
2026-10-10 13:59:47,945 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 51/155 for batch 17.
2026-10-10 13:59:48,246 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 52/155 for batch 17.
2026-10-10 13:59:48,406 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 53/155 for batch 17.
2026-10-10 13:59:48,567 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 54/155 for batch 17.
2026-10-10 13:59:48,726 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 55/155 for batch 17.
2026-10-10 13:59:49,026 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 56/155 for batch 17.
2026-10-10 13:59:49,187 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 57/155 for batch 17.
2026-10-10 13:59:49,348 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 58/155 for batch 17.
2026-10-10 13:59:49,551 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 59/155 for batch 17.
2026-10-10 13:59:49,748 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 60/155 for batch 17.
2026-10-10 13:59:52,014 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 61/155 for batch 17.
2026-10-10 13:59:52,252 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 62/155 for batch 17.
2026-10-10 13:59:53,113 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 63/155 for batch 17.
2026-10-10 13:59:53,280 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 64/155 for batch 17.
2026-10-10 13:59:53,486 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 65/155 for batch 17.
2026-10-10 13:59:53,651 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 66/155 for batch 17.
2026-10-10 13:59:53,881 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 67/155 for batch 17.
2026-10-10 13:59:54,042 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 68/155 for batch 17.
2026-10-10 13:59:54,202 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 69/155 for batch 17.
2026-10-10 13:59:54,365 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 70/155 for batch 17.
2026-10-10 13:59:54,560 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 71/155 for batch 17.
2026-10-10 13:59:54,722 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 72/155 for batch 17.
2026-10-10 13:59:54,880 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 73/155 for batch 17.
2026-10-10 13:59:55,173 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 74/155 for batch 17.
2026-10-10 13:59:55,332 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 75/155 for batch 17.
2026-10-10 13:59:55,496 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 76/155 for batch 17.
2026-10-10 13:59:55,663 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 77/155 for batch 17.
2026-10-10 13:59:55,860 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 78/155 for batch 17.
2026-10-10 13:59:56,020 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 79/155 for batch 17.
2026-10-10 13:59:56,184 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 80/155 for batch 17.
2026-10-10 13:59:56,500 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 81/155 for batch 17.
2026-10-10 13:59:56,696 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 82/155 for batch 17.
2026-10-10 13:59:56,932 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 83/155 for batch 17.
2026-10-10 13:59:57,091 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 84/155 for batch 17.
2026-10-10 13:59:57,249 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 85/155 for batch 17.
2026-10-10 13:59:57,414 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 86/155 for batch 17.
2026-10-10 13:59:57,656 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 87/155 for batch 17.
2026-10-10 13:59:59,884 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 88/155 for batch 17.
2026-10-10 14:00:02,090 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 89/155 for batch 17.
2026-10-10 14:00:04,364 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 90/155 for batch 17.
2026-10-10 14:00:04,528 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 91/155 for batch 17.
2026-10-10 14:00:04,692 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 92/155 for batch 17.
2026-10-10 14:00:04,854 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 93/155 for batch 17.
2026-10-10 14:00:05,104 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 94/155 for batch 17.
2026-10-10 14:00:05,275 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 95/155 for batch 17.
2026-10-10 14:00:05,437 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 96/155 for batch 17.
2026-10-10 14:00:05,640 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 97/155 for batch 17.
2026-10-10 14:00:05,804 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 98/155 for batch 17.
2026-10-10 14:00:05,965 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 99/155 for batch 17.
2026-10-10 14:00:08,261 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 100/155 for batch 17.
2026-10-10 14:00:08,429 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 101/155 for batch 17.
2026-10-10 14:00:08,593 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 102/155 for batch 17.
2026-10-10 14:00:08,755 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 103/155 for batch 17.
2026-10-10 14:00:08,959 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 104/155 for batch 17.
2026-10-10 14:00:09,127 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 105/155 for batch 17.
2026-10-10 14:00:09,464 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 106/155 for batch 17.
2026-10-10 14:00:09,639 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 107/155 for batch 17.
2026-10-10 14:00:09,806 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 108/155 for batch 17.
2026-10-10 14:00:09,966 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 109/155 for batch 17.
2026-10-10 14:00:10,166 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 110/155 for batch 17.
2026-10-10 14:00:10,328 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 111/155 for batch 17.
2026-10-10 14:00:10,491 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 112/155 for batch 17.
2026-10-10 14:00:10,791 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 113/155 for batch 17.
2026-10-10 14:00:10,952 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 114/155 for batch 17.
2026-10-10 14:00:11,114 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 115/155 for batch 17.
2026-10-10 14:00:11,314 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 116/155 for batch 17.
2026-10-10 14:00:11,482 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 117/155 for batch 17.
2026-10-10 14:00:11,644 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 118/155 for batch 17.
2026-10-10 14:00:11,803 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 119/155 for batch 17.
2026-10-10 14:00:12,104 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 120/155 for batch 17.
2026-10-10 14:00:12,267 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 121/155 for batch 17.
2026-10-10 14:00:12,429 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 122/155 for batch 17.
2026-10-10 14:00:12,628 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Cleaned acquisition 123/155 for batch 17.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00017_monthly_cleaning_report.partial.parquet

2026-10-10 14:00:39,400 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 10/155.
2026-10-10 14:00:44,782 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 20/155.
2026-10-10 14:00:50,064 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 30/155.
2026-10-10 14:00:55,000 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 40/155.
2026-10-10 14:01:00,047 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 50/155.
2026-10-10 14:01:04,989 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 60/155.
2026-10-10 14:01:09,923 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 70/155.
2026-10-10 14:01:15,651 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 80/155.
2026-10-10 14:01:22,188 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 90/155.
2026-10-10 14:01:28,651 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 100/155.
2026-10-10 14:01:35,722 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 110/155.
2026-10-10 14:01:42,919 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 120/155.
2026-10-10 14:01:50,409 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 130/155.
2026-10-10 14:01:58,085 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 140/155.
2026-10-10 14:02:05,727 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 150/155.
2026-10-10 14:02:09,439 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Saved output indices for acquisition 155/155.
2026-10-10 14:02:10,479 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\5d82807dd94c510f-tiles-669b4d35\batch_00017_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/5d82807dd94c510f-tiles-669b4d35/batch_00017_monthly_cleaning_report.parquet

2026-10-10 14:04:24,292 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 145 parcels from batch_00017_monthly.nc.
2026-10-10 14:04:27,295 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.parcels | Reshaped 36 parcel-period rows into 3 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:27,482 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.parcels | Reshaped 24 parcel-period rows into 2 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_2/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_3/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:27,677 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_4/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:27,921 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.parcels | Reshaped 24 parcel-period rows into 2 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_5/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:28,146 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_6/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:28,370 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:28,579 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_7/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_8/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:29,277 | INFO | parcel_stats_pipeline.a045c6ab67.2435164612368.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_pixel_cleaning_report.csv (3 rows).
2026-10-10 14:04:29,282 | INFO | parcel_stats_pipeline.c795cd6857.2435164612688.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_pixel_cleaning_report.csv (2 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_2/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_3/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_2/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_4/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_3/satellite_pixel_cleaning_report.csv
[Completed] Partition 2 result stored
[Completed] Partition 3 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_4/satellite_pixel_cleaning_report.csv

2026-10-10 14:04:29,374 | INFO | parcel_stats_pipeline.d3b9f11ce8.2435164613648.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_pixel_cleaning_report.csv (1 rows).
2026-10-10 14:04:29,534 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.parcels | Reshaped 480 parcel-period rows into 40 ML-ready parcel rows with 1632 dated features in EPSG:32635.

[Completed] Partition 4 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_6/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_5/.satellite_parcel_annual_stats.tmp.geoparquet

2026-10-10 14:04:29,837 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:29,876 | INFO | parcel_stats_pipeline.ac8c6d540a.2435164614288.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_pixel_cleaning_report.csv (2 rows).
2026-10-10 14:04:29,879 | INFO | parcel_stats_pipeline.41d4df1703.2435164613008.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_pixel_cleaning_report.csv (1 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_5/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_6/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_9/satellite_parcel_time_stats.geoparquet
[Completed] Partition 5 result stored
[Completed] Partition 6 result stored

2026-10-10 14:04:30,058 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_10/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:30,297 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.parcels | Reshaped 12 parcel-period rows into 1 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_11/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:30,795 | INFO | parcel_stats_pipeline.b79d675521.2435164614608.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_pixel_cleaning_report.csv (1 rows).
2026-10-10 14:04:30,805 | INFO | parcel_stats_pipeline.968646fcee.2435164613968.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_pixel_cleaning_report.csv (1 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_8/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_7/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_8/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_7/satellite_pixel_cleaning_report.csv
[Completed] Partition 8 result stored
[Completed] Partition 7 result stored

2026-10-10 14:04:31,180 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.parcels | Reshaped 84 parcel-period rows into 7 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:31,429 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.parcels | Reshaped 36 parcel-period rows into 3 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:31,536 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.parcels | Reshaped 324 parcel-period rows into 27 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:31,619 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.parcels | Reshaped 1176 parcel-period rows into 98 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_14/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_15/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:31,945 | INFO | parcel_stats_pipeline.6ed1533047.2435164615248.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_pixel_cleaning_report.csv (1 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_10/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_9/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_9/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_10/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_1/satellite_pixel_cleaning_report.csv
[Completed] Partition 9 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_11/.satellite_parcel_annual_stats.tmp.geoparquet

2026-10-10 14:04:32,018 | INFO | parcel_stats_pipeline.9954fc637f.2435164615568.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_pixel_cleaning_report.csv (1 rows).
2026-10-10 14:04:32,222 | INFO | parcel_stats_pipeline.59f6705c58.2435119877488.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_pixel_cleaning_report.csv (40 rows).

[Completed] Partition 10 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_11/satellite_pixel_cleaning_report.csv

2026-10-10 14:04:32,225 | INFO | parcel_stats_pipeline.06ac1dc7c7.2435164614928.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_pixel_cleaning_report.csv (1 rows).

[Completed] Partition 1 result stored
[Completed] Partition 11 result stored

2026-10-10 14:04:32,595 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.parcels | Reshaped 228 parcel-period rows into 19 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:32,699 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.parcels | Reshaped 24 parcel-period rows into 2 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_16/satellite_parcel_time_stats.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_17/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:33,041 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.parcels | Reshaped 192 parcel-period rows into 16 ML-ready parcel rows with 1632 dated features in EPSG:32635.
2026-10-10 14:04:33,079 | INFO | parcel_stats_pipeline.0d4f4abe05.2435164616208.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_pixel_cleaning_report.csv (7 rows).
2026-10-10 14:04:33,087 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.parcels | Reshaped 36 parcel-period rows into 3 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_13/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_14/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_18/satellite_parcel_time_stats.geoparquet
[Completed] Partition 13 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_19/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:33,196 | INFO | parcel_stats_pipeline.7028f15ab9.2435164616528.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_pixel_cleaning_report.csv (3 rows).
2026-10-10 14:04:33,331 | INFO | parcel_stats_pipeline.849566e3ee.2435164616848.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_pixel_cleaning_report.csv (27 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_14/satellite_pixel_cleaning_report.csv
[Completed] Partition 14 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_15/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_15/satellite_pixel_cleaning_report.csv
[Completed] Partition 15 result stored
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_12/satellite_pixel_cleaning_report.csv

2026-10-10 14:04:33,593 | INFO | parcel_stats_pipeline.bf4ce84bfa.2435164615888.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_pixel_cleaning_report.csv (98 rows).

[Completed] Partition 12 result stored

2026-10-10 14:04:34,054 | INFO | parcel_stats_pipeline.0801865a14.2435164617808.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_pixel_cleaning_report.csv (2 rows).
2026-10-10 14:04:34,055 | INFO | parcel_stats_pipeline.1f869c30b1.2435164617168.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_pixel_cleaning_report.csv (19 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_16/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_17/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_17/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_16/satellite_pixel_cleaning_report.csv
[Completed] Partition 17 result stored
[Completed] Partition 16 result stored

2026-10-10 14:04:34,349 | INFO | parcel_stats_pipeline.0ba46dc589.2435164618448.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_pixel_cleaning_report.csv (3 rows).
2026-10-10 14:04:34,350 | INFO | parcel_stats_pipeline.911a3c146a.2435164618128.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_pixel_cleaning_report.csv (16 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_19/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_18/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_19/satellite_pixel_cleaning_report.csv
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_18/satellite_pixel_cleaning_report.csv
[Completed] Partition 18 result stored
[Completed] Partition 19 result stored

2026-10-10 14:04:36,835 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.parcels | Reshaped 10356 parcel-period rows into 863 ML-ready parcel rows with 1632 dated features in EPSG:32635.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/satellite_parcel_time_stats.geoparquet

2026-10-10 14:04:37,263 | INFO | parcel_stats_pipeline.e80976f815.2436240785488.orchestrator | Created C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_parcel_time_stats.geoparquet (1654 columns), C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_parcel_annual_stats.geoparquet (90 columns), and C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_pixel_cleaning_report.csv (863 rows).

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/.satellite_parcel_annual_stats.tmp.geoparquet
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/satellite_pixel_cleaning_report.csv
[Completed] Partition 20 result stored

All 20 partition(s) completed in 13011.6s

Extraction complete!

In [14]:
# ============================================================================
# STEP 4: Merge results and save to files
# ============================================================================
# Combines all partition results and removes duplicates
# Saves one file:
#   1. satellite_parcel_time_stats.geoparquet (full results with geometry)

merged_gdf, geoparquet_path = merge_and_save_results(
    output_dir=OUTPUT_DIR,
    parcel_id_column=parcel_id_column,
    working_epsg=WORKING_EPSG
)

Loading partition 1: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_parcel_time_stats.geoparquet
Loading partition 2: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_parcel_time_stats.geoparquet
Loading partition 3: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_parcel_time_stats.geoparquet
Loading partition 4: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_parcel_time_stats.geoparquet
Loading partition 5: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_parcel_time_stats.geoparquet
Loading partition 6: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_parcel_time_stats.geoparquet
Loading partition 7: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_parcel_time_stats.geoparquet
Loading partition 8: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_parcel_time_stats.geoparquet
Loading partition 9: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_parcel_time_stats.geoparquet
Loading partition 10: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_parcel_time_stats.geoparquet
Loading partition 11: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_parcel_time_stats.geoparquet
Loading partition 12: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_parcel_time_stats.geoparquet
Loading partition 13: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_parcel_time_stats.geoparquet
Loading partition 14: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_parcel_time_stats.geoparquet
Loading partition 15: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_parcel_time_stats.geoparquet
Loading partition 16: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_parcel_time_stats.geoparquet
Loading partition 17: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_parcel_time_stats.geoparquet
Loading partition 18: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_parcel_time_stats.geoparquet
Loading partition 19: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_parcel_time_stats.geoparquet
Loading partition 20: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_parcel_time_stats.geoparquet

======================================================================
Merging 20 partition result(s)
======================================================================

Merged results: 1092 parcels (input: 1092)
Output columns: 1654
Output CRS: {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "WGS 84 / UTM zone 35N", "base_crs": {"name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4326}}, "conversion": {"name": "UTM zone 35N", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 27, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Navigation and medium accuracy spatial referencing.", "area": "Between 24\u00b0E and 30\u00b0E, northern hemisphere between equator and 84\u00b0N, onshore and offshore. Belarus. Bulgaria. Central African Republic. Democratic Republic of the Congo (Zaire). Egypt. Estonia. Finland. Greece. Latvia. Lesotho. Libya. Lithuania. Moldova. Norway. Poland. Romania. Russian Federation. Sudan. Svalbard. T\u00fcrkiye (Turkey). Uganda. Ukraine.", "bbox": {"south_latitude": 0, "west_longitude": 24, "north_latitude": 84, "east_longitude": 30}, "id": {"authority": "EPSG", "code": 32635}}

======================================================================
Saving final merged results
======================================================================
Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/satellite_parcel_time_stats.geoparquet

Saved final output: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\satellite_parcel_time_stats.geoparquet

In [15]:
# ============================================================================
# STEP 5: Inspect results
# ============================================================================

print(f"\n{'='*70}")
print("FINAL RESULTS")
print(f"{'='*70}")

print("\nMerged GeoDataFrame:")
print(f"  Rows: {len(merged_gdf)}")
print(f"  Columns: {len(merged_gdf.columns)}")
print(f"  Has geometry: {merged_gdf.geometry.name in merged_gdf.columns}")

print("\nOutput files:")
print(f"  GeoParquet: {geoparquet_path}")
print(f"    Size: {geoparquet_path.stat().st_size / 1e6:.1f} MB")

print("\nFirst 5 rows:")
display(merged_gdf.head())

======================================================================
FINAL RESULTS
======================================================================

Merged GeoDataFrame:
  Rows: 1092
  Columns: 1654
  Has geometry: True

Output files:
  GeoParquet: C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\satellite_parcel_time_stats.geoparquet
    Size: 15.8 MB

First 5 rows:

,parcel_id,crop_category,cluster,geometry,batch_number,intersected_pixel_count,meets_minimum_pixel_count,expected_pixel_count,observed_count,temporal_filled_pixel_count,...,VV_variance__20241201,VV_variance__20250101,VV_variance__20250201,VV_variance__20250301,VV_variance__20250401,VV_variance__20250501,VV_variance__20250601,VV_variance__20250701,VV_variance__20250801,VV_variance__20250901
0,590,ΒΑΜΒΑΚΙ,Cluster 1,"POLYGON ((161235.464 4244593.216, 161238.605 4...",3,74,True,196248,104607,10699,...,0.002985,0.001256,0.003112,0.000376,0.000904,0.001236,0.001056,0.000583,0.001011,0.000684
1,591,ΒΑΜΒΑΚΙ,Cluster 1,"POLYGON ((156463.595 4261466.069, 156461.908 4...",4,170,True,450840,237143,28886,...,0.010040,0.011058,0.027847,0.001181,0.000886,0.000865,0.001662,0.002631,0.004836,0.003558
2,592,ΑΜΠΕΛΩΝΕΣ,Cluster 1,"POLYGON ((130883.051 4278200.18, 130900.435 42...",2,11,True,34221,16960,1482,...,0.004332,0.005543,0.004471,0.002624,0.002956,0.001201,0.002140,0.001810,0.001360,0.001750
3,637,ΒΑΜΒΑΚΙ,Cluster 1,"POLYGON ((163865.337 4245177.202, 163864.092 4...",3,40,True,106080,57692,6305,...,0.004665,0.001611,0.002858,0.000714,0.000387,0.000705,0.000837,0.000778,0.000907,0.000588
4,638,ΒΑΜΒΑΚΙ,Cluster 1,"POLYGON ((160558.592 4244150.05, 160559.852 42...",3,61,True,161772,89890,8554,...,0.001174,0.000662,0.001312,0.001122,0.001581,0.000936,0.001024,0.001207,0.001493,0.001108