# Sentinel-1 and Sentinel-2 parcel zonal statistics

Configure and run `OpenEOJobManagerZonalStats` through the multi-user scheduler. openEO creates sensor-preprocessed physical-band NetCDF cubes per spatial batch. IQR cleaning, null filling, pixel indices, and parcel statistics run locally, producing one GeoParquet row per parcel with dated features and a separate annual summary. See [the detailed workflow](../../../docs/data_preparation/openeo/WORKFLOW.md).

In [ ]:
from pathlib import Path
import os
from IPython.display import display

from data_preparation.parcel_stats import estimate_utm_epsg_from_parcels
from data_preparation.parcel_stats.job_manager import compute_tile_buffer_metres
from data_preparation.parcel_stats.multiuser import (
    load_openeo_users_from_db,
    merge_and_save_results,
    run_parallel_extractions,
)
from shared.io import read_data, write_data
from shared.spatial_statistics import spatial_clustering_using_buffer

## Inputs

Processing order:

`Sentinel-2 L2A`
`acquisition cloud mask`
`optional temporal reduction, or retain acquisitions`
`per-band, per-time-slice raster IQR outlier removal when enabled`
`local null filling`
`local pixel indices from cleaned physical bands`
`parcel statistics`
`one-row-per-parcel time-series pivot`
`ML-ready GeoParquet`

Temporal filling is past-only so later observations cannot leak into earlier feature periods.

In [3]:
# ============================================================================
# STEP 1: Read data and re-project
# ============================================================================
# Read the data and re-project to the desired EPSG

WORK_PATH = Path("C:/work_sat")
RUN_IDENTIFIER = "neuro_2024-2025"

# PARCELS_PATH = WORK_PATH / RUN_IDENTIFIER / "sample_parcels.csv"
# gdf_parcels = read_data(str(PARCELS_PATH))
# print("Initial parcels data:")
# display(gdf_parcels.head())

# print(f"Parcels before dropping duplicate geometries: {len(gdf_parcels)}")
# gdf_parcels = gdf_parcels.drop_duplicates(subset=["geom_wkt"]).copy()
# print(f"Parcels after dropping duplicate geometries: {len(gdf_parcels)}")

# gdf_parcels = gpd.GeoDataFrame(gdf_parcels, geometry=gpd.GeoSeries.from_wkt(gdf_parcels["geom_wkt"]), crs="EPSG:2100")
# print(f"Number of parcels: {len(gdf_parcels)}")
# gdf_parcels = geom_l.return_valid_geometries(gdf_parcels)
# gdf_parcels = geom_l.convert_multipolygons_to_polygons(gdf_parcels)
# print(f"Number of parcels after ensuring valid geometries and converting multipolygons to polygons: {len(gdf_parcels)}")
# gdf_parcels = gdf_parcels.drop(columns=["geom_wkt"])

# write_data(gdf_parcels, str(PARCELS_PATH).replace(".csv", ".gpkg"))

PARCELS_PATH = WORK_PATH / RUN_IDENTIFIER / "sample_parcels.gpkg"
gdf_parcels = read_data(str(PARCELS_PATH))
display(gdf_parcels)

Reading file: C:/work_sat/neuro_2024-2025/sample_parcels.gpkg

,parcel_id,crop_category,geometry
0,552,ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ,"POLYGON ((276662.481 4436671.199, 276678.713 4..."
1,553,jjjj,"POLYGON ((278512.622 4438032.513, 278569.445 4..."
2,554,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((278217.407 4437980.985, 278216.142 4..."
3,555,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((274769.372 4440021.269, 274765.086 4..."
4,556,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((272117.609 4439208.353, 272117.343 4..."
...,...,...,...
1147,25568,ΑΡΑΒΟΣΙΤΟΣ,"POLYGON ((279312.404 4518258.109, 279282.821 4..."
1148,25601,ΕΛΑΙΩΝΕΣ,"POLYGON ((617782.701 4067252.962, 617772.565 4..."
1149,25602,ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ,"POLYGON ((625014.344 3873755.626, 625003.543 3..."
1150,25651,ΒΑΜΒΑΚΙ,"POLYGON ((700907.829 4610302.442, 700796.329 4..."
1151,25652,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,"POLYGON ((696573.67 4346147.612, 696566.604 43..."

In [4]:
print(gdf_parcels.crs)
WORKING_EPSG = estimate_utm_epsg_from_parcels(gdf_parcels)
WORKING_EPSG

EPSG:2100

32635

In [5]:
# ============================================================================
# Define the class column and parcel ID column names.
# These are used in the extraction process to identify the class of each parcel
# and its unique identifier.
# ============================================================================
class_column = "crop_category"
parcel_id_column = "parcel_id"

In [6]:
gdf_parcels = gdf_parcels[gdf_parcels[class_column] != "jjjj"]
label_counts = gdf_parcels[class_column].value_counts()
print(f"Number of unique labels: {len(label_counts)}")
print(gdf_parcels[class_column].value_counts())
print(50*"-")
rare_labels = label_counts[label_counts < 10].index
gdf_parcels.loc[gdf_parcels[class_column].isin(rare_labels), class_column] = "9999"
print(f"Number of unique labels after grouping rare labels: {len(gdf_parcels[class_column].value_counts())}")
print(gdf_parcels[class_column].value_counts())

cond = gdf_parcels[class_column] == "9999"
print(50*"-")
print(f"Excluded parcels with label '9999': {cond.sum()} out of {len(gdf_parcels)}")
gdf_parcels = gdf_parcels[~cond].copy()
print(f"Selected parcels after excluding label '9999': {len(gdf_parcels)}")

Number of unique labels: 25
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       302
ΒΑΜΒΑΚΙ                                                 221
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           147
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           48
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 24
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     11
ΑΜΠΕΛΩΝΕΣ                                                10
ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)                              9
ΑΡΑΒΟΣΙΤΟΣ                                                6
ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ                                            5
KHPEYTIKA                                                 5
ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ                                4
ΚΑΠΝΟΣ                                                    4
ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ                                          4
ΠΥΡΗΝΟΚΑΡΠΑ                                               4
ΣΠΟΡΟΠΑΡΑΓΩΓΗ                                             2
ΜΗΛΟΕΙΔΗ                                                  2
ΡΟΔΑΚΙΝΙΕΣ                                                1
ΖΑΧΑΡΟΤΕΥΤΛΑ                                              1
ΕΣΠΕΡΙΔΟΕΙΔΗ                                              1
Name: count, dtype: int64
--------------------------------------------------
Number of unique labels after grouping rare labels: 13
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       302
ΒΑΜΒΑΚΙ                                                 221
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           147
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           48
9999                                                     48
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 24
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     11
ΑΜΠΕΛΩΝΕΣ                                                10
Name: count, dtype: int64
--------------------------------------------------
Excluded parcels with label '9999': 48 out of 1140
Selected parcels after excluding label '9999': 1092

In [7]:
# Reuse saved cluster labels; generate them only when the input has none.
CLUSTER_FIELD = "cluster"
if CLUSTER_FIELD in gdf_parcels.columns:
    gdf_grouped = gdf_parcels.copy()
else:
    gdf_grouped = spatial_clustering_using_buffer(
        gdf_parcels.to_crs(epsg=WORKING_EPSG),
        parcel_id_column,
        min_cluster_distance_in_m=20_000,
        field_cluster=CLUSTER_FIELD,
        plot_results=False,
    )

# groupby would silently omit parcels with missing labels.
if gdf_grouped[CLUSTER_FIELD].isna().any():
    raise ValueError("Every parcel must have a cluster label before partitioning.")

write_data(gdf_grouped, str(PARCELS_PATH).replace(".csv", ".gpkg").replace("sample_parcels", "cleaned_grouped_parcels"))

Buffer distance in data units:  10000.0

         cluster                                          parcel_id  total
0      Cluster 1  [590, 591, 592, 637, 638, 639, 640, 689, 690, ...     40
1     Cluster 10                                [951, 20752, 20804]      3
2     Cluster 11                                       [901, 20502]      2
3     Cluster 12                                             [1013]      1
4     Cluster 13                                         [751, 801]      2
5     Cluster 14                                              [664]      1
6     Cluster 15                                              [864]      1
7     Cluster 16                                              [701]      1
8     Cluster 17                                            [25567]      1
9     Cluster 18                                              [963]      1
10    Cluster 19                                            [25601]      1
11     Cluster 2  [552, 554, 555, 556, 557, 558, 560, 561, 562, ...     98
12     Cluster 3            [598, 645, 846, 1000, 1205, 1206, 1255]      7
13     Cluster 4                                  [559, 608, 25652]      3
14     Cluster 5  [595, 596, 597, 642, 643, 644, 697, 698, 699, ...     27
15     Cluster 6  [1338, 1548, 1549, 1562, 1620, 1621, 1622, 166...     19
16     Cluster 7                                         [651, 902]      2
17     Cluster 8  [636, 686, 687, 688, 741, 742, 791, 793, 838, ...     16
18     Cluster 9                                    [563, 612, 712]      3
19  Cluster Main  [564, 565, 566, 567, 568, 569, 570, 571, 572, ...    863

Removing existing file: C:/work_sat/neuro_2024-2025/cleaned_grouped_parcels.gpkg
Writing file: C:/work_sat/neuro_2024-2025/cleaned_grouped_parcels.gpkg

## Multi-user extraction planning

Accounts are loaded from PostgreSQL using `load_openeo_users_from_db()`. Install the `database` extra and set
`DB_NAME`, `TBL_USERS`, and `POSTGRES_*` in the kernel environment; `.env` is not loaded automatically.
The account table requires non-empty text `username` and `password` columns with unique usernames.
Accounts are sorted by username. Explicitly restore the original account order when resuming legacy jobs
without saved owners or using partition scheduling. See [database account setup](../../../docs/data_preparation/openeo/CREDENTIALS.md).

Create one spatial partition per cluster, then plan all tile batches before
submission. A shared queue lets every account process batches from any partition. With `fit_tiles_to_parcels=True`, a cube covers the
group's complete bounding box plus `TILE_BUFFER_METRES` on every side:

- width = east - west + 2 * buffer
- height = north - south + 2 * buffer

Only if either dimension exceeds `TILE_SIZE_METRES` does the planner split the
group spatially, then fit and check each subgroup in the same way. Parcels stay
whole and belong to exactly one job. A single parcel that exceeds the limit with
its buffer raises an error before submission.

A large partition can use all available accounts at once. Each account stays
within OPENEO_JOBS_PER_USER. Existing cubes are reused; previously submitted
jobs resume on their owning account. Keep the original account order when
first resuming a legacy run, which did not record account names.

Partition outputs and the merge step stay the same. Local statistics run after
the shared download queue completes, using LOCAL_BATCH_WORKERS per active
partition (up to one active partition per account).

In [ ]:
# ============================================================================
# STEP 2: Load accounts for the shared batch queue
# ============================================================================
# Accounts share unsubmitted batches from all cluster partitions.

OPENEO_JOBS_PER_USER = 2  # This is default by openEO
users_list = load_openeo_users_from_db()
print(f"Loaded {len(users_list)} openEO user(s):")
for i, (user, _) in enumerate(users_list, 1):
    print(f"  User {i}: {user}")

Loaded 8 openEO user(s): ['esagovhub1@gmail.com', 'esagovhub2@gmail.com', 'esagovhub3@gmail.com', 'esagovhub4@gmail.com', 'katrinporo@gmail.com', 'louvarieleni@gmail.com', 'farfarasmpoytos@gmail.com', 'sofiaargirou03@gmail.com']
Remote capacity: 8 users x 2 jobs
Loaded 8 openEO user(s):
  User 1: esagovhub1@gmail.com
  User 2: esagovhub2@gmail.com
  User 3: esagovhub3@gmail.com
  User 4: esagovhub4@gmail.com
  User 5: katrinporo@gmail.com
  User 6: louvarieleni@gmail.com
  User 7: farfarasmpoytos@gmail.com
  User 8: sofiaargirou03@gmail.com

In [9]:
# Keep each cluster together; the existing tile planner handles its size limit.
spatial_parts = [
    part.copy()
    for _, part in gdf_grouped.groupby(CLUSTER_FIELD, sort=True, observed=True)
]
assert sum(len(part) for part in spatial_parts) == len(gdf_grouped)

print(f"Created {len(spatial_parts)} cluster partitions:")
for i, part in enumerate(spatial_parts, 1):
    print(f"  Partition {i}: {part[CLUSTER_FIELD].iloc[0]} - {len(part)} parcels")

Created 20 cluster partitions:
  Partition 1: Cluster 1 - 40 parcels
  Partition 2: Cluster 10 - 3 parcels
  Partition 3: Cluster 11 - 2 parcels
  Partition 4: Cluster 12 - 1 parcels
  Partition 5: Cluster 13 - 2 parcels
  Partition 6: Cluster 14 - 1 parcels
  Partition 7: Cluster 15 - 1 parcels
  Partition 8: Cluster 16 - 1 parcels
  Partition 9: Cluster 17 - 1 parcels
  Partition 10: Cluster 18 - 1 parcels
  Partition 11: Cluster 19 - 1 parcels
  Partition 12: Cluster 2 - 98 parcels
  Partition 13: Cluster 3 - 7 parcels
  Partition 14: Cluster 4 - 3 parcels
  Partition 15: Cluster 5 - 27 parcels
  Partition 16: Cluster 6 - 19 parcels
  Partition 17: Cluster 7 - 2 parcels
  Partition 18: Cluster 8 - 16 parcels
  Partition 19: Cluster 9 - 3 parcels
  Partition 20: Cluster Main - 863 parcels

In [10]:
# Maximum requested cube width AND height, including the buffer.
# Each group gets its own fitted extent; only oversized groups are split.
TILE_SIZE_METRES = 20_000
TILE_BUFFER_METRES = compute_tile_buffer_metres(gdf_grouped, WORKING_EPSG)

Recommended tile buffer: 1,400 m

In [11]:
print(f"Maximum buffered cube width/height: {TILE_SIZE_METRES:,} m")
print(f"Buffer on each side: {TILE_BUFFER_METRES:,} m")

Maximum buffered cube width/height: 20,000 m
Buffer on each side: 1,400 m

In [12]:
# ============================================================================
# Confirm the planned global remote concurrency.
# ============================================================================
TOTAL_REMOTE_JOB_CAPACITY = len(users_list) * OPENEO_JOBS_PER_USER
print(
    f"Remote capacity: {len(users_list)} users x {OPENEO_JOBS_PER_USER} jobs "
    f"= {TOTAL_REMOTE_JOB_CAPACITY} simultaneous jobs"
)

Remote capacity: 8 users x 2 jobs = 16 simultaneous jobs

In [13]:
# ============================================================================
# STEP 3: Create extraction configuration dictionary
# ============================================================================
# Single dictionary containing all parameters for the extraction process,
# to be passed to each parallel worker.

START_DATE = "2024-10-01"
END_DATE = "2025-09-30"
OUTPUT_DIR = WORK_PATH / RUN_IDENTIFIER / "1_eo_parcel_stats_fill"

extraction_config = {
    # Output paths
    "output_dir": OUTPUT_DIR,
    "run_identifier": RUN_IDENTIFIER,

    # Parcel configuration
    "parcel_id_field": parcel_id_column,

    # Temporal bounds
    "start_date": START_DATE,
    "end_date": END_DATE,

    # Spatial configuration
    "working_epsg": WORKING_EPSG,

    # Fit cluster bounds plus buffer; split only above the maximum size.
    "fit_tiles_to_parcels": True,
    "tile_size_metres": TILE_SIZE_METRES,
    "tile_buffer_metres": TILE_BUFFER_METRES,

    # Parallel processing
    "openeo_parallel_jobs": OPENEO_JOBS_PER_USER,
    "job_poll_seconds": 30,

    # Sentinel-2 configuration
    "sentinel2_bands": ["B02", "B03", "B04", "B05", "B08", "B11", "B12"],
    "sentinel2_indices": ["EVI", "NDMI", "NDRE", "NDVI", "NDWI",  "SAVI"],

    # Sentinel-1 configuration
    "sentinel1_bands": ["VV", "VH"],
    "sentinel1_indices": ["R", "RVI"],
    "sentinel1_orbit_direction": "ASCENDING",  # ASCENDING, DESCENDING, or BOTH

    # Data cleaning (IQR outlier removal)
    "remove_outliers": False,
    "iqr_quantiles": (0.1, 0.9),
    "iqr_multiplier": 1.5,
    "iqr_min_valid_pixels": 20,

    # Null filling
    "fill_nulls": True,
    "temporal_fill_mode": "bidirectional",  # or past_only
    "minimum_parcel_pixels": 3,
    "minimum_observed_fraction_for_fill": 0.20,
    "temporal_fill_window_sizes": (3,),

    # Interpolation
    # 1. Try 3x3, then 5x5, then 7x7; if all fail, leave null.
    "spatial_fill_window_sizes": (3, 5, 7),
    # Fill remaining nulls using the specified interpolation method and maximum distance.
    "interpolation_method": "nearest",  # "idw"
    "interpolation_max_distance_in_meters": 500,

    # Temporal period and reducer for the temporal aggregation of the data.
    # "1M" means monthly aggregation, and "none" means no temporal reduction (keep all observations).
    "temporal_period": "1M",
    "temporal_reducer": "none",  # All valid pixels will be used

    # Statistics to calculate for the selected bands and indices; these are calculated for each parcel and each temporal period.
    "spatial_statistics": ["mean", "median", "sd", "min", "max", "range"],

    # Each worker loads one complete monthly cube; use one unless RAM has been sized for parallel cubes.
    "batch_workers": 2,  # For local processes only

    "remove_nc_after_completion": True,
    "resume_completed_partitions": True,
}

In [ ]:
# ============================================================================
# STEP 4: Plan all batches, then download across all users
# ============================================================================
# Plan all partition tiles first; any free account slot takes the next batch.
# Batches from the same partition may run on different accounts.
run_parallel_extractions(
    spatial_parts=spatial_parts,
    users_list=users_list,
    config=extraction_config,
    scheduling="batches",
)

# Each partition result is saved below OUTPUT_DIR/partition_<n>.
print("\nExtraction complete!")

2026-10-08 09:09:15,461 | INFO | parcel_stats_pipeline.59f6705c58.3021555834496.orchestrator | Prepared 40 valid parcels.
2026-10-08 09:09:15,463 | INFO | parcel_stats_pipeline.59f6705c58.3021555834496.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1\satellite_parcel_statistics.log.
2026-10-08 09:09:15,465 | INFO | parcel_stats_pipeline.59f6705c58.3021555834496.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:15,466 | INFO | parcel_stats_pipeline.59f6705c58.3021555834496.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

======================================================================
Running extraction on 20 spatial partition(s) across 8 user queue(s)
Remote concurrency capacity: 8 users x 2 jobs = 16
======================================================================

2026-10-08 09:09:15,914 | INFO | parcel_stats_pipeline.59f6705c58.3021555834496.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_1.
2026-10-08 09:09:15,928 | INFO | parcel_stats_pipeline.a045c6ab67.3021555972880.orchestrator | Prepared 3 valid parcels.
2026-10-08 09:09:15,929 | INFO | parcel_stats_pipeline.a045c6ab67.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2\satellite_parcel_statistics.log.
2026-10-08 09:09:15,931 | INFO | parcel_stats_pipeline.a045c6ab67.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:15,933 | INFO | parcel_stats_pipeline.a045c6ab67.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 1: reusing completed outputs.

2026-10-08 09:09:16,215 | INFO | parcel_stats_pipeline.a045c6ab67.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_2.
2026-10-08 09:09:16,228 | INFO | parcel_stats_pipeline.c795cd6857.3021555973840.orchestrator | Prepared 2 valid parcels.
2026-10-08 09:09:16,229 | INFO | parcel_stats_pipeline.c795cd6857.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3\satellite_parcel_statistics.log.
2026-10-08 09:09:16,231 | INFO | parcel_stats_pipeline.c795cd6857.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:16,232 | INFO | parcel_stats_pipeline.c795cd6857.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 2: reusing completed outputs.

2026-10-08 09:09:16,518 | INFO | parcel_stats_pipeline.c795cd6857.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_3.
2026-10-08 09:09:16,530 | INFO | parcel_stats_pipeline.d3b9f11ce8.3021555972880.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:16,532 | INFO | parcel_stats_pipeline.d3b9f11ce8.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4\satellite_parcel_statistics.log.
2026-10-08 09:09:16,533 | INFO | parcel_stats_pipeline.d3b9f11ce8.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:16,534 | INFO | parcel_stats_pipeline.d3b9f11ce8.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 3: reusing completed outputs.

2026-10-08 09:09:16,818 | INFO | parcel_stats_pipeline.d3b9f11ce8.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_4.
2026-10-08 09:09:16,830 | INFO | parcel_stats_pipeline.ac8c6d540a.3021555973840.orchestrator | Prepared 2 valid parcels.
2026-10-08 09:09:16,832 | INFO | parcel_stats_pipeline.ac8c6d540a.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5\satellite_parcel_statistics.log.
2026-10-08 09:09:16,833 | INFO | parcel_stats_pipeline.ac8c6d540a.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:16,835 | INFO | parcel_stats_pipeline.ac8c6d540a.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 4: reusing completed outputs.

2026-10-08 09:09:17,141 | INFO | parcel_stats_pipeline.ac8c6d540a.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_5.
2026-10-08 09:09:17,155 | INFO | parcel_stats_pipeline.41d4df1703.3021555972880.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:17,157 | INFO | parcel_stats_pipeline.41d4df1703.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6\satellite_parcel_statistics.log.
2026-10-08 09:09:17,160 | INFO | parcel_stats_pipeline.41d4df1703.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:17,162 | INFO | parcel_stats_pipeline.41d4df1703.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 5: reusing completed outputs.

2026-10-08 09:09:17,442 | INFO | parcel_stats_pipeline.41d4df1703.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_6.
2026-10-08 09:09:17,454 | INFO | parcel_stats_pipeline.968646fcee.3021555973840.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:17,456 | INFO | parcel_stats_pipeline.968646fcee.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7\satellite_parcel_statistics.log.
2026-10-08 09:09:17,458 | INFO | parcel_stats_pipeline.968646fcee.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:17,460 | INFO | parcel_stats_pipeline.968646fcee.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 6: reusing completed outputs.

2026-10-08 09:09:17,744 | INFO | parcel_stats_pipeline.968646fcee.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_7.
2026-10-08 09:09:17,757 | INFO | parcel_stats_pipeline.b79d675521.3021555972880.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:17,759 | INFO | parcel_stats_pipeline.b79d675521.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8\satellite_parcel_statistics.log.
2026-10-08 09:09:17,760 | INFO | parcel_stats_pipeline.b79d675521.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:17,761 | INFO | parcel_stats_pipeline.b79d675521.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 7: reusing completed outputs.

2026-10-08 09:09:18,047 | INFO | parcel_stats_pipeline.b79d675521.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_8.
2026-10-08 09:09:18,062 | INFO | parcel_stats_pipeline.6ed1533047.3021555973840.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:18,064 | INFO | parcel_stats_pipeline.6ed1533047.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9\satellite_parcel_statistics.log.
2026-10-08 09:09:18,065 | INFO | parcel_stats_pipeline.6ed1533047.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:18,066 | INFO | parcel_stats_pipeline.6ed1533047.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 8: reusing completed outputs.

2026-10-08 09:09:18,342 | INFO | parcel_stats_pipeline.6ed1533047.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_9.
2026-10-08 09:09:18,355 | INFO | parcel_stats_pipeline.9954fc637f.3021555972880.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:18,357 | INFO | parcel_stats_pipeline.9954fc637f.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10\satellite_parcel_statistics.log.
2026-10-08 09:09:18,359 | INFO | parcel_stats_pipeline.9954fc637f.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:18,360 | INFO | parcel_stats_pipeline.9954fc637f.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 9: reusing completed outputs.

2026-10-08 09:09:18,659 | INFO | parcel_stats_pipeline.9954fc637f.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_10.
2026-10-08 09:09:18,672 | INFO | parcel_stats_pipeline.06ac1dc7c7.3021555973840.orchestrator | Prepared 1 valid parcels.
2026-10-08 09:09:18,674 | INFO | parcel_stats_pipeline.06ac1dc7c7.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11\satellite_parcel_statistics.log.
2026-10-08 09:09:18,675 | INFO | parcel_stats_pipeline.06ac1dc7c7.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:18,677 | INFO | parcel_stats_pipeline.06ac1dc7c7.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 10: reusing completed outputs.

2026-10-08 09:09:18,951 | INFO | parcel_stats_pipeline.06ac1dc7c7.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_11.
2026-10-08 09:09:18,969 | INFO | parcel_stats_pipeline.bf4ce84bfa.3021555972880.orchestrator | Prepared 98 valid parcels.
2026-10-08 09:09:18,972 | INFO | parcel_stats_pipeline.bf4ce84bfa.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12\satellite_parcel_statistics.log.
2026-10-08 09:09:18,975 | INFO | parcel_stats_pipeline.bf4ce84bfa.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:18,976 | INFO | parcel_stats_pipeline.bf4ce84bfa.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 11: reusing completed outputs.

2026-10-08 09:09:19,256 | INFO | parcel_stats_pipeline.bf4ce84bfa.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_12.
2026-10-08 09:09:19,269 | INFO | parcel_stats_pipeline.0d4f4abe05.3021555973840.orchestrator | Prepared 7 valid parcels.
2026-10-08 09:09:19,271 | INFO | parcel_stats_pipeline.0d4f4abe05.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13\satellite_parcel_statistics.log.
2026-10-08 09:09:19,273 | INFO | parcel_stats_pipeline.0d4f4abe05.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:19,275 | INFO | parcel_stats_pipeline.0d4f4abe05.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 12: reusing completed outputs.

2026-10-08 09:09:19,548 | INFO | parcel_stats_pipeline.0d4f4abe05.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_13.
2026-10-08 09:09:19,562 | INFO | parcel_stats_pipeline.7028f15ab9.3021555972880.orchestrator | Prepared 3 valid parcels.
2026-10-08 09:09:19,563 | INFO | parcel_stats_pipeline.7028f15ab9.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14\satellite_parcel_statistics.log.
2026-10-08 09:09:19,566 | INFO | parcel_stats_pipeline.7028f15ab9.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:19,568 | INFO | parcel_stats_pipeline.7028f15ab9.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 13: reusing completed outputs.

2026-10-08 09:09:19,860 | INFO | parcel_stats_pipeline.7028f15ab9.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_14.
2026-10-08 09:09:19,875 | INFO | parcel_stats_pipeline.849566e3ee.3021555973840.orchestrator | Prepared 27 valid parcels.
2026-10-08 09:09:19,877 | INFO | parcel_stats_pipeline.849566e3ee.3021555973840.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15\satellite_parcel_statistics.log.
2026-10-08 09:09:19,879 | INFO | parcel_stats_pipeline.849566e3ee.3021555973840.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:19,881 | INFO | parcel_stats_pipeline.849566e3ee.3021555973840.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 14: reusing completed outputs.

2026-10-08 09:09:20,151 | INFO | parcel_stats_pipeline.849566e3ee.3021555973840.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_15.
2026-10-08 09:09:20,165 | INFO | parcel_stats_pipeline.1f869c30b1.3021555972880.orchestrator | Prepared 19 valid parcels.
2026-10-08 09:09:20,168 | INFO | parcel_stats_pipeline.1f869c30b1.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16\satellite_parcel_statistics.log.
2026-10-08 09:09:20,169 | INFO | parcel_stats_pipeline.1f869c30b1.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:20,171 | INFO | parcel_stats_pipeline.1f869c30b1.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 15: reusing completed outputs.

2026-10-08 09:09:20,446 | INFO | parcel_stats_pipeline.1f869c30b1.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_16.
2026-10-08 09:09:20,458 | INFO | parcel_stats_pipeline.0801865a14.3021555973200.orchestrator | Prepared 2 valid parcels.
2026-10-08 09:09:20,461 | INFO | parcel_stats_pipeline.0801865a14.3021555973200.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17\satellite_parcel_statistics.log.
2026-10-08 09:09:20,462 | INFO | parcel_stats_pipeline.0801865a14.3021555973200.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:20,463 | INFO | parcel_stats_pipeline.0801865a14.3021555973200.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 16: reusing completed outputs.

2026-10-08 09:09:20,751 | INFO | parcel_stats_pipeline.0801865a14.3021555973200.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_17.
2026-10-08 09:09:20,766 | INFO | parcel_stats_pipeline.911a3c146a.3021555972880.orchestrator | Prepared 16 valid parcels.
2026-10-08 09:09:20,768 | INFO | parcel_stats_pipeline.911a3c146a.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18\satellite_parcel_statistics.log.
2026-10-08 09:09:20,769 | INFO | parcel_stats_pipeline.911a3c146a.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:20,771 | INFO | parcel_stats_pipeline.911a3c146a.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 17: reusing completed outputs.

2026-10-08 09:09:21,046 | INFO | parcel_stats_pipeline.911a3c146a.3021555972880.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_18.
2026-10-08 09:09:21,059 | INFO | parcel_stats_pipeline.0ba46dc589.3021555973200.orchestrator | Prepared 3 valid parcels.
2026-10-08 09:09:21,061 | INFO | parcel_stats_pipeline.0ba46dc589.3021555973200.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19\satellite_parcel_statistics.log.
2026-10-08 09:09:21,062 | INFO | parcel_stats_pipeline.0ba46dc589.3021555973200.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:21,063 | INFO | parcel_stats_pipeline.0ba46dc589.3021555973200.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 18: reusing completed outputs.

2026-10-08 09:09:21,342 | INFO | parcel_stats_pipeline.0ba46dc589.3021555973200.orchestrator | Reusing completed partition outputs in C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_19.
2026-10-08 09:09:21,388 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.orchestrator | Prepared 863 valid parcels.
2026-10-08 09:09:21,391 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.orchestrator | Log files: orchestration=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_zonal_stats.log, source=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_source.log, raster filling=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_raster_filling.log, parcel statistics=C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\satellite_parcel_statistics.log.
2026-10-08 09:09:21,393 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.orchestrator | Source=openEO, optical bands=['B02', 'B03', 'B04', 'B05', 'B08', 'B11', 'B12'], optical indices=['EVI', 'NDMI', 'NDRE', 'NDVI', 'NDWI', 'SAVI'], parcel statistics=['mean', 'median', 'sd', 'min', 'max', 'range'], remove_outliers=False, iqr_quantiles=(0.1, 0.9), iqr_multiplier=1.5, and fill_nulls=True, temporal_period=1M, and temporal_reducer=none, and batch_workers=2.
2026-10-08 09:09:21,395 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.orchestrator | Radar source=Sentinel-1, bands=['VV', 'VH'], indices=['R', 'RVI'], orbit direction=ASCENDING.

Partition 19: reusing completed outputs.

2026-10-08 09:09:21,940 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00015_monthly.nc.

Partition 20: 863 parcels, 17 batches, 17 queued.
Shared queue: 3 unsubmitted batches; 14 owned jobs to resume.

2026-10-08 09:09:23,325 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 2 from finished job j-2610070947014f3fafdf6adfd7242c17.
2026-10-08 09:09:23,559 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 6 from finished job j-2610070953084cb3b299d15dcc8508f5.
2026-10-08 09:09:23,631 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 9 from finished job j-261007095442407a89ab0793eccec9c1.
2026-10-08 09:09:23,793 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 4 from finished job j-2610070950404d9da7f9cb318374c66c.
2026-10-08 09:09:23,830 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 1 from finished job j-26100709431541cc97f574c7ed25743e.
2026-10-08 09:09:23,851 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 13 from finished job j-26100710044141ce82fe779b136303d4.
2026-10-08 09:09:23,897 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 11 from finished job j-2610070958574d26a9e46fe66c5c8c36.
2026-10-08 09:09:23,908 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 8 from finished job j-2610070953574e7cb6b3e43bf035b852.
2026-10-08 09:09:23,925 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 12 from finished job j-261007095912449f8d8a5a1d0ba5df48.
2026-10-08 09:09:27,274 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/181.
2026-10-08 09:09:33,067 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/181.
2026-10-08 09:09:42,813 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/181.
2026-10-08 09:09:53,781 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/181.
2026-10-08 09:10:09,965 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/181.
2026-10-08 09:10:23,843 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/181.
2026-10-08 09:10:30,895 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/181.
2026-10-08 09:10:38,277 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/181.
2026-10-08 09:10:47,302 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/181.
2026-10-08 09:10:57,160 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/181.
2026-10-08 09:11:15,780 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/181.
2026-10-08 09:11:25,996 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/181.
2026-10-08 09:11:34,651 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/181.
2026-10-08 09:11:43,028 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/181.
2026-10-08 09:11:51,878 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 150/181.
2026-10-08 09:12:00,694 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 160/181.
2026-10-08 09:12:09,764 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 170/181.
2026-10-08 09:12:18,202 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 180/181.
2026-10-08 09:12:19,034 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 181/181.
2026-10-08 09:12:21,905 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00015_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00015_monthly_cleaning_report.parquet

2026-10-08 09:15:04,104 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 36 parcels from batch_00015_monthly.nc.
2026-10-08 09:15:09,358 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00016_monthly.nc.
2026-10-08 09:15:10,917 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 10 from finished job j-2610070958424f449285ddccaa80813e.
2026-10-08 09:15:11,165 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/145 for batch 16.
2026-10-08 09:15:12,669 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/145 for batch 16.
2026-10-08 09:15:14,264 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/145 for batch 16.
2026-10-08 09:15:15,631 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/145 for batch 16.
2026-10-08 09:15:16,988 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/145 for batch 16.
2026-10-08 09:15:18,379 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/145 for batch 16.
2026-10-08 09:15:19,933 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/145 for batch 16.
2026-10-08 09:15:21,371 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/145 for batch 16.
2026-10-08 09:15:23,314 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/145 for batch 16.
2026-10-08 09:15:24,781 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/145 for batch 16.
2026-10-08 09:15:26,331 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/145 for batch 16.
2026-10-08 09:15:27,984 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/145 for batch 16.
2026-10-08 09:15:29,743 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/145 for batch 16.
2026-10-08 09:15:31,284 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/145 for batch 16.
2026-10-08 09:15:31,995 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 145/145 for batch 16.
2026-10-08 09:15:31,999 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 47 rows.
2026-10-08 09:15:33,708 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 47 rows.
2026-10-08 09:15:35,319 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 47 rows.
2026-10-08 09:15:37,018 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 47 rows.
2026-10-08 09:15:38,728 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 47 rows.
2026-10-08 09:15:40,397 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 47 rows.
2026-10-08 09:15:42,068 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 47 rows.
2026-10-08 09:15:43,792 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 47 rows.
2026-10-08 09:15:45,423 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 47 rows.
2026-10-08 09:15:47,182 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/145 for batch 16.
2026-10-08 09:15:47,251 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/145 for batch 16.
2026-10-08 09:15:47,320 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/145 for batch 16.
2026-10-08 09:15:47,401 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/145 for batch 16.
2026-10-08 09:15:47,480 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/145 for batch 16.
2026-10-08 09:15:47,549 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/145 for batch 16.
2026-10-08 09:15:47,620 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/145 for batch 16.
2026-10-08 09:15:47,690 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/145 for batch 16.
2026-10-08 09:15:47,752 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/145 for batch 16.
2026-10-08 09:15:47,818 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/145 for batch 16.
2026-10-08 09:15:47,885 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/145 for batch 16.
2026-10-08 09:15:47,947 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/145 for batch 16.
2026-10-08 09:15:48,003 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/145 for batch 16.
2026-10-08 09:15:48,063 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/145 for batch 16.
2026-10-08 09:15:48,135 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/145 for batch 16.
2026-10-08 09:15:48,202 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/145 for batch 16.
2026-10-08 09:15:48,486 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/145 for batch 16.
2026-10-08 09:15:48,557 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/145 for batch 16.
2026-10-08 09:15:48,618 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/145 for batch 16.
2026-10-08 09:15:48,688 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/145 for batch 16.
2026-10-08 09:15:48,751 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/145 for batch 16.
2026-10-08 09:15:48,824 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/145 for batch 16.
2026-10-08 09:15:48,898 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/145 for batch 16.
2026-10-08 09:15:48,994 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/145 for batch 16.
2026-10-08 09:15:49,092 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/145 for batch 16.
2026-10-08 09:15:49,189 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/145 for batch 16.
2026-10-08 09:15:49,263 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/145 for batch 16.
2026-10-08 09:15:49,352 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/145 for batch 16.
2026-10-08 09:15:49,426 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/145 for batch 16.
2026-10-08 09:15:49,507 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/145 for batch 16.
2026-10-08 09:15:49,571 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/145 for batch 16.
2026-10-08 09:15:49,636 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/145 for batch 16.
2026-10-08 09:15:49,699 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/145 for batch 16.
2026-10-08 09:15:49,766 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/145 for batch 16.
2026-10-08 09:15:49,832 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/145 for batch 16.
2026-10-08 09:15:49,907 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/145 for batch 16.
2026-10-08 09:15:49,998 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/145 for batch 16.
2026-10-08 09:15:50,343 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/145 for batch 16.
2026-10-08 09:15:50,427 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/145 for batch 16.
2026-10-08 09:15:50,794 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/145 for batch 16.
2026-10-08 09:15:50,868 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/145 for batch 16.
2026-10-08 09:15:51,043 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/145 for batch 16.
2026-10-08 09:15:51,217 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/145 for batch 16.
2026-10-08 09:15:51,279 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/145 for batch 16.
2026-10-08 09:15:51,355 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/145 for batch 16.
2026-10-08 09:15:51,426 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/145 for batch 16.
2026-10-08 09:15:51,504 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/145 for batch 16.
2026-10-08 09:15:51,576 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/145 for batch 16.
2026-10-08 09:15:51,656 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/145 for batch 16.
2026-10-08 09:15:51,717 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/145 for batch 16.
2026-10-08 09:15:51,777 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/145 for batch 16.
2026-10-08 09:15:51,847 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/145 for batch 16.
2026-10-08 09:15:51,913 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/145 for batch 16.
2026-10-08 09:15:51,986 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/145 for batch 16.
2026-10-08 09:15:52,065 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/145 for batch 16.
2026-10-08 09:15:52,136 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/145 for batch 16.
2026-10-08 09:15:52,204 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/145 for batch 16.
2026-10-08 09:15:52,276 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/145 for batch 16.
2026-10-08 09:15:52,338 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/145 for batch 16.
2026-10-08 09:15:52,403 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/145 for batch 16.
2026-10-08 09:15:52,468 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/145 for batch 16.
2026-10-08 09:15:52,531 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/145 for batch 16.
2026-10-08 09:15:52,599 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/145 for batch 16.
2026-10-08 09:15:52,675 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/145 for batch 16.
2026-10-08 09:15:52,746 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/145 for batch 16.
2026-10-08 09:15:52,808 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/145 for batch 16.
2026-10-08 09:15:52,886 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/145 for batch 16.
2026-10-08 09:15:52,953 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/145 for batch 16.
2026-10-08 09:15:53,015 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/145 for batch 16.
2026-10-08 09:15:53,081 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/145 for batch 16.
2026-10-08 09:15:53,148 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/145 for batch 16.
2026-10-08 09:15:53,545 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/145 for batch 16.
2026-10-08 09:15:53,963 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/145 for batch 16.
2026-10-08 09:15:54,036 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/145 for batch 16.
2026-10-08 09:15:54,105 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/145 for batch 16.
2026-10-08 09:15:54,176 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/145 for batch 16.
2026-10-08 09:15:54,242 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/145 for batch 16.
2026-10-08 09:15:54,318 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/145 for batch 16.
2026-10-08 09:15:54,385 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/145 for batch 16.
2026-10-08 09:15:54,463 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/145 for batch 16.
2026-10-08 09:15:54,845 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/145 for batch 16.
2026-10-08 09:15:55,219 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/145 for batch 16.
2026-10-08 09:15:55,582 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/145 for batch 16.
2026-10-08 09:15:55,649 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/145 for batch 16.
2026-10-08 09:15:55,714 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/145 for batch 16.
2026-10-08 09:15:55,785 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/145 for batch 16.
2026-10-08 09:15:55,871 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/145 for batch 16.
2026-10-08 09:15:55,949 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/145 for batch 16.
2026-10-08 09:15:56,025 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/145 for batch 16.
2026-10-08 09:15:56,104 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/145 for batch 16.
2026-10-08 09:15:56,176 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/145 for batch 16.
2026-10-08 09:15:56,240 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/145 for batch 16.
2026-10-08 09:15:56,315 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/145 for batch 16.
2026-10-08 09:15:56,375 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/145 for batch 16.
2026-10-08 09:15:56,448 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/145 for batch 16.
2026-10-08 09:15:56,513 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/145 for batch 16.
2026-10-08 09:15:56,603 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/145 for batch 16.
2026-10-08 09:15:56,669 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/145 for batch 16.
2026-10-08 09:15:56,744 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/145 for batch 16.
2026-10-08 09:15:56,811 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/145 for batch 16.
2026-10-08 09:15:56,878 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/145 for batch 16.
2026-10-08 09:15:56,940 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/145 for batch 16.
2026-10-08 09:15:57,015 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/145 for batch 16.
2026-10-08 09:15:57,079 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/145 for batch 16.
2026-10-08 09:15:57,144 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/145 for batch 16.
2026-10-08 09:15:57,212 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/145 for batch 16.
2026-10-08 09:15:57,279 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/145 for batch 16.
2026-10-08 09:15:57,343 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/145 for batch 16.
2026-10-08 09:15:57,419 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/145 for batch 16.
2026-10-08 09:15:57,488 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/145 for batch 16.
2026-10-08 09:15:57,550 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/145 for batch 16.
2026-10-08 09:15:57,617 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/145 for batch 16.
2026-10-08 09:15:57,709 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/145 for batch 16.
2026-10-08 09:15:57,777 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/145 for batch 16.
2026-10-08 09:15:57,846 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/145 for batch 16.
2026-10-08 09:15:57,922 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/145 for batch 16.
2026-10-08 09:15:57,997 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/145 for batch 16.
2026-10-08 09:15:58,073 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/145 for batch 16.
2026-10-08 09:15:58,139 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/145 for batch 16.
2026-10-08 09:15:58,226 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/145 for batch 16.
2026-10-08 09:15:58,302 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 121/145 for batch 16.
2026-10-08 09:15:58,375 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 122/145 for batch 16.
2026-10-08 09:15:58,439 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 123/145 for batch 16.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00016_monthly_cleaning_report.partial.parquet

2026-10-08 09:16:02,276 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/145.
2026-10-08 09:16:03,403 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/145.
2026-10-08 09:16:04,549 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/145.
2026-10-08 09:16:05,601 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/145.
2026-10-08 09:16:06,635 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/145.
2026-10-08 09:16:07,778 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/145.
2026-10-08 09:16:08,950 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/145.
2026-10-08 09:16:10,115 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/145.
2026-10-08 09:16:11,259 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/145.
2026-10-08 09:16:12,329 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/145.
2026-10-08 09:16:13,436 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/145.
2026-10-08 09:16:14,467 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/145.
2026-10-08 09:16:15,400 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/145.
2026-10-08 09:16:16,406 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/145.
2026-10-08 09:16:16,932 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 145/145.
2026-10-08 09:16:17,576 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00016_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00016_monthly_cleaning_report.parquet

2026-10-08 09:16:21,629 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 1 parcels from batch_00016_monthly.nc.
2026-10-08 09:16:23,611 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00017_monthly.nc.
2026-10-08 09:16:35,917 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/155 for batch 17.
2026-10-08 09:16:48,411 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/155 for batch 17.
2026-10-08 09:17:00,900 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/155 for batch 17.
2026-10-08 09:17:12,290 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/155 for batch 17.
2026-10-08 09:17:24,221 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/155 for batch 17.
2026-10-08 09:17:37,116 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/155 for batch 17.
2026-10-08 09:17:51,767 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/155 for batch 17.
2026-10-08 09:18:06,246 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/155 for batch 17.
2026-10-08 09:18:20,477 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/155 for batch 17.
2026-10-08 09:18:37,159 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/155 for batch 17.
2026-10-08 09:18:53,386 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/155 for batch 17.
2026-10-08 09:19:09,248 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/155 for batch 17.
2026-10-08 09:19:25,136 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/155 for batch 17.
2026-10-08 09:19:40,487 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/155 for batch 17.
2026-10-08 09:19:55,910 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 150/155 for batch 17.
2026-10-08 09:20:03,208 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 155/155 for batch 17.
2026-10-08 09:20:03,211 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-08 09:21:23,717 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-08 09:22:45,608 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-08 09:24:04,938 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-08 09:25:25,608 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-08 09:26:48,329 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-08 09:28:10,229 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-08 09:29:36,742 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-08 09:31:07,932 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-08 09:32:26,636 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/155 for batch 17.
2026-10-08 09:32:27,609 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/155 for batch 17.
2026-10-08 09:32:28,373 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/155 for batch 17.
2026-10-08 09:32:29,058 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/155 for batch 17.
2026-10-08 09:32:30,458 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/155 for batch 17.
2026-10-08 09:32:31,187 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/155 for batch 17.
2026-10-08 09:32:37,002 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/155 for batch 17.
2026-10-08 09:32:37,691 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/155 for batch 17.
2026-10-08 09:32:39,126 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/155 for batch 17.
2026-10-08 09:32:40,053 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/155 for batch 17.
2026-10-08 09:32:40,761 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/155 for batch 17.
2026-10-08 09:32:41,655 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/155 for batch 17.
2026-10-08 09:32:42,684 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/155 for batch 17.
2026-10-08 09:32:44,019 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/155 for batch 17.
2026-10-08 09:32:44,714 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/155 for batch 17.
2026-10-08 09:32:45,469 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/155 for batch 17.
2026-10-08 09:32:46,187 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/155 for batch 17.
2026-10-08 09:32:47,203 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/155 for batch 17.
2026-10-08 09:32:48,044 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/155 for batch 17.
2026-10-08 09:32:54,597 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/155 for batch 17.
2026-10-08 09:32:55,841 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/155 for batch 17.
2026-10-08 09:33:04,584 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/155 for batch 17.
2026-10-08 09:33:05,843 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/155 for batch 17.
2026-10-08 09:33:13,979 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/155 for batch 17.
2026-10-08 09:33:14,612 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/155 for batch 17.
2026-10-08 09:33:15,288 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/155 for batch 17.
2026-10-08 09:33:16,398 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/155 for batch 17.
2026-10-08 09:33:17,123 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/155 for batch 17.
2026-10-08 09:33:17,807 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/155 for batch 17.
2026-10-08 09:33:19,054 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/155 for batch 17.
2026-10-08 09:33:19,699 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/155 for batch 17.
2026-10-08 09:33:27,807 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/155 for batch 17.
2026-10-08 09:33:29,098 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/155 for batch 17.
2026-10-08 09:33:30,056 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/155 for batch 17.
2026-10-08 09:33:38,257 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/155 for batch 17.
2026-10-08 09:33:38,979 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/155 for batch 17.
2026-10-08 09:33:39,726 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/155 for batch 17.
2026-10-08 09:33:40,929 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/155 for batch 17.
2026-10-08 09:33:49,637 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/155 for batch 17.
2026-10-08 09:33:57,872 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/155 for batch 17.
2026-10-08 09:33:58,507 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/155 for batch 17.
2026-10-08 09:33:59,141 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/155 for batch 17.
2026-10-08 09:33:59,815 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/155 for batch 17.
2026-10-08 09:34:00,948 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/155 for batch 17.
2026-10-08 09:34:09,016 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/155 for batch 17.
2026-10-08 09:34:09,706 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/155 for batch 17.
2026-10-08 09:34:17,551 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/155 for batch 17.
2026-10-08 09:34:18,413 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/155 for batch 17.
2026-10-08 09:34:23,900 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/155 for batch 17.
2026-10-08 09:34:29,421 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/155 for batch 17.
2026-10-08 09:34:30,186 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/155 for batch 17.
2026-10-08 09:34:31,352 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/155 for batch 17.
2026-10-08 09:34:32,397 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/155 for batch 17.
2026-10-08 09:34:33,146 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/155 for batch 17.
2026-10-08 09:34:33,794 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/155 for batch 17.
2026-10-08 09:34:34,985 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/155 for batch 17.
2026-10-08 09:34:35,662 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/155 for batch 17.
2026-10-08 09:34:36,310 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/155 for batch 17.
2026-10-08 09:34:37,138 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/155 for batch 17.
2026-10-08 09:34:37,922 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/155 for batch 17.
2026-10-08 09:34:46,092 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/155 for batch 17.
2026-10-08 09:34:47,024 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/155 for batch 17.
2026-10-08 09:34:50,127 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/155 for batch 17.
2026-10-08 09:34:50,767 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/155 for batch 17.
2026-10-08 09:34:51,541 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/155 for batch 17.
2026-10-08 09:34:52,218 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/155 for batch 17.
2026-10-08 09:34:53,160 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/155 for batch 17.
2026-10-08 09:34:54,071 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/155 for batch 17.
2026-10-08 09:34:54,739 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/155 for batch 17.
2026-10-08 09:34:55,418 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/155 for batch 17.
2026-10-08 09:34:56,246 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/155 for batch 17.
2026-10-08 09:34:56,969 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/155 for batch 17.
2026-10-08 09:34:58,124 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/155 for batch 17.
2026-10-08 09:34:59,718 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/155 for batch 17.
2026-10-08 09:35:00,515 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/155 for batch 17.
2026-10-08 09:35:01,170 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/155 for batch 17.
2026-10-08 09:35:01,846 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/155 for batch 17.
2026-10-08 09:35:02,861 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/155 for batch 17.
2026-10-08 09:35:03,858 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/155 for batch 17.
2026-10-08 09:35:04,487 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/155 for batch 17.
2026-10-08 09:35:05,694 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/155 for batch 17.
2026-10-08 09:35:06,456 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/155 for batch 17.
2026-10-08 09:35:07,543 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/155 for batch 17.
2026-10-08 09:35:08,578 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/155 for batch 17.
2026-10-08 09:35:09,178 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/155 for batch 17.
2026-10-08 09:35:09,817 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/155 for batch 17.
2026-10-08 09:35:10,764 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/155 for batch 17.
2026-10-08 09:35:18,383 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/155 for batch 17.
2026-10-08 09:35:25,903 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/155 for batch 17.
2026-10-08 09:35:33,533 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/155 for batch 17.
2026-10-08 09:35:34,175 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/155 for batch 17.
2026-10-08 09:35:34,873 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/155 for batch 17.
2026-10-08 09:35:35,495 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/155 for batch 17.
2026-10-08 09:35:36,494 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/155 for batch 17.
2026-10-08 09:35:37,173 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/155 for batch 17.
2026-10-08 09:35:37,791 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/155 for batch 17.
2026-10-08 09:35:38,557 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/155 for batch 17.
2026-10-08 09:35:39,161 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/155 for batch 17.
2026-10-08 09:35:39,824 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/155 for batch 17.
2026-10-08 09:35:47,633 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/155 for batch 17.
2026-10-08 09:35:48,283 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/155 for batch 17.
2026-10-08 09:35:49,003 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/155 for batch 17.
2026-10-08 09:35:49,680 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/155 for batch 17.
2026-10-08 09:35:50,882 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/155 for batch 17.
2026-10-08 09:35:51,601 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/155 for batch 17.
2026-10-08 09:35:52,720 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/155 for batch 17.
2026-10-08 09:35:53,363 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/155 for batch 17.
2026-10-08 09:35:53,987 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/155 for batch 17.
2026-10-08 09:35:54,583 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/155 for batch 17.
2026-10-08 09:35:55,365 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/155 for batch 17.
2026-10-08 09:35:56,022 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/155 for batch 17.
2026-10-08 09:35:57,042 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/155 for batch 17.
2026-10-08 09:35:58,458 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/155 for batch 17.
2026-10-08 09:35:59,109 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/155 for batch 17.
2026-10-08 09:35:59,709 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/155 for batch 17.
2026-10-08 09:36:00,463 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/155 for batch 17.
2026-10-08 09:36:01,064 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/155 for batch 17.
2026-10-08 09:36:01,821 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/155 for batch 17.
2026-10-08 09:36:02,832 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/155 for batch 17.
2026-10-08 09:36:04,118 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/155 for batch 17.
2026-10-08 09:36:04,764 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 121/155 for batch 17.
2026-10-08 09:36:05,414 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 122/155 for batch 17.
2026-10-08 09:36:06,468 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 123/155 for batch 17.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00017_monthly_cleaning_report.partial.parquet

2026-10-08 09:37:49,732 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/155.
2026-10-08 09:38:09,346 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/155.
2026-10-08 09:38:29,337 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/155.
2026-10-08 09:38:49,647 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/155.
2026-10-08 09:39:10,023 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/155.
2026-10-08 09:39:30,942 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/155.
2026-10-08 09:39:52,519 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/155.
2026-10-08 09:40:18,992 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/155.
2026-10-08 09:40:45,688 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/155.
2026-10-08 09:41:11,490 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/155.
2026-10-08 09:41:36,765 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/155.
2026-10-08 09:42:03,717 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/155.
2026-10-08 09:42:30,294 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/155.
2026-10-08 09:42:56,978 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/155.
2026-10-08 09:43:22,349 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 150/155.
2026-10-08 09:43:35,682 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 155/155.
2026-10-08 09:43:39,399 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00017_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00017_monthly_cleaning_report.parquet

2026-10-08 09:51:12,320 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 145 parcels from batch_00017_monthly.nc.
2026-10-08 09:51:20,738 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00008_monthly.nc.
2026-10-08 09:51:22,349 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.source | Restoring missing raw cube for batch 7 from finished job j-26100709534344ca827ec6d224571b2d.
2026-10-08 09:51:27,115 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/189 for batch 8.
2026-10-08 09:51:34,176 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/189 for batch 8.
2026-10-08 09:51:39,842 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/189 for batch 8.
2026-10-08 09:51:45,387 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/189 for batch 8.
2026-10-08 09:51:51,473 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/189 for batch 8.
2026-10-08 09:51:57,791 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/189 for batch 8.
2026-10-08 09:52:04,218 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/189 for batch 8.
2026-10-08 09:52:09,159 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/189 for batch 8.
2026-10-08 09:52:15,417 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/189 for batch 8.
2026-10-08 09:52:21,481 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/189 for batch 8.
2026-10-08 09:52:27,386 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/189 for batch 8.
2026-10-08 09:52:33,996 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/189 for batch 8.
2026-10-08 09:52:39,988 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/189 for batch 8.
2026-10-08 09:52:46,531 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/189 for batch 8.
2026-10-08 09:52:53,044 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 150/189 for batch 8.
2026-10-08 09:52:59,174 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 160/189 for batch 8.
2026-10-08 09:53:05,871 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 170/189 for batch 8.
2026-10-08 09:53:11,891 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 180/189 for batch 8.
2026-10-08 09:53:17,322 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 189/189 for batch 8.
2026-10-08 09:53:17,324 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 10 rows.
2026-10-08 09:53:55,480 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 10 rows.
2026-10-08 09:54:37,039 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 10 rows.
2026-10-08 09:55:16,691 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 10 rows.
2026-10-08 09:55:57,613 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 10 rows.
2026-10-08 09:56:37,384 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 10 rows.
2026-10-08 09:57:16,766 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 10 rows.
2026-10-08 09:58:01,747 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 10 rows.
2026-10-08 09:58:40,542 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 10 rows.
2026-10-08 09:59:23,153 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/189 for batch 8.
2026-10-08 09:59:23,465 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/189 for batch 8.
2026-10-08 09:59:26,555 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/189 for batch 8.
2026-10-08 09:59:29,528 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/189 for batch 8.
2026-10-08 09:59:32,521 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/189 for batch 8.
2026-10-08 09:59:32,962 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/189 for batch 8.
2026-10-08 09:59:35,950 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/189 for batch 8.
2026-10-08 09:59:36,280 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/189 for batch 8.
2026-10-08 09:59:39,333 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/189 for batch 8.
2026-10-08 09:59:39,584 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/189 for batch 8.
2026-10-08 09:59:40,001 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/189 for batch 8.
2026-10-08 09:59:40,253 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/189 for batch 8.
2026-10-08 09:59:40,571 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/189 for batch 8.
2026-10-08 09:59:40,821 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/189 for batch 8.
2026-10-08 09:59:43,875 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/189 for batch 8.
2026-10-08 09:59:47,068 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/189 for batch 8.
2026-10-08 09:59:50,037 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/189 for batch 8.
2026-10-08 09:59:50,383 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/189 for batch 8.
2026-10-08 09:59:53,426 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/189 for batch 8.
2026-10-08 09:59:53,672 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/189 for batch 8.
2026-10-08 09:59:53,916 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/189 for batch 8.
2026-10-08 09:59:54,183 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/189 for batch 8.
2026-10-08 09:59:54,451 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/189 for batch 8.
2026-10-08 09:59:54,721 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/189 for batch 8.
2026-10-08 09:59:54,969 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/189 for batch 8.
2026-10-08 09:59:57,984 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/189 for batch 8.
2026-10-08 09:59:58,337 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/189 for batch 8.
2026-10-08 10:00:01,344 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/189 for batch 8.
2026-10-08 10:00:04,262 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/189 for batch 8.
2026-10-08 10:00:04,578 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/189 for batch 8.
2026-10-08 10:00:07,560 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/189 for batch 8.
2026-10-08 10:00:07,909 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/189 for batch 8.
2026-10-08 10:00:10,883 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/189 for batch 8.
2026-10-08 10:00:11,176 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/189 for batch 8.
2026-10-08 10:00:11,431 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/189 for batch 8.
2026-10-08 10:00:11,859 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/189 for batch 8.
2026-10-08 10:00:12,104 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/189 for batch 8.
2026-10-08 10:00:12,411 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/189 for batch 8.
2026-10-08 10:00:12,664 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/189 for batch 8.
2026-10-08 10:00:12,982 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/189 for batch 8.
2026-10-08 10:00:13,301 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/189 for batch 8.
2026-10-08 10:00:16,272 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/189 for batch 8.
2026-10-08 10:00:18,725 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/189 for batch 8.
2026-10-08 10:00:21,738 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/189 for batch 8.
2026-10-08 10:00:22,166 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/189 for batch 8.
2026-10-08 10:00:25,053 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/189 for batch 8.
2026-10-08 10:00:25,307 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/189 for batch 8.
2026-10-08 10:00:25,600 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/189 for batch 8.
2026-10-08 10:00:28,599 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/189 for batch 8.
2026-10-08 10:00:28,849 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/189 for batch 8.
2026-10-08 10:00:31,803 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/189 for batch 8.
2026-10-08 10:00:32,131 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/189 for batch 8.
2026-10-08 10:00:32,399 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/189 for batch 8.
2026-10-08 10:00:32,668 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/189 for batch 8.
2026-10-08 10:00:32,992 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/189 for batch 8.
2026-10-08 10:00:33,242 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/189 for batch 8.
2026-10-08 10:00:36,347 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/189 for batch 8.
2026-10-08 10:00:36,763 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/189 for batch 8.
2026-10-08 10:00:39,776 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/189 for batch 8.
2026-10-08 10:00:42,840 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/189 for batch 8.
2026-10-08 10:00:43,135 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/189 for batch 8.
2026-10-08 10:00:43,383 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/189 for batch 8.
2026-10-08 10:00:43,716 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/189 for batch 8.
2026-10-08 10:00:46,714 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/189 for batch 8.
2026-10-08 10:00:50,004 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/189 for batch 8.
2026-10-08 10:00:50,258 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/189 for batch 8.
2026-10-08 10:00:50,569 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/189 for batch 8.
2026-10-08 10:00:53,590 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/189 for batch 8.
2026-10-08 10:00:56,711 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/189 for batch 8.
2026-10-08 10:00:57,160 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/189 for batch 8.
2026-10-08 10:00:57,439 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/189 for batch 8.
2026-10-08 10:00:57,700 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/189 for batch 8.
2026-10-08 10:00:58,022 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/189 for batch 8.
2026-10-08 10:00:58,331 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/189 for batch 8.
2026-10-08 10:01:01,466 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/189 for batch 8.
2026-10-08 10:01:01,716 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/189 for batch 8.
2026-10-08 10:01:01,974 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/189 for batch 8.
2026-10-08 10:01:02,223 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/189 for batch 8.
2026-10-08 10:01:05,327 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/189 for batch 8.
2026-10-08 10:01:05,648 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/189 for batch 8.
2026-10-08 10:01:05,953 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/189 for batch 8.
2026-10-08 10:01:09,004 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/189 for batch 8.
2026-10-08 10:01:09,304 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/189 for batch 8.
2026-10-08 10:01:09,615 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/189 for batch 8.
2026-10-08 10:01:12,568 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/189 for batch 8.
2026-10-08 10:01:15,499 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/189 for batch 8.
2026-10-08 10:01:15,795 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/189 for batch 8.
2026-10-08 10:01:16,104 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/189 for batch 8.
2026-10-08 10:01:16,356 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/189 for batch 8.
2026-10-08 10:01:16,608 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/189 for batch 8.
2026-10-08 10:01:16,863 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/189 for batch 8.
2026-10-08 10:01:20,051 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/189 for batch 8.
2026-10-08 10:01:20,323 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/189 for batch 8.
2026-10-08 10:01:20,600 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/189 for batch 8.
2026-10-08 10:01:20,931 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/189 for batch 8.
2026-10-08 10:01:21,277 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/189 for batch 8.
2026-10-08 10:01:24,596 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/189 for batch 8.
2026-10-08 10:01:24,857 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/189 for batch 8.
2026-10-08 10:01:25,162 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/189 for batch 8.
2026-10-08 10:01:25,462 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/189 for batch 8.
2026-10-08 10:01:25,718 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/189 for batch 8.
2026-10-08 10:01:26,037 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/189 for batch 8.
2026-10-08 10:01:29,220 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/189 for batch 8.
2026-10-08 10:01:32,382 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/189 for batch 8.
2026-10-08 10:01:35,421 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/189 for batch 8.
2026-10-08 10:01:38,439 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/189 for batch 8.
2026-10-08 10:01:38,728 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/189 for batch 8.
2026-10-08 10:01:38,968 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/189 for batch 8.
2026-10-08 10:01:39,214 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/189 for batch 8.
2026-10-08 10:01:39,522 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/189 for batch 8.
2026-10-08 10:01:42,611 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/189 for batch 8.
2026-10-08 10:01:45,682 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/189 for batch 8.
2026-10-08 10:01:45,932 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/189 for batch 8.
2026-10-08 10:01:46,227 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/189 for batch 8.
2026-10-08 10:01:46,532 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/189 for batch 8.
2026-10-08 10:01:46,790 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/189 for batch 8.
2026-10-08 10:01:47,046 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/189 for batch 8.
2026-10-08 10:01:47,344 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/189 for batch 8.
2026-10-08 10:01:47,639 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/189 for batch 8.
2026-10-08 10:01:47,906 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/189 for batch 8.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00008_monthly_cleaning_report.partial.parquet

2026-10-08 10:02:57,434 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/189.
2026-10-08 10:03:04,247 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/189.
2026-10-08 10:03:10,430 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/189.
2026-10-08 10:03:16,418 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/189.
2026-10-08 10:03:23,302 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/189.
2026-10-08 10:03:30,443 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/189.
2026-10-08 10:03:37,647 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/189.
2026-10-08 10:03:45,093 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/189.
2026-10-08 10:03:52,633 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/189.
2026-10-08 10:03:59,785 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/189.
2026-10-08 10:04:06,684 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/189.
2026-10-08 10:04:14,043 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/189.
2026-10-08 10:04:21,894 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/189.
2026-10-08 10:04:29,965 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/189.
2026-10-08 10:04:38,536 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 150/189.
2026-10-08 10:04:47,409 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 160/189.
2026-10-08 10:04:58,134 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 170/189.
2026-10-08 10:05:08,810 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 180/189.
2026-10-08 10:05:18,710 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 189/189.
2026-10-08 10:05:22,234 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00008_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00008_monthly_cleaning_report.parquet

2026-10-08 10:12:30,104 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 135 parcels from batch_00008_monthly.nc.
2026-10-08 10:12:36,881 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00012_monthly.nc.
2026-10-08 10:12:42,626 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/181 for batch 12.
2026-10-08 10:12:49,116 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/181 for batch 12.
2026-10-08 10:12:54,568 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/181 for batch 12.
2026-10-08 10:13:00,417 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/181 for batch 12.
2026-10-08 10:13:06,352 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/181 for batch 12.
2026-10-08 10:13:12,841 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/181 for batch 12.
2026-10-08 10:13:19,029 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/181 for batch 12.
2026-10-08 10:13:25,073 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/181 for batch 12.
2026-10-08 10:13:31,862 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/181 for batch 12.
2026-10-08 10:13:37,760 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/181 for batch 12.
2026-10-08 10:13:43,993 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/181 for batch 12.
2026-10-08 10:13:50,395 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/181 for batch 12.
2026-10-08 10:13:56,996 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/181 for batch 12.
2026-10-08 10:14:03,615 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/181 for batch 12.
2026-10-08 10:14:10,654 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 150/181 for batch 12.
2026-10-08 10:14:17,054 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 160/181 for batch 12.
2026-10-08 10:14:23,160 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 170/181 for batch 12.
2026-10-08 10:14:29,675 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 180/181 for batch 12.
2026-10-08 10:14:30,294 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 181/181 for batch 12.
2026-10-08 10:14:30,296 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 16 rows.
2026-10-08 10:14:53,785 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 16 rows.
2026-10-08 10:15:17,284 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 16 rows.
2026-10-08 10:15:40,994 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 16 rows.
2026-10-08 10:16:04,374 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 16 rows.
2026-10-08 10:16:28,093 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 16 rows.
2026-10-08 10:16:51,530 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 16 rows.
2026-10-08 10:17:15,107 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 16 rows.
2026-10-08 10:17:38,631 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 16 rows.
2026-10-08 10:18:02,064 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/181 for batch 12.
2026-10-08 10:18:02,440 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/181 for batch 12.
2026-10-08 10:18:02,712 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/181 for batch 12.
2026-10-08 10:18:02,981 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/181 for batch 12.
2026-10-08 10:18:03,278 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/181 for batch 12.
2026-10-08 10:18:03,616 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/181 for batch 12.
2026-10-08 10:18:03,870 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/181 for batch 12.
2026-10-08 10:18:04,232 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/181 for batch 12.
2026-10-08 10:18:04,488 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/181 for batch 12.
2026-10-08 10:18:04,760 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/181 for batch 12.
2026-10-08 10:18:05,189 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/181 for batch 12.
2026-10-08 10:18:05,519 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/181 for batch 12.
2026-10-08 10:18:05,881 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/181 for batch 12.
2026-10-08 10:18:06,150 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/181 for batch 12.
2026-10-08 10:18:06,406 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/181 for batch 12.
2026-10-08 10:18:06,713 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/181 for batch 12.
2026-10-08 10:18:06,963 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/181 for batch 12.
2026-10-08 10:18:07,324 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/181 for batch 12.
2026-10-08 10:18:08,651 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/181 for batch 12.
2026-10-08 10:18:08,904 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/181 for batch 12.
2026-10-08 10:18:09,160 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/181 for batch 12.
2026-10-08 10:18:09,406 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/181 for batch 12.
2026-10-08 10:18:09,685 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/181 for batch 12.
2026-10-08 10:18:09,953 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/181 for batch 12.
2026-10-08 10:18:13,309 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/181 for batch 12.
2026-10-08 10:18:13,674 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/181 for batch 12.
2026-10-08 10:18:17,217 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/181 for batch 12.
2026-10-08 10:18:21,277 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/181 for batch 12.
2026-10-08 10:18:21,665 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/181 for batch 12.
2026-10-08 10:18:21,993 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/181 for batch 12.
2026-10-08 10:18:22,488 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/181 for batch 12.
2026-10-08 10:18:26,131 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/181 for batch 12.
2026-10-08 10:18:26,536 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/181 for batch 12.
2026-10-08 10:18:26,813 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/181 for batch 12.
2026-10-08 10:18:27,173 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/181 for batch 12.
2026-10-08 10:18:27,505 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/181 for batch 12.
2026-10-08 10:18:31,082 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/181 for batch 12.
2026-10-08 10:18:31,368 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/181 for batch 12.
2026-10-08 10:18:31,651 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/181 for batch 12.
2026-10-08 10:18:31,937 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/181 for batch 12.
2026-10-08 10:18:32,214 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/181 for batch 12.
2026-10-08 10:18:35,634 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/181 for batch 12.
2026-10-08 10:18:35,945 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/181 for batch 12.
2026-10-08 10:18:36,209 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/181 for batch 12.
2026-10-08 10:18:36,467 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/181 for batch 12.
2026-10-08 10:18:36,822 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/181 for batch 12.
2026-10-08 10:18:40,087 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/181 for batch 12.
2026-10-08 10:18:40,351 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/181 for batch 12.
2026-10-08 10:18:43,760 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/181 for batch 12.
2026-10-08 10:18:44,146 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/181 for batch 12.
2026-10-08 10:18:47,692 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/181 for batch 12.
2026-10-08 10:18:48,010 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/181 for batch 12.
2026-10-08 10:18:50,478 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/181 for batch 12.
2026-10-08 10:18:53,066 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/181 for batch 12.
2026-10-08 10:18:53,463 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/181 for batch 12.
2026-10-08 10:18:55,943 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/181 for batch 12.
2026-10-08 10:18:58,469 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/181 for batch 12.
2026-10-08 10:18:58,725 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/181 for batch 12.
2026-10-08 10:18:58,988 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/181 for batch 12.
2026-10-08 10:18:59,308 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/181 for batch 12.
2026-10-08 10:18:59,581 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/181 for batch 12.
2026-10-08 10:18:59,914 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/181 for batch 12.
2026-10-08 10:19:00,221 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/181 for batch 12.
2026-10-08 10:19:00,480 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/181 for batch 12.
2026-10-08 10:19:00,740 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/181 for batch 12.
2026-10-08 10:19:01,054 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/181 for batch 12.
2026-10-08 10:19:01,337 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/181 for batch 12.
2026-10-08 10:19:01,602 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/181 for batch 12.
2026-10-08 10:19:05,048 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/181 for batch 12.
2026-10-08 10:19:05,327 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/181 for batch 12.
2026-10-08 10:19:05,589 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/181 for batch 12.
2026-10-08 10:19:08,922 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/181 for batch 12.
2026-10-08 10:19:12,331 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/181 for batch 12.
2026-10-08 10:19:12,671 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/181 for batch 12.
2026-10-08 10:19:12,980 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/181 for batch 12.
2026-10-08 10:19:13,317 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/181 for batch 12.
2026-10-08 10:19:13,718 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/181 for batch 12.
2026-10-08 10:19:14,026 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/181 for batch 12.
2026-10-08 10:19:14,295 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/181 for batch 12.
2026-10-08 10:19:14,553 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/181 for batch 12.
2026-10-08 10:19:14,874 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/181 for batch 12.
2026-10-08 10:19:15,182 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/181 for batch 12.
2026-10-08 10:19:18,539 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/181 for batch 12.
2026-10-08 10:19:21,835 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/181 for batch 12.
2026-10-08 10:19:22,142 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/181 for batch 12.
2026-10-08 10:19:22,471 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/181 for batch 12.
2026-10-08 10:19:22,725 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/181 for batch 12.
2026-10-08 10:19:22,977 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/181 for batch 12.
2026-10-08 10:19:23,277 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/181 for batch 12.
2026-10-08 10:19:23,631 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/181 for batch 12.
2026-10-08 10:19:26,975 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/181 for batch 12.
2026-10-08 10:19:30,450 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/181 for batch 12.
2026-10-08 10:19:30,749 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/181 for batch 12.
2026-10-08 10:19:31,032 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/181 for batch 12.
2026-10-08 10:19:34,841 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/181 for batch 12.
2026-10-08 10:19:35,158 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/181 for batch 12.
2026-10-08 10:19:38,628 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/181 for batch 12.
2026-10-08 10:19:38,895 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/181 for batch 12.
2026-10-08 10:19:42,247 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/181 for batch 12.
2026-10-08 10:19:45,703 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/181 for batch 12.
2026-10-08 10:19:46,020 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/181 for batch 12.
2026-10-08 10:19:49,276 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/181 for batch 12.
2026-10-08 10:19:49,531 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/181 for batch 12.
2026-10-08 10:19:49,841 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/181 for batch 12.
2026-10-08 10:19:53,308 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/181 for batch 12.
2026-10-08 10:19:53,579 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/181 for batch 12.
2026-10-08 10:19:53,838 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/181 for batch 12.
2026-10-08 10:19:54,103 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/181 for batch 12.
2026-10-08 10:19:54,433 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/181 for batch 12.
2026-10-08 10:19:54,713 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/181 for batch 12.
2026-10-08 10:19:54,983 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/181 for batch 12.
2026-10-08 10:19:55,244 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/181 for batch 12.
2026-10-08 10:19:55,510 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/181 for batch 12.
2026-10-08 10:19:55,797 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/181 for batch 12.
2026-10-08 10:19:59,205 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/181 for batch 12.
2026-10-08 10:19:59,483 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/181 for batch 12.
2026-10-08 10:19:59,759 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/181 for batch 12.
2026-10-08 10:20:00,018 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/181 for batch 12.
2026-10-08 10:20:00,280 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/181 for batch 12.
2026-10-08 10:20:00,592 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/181 for batch 12.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00012_monthly_cleaning_report.partial.parquet

2026-10-08 10:20:31,375 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/181.
2026-10-08 10:20:37,964 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/181.
2026-10-08 10:20:44,425 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/181.
2026-10-08 10:20:51,156 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/181.
2026-10-08 10:20:57,833 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/181.
2026-10-08 10:21:04,434 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/181.
2026-10-08 10:21:10,880 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/181.
2026-10-08 10:21:17,812 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/181.
2026-10-08 10:21:24,597 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/181.
2026-10-08 10:21:31,228 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/181.
2026-10-08 10:21:37,856 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/181.
2026-10-08 10:21:44,664 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/181.
2026-10-08 10:21:51,275 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/181.
2026-10-08 10:21:58,702 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/181.
2026-10-08 10:22:06,021 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 150/181.
2026-10-08 10:22:13,737 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 160/181.
2026-10-08 10:22:21,998 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 170/181.
2026-10-08 10:22:30,095 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 180/181.
2026-10-08 10:22:30,985 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 181/181.
2026-10-08 10:22:34,552 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00012_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00012_monthly_cleaning_report.parquet

2026-10-08 10:23:13,755 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 12 parcels from batch_00012_monthly.nc.
2026-10-08 10:23:20,317 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00013_monthly.nc.
2026-10-08 10:23:28,019 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/181 for batch 13.
2026-10-08 10:23:37,077 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/181 for batch 13.
2026-10-08 10:23:44,255 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/181 for batch 13.
2026-10-08 10:23:52,599 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/181 for batch 13.
2026-10-08 10:24:00,739 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/181 for batch 13.
2026-10-08 10:24:09,241 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/181 for batch 13.
2026-10-08 10:24:16,992 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/181 for batch 13.
2026-10-08 10:24:26,127 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/181 for batch 13.
2026-10-08 10:24:35,229 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/181 for batch 13.
2026-10-08 10:24:43,000 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/181 for batch 13.
2026-10-08 10:24:51,205 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/181 for batch 13.
2026-10-08 10:24:59,963 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/181 for batch 13.
2026-10-08 10:25:08,630 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/181 for batch 13.
2026-10-08 10:25:17,067 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/181 for batch 13.
2026-10-08 10:25:25,813 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 150/181 for batch 13.
2026-10-08 10:25:34,262 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 160/181 for batch 13.
2026-10-08 10:25:42,067 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 170/181 for batch 13.
2026-10-08 10:25:49,722 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 180/181 for batch 13.
2026-10-08 10:25:50,690 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 181/181 for batch 13.
2026-10-08 10:25:50,693 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 9 rows.
2026-10-08 10:26:40,833 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 9 rows.
2026-10-08 10:27:32,485 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 9 rows.
2026-10-08 10:28:23,374 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 9 rows.
2026-10-08 10:29:16,574 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 9 rows.
2026-10-08 10:30:11,317 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 9 rows.
2026-10-08 10:31:06,219 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 9 rows.
2026-10-08 10:32:00,315 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 9 rows.
2026-10-08 10:32:54,959 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 9 rows.
2026-10-08 10:33:49,456 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/181 for batch 13.
2026-10-08 10:33:51,109 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/181 for batch 13.
2026-10-08 10:33:56,205 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/181 for batch 13.
2026-10-08 10:33:56,587 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/181 for batch 13.
2026-10-08 10:33:56,949 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/181 for batch 13.
2026-10-08 10:33:57,640 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/181 for batch 13.
2026-10-08 10:33:58,009 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/181 for batch 13.
2026-10-08 10:33:59,776 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/181 for batch 13.
2026-10-08 10:34:00,165 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/181 for batch 13.
2026-10-08 10:34:00,538 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/181 for batch 13.
2026-10-08 10:34:01,013 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/181 for batch 13.
2026-10-08 10:34:01,383 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/181 for batch 13.
2026-10-08 10:34:03,026 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/181 for batch 13.
2026-10-08 10:34:03,415 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/181 for batch 13.
2026-10-08 10:34:03,786 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/181 for batch 13.
2026-10-08 10:34:04,246 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/181 for batch 13.
2026-10-08 10:34:04,617 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/181 for batch 13.
2026-10-08 10:34:06,298 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/181 for batch 13.
2026-10-08 10:34:06,664 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/181 for batch 13.
2026-10-08 10:34:07,111 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/181 for batch 13.
2026-10-08 10:34:07,554 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/181 for batch 13.
2026-10-08 10:34:08,027 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/181 for batch 13.
2026-10-08 10:34:08,545 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/181 for batch 13.
2026-10-08 10:34:09,077 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/181 for batch 13.
2026-10-08 10:34:14,178 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/181 for batch 13.
2026-10-08 10:34:14,643 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/181 for batch 13.
2026-10-08 10:34:19,722 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/181 for batch 13.
2026-10-08 10:34:24,842 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/181 for batch 13.
2026-10-08 10:34:26,522 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/181 for batch 13.
2026-10-08 10:34:26,906 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/181 for batch 13.
2026-10-08 10:34:27,365 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/181 for batch 13.
2026-10-08 10:34:27,740 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/181 for batch 13.
2026-10-08 10:34:29,471 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/181 for batch 13.
2026-10-08 10:34:29,859 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/181 for batch 13.
2026-10-08 10:34:30,349 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/181 for batch 13.
2026-10-08 10:34:30,934 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/181 for batch 13.
2026-10-08 10:34:36,764 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/181 for batch 13.
2026-10-08 10:34:37,265 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/181 for batch 13.
2026-10-08 10:34:37,764 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/181 for batch 13.
2026-10-08 10:34:43,570 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/181 for batch 13.
2026-10-08 10:34:43,982 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/181 for batch 13.
2026-10-08 10:34:49,493 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/181 for batch 13.
2026-10-08 10:34:49,947 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/181 for batch 13.
2026-10-08 10:34:54,994 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/181 for batch 13.
2026-10-08 10:35:00,177 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/181 for batch 13.
2026-10-08 10:35:01,861 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/181 for batch 13.
2026-10-08 10:35:06,984 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/181 for batch 13.
2026-10-08 10:35:07,359 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/181 for batch 13.
2026-10-08 10:35:12,426 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/181 for batch 13.
2026-10-08 10:35:12,950 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/181 for batch 13.
2026-10-08 10:35:18,041 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/181 for batch 13.
2026-10-08 10:35:19,748 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/181 for batch 13.
2026-10-08 10:35:24,836 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/181 for batch 13.
2026-10-08 10:35:29,862 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/181 for batch 13.
2026-10-08 10:35:30,301 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/181 for batch 13.
2026-10-08 10:35:30,668 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/181 for batch 13.
2026-10-08 10:35:31,113 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/181 for batch 13.
2026-10-08 10:35:31,548 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/181 for batch 13.
2026-10-08 10:35:31,921 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/181 for batch 13.
2026-10-08 10:35:33,546 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/181 for batch 13.
2026-10-08 10:35:33,935 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/181 for batch 13.
2026-10-08 10:35:34,452 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/181 for batch 13.
2026-10-08 10:35:34,905 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/181 for batch 13.
2026-10-08 10:35:38,601 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/181 for batch 13.
2026-10-08 10:35:42,320 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/181 for batch 13.
2026-10-08 10:35:42,771 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/181 for batch 13.
2026-10-08 10:35:43,156 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/181 for batch 13.
2026-10-08 10:35:43,628 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/181 for batch 13.
2026-10-08 10:35:48,768 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/181 for batch 13.
2026-10-08 10:35:49,216 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/181 for batch 13.
2026-10-08 10:35:49,664 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/181 for batch 13.
2026-10-08 10:35:54,748 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/181 for batch 13.
2026-10-08 10:35:59,736 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/181 for batch 13.
2026-10-08 10:36:00,188 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/181 for batch 13.
2026-10-08 10:36:00,656 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/181 for batch 13.
2026-10-08 10:36:01,017 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/181 for batch 13.
2026-10-08 10:36:01,701 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/181 for batch 13.
2026-10-08 10:36:02,369 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/181 for batch 13.
2026-10-08 10:36:02,736 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/181 for batch 13.
2026-10-08 10:36:03,099 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/181 for batch 13.
2026-10-08 10:36:03,630 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/181 for batch 13.
2026-10-08 10:36:04,167 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/181 for batch 13.
2026-10-08 10:36:04,532 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/181 for batch 13.
2026-10-08 10:36:04,894 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/181 for batch 13.
2026-10-08 10:36:05,552 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/181 for batch 13.
2026-10-08 10:36:06,249 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/181 for batch 13.
2026-10-08 10:36:06,634 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/181 for batch 13.
2026-10-08 10:36:07,019 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/181 for batch 13.
2026-10-08 10:36:07,484 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/181 for batch 13.
2026-10-08 10:36:07,934 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/181 for batch 13.
2026-10-08 10:36:13,042 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/181 for batch 13.
2026-10-08 10:36:17,968 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/181 for batch 13.
2026-10-08 10:36:18,484 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/181 for batch 13.
2026-10-08 10:36:19,004 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/181 for batch 13.
2026-10-08 10:36:24,191 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/181 for batch 13.
2026-10-08 10:36:24,647 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/181 for batch 13.
2026-10-08 10:36:29,732 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/181 for batch 13.
2026-10-08 10:36:30,109 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/181 for batch 13.
2026-10-08 10:36:33,786 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/181 for batch 13.
2026-10-08 10:36:37,450 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/181 for batch 13.
2026-10-08 10:36:37,923 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/181 for batch 13.
2026-10-08 10:36:43,202 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/181 for batch 13.
2026-10-08 10:36:43,571 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/181 for batch 13.
2026-10-08 10:36:44,042 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/181 for batch 13.
2026-10-08 10:36:49,206 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/181 for batch 13.
2026-10-08 10:36:49,570 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/181 for batch 13.
2026-10-08 10:36:49,937 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/181 for batch 13.
2026-10-08 10:36:50,384 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/181 for batch 13.
2026-10-08 10:36:50,851 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/181 for batch 13.
2026-10-08 10:36:51,231 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/181 for batch 13.
2026-10-08 10:36:51,611 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/181 for batch 13.
2026-10-08 10:36:52,050 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/181 for batch 13.
2026-10-08 10:36:52,496 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/181 for batch 13.
2026-10-08 10:36:52,870 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/181 for batch 13.
2026-10-08 10:36:58,044 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/181 for batch 13.
2026-10-08 10:36:58,678 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/181 for batch 13.
2026-10-08 10:36:59,287 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/181 for batch 13.
2026-10-08 10:36:59,662 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/181 for batch 13.
2026-10-08 10:37:00,033 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/181 for batch 13.
2026-10-08 10:37:00,508 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/181 for batch 13.

Writing file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00013_monthly_cleaning_report.partial.parquet

2026-10-08 10:37:44,213 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 10/181.
2026-10-08 10:37:54,371 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 20/181.
2026-10-08 10:38:04,582 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 30/181.
2026-10-08 10:38:15,036 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 40/181.
2026-10-08 10:38:25,188 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 50/181.
2026-10-08 10:38:35,366 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 60/181.
2026-10-08 10:38:45,562 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 70/181.
2026-10-08 10:38:55,900 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 80/181.
2026-10-08 10:39:09,378 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 90/181.
2026-10-08 10:39:21,174 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 100/181.
2026-10-08 10:39:33,649 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 110/181.
2026-10-08 10:39:46,748 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 120/181.
2026-10-08 10:40:02,631 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 130/181.
2026-10-08 10:40:19,557 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 140/181.
2026-10-08 10:40:37,654 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 150/181.
2026-10-08 10:40:54,865 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 160/181.
2026-10-08 10:41:10,975 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 170/181.
2026-10-08 10:41:27,907 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 180/181.
2026-10-08 10:41:29,397 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Saved output indices for acquisition 181/181.
2026-10-08 10:41:33,224 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Removed intermediate cleaning raster C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00013_monthly_cleaned.nc; raw data and audit remain available.

Reading file: C:/work_sat/neuro_2024-2025/1_eo_parcel_stats_fill/partition_20/monthly_cubes/fa8e5a4c7d9277b2-tiles-669b4d35/batch_00013_monthly_cleaning_report.parquet

2026-10-08 10:44:04,292 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Calculated ['mean', 'median', 'sd', 'min', 'max', 'range'] locally for 43 parcels from batch_00013_monthly.nc.
2026-10-08 10:44:11,385 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Reading temporal pixel cube C:\work_sat\neuro_2024-2025\1_eo_parcel_stats_fill\partition_20\monthly_cubes\fa8e5a4c7d9277b2-tiles-669b4d35\batch_00004_monthly.nc.
2026-10-08 10:44:21,427 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 10/189 for batch 4.
2026-10-08 10:44:32,404 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 20/189 for batch 4.
2026-10-08 10:44:42,209 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 30/189 for batch 4.
2026-10-08 10:44:52,317 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 40/189 for batch 4.
2026-10-08 10:45:01,634 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 50/189 for batch 4.
2026-10-08 10:45:11,275 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 60/189 for batch 4.
2026-10-08 10:45:22,729 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 70/189 for batch 4.
2026-10-08 10:45:33,086 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 80/189 for batch 4.
2026-10-08 10:45:43,891 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 90/189 for batch 4.
2026-10-08 10:45:56,475 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 100/189 for batch 4.
2026-10-08 10:46:09,080 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 110/189 for batch 4.
2026-10-08 10:46:21,359 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 120/189 for batch 4.
2026-10-08 10:46:33,151 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 130/189 for batch 4.
2026-10-08 10:46:44,428 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 140/189 for batch 4.
2026-10-08 10:46:55,747 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 150/189 for batch 4.
2026-10-08 10:47:07,963 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 160/189 for batch 4.
2026-10-08 10:47:19,238 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 170/189 for batch 4.
2026-10-08 10:47:31,538 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 180/189 for batch 4.
2026-10-08 10:47:41,021 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Stored observations 189/189 for batch 4.
2026-10-08 10:47:41,025 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 1/9 in strips of 6 rows.
2026-10-08 10:49:45,990 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 2/9 in strips of 6 rows.
2026-10-08 10:51:48,347 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 3/9 in strips of 6 rows.
2026-10-08 10:53:43,055 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 4/9 in strips of 6 rows.
2026-10-08 10:55:39,430 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 5/9 in strips of 6 rows.
2026-10-08 10:57:37,089 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 6/9 in strips of 6 rows.
2026-10-08 10:59:32,227 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 7/9 in strips of 6 rows.
2026-10-08 11:01:25,818 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 8/9 in strips of 6 rows.
2026-10-08 11:03:21,664 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Temporal filling band 9/9 in strips of 6 rows.
2026-10-08 11:05:29,829 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 1/189 for batch 4.
2026-10-08 11:05:30,451 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 2/189 for batch 4.
2026-10-08 11:05:30,966 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 3/189 for batch 4.
2026-10-08 11:05:38,453 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 4/189 for batch 4.
2026-10-08 11:05:38,985 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 5/189 for batch 4.
2026-10-08 11:05:39,625 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 6/189 for batch 4.
2026-10-08 11:05:47,118 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 7/189 for batch 4.
2026-10-08 11:05:47,744 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 8/189 for batch 4.
2026-10-08 11:05:55,466 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 9/189 for batch 4.
2026-10-08 11:05:55,981 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 10/189 for batch 4.
2026-10-08 11:06:03,598 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 11/189 for batch 4.
2026-10-08 11:06:04,108 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 12/189 for batch 4.
2026-10-08 11:06:05,102 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 13/189 for batch 4.
2026-10-08 11:06:05,670 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 14/189 for batch 4.
2026-10-08 11:06:13,891 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 15/189 for batch 4.
2026-10-08 11:06:14,860 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 16/189 for batch 4.
2026-10-08 11:06:22,828 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 17/189 for batch 4.
2026-10-08 11:06:23,466 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 18/189 for batch 4.
2026-10-08 11:06:31,086 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 19/189 for batch 4.
2026-10-08 11:06:31,624 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 20/189 for batch 4.
2026-10-08 11:06:32,176 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 21/189 for batch 4.
2026-10-08 11:06:32,736 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 22/189 for batch 4.
2026-10-08 11:06:33,298 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 23/189 for batch 4.
2026-10-08 11:06:33,857 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 24/189 for batch 4.
2026-10-08 11:06:34,411 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 25/189 for batch 4.
2026-10-08 11:06:42,094 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 26/189 for batch 4.
2026-10-08 11:06:42,729 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 27/189 for batch 4.
2026-10-08 11:06:50,583 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 28/189 for batch 4.
2026-10-08 11:06:51,123 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 29/189 for batch 4.
2026-10-08 11:06:51,632 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 30/189 for batch 4.
2026-10-08 11:06:52,147 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 31/189 for batch 4.
2026-10-08 11:06:52,785 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 32/189 for batch 4.
2026-10-08 11:06:53,324 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 33/189 for batch 4.
2026-10-08 11:06:53,852 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 34/189 for batch 4.
2026-10-08 11:06:59,383 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 35/189 for batch 4.
2026-10-08 11:07:00,084 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 36/189 for batch 4.
2026-10-08 11:07:00,623 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 37/189 for batch 4.
2026-10-08 11:07:01,289 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 38/189 for batch 4.
2026-10-08 11:07:01,945 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 39/189 for batch 4.
2026-10-08 11:07:02,568 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 40/189 for batch 4.
2026-10-08 11:07:03,147 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 41/189 for batch 4.
2026-10-08 11:07:12,250 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 42/189 for batch 4.
2026-10-08 11:07:12,927 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 43/189 for batch 4.
2026-10-08 11:07:22,292 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 44/189 for batch 4.
2026-10-08 11:07:23,032 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 45/189 for batch 4.
2026-10-08 11:07:23,606 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 46/189 for batch 4.
2026-10-08 11:07:24,255 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 47/189 for batch 4.
2026-10-08 11:07:25,000 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 48/189 for batch 4.
2026-10-08 11:07:25,609 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 49/189 for batch 4.
2026-10-08 11:07:26,194 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 50/189 for batch 4.
2026-10-08 11:07:26,774 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 51/189 for batch 4.
2026-10-08 11:07:27,509 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 52/189 for batch 4.
2026-10-08 11:07:36,882 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 53/189 for batch 4.
2026-10-08 11:07:37,561 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 54/189 for batch 4.
2026-10-08 11:07:38,384 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 55/189 for batch 4.
2026-10-08 11:07:39,102 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 56/189 for batch 4.
2026-10-08 11:07:39,809 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 57/189 for batch 4.
2026-10-08 11:07:40,620 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 58/189 for batch 4.
2026-10-08 11:07:41,194 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 59/189 for batch 4.
2026-10-08 11:07:50,257 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 60/189 for batch 4.
2026-10-08 11:07:50,939 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 61/189 for batch 4.
2026-10-08 11:07:51,852 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 62/189 for batch 4.
2026-10-08 11:07:52,569 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 63/189 for batch 4.
2026-10-08 11:08:01,142 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 64/189 for batch 4.
2026-10-08 11:08:01,922 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 65/189 for batch 4.
2026-10-08 11:08:09,946 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 66/189 for batch 4.
2026-10-08 11:08:10,584 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 67/189 for batch 4.
2026-10-08 11:08:18,531 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 68/189 for batch 4.
2026-10-08 11:08:19,087 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 69/189 for batch 4.
2026-10-08 11:08:19,783 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 70/189 for batch 4.
2026-10-08 11:08:20,326 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 71/189 for batch 4.
2026-10-08 11:08:20,917 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 72/189 for batch 4.
2026-10-08 11:08:21,491 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 73/189 for batch 4.
2026-10-08 11:08:22,043 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 74/189 for batch 4.
2026-10-08 11:08:30,075 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 75/189 for batch 4.
2026-10-08 11:08:30,665 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 76/189 for batch 4.
2026-10-08 11:08:31,229 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 77/189 for batch 4.
2026-10-08 11:08:39,239 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 78/189 for batch 4.
2026-10-08 11:08:39,782 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 79/189 for batch 4.
2026-10-08 11:08:40,382 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 80/189 for batch 4.
2026-10-08 11:08:40,938 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 81/189 for batch 4.
2026-10-08 11:08:48,947 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 82/189 for batch 4.
2026-10-08 11:08:49,490 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 83/189 for batch 4.
2026-10-08 11:08:50,056 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 84/189 for batch 4.
2026-10-08 11:08:50,625 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 85/189 for batch 4.
2026-10-08 11:08:51,205 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 86/189 for batch 4.
2026-10-08 11:08:51,823 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 87/189 for batch 4.
2026-10-08 11:08:52,364 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 88/189 for batch 4.
2026-10-08 11:08:52,896 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 89/189 for batch 4.
2026-10-08 11:08:53,435 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 90/189 for batch 4.
2026-10-08 11:08:53,995 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 91/189 for batch 4.
2026-10-08 11:08:54,549 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 92/189 for batch 4.
2026-10-08 11:08:55,094 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 93/189 for batch 4.
2026-10-08 11:08:55,673 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 94/189 for batch 4.
2026-10-08 11:08:56,201 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 95/189 for batch 4.
2026-10-08 11:08:56,735 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 96/189 for batch 4.
2026-10-08 11:09:05,127 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 97/189 for batch 4.
2026-10-08 11:09:05,715 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 98/189 for batch 4.
2026-10-08 11:09:06,254 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 99/189 for batch 4.
2026-10-08 11:09:06,804 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 100/189 for batch 4.
2026-10-08 11:09:07,388 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 101/189 for batch 4.
2026-10-08 11:09:07,979 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 102/189 for batch 4.
2026-10-08 11:09:15,898 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 103/189 for batch 4.
2026-10-08 11:09:16,461 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 104/189 for batch 4.
2026-10-08 11:09:17,052 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 105/189 for batch 4.
2026-10-08 11:09:25,043 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 106/189 for batch 4.
2026-10-08 11:09:25,596 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 107/189 for batch 4.
2026-10-08 11:09:33,902 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 108/189 for batch 4.
2026-10-08 11:09:42,167 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 109/189 for batch 4.
2026-10-08 11:09:42,798 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 110/189 for batch 4.
2026-10-08 11:09:43,349 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 111/189 for batch 4.
2026-10-08 11:09:43,879 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 112/189 for batch 4.
2026-10-08 11:09:44,415 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 113/189 for batch 4.
2026-10-08 11:09:44,950 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 114/189 for batch 4.
2026-10-08 11:09:45,551 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 115/189 for batch 4.
2026-10-08 11:09:46,117 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 116/189 for batch 4.
2026-10-08 11:09:46,674 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 117/189 for batch 4.
2026-10-08 11:09:47,252 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 118/189 for batch 4.
2026-10-08 11:09:47,819 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 119/189 for batch 4.
2026-10-08 11:09:55,601 | INFO | parcel_stats_pipeline.e80976f815.3021555972880.parcels | Cleaned acquisition 120/189 for batch 4.

In [ ]:
# ============================================================================
# STEP 4: Merge results and save to files
# ============================================================================
# Combines all partition results and removes duplicates
# Saves one file:
#   1. satellite_parcel_time_stats.geoparquet (full results with geometry)

merged_gdf, geoparquet_path = merge_and_save_results(
    output_dir=OUTPUT_DIR,
    parcel_id_column=parcel_id_column,
    working_epsg=WORKING_EPSG
)

In [ ]:
# ============================================================================
# STEP 5: Inspect results
# ============================================================================

print(f"\n{'='*70}")
print("FINAL RESULTS")
print(f"{'='*70}")

print("\nMerged GeoDataFrame:")
print(f"  Rows: {len(merged_gdf)}")
print(f"  Columns: {len(merged_gdf.columns)}")
print(f"  Has geometry: {merged_gdf.geometry.name in merged_gdf.columns}")

print("\nOutput files:")
print(f"  GeoParquet: {geoparquet_path}")
print(f"    Size: {geoparquet_path.stat().st_size / 1e6:.1f} MB")

print("\nFirst 5 rows:")
display(merged_gdf.head())