# EDA Pipeline Example

This notebook shows how to run the reusable EDA pipeline on a pandas DataFrame and, when GeoPandas is installed, on a GeoDataFrame.

In [1]:
from pathlib import Path
import os
import random

from IPython.display import display
from pathlib import Path
import numpy as np
import os
import random
from satellites.shared.io import read_data
from satellites.eda import run_eda
import webbrowser

# Global reproducibility seed
random_seed = 42
os.environ["PYTHONHASHSEED"] = str(random_seed)
os.environ["TF_DETERMINISTIC_OPS"] = "1"
random.seed(random_seed)
np.random.seed(random_seed)

## GeoDataFrame Example

In [2]:
try:
    WORK_PATH = Path("C:/work_dir/neuro_2024-2025")
    PARCELS_PATH = WORK_PATH / "1_eo_parcel_stats_fill" / "satellite_parcel_time_stats.geoparquet"
    OUTPUT_PATH = WORK_PATH / "2_eo_results_eda_fill"
    COL_PARCEL_ID = "parcel_id"
    COL_TARGET = "crop_category"

    gdf = read_data(str(PARCELS_PATH))
    print(f"Initial columns in GeoDataFrame: {len(gdf.columns)}: {list(gdf.columns)}")

    extra_features = ["elevation_mean_m", "GAIOIKANOT", "geom_interior_area_ratio", "data_reliability_score", "geom_shape_complexity_score"]
    show_indices =  ("R", "RVI", "NDMI", "NDRE", "SAVI", "NDVI", "EVI", "NDWI",)
    show_statistics = ("_median",)
    base_columns = [x for x in gdf.columns if x in extra_features or (any(stat in x for stat in show_statistics) and any(idx in x for idx in show_indices))]

    columns_to_display = [COL_PARCEL_ID, COL_TARGET] + base_columns + ["geometry"]
    print(f"\nColumns to display {len(columns_to_display)}: {columns_to_display}")

    display(gdf[columns_to_display].head())
    geo_result = run_eda(
        gdf[columns_to_display],
        output_dir=str(OUTPUT_PATH),
        target_task="classification",
        target_column=COL_TARGET,
        id_column=COL_PARCEL_ID,
        report_title="Sample GeoDataFrame EDA",
        feature_selection_max_features=None,
        max_features_per_plot=36,
        max_target_levels_for_plots=20,
    )
    html_path = geo_result["report_path"]
    proposed_features = geo_result["proposed_features"]
    annotated_gdf = geo_result["annotated_data"]
    display(geo_result["artifacts"]["feature_selection_proposal"])
    print(f"Annotated GeoParquet: {geo_result['saved_paths']['annotated_data']}")
    webbrowser.open(html_path.as_uri())
except ImportError as exc:
    print(f"GeoDataFrame example skipped: {exc}")

Reading file: C:/work_dir/neuro_2024-2025/1_eo_parcel_stats_fill/satellite_parcel_time_stats.geoparquet

,parcel_id,crop_category,data_reliability_score,geom_interior_area_ratio,geom_shape_complexity_score,EVI_median__20250301,EVI_median__20250401,EVI_median__20250501,EVI_median__20250601,EVI_median__20250701,...,SAVI_median__20250601,SAVI_median__20250701,SAVI_median__20250801,SAVI_median__20250901,SAVI_median__20251001,SAVI_median__20251101,SAVI_median__20251201,GAIOIKANOT,elevation_mean_m,geometry
0,552,ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ,0.805579,1.581149,1.003565,0.329921,0.559387,0.588669,0.271265,0.141044,...,0.280032,0.152691,0.119601,0.118962,0.094129,0.084061,0.116741,T3T7-121-1-D1BN,611.127225,"POLYGON ((276662.48 4436671.197, 276678.712 44..."
1,553,jjjj,0.835100,1.250683,0.166070,0.407966,0.656679,0.624080,0.210309,0.148420,...,0.227716,0.159265,0.143648,0.110895,0.069545,0.068450,0.112045,T7T3-121-1-D9BN,599.475838,"POLYGON ((278512.621 4438032.511, 278569.444 4..."
2,554,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,0.835647,1.405511,0.621168,0.404978,0.725193,0.681621,0.273857,0.183156,...,0.291454,0.190522,0.191163,0.153629,0.102976,0.105914,0.134897,T7T3-121-1-D9BN,599.440261,"POLYGON ((278217.406 4437980.983, 278216.141 4..."
3,555,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,0.849672,1.581203,0.557263,0.294356,0.581081,0.696555,0.279653,0.149791,...,0.287687,0.155396,0.140551,0.149648,0.107024,0.097125,0.125472,T3T7-121-4-D9QQ,663.806288,"POLYGON ((274769.371 4440021.267, 274765.085 4..."
4,556,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,0.785333,1.279186,0.344045,0.249964,0.493637,0.593259,0.295206,0.170150,...,0.293234,0.170878,0.211001,0.234882,0.134089,0.131795,0.138787,T3T7-121-4-D9QQ,764.202630,"POLYGON ((272117.608 4439208.351, 272117.342 4..."

Proposed initial ML features (19): GAIOIKANOT, NDRE_median__20251101, NDMI_median__20251101, NDVI_median__20251001, NDRE_median__20251201, elevation_mean_m, NDMI_median__20251001, NDVI_median__20250901, NDMI_median__20251201, NDVI_median__20250701, NDVI_median__20250301, NDVI_median__20250501, NDVI_median__20250401, NDVI_median__20250601, NDMI_median__20250301, data_reliability_score, NDMI_median__20250901, NDMI_median__20250701, NDMI_median__20250601. Review separately (46): NDWI_median__20251201, EVI_median__20251101, NDVI_median__20251101, SAVI_median__20251101, NDRE_median__20251001, NDWI_median__20251101, NDVI_median__20251201, NDWI_median__20251001, SAVI_median__20251001, EVI_median__20251001, ... 36 more (see feature_selection_proposal.csv). Automatically excluded: 0. Criteria order: hard exclusions and leakage review -> data quality and availability -> target association -> redundancy -> parsimonious initial shortlist -> train-only model validation. This is an EDA shortlist; confirm it with train-only cross-validation and permutation importance.
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/overview/column_profile.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/data_quality/data_quality_flags.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/numeric/numeric_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/numeric/robust_numeric_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/categorical/categorical_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/overview/datetime_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/numeric/normality_tests.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/numeric/outlier_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/correlation/strong_correlation_pairs.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/correlation/multicollinearity.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/data_quality/missingness_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/missingness_target_tests.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/categorical/categorical_associations.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/categorical_target_tests.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/categorical_numeric_target_tests.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/numeric_target_tests.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/numeric_target_correlations.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/feature_selection/feature_target_associations.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/feature_selection/feature_selection_criteria.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/feature_selection/feature_selection_proposal.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/multivariate/pca_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/multivariate/multivariate_outliers.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/target/target_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/geospatial/geospatial_summary.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/eda_annotated_data.parquet
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/correlation/pearson_correlation_matrix.csv
Writing file: C:/work_dir/neuro_2024-2025/2_eo_results_eda_fill/tables/correlation/spearman_correlation_matrix.csv

,selection_order,feature,feature_type,proposed_action,primary_reason,association_method,effect_size,association_strength,qvalue,missing_percent,redundant_with,redundancy_measure,passes_hard_exclusions,passes_data_quality,passes_target_evidence,passes_redundancy,passes_shortlist_limit
0,1,GAIOIKANOT,categorical,use,priority target association after FDR correction,bias_corrected_cramers_v,0.3949,moderate,0.0000,0.0,,NaN,True,True,True,True,True
1,2,NDRE_median__20251101,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3709,large,0.0000,0.0,,NaN,True,True,True,True,True
2,3,NDMI_median__20251101,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3666,large,0.0000,0.0,,NaN,True,True,True,True,True
3,4,NDVI_median__20251001,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3483,large,0.0000,0.0,,NaN,True,True,True,True,True
4,5,NDRE_median__20251201,numeric,use,priority target association after FDR correction,kruskal_epsilon_squared,0.3318,large,0.0000,0.0,,NaN,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,61,NDMI_median__20250801,numeric,review,redundant with retained feature NDMI_median__2...,kruskal_epsilon_squared,0.1179,moderate,0.0000,0.0,NDMI_median__20250901,0.9245,True,True,True,False,True
61,62,SAVI_median__20250601,numeric,review,redundant with retained feature NDVI_median__2...,kruskal_epsilon_squared,0.1174,moderate,0.0000,0.0,NDVI_median__20250601,0.9760,True,True,True,False,True
62,63,EVI_median__20250601,numeric,review,redundant with retained feature NDVI_median__2...,kruskal_epsilon_squared,0.1144,moderate,0.0000,0.0,NDVI_median__20250601,0.9687,True,True,True,False,True
63,64,geom_interior_area_ratio,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0567,small,0.0000,0.0,,NaN,True,True,False,True,True
64,65,geom_shape_complexity_score,numeric,review,statistically detectable but weak univariate e...,kruskal_epsilon_squared,0.0155,small,0.0135,0.0,,NaN,True,True,False,True,True

Annotated GeoParquet: C:\work_dir\neuro_2024-2025\2_eo_results_eda_fill\eda_annotated_data.parquet

In [3]:
# import satellites.shared.legacy.eda_report as eda_l

# report = eda_l.EdaReport(gdf[columns_to_display], report_folder=os.path.join(str(OUTPUT_PATH), "geodataframe_eda2"), report_name="eda_report_sample")
# report.create_eda_report()